# CNN Deep Conv1D baseline

This notebook contains the selected CNN architecture for the forecasting practice.

The model receives a tensor with shape:

```text
X = samples × input_window × 23 assets
```

and predicts:

```text
y = samples × 23 assets
```

By default, the experiment uses `input_window = 30` and `output_window = 5`, because this was the first validated CNN setup. The model is trained with MAE, uses a validation split taken from the training set, and keeps the test set untouched for final evaluation.

In [1]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

from pathlib import Path
import sys

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler

import keras
from keras.layers import (
    Input,
    Conv1D,
    BatchNormalization,
    SpatialDropout1D,
    GlobalAveragePooling1D,
    GlobalMaxPooling1D,
    Concatenate,
    Dense,
    Dropout,
)
from keras.models import Model
from keras.callbacks import EarlyStopping, ReduceLROnPlateau

def find_project_root(start=None):
    start = Path.cwd() if start is None else Path(start)
    for candidate in [start, *start.parents]:
        if (candidate / "util.py").exists() and (candidate / "data").exists():
            return candidate
    raise FileNotFoundError("Could not find project root containing util.py and data/")

PROJECT_ROOT = find_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from util import get_train_test, RANDOM_SEED

np.random.seed(RANDOM_SEED)
keras.utils.set_random_seed(RANDOM_SEED)

OUTPUT_DIR = PROJECT_ROOT / "data" / "cnn"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("Output dir:", OUTPUT_DIR)

Project root: /Users/jchulvi/projects/Neural-Networks-Forecasting
Output dir: /Users/jchulvi/projects/Neural-Networks-Forecasting/data/cnn

## Configuration

The default window is `30 → 5`: the model observes 30 past days and predicts the average return over the following 5 days. You can change these values to run another combination required by the practice.

In [2]:
INPUT_WINDOW = 30
OUTPUT_WINDOW = 5

EPOCHS = 150
BATCH_SIZE = 128
VALIDATION_RATIO = 0.10

## Data split and scaling

The repository already provides `get_train_test`, which builds the time windows. We create a validation set from the last part of the training data and fit the scaler only on training observations to avoid leakage.

In [3]:
def split_train_val(X_train, y_train, val_ratio=0.10):
    val_size = int(len(X_train) * val_ratio)
    if val_size <= 0:
        raise ValueError("Validation split is empty. Increase training size or val_ratio.")

    X_val = X_train[-val_size:]
    y_val = y_train[-val_size:]
    X_train_final = X_train[:-val_size]
    y_train_final = y_train[:-val_size]
    return X_train_final, y_train_final, X_val, y_val


def scale_X_only(X_train, X_val, X_test):
    n_train, window, n_assets = X_train.shape
    n_val = X_val.shape[0]
    n_test = X_test.shape[0]

    scaler = StandardScaler()
    X_train_2d = X_train.reshape(n_train, -1)
    X_val_2d = X_val.reshape(n_val, -1)
    X_test_2d = X_test.reshape(n_test, -1)

    X_train_scaled = scaler.fit_transform(X_train_2d).reshape(n_train, window, n_assets)
    X_val_scaled = scaler.transform(X_val_2d).reshape(n_val, window, n_assets)
    X_test_scaled = scaler.transform(X_test_2d).reshape(n_test, window, n_assets)
    return X_train_scaled, X_val_scaled, X_test_scaled


d = get_train_test(INPUT_WINDOW, OUTPUT_WINDOW)

X_train_raw, y_train_raw = d.X_train, d.y_train
X_test_raw, y_test = d.X_test, d.y_test

X_train_raw, y_train, X_val_raw, y_val = split_train_val(
    X_train_raw, y_train_raw, val_ratio=VALIDATION_RATIO
)
X_train, X_val, X_test = scale_X_only(X_train_raw, X_val_raw, X_test_raw)

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)
print("X_val:  ", X_val.shape)
print("y_val:  ", y_val.shape)
print("X_test: ", X_test.shape)
print("y_test: ", y_test.shape)

X_train: (13090, 30, 23)
y_train: (13090, 23)
X_val:   (1454, 30, 23)
y_val:   (1454, 23)
X_test:  (1617, 30, 23)
y_test:  (1617, 23)

## CNN architecture

This is the deeper CNN selected after the first exploratory run. It uses causal `Conv1D` layers, dilations to capture a wider temporal context, pooling layers to summarize the sequence, and dense layers to produce one prediction per asset.

In [4]:
def build_deep_cnn(input_window, n_assets):
    inputs = Input(shape=(input_window, n_assets))

    x = Conv1D(filters=64, kernel_size=3, padding="causal", activation="relu")(inputs)
    x = BatchNormalization()(x)
    x = SpatialDropout1D(0.10)(x)

    x = Conv1D(filters=64, kernel_size=5, padding="causal", dilation_rate=2, activation="relu")(x)
    x = BatchNormalization()(x)
    x = SpatialDropout1D(0.10)(x)

    x = Conv1D(filters=128, kernel_size=3, padding="causal", dilation_rate=4, activation="relu")(x)
    x = BatchNormalization()(x)

    avg_pool = GlobalAveragePooling1D()(x)
    max_pool = GlobalMaxPooling1D()(x)
    x = Concatenate()([avg_pool, max_pool])

    x = Dense(128, activation="relu")(x)
    x = Dropout(0.25)(x)
    x = Dense(64, activation="relu")(x)
    x = Dropout(0.15)(x)

    outputs = Dense(n_assets, activation="linear")(x)
    model = Model(inputs=inputs, outputs=outputs)

    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=3e-4),
        loss="mae",
        metrics=["mae"],
    )
    return model


model = build_deep_cnn(INPUT_WINDOW, X_train.shape[2])
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 30, 23)    │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d (Conv1D)     │ (None, 30, 64)    │      4,480 │ input_layer[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalization │ (None, 30, 64)    │        256 │ conv1d[0][0]      │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ spatial_dropout1d   │ (None, 30, 64)    │          0 │ batch_normalizat… │
│ (SpatialDropout1D)  │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_1 (Conv1D)   │ (None, 30, 64)    │     20,544 │ spatial_dropout1… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 30, 64)    │        256 │ conv1d_1[0][0]    │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ spatial_dropout1d_1 │ (None, 30, 64)    │          0 │ batch_normalizat… │
│ (SpatialDropout1D)  │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ conv1d_2 (Conv1D)   │ (None, 30, 128)   │     24,704 │ spatial_dropout1… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ batch_normalizatio… │ (None, 30, 128)   │        512 │ conv1d_2[0][0]    │
│ (BatchNormalizatio… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_average_poo… │ (None, 128)       │          0 │ batch_normalizat… │
│ (GlobalAveragePool… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ global_max_pooling… │ (None, 128)       │          0 │ batch_normalizat… │
│ (GlobalMaxPooling1… │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 256)       │          0 │ global_average_p… │
│ (Concatenate)       │                   │            │ global_max_pooli… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 128)       │     32,896 │ concatenate[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 128)       │          0 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 64)        │      8,256 │ dropout[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 64)        │          0 │ dense_1[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 23)        │      1,495 │ dropout_1[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 93,399 (364.84 KB)

 Trainable params: 92,887 (362.84 KB)

 Non-trainable params: 512 (2.00 KB)

## Training

We use `EarlyStopping` to stop when validation MAE no longer improves and `ReduceLROnPlateau` to reduce the learning rate when the validation loss reaches a plateau.

In [5]:
callbacks = [
    EarlyStopping(
        monitor="val_loss",
        patience=20,
        min_delta=1e-6,
        restore_best_weights=True,
    ),
    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=8,
        min_lr=1e-6,
    ),
]

history = model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=callbacks,
    verbose=1,
    shuffle=True,
)

Epoch 1/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:43 2s/step - loss: 1.8742 - mae: 1.8742

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.6944 - mae: 1.6944

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.5405 - mae: 1.5405

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.4136 - mae: 1.4136

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.3091 - mae: 1.3091

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.2214 - mae: 1.2214

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.1466 - mae: 1.1466

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0816 - mae: 1.0816

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0244 - mae: 1.0244

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9738 - mae: 0.9738

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9286 - mae: 0.9286

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8945 - mae: 0.8945

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8632 - mae: 0.8632

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8343 - mae: 0.8343

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.8075 - mae: 0.8075

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7827 - mae: 0.7827

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7595 - mae: 0.7595

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7379 - mae: 0.7379

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.7176 - mae: 0.7176

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 0.3192 - mae: 0.3192 - val_loss: 0.0056 - val_mae: 0.0056 - learning_rate: 3.0000e-04

Epoch 2/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0325 - mae: 0.0325

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0320 - mae: 0.0320

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0314 - mae: 0.0314

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0308 - mae: 0.0308

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0301 - mae: 0.0301

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0294 - mae: 0.0294

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0288 - mae: 0.0288

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0282 - mae: 0.0282

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0277 - mae: 0.0277

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0272 - mae: 0.0272

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0267 - mae: 0.0267

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0263 - mae: 0.0263

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0259 - mae: 0.0259

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0255 - mae: 0.0255

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0251 - mae: 0.0251

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0248 - mae: 0.0248

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0244 - mae: 0.0244

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0241 - mae: 0.0241

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0239 - mae: 0.0239

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0236 - mae: 0.0236

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0234 - mae: 0.0234

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0176 - mae: 0.0176 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 3/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0064 - mae: 0.0064

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0085 - mae: 0.0085

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0092 - mae: 0.0092

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0095 - mae: 0.0095

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0097 - mae: 0.0097

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0098 - mae: 0.0098

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0098 - mae: 0.0098

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0099 - mae: 0.0099

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0098 - mae: 0.0098

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0098 - mae: 0.0098

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0098 - mae: 0.0098

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0098 - mae: 0.0098

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0098 - mae: 0.0098

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0097 - mae: 0.0097

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0097 - mae: 0.0097

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0097 - mae: 0.0097

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0096 - mae: 0.0096

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0096 - mae: 0.0096

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0096 - mae: 0.0096

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0096 - mae: 0.0096

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0095 - mae: 0.0095

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0095 - mae: 0.0095

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0095 - mae: 0.0095

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0087 - mae: 0.0087 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 4/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0065 - mae: 0.0065

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0070 - mae: 0.0070

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0072 - mae: 0.0072

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0073 - mae: 0.0073

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0074 - mae: 0.0074

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0074 - mae: 0.0074

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0075 - mae: 0.0075

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0075 - mae: 0.0075

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0075 - mae: 0.0075

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0076 - mae: 0.0076

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0076 - mae: 0.0076

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0076 - mae: 0.0076

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0076 - mae: 0.0076

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0076 - mae: 0.0076

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0076 - mae: 0.0076

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0076 - mae: 0.0076

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0076 - mae: 0.0076

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0075 - mae: 0.0075

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0075 - mae: 0.0075

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0075 - mae: 0.0075

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0075 - mae: 0.0075

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0075 - mae: 0.0075

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0075 - mae: 0.0075

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0073 - mae: 0.0073 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 5/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0067 - mae: 0.0067

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0065 - mae: 0.0065

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0065 - mae: 0.0065

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0066 - mae: 0.0066

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0067 - mae: 0.0067

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0067 - mae: 0.0067

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0067 - mae: 0.0067

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0067 - mae: 0.0067

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0067 - mae: 0.0067

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0067 - mae: 0.0067

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0067 - mae: 0.0067

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0067 - mae: 0.0067

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0066 - mae: 0.0066

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0066 - mae: 0.0066

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0066 - mae: 0.0066

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0066 - mae: 0.0066

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0066 - mae: 0.0066

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0066 - mae: 0.0066

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0066 - mae: 0.0066

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0066 - mae: 0.0066

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0066 - mae: 0.0066

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0066 - mae: 0.0066

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0064 - mae: 0.0064 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 6/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0059 - mae: 0.0059

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0060 - mae: 0.0060

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0062 - mae: 0.0062

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0062 - mae: 0.0062

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0062 - mae: 0.0062 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 7/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0077 - mae: 0.0077

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0074 - mae: 0.0074

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0071 - mae: 0.0071

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0070 - mae: 0.0070

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0068 - mae: 0.0068

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0067 - mae: 0.0067

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0066 - mae: 0.0066

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0066 - mae: 0.0066

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0066 - mae: 0.0066

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0065 - mae: 0.0065

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0065 - mae: 0.0065

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0065 - mae: 0.0065

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0065 - mae: 0.0065

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0065 - mae: 0.0065

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0064 - mae: 0.0064

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0064 - mae: 0.0064

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0064 - mae: 0.0064

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0064 - mae: 0.0064

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0064 - mae: 0.0064

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0064 - mae: 0.0064

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0061 - mae: 0.0061 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 8/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 9/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 10/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0056 - mae: 0.0056

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0056 - mae: 0.0056

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0056 - mae: 0.0056

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0056 - mae: 0.0056

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0057 - mae: 0.0057

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0057 - mae: 0.0057

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0057 - mae: 0.0057

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0057 - mae: 0.0057

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0057 - mae: 0.0057

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0057 - mae: 0.0057

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0057 - mae: 0.0057

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 11/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0063 - mae: 0.0063

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0062 - mae: 0.0062

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0061 - mae: 0.0061

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0060 - mae: 0.0060

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0060 - mae: 0.0060

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0059 - mae: 0.0059

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0059 - mae: 0.0059

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0059 - mae: 0.0059

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0058 - mae: 0.0058

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0058 - mae: 0.0058

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 12/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 13/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 14/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 15/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 16/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 17/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 18/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0057 - mae: 0.0057

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0057 - mae: 0.0057

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0057 - mae: 0.0057

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0057 - mae: 0.0057

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0057 - mae: 0.0057

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 19/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 20/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0053 - mae: 0.0053

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 21/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0056 - mae: 0.0056

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0056 - mae: 0.0056

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0056 - mae: 0.0056

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0056 - mae: 0.0056

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0056 - mae: 0.0056

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0056 - mae: 0.0056

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0056 - mae: 0.0056

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0056 - mae: 0.0056

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 22/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0053 - mae: 0.0053

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 23/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0053 - mae: 0.0053

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0053 - mae: 0.0053

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 24/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 25/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 26/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 27/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 28/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 29/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 30/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0053 - mae: 0.0053

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0053 - mae: 0.0053

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 31/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0061 - mae: 0.0061

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0057 - mae: 0.0057

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 32/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0053 - mae: 0.0053

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 33/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 34/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0053 - mae: 0.0053

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 35/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 36/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 37/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0053 - mae: 0.0053

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 38/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0053 - mae: 0.0053

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 39/150

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0053 - mae: 0.0053

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0053 - mae: 0.0053

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

## Evaluation and saved outputs

The model is evaluated on train, validation and test. The notebook also compares the test MAE against the linear regression benchmark provided in the repository when available.

In [6]:
y_pred_train = model.predict(X_train, verbose=0)
y_pred_val = model.predict(X_val, verbose=0)
y_pred_test = model.predict(X_test, verbose=0)

result = {
    "model": "CNN_Deep_Conv1D",
    "input_window": INPUT_WINDOW,
    "output_window": OUTPUT_WINDOW,
    "MAE_train": mean_absolute_error(y_train, y_pred_train),
    "MAE_val": mean_absolute_error(y_val, y_pred_val),
    "MAE_test": mean_absolute_error(y_test, y_pred_test),
    "params": model.count_params(),
    "epochs_trained": len(history.history["loss"]),
}

results_df = pd.DataFrame([result])
results_path = OUTPUT_DIR / f"cnn_deep_{INPUT_WINDOW}_{OUTPUT_WINDOW}_results.csv"
results_df.to_csv(results_path, index=False)

history_df = pd.DataFrame(history.history)
history_path = OUTPUT_DIR / f"cnn_deep_{INPUT_WINDOW}_{OUTPUT_WINDOW}_history.csv"
history_df.to_csv(history_path, index=False)

model_path = OUTPUT_DIR / f"cnn_deep_{INPUT_WINDOW}_{OUTPUT_WINDOW}.keras"
model.save(model_path)

curve_path = OUTPUT_DIR / f"cnn_deep_{INPUT_WINDOW}_{OUTPUT_WINDOW}_training_curve.png"
plt.figure(figsize=(8, 4))
plt.plot(history_df["loss"], label="Train loss")
plt.plot(history_df["val_loss"], label="Validation loss")
plt.title(f"CNN Deep - input={INPUT_WINDOW}, output={OUTPUT_WINDOW}")
plt.xlabel("Epoch")
plt.ylabel("MAE")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.savefig(curve_path, dpi=150)
plt.show()

comparison_df = None
lr_path = PROJECT_ROOT / "data" / "lr_benchmark.csv"
if lr_path.exists():
    lr = pd.read_csv(lr_path)
    lr_match = lr[(lr["input_window"] == INPUT_WINDOW) & (lr["output_window"] == OUTPUT_WINDOW)]
    if len(lr_match) == 1:
        lr_row = lr_match.iloc[0]
        comparison_df = pd.DataFrame([
            {
                "model": "Linear_Regression_Benchmark",
                "input_window": INPUT_WINDOW,
                "output_window": OUTPUT_WINDOW,
                "MAE_train": lr_row["MAE_train"],
                "MAE_val": np.nan,
                "MAE_test": lr_row["MAE_test"],
                "params": np.nan,
                "epochs_trained": np.nan,
            },
            result,
        ])
        comparison_df["improvement_abs_vs_lr"] = comparison_df["MAE_test"].iloc[0] - comparison_df["MAE_test"]
        comparison_df["improvement_pct_vs_lr"] = (
            comparison_df["improvement_abs_vs_lr"] / comparison_df["MAE_test"].iloc[0] * 100
        )
        comparison_path = OUTPUT_DIR / f"cnn_deep_{INPUT_WINDOW}_{OUTPUT_WINDOW}_comparison_vs_lr.csv"
        comparison_df.to_csv(comparison_path, index=False)

print("Results saved to:", results_path)
print("History saved to:", history_path)
print("Model saved to:", model_path)
print("Curve saved to:", curve_path)

display(results_df)
if comparison_df is not None:
    display(comparison_df)

Results saved to: /Users/jchulvi/projects/Neural-Networks-Forecasting/data/cnn/cnn_deep_30_5_results.csv
History saved to: /Users/jchulvi/projects/Neural-Networks-Forecasting/data/cnn/cnn_deep_30_5_history.csv
Model saved to: /Users/jchulvi/projects/Neural-Networks-Forecasting/data/cnn/cnn_deep_30_5.keras
Curve saved to: /Users/jchulvi/projects/Neural-Networks-Forecasting/data/cnn/cnn_deep_30_5_training_curve.png

/var/folders/py/c5_xfbqn469g5_844mv32gt40000gn/T/ipykernel_67584/952401653.py:38: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

,model,input_window,output_window,MAE_train,MAE_val,MAE_test,params,epochs_trained
0,CNN_Deep_Conv1D,30,5,0.005474,0.004141,0.005595,93399,39

,model,input_window,output_window,MAE_train,MAE_val,MAE_test,params,epochs_trained,improvement_abs_vs_lr,improvement_pct_vs_lr
0,Linear_Regression_Benchmark,30,5,0.005337,NaN,0.005877,NaN,NaN,0.000000,0.00000
1,CNN_Deep_Conv1D,30,5,0.005474,0.004141,0.005595,93399.0,39.0,0.000282,4.79148

## Interpretation

In the exploratory run, this architecture improved the linear regression benchmark for `30 → 5` with a test MAE around `0.00558` versus the benchmark around `0.00588`. The validation curve tends to become flat quickly because the target returns are centered close to zero, so a conservative prediction already gives a competitive MAE.