# CNN hyperparameter search

This notebook performs a lightweight random search for the CNN model.

The selection rule is:

```text
choose the configuration with the lowest validation MAE
```

The test set is not used during hyperparameter selection. It is evaluated only once at the end using the best validation configuration.

In [1]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

from pathlib import Path
import sys
import json
import random

import numpy as np
import pandas as pd

from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler

import keras
from keras import backend as K
from keras.layers import (
    Input,
    Conv1D,
    BatchNormalization,
    SpatialDropout1D,
    GlobalAveragePooling1D,
    GlobalMaxPooling1D,
    Concatenate,
    Dense,
    Dropout,
)
from keras.models import Model
from keras.callbacks import EarlyStopping, ReduceLROnPlateau

def find_project_root(start=None):
    start = Path.cwd() if start is None else Path(start)
    for candidate in [start, *start.parents]:
        if (candidate / "util.py").exists() and (candidate / "data").exists():
            return candidate
    raise FileNotFoundError("Could not find project root containing util.py and data/")

PROJECT_ROOT = find_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from util import get_train_test, RANDOM_SEED

OUTPUT_DIR = PROJECT_ROOT / "data" / "cnn_search"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
TRIAL_HISTORY_DIR = OUTPUT_DIR / "trial_histories"
TRIAL_HISTORY_DIR.mkdir(parents=True, exist_ok=True)

np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)
keras.utils.set_random_seed(RANDOM_SEED)

print("Project root:", PROJECT_ROOT)
print("Output dir:", OUTPUT_DIR)

Project root: /Users/jchulvi/projects/Neural-Networks-Forecasting
Output dir: /Users/jchulvi/projects/Neural-Networks-Forecasting/data/cnn_search

## Search configuration

The default search is centered on the validated `30 → 5` setup. Increase `N_TRIALS` for a more complete search or reduce it temporarily for a quick smoke test.

In [2]:
INPUT_WINDOW = 30
OUTPUT_WINDOW = 5
VALIDATION_RATIO = 0.10

N_TRIALS = 15
EPOCHS = 100

## Data preparation

As in the CNN Deep notebook, the scaler is fitted only on the training split and then applied to validation and test.

In [3]:
def split_train_val(X_train, y_train, val_ratio=0.10):
    val_size = int(len(X_train) * val_ratio)
    if val_size <= 0:
        raise ValueError("Validation split is empty. Increase training size or val_ratio.")

    X_val = X_train[-val_size:]
    y_val = y_train[-val_size:]
    X_train_final = X_train[:-val_size]
    y_train_final = y_train[:-val_size]
    return X_train_final, y_train_final, X_val, y_val


def scale_X_only(X_train, X_val, X_test):
    n_train, window, n_assets = X_train.shape
    n_val = X_val.shape[0]
    n_test = X_test.shape[0]

    scaler = StandardScaler()
    X_train_2d = X_train.reshape(n_train, -1)
    X_val_2d = X_val.reshape(n_val, -1)
    X_test_2d = X_test.reshape(n_test, -1)

    X_train_scaled = scaler.fit_transform(X_train_2d).reshape(n_train, window, n_assets)
    X_val_scaled = scaler.transform(X_val_2d).reshape(n_val, window, n_assets)
    X_test_scaled = scaler.transform(X_test_2d).reshape(n_test, window, n_assets)
    return X_train_scaled, X_val_scaled, X_test_scaled


d = get_train_test(INPUT_WINDOW, OUTPUT_WINDOW)

X_train_raw, y_train_raw = d.X_train, d.y_train
X_test_raw, y_test = d.X_test, d.y_test

X_train_raw, y_train, X_val_raw, y_val = split_train_val(
    X_train_raw, y_train_raw, val_ratio=VALIDATION_RATIO
)
X_train, X_val, X_test = scale_X_only(X_train_raw, X_val_raw, X_test_raw)

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)
print("X_val:  ", X_val.shape)
print("y_val:  ", y_val.shape)
print("X_test: ", X_test.shape)
print("y_test: ", y_test.shape)

X_train: (13090, 30, 23)
y_train: (13090, 23)
X_val:   (1454, 30, 23)
y_val:   (1454, 23)
X_test:  (1617, 30, 23)
y_test:  (1617, 23)

## Hyperparameter space

The search varies filters, kernel sizes, dilation, dropout, dense layer sizes, learning rate and batch size. This is a controlled random search, not an exhaustive grid search.

In [4]:
def sample_config(trial_id):
    cfg = {
        "filters_1": random.choice([32, 64, 96]),
        "filters_2": random.choice([32, 64, 96]),
        "filters_3": random.choice([64, 96, 128]),
        "kernel_1": random.choice([3, 5]),
        "kernel_2": random.choice([3, 5, 7]),
        "kernel_3": random.choice([3, 5]),
        "dilation_2": random.choice([1, 2]),
        "dilation_3": random.choice([2, 4]),
        "spatial_dropout": random.choice([0.05, 0.10, 0.15, 0.20]),
        "dense_1": random.choice([64, 128, 256]),
        "dense_2": random.choice([32, 64, 128]),
        "dropout_1": random.choice([0.10, 0.20, 0.30]),
        "dropout_2": random.choice([0.05, 0.10, 0.20]),
        "learning_rate": random.choice([1e-3, 5e-4, 3e-4, 1e-4]),
        "batch_size": random.choice([64, 128, 256]),
    }
    cfg["trial_id"] = trial_id
    return cfg


def build_model(input_window, n_assets, cfg):
    inputs = Input(shape=(input_window, n_assets))

    x = Conv1D(cfg["filters_1"], cfg["kernel_1"], padding="causal", activation="relu")(inputs)
    x = BatchNormalization()(x)
    x = SpatialDropout1D(cfg["spatial_dropout"])(x)

    x = Conv1D(
        cfg["filters_2"],
        cfg["kernel_2"],
        padding="causal",
        dilation_rate=cfg["dilation_2"],
        activation="relu",
    )(x)
    x = BatchNormalization()(x)
    x = SpatialDropout1D(cfg["spatial_dropout"])(x)

    x = Conv1D(
        cfg["filters_3"],
        cfg["kernel_3"],
        padding="causal",
        dilation_rate=cfg["dilation_3"],
        activation="relu",
    )(x)
    x = BatchNormalization()(x)

    avg_pool = GlobalAveragePooling1D()(x)
    max_pool = GlobalMaxPooling1D()(x)
    x = Concatenate()([avg_pool, max_pool])

    x = Dense(cfg["dense_1"], activation="relu")(x)
    x = Dropout(cfg["dropout_1"])(x)
    x = Dense(cfg["dense_2"], activation="relu")(x)
    x = Dropout(cfg["dropout_2"])(x)

    outputs = Dense(n_assets, activation="linear")(x)
    model = Model(inputs=inputs, outputs=outputs)

    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=cfg["learning_rate"]),
        loss="mae",
        metrics=["mae"],
    )
    return model

## Random search

Each trial is selected by validation MAE. During the search, partial results are saved to disk so the experiment can be inspected even if it is interrupted.

In [5]:
def train_trial(trial_id, cfg):
    K.clear_session()
    keras.utils.set_random_seed(RANDOM_SEED + trial_id)

    model = build_model(INPUT_WINDOW, X_train.shape[2], cfg)

    callbacks = [
        EarlyStopping(
            monitor="val_loss",
            patience=15,
            min_delta=1e-6,
            restore_best_weights=True,
        ),
        ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.5,
            patience=6,
            min_lr=1e-6,
        ),
    ]

    print("\n" + "=" * 80)
    print(f"Trial {trial_id}/{N_TRIALS}")
    print(json.dumps(cfg, indent=2))
    print("=" * 80)

    history = model.fit(
        X_train,
        y_train,
        validation_data=(X_val, y_val),
        epochs=EPOCHS,
        batch_size=cfg["batch_size"],
        callbacks=callbacks,
        verbose=1,
        shuffle=True,
    )

    y_pred_train = model.predict(X_train, verbose=0)
    y_pred_val = model.predict(X_val, verbose=0)

    row = {
        "trial_id": trial_id,
        "input_window": INPUT_WINDOW,
        "output_window": OUTPUT_WINDOW,
        "MAE_train": mean_absolute_error(y_train, y_pred_train),
        "MAE_val": mean_absolute_error(y_val, y_pred_val),
        "params": model.count_params(),
        "epochs_trained": len(history.history["loss"]),
        **cfg,
    }

    pd.DataFrame(history.history).to_csv(TRIAL_HISTORY_DIR / f"trial_{trial_id:02d}_history.csv", index=False)
    return row, model


rows = []
best_val = float("inf")
best_trial_id = None
best_config = None

for trial_id in range(1, N_TRIALS + 1):
    cfg = sample_config(trial_id)
    row, model = train_trial(trial_id, cfg)
    rows.append(row)

    partial_df = pd.DataFrame(rows).sort_values("MAE_val")
    partial_df.to_csv(OUTPUT_DIR / "cnn_hyperparameter_trials_partial.csv", index=False)

    if row["MAE_val"] < best_val:
        best_val = row["MAE_val"]
        best_trial_id = trial_id
        best_config = cfg
        model.save(OUTPUT_DIR / "best_cnn_model.keras")
        with open(OUTPUT_DIR / "best_config.json", "w", encoding="utf-8") as f:
            json.dump(best_config, f, indent=2)
        print(f"New best model: trial {trial_id}, MAE_val={best_val:.10f}")

trials_df = pd.DataFrame(rows).sort_values("MAE_val").reset_index(drop=True)
trials_path = OUTPUT_DIR / "cnn_hyperparameter_trials.csv"
trials_df.to_csv(trials_path, index=False)

display(trials_df.head(10))
print("Trials saved to:", trials_path)
print("Best config saved to:", OUTPUT_DIR / "best_config.json")

================================================================================
Trial 1/15
{
  "filters_1": 96,
  "filters_2": 32,
  "filters_3": 64,
  "kernel_1": 5,
  "kernel_2": 3,
  "kernel_3": 3,
  "dilation_2": 1,
  "dilation_3": 2,
  "spatial_dropout": 0.05,
  "dense_1": 256,
  "dense_2": 64,
  "dropout_1": 0.1,
  "dropout_2": 0.05,
  "learning_rate": 0.001,
  "batch_size": 64,
  "trial_id": 1
}
================================================================================
Epoch 1/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5:18 2s/step - loss: 0.9901 - mae: 0.9901

 13/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.5288 - mae: 0.5288

 26/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.3641 - mae: 0.3641

 39/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2830 - mae: 0.2830

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2372 - mae: 0.2372

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2056 - mae: 0.2056

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1822 - mae: 0.1822

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1642 - mae: 0.1642

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1499 - mae: 0.1499

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1390 - mae: 0.1390

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1298 - mae: 0.1298

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1219 - mae: 0.1219

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1151 - mae: 0.1151

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1090 - mae: 0.1090

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1037 - mae: 0.1037

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.0989 - mae: 0.0989

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0947 - mae: 0.0947

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0908 - mae: 0.0908

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - loss: 0.0239 - mae: 0.0239 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 2/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0057 - mae: 0.0057

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 3/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 4/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 44/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 77/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 5/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0058 - mae: 0.0058

 11/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 32/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 42/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 53/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 64/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 86/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 6/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 7/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0058 - mae: 0.0058

 11/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 32/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 43/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 54/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 8/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0058 - mae: 0.0058

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 62/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 83/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 93/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

103/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 9/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 10/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

103/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 11/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 12/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 13/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 14/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 15/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0058 - mae: 0.0058

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 16/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0057 - mae: 0.0057

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 17/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0057 - mae: 0.0057

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 18/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0057 - mae: 0.0057

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 19/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0057 - mae: 0.0057

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 20/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0057 - mae: 0.0057

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 21/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0058 - mae: 0.0058

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 22/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0058 - mae: 0.0058

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 23/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0058 - mae: 0.0058

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 24/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0058 - mae: 0.0058

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 16/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 24/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 32/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 25/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0058 - mae: 0.0058

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0056 - mae: 0.0056

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 26/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0058 - mae: 0.0058

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 27/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 16/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 86/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 28/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 32/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 29/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0056 - mae: 0.0056

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0056 - mae: 0.0056

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 86/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 30/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 16/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 30/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 31/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0058 - mae: 0.0058

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0056 - mae: 0.0056

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0056 - mae: 0.0056

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0056 - mae: 0.0056

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

New best model: trial 1, MAE_val=0.0041383760

================================================================================
Trial 2/15
{
  "filters_1": 32,
  "filters_2": 64,
  "filters_3": 128,
  "kernel_1": 5,
  "kernel_2": 7,
  "kernel_3": 3,
  "dilation_2": 2,
  "dilation_3": 4,
  "spatial_dropout": 0.2,
  "dense_1": 128,
  "dense_2": 32,
  "dropout_1": 0.1,
  "dropout_2": 0.05,
  "learning_rate": 0.001,
  "batch_size": 128,
  "trial_id": 2
}
================================================================================
Epoch 1/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:41 2s/step - loss: 1.9878 - mae: 1.9878

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 1.5115 - mae: 1.5115

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 1.1875 - mae: 1.1875

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.9879 - mae: 0.9879

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.8498 - mae: 0.8498

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7486 - mae: 0.7486

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6853 - mae: 0.6853

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6330 - mae: 0.6330

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5890 - mae: 0.5890

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5514 - mae: 0.5514

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5189 - mae: 0.5189

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4905 - mae: 0.4905

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4654 - mae: 0.4654

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4431 - mae: 0.4431

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4230 - mae: 0.4230

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4050 - mae: 0.4050

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3886 - mae: 0.3886

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3736 - mae: 0.3736

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3599 - mae: 0.3599

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3473 - mae: 0.3473

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3356 - mae: 0.3356

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3223 - mae: 0.3223

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.3101 - mae: 0.3101

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.2989 - mae: 0.2989

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0826 - mae: 0.0826 - val_loss: 0.0044 - val_mae: 0.0044 - learning_rate: 0.0010

Epoch 2/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0056 - mae: 0.0056

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0056 - mae: 0.0056

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0057 - mae: 0.0057

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0057 - mae: 0.0057

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0058 - mae: 0.0058

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0058 - mae: 0.0058

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0058 - mae: 0.0058

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0058 - mae: 0.0058

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0058 - mae: 0.0058

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0058 - mae: 0.0058

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0058 - mae: 0.0058

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 3/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 4/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 5/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 6/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 7/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 8/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 9/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 10/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 11/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 12/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 13/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0057 - mae: 0.0057

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0057 - mae: 0.0057

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0057 - mae: 0.0057

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0057 - mae: 0.0057

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0057 - mae: 0.0057

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0057 - mae: 0.0057

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0057 - mae: 0.0057

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0057 - mae: 0.0057

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0057 - mae: 0.0057

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 14/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 15/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 16/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 17/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 18/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 19/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 20/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 21/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.0055 - mae: 0.0055

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0056 - mae: 0.0056

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 22/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 23/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 24/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 25/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 26/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 27/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 28/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 29/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 30/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 31/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 32/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

New best model: trial 2, MAE_val=0.0041367089

================================================================================
Trial 3/15
{
  "filters_1": 32,
  "filters_2": 32,
  "filters_3": 64,
  "kernel_1": 3,
  "kernel_2": 3,
  "kernel_3": 3,
  "dilation_2": 2,
  "dilation_3": 4,
  "spatial_dropout": 0.2,
  "dense_1": 256,
  "dense_2": 128,
  "dropout_1": 0.2,
  "dropout_2": 0.1,
  "learning_rate": 0.001,
  "batch_size": 128,
  "trial_id": 3
}
================================================================================
Epoch 1/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:43 2s/step - loss: 1.1895 - mae: 1.1895

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.9694 - mae: 0.9694

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.8113 - mae: 0.8113

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.6926 - mae: 0.6926

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.6095 - mae: 0.6095

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.5459 - mae: 0.5459

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4951 - mae: 0.4951

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4537 - mae: 0.4537

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4193 - mae: 0.4193

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3903 - mae: 0.3903

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3655 - mae: 0.3655

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3440 - mae: 0.3440

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3252 - mae: 0.3252

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3117 - mae: 0.3117

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2938 - mae: 0.2938

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2806 - mae: 0.2806

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2664 - mae: 0.2664

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2557 - mae: 0.2557

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2442 - mae: 0.2442

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2354 - mae: 0.2354

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2289 - mae: 0.2289

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 0.0715 - mae: 0.0715 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 2/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 3/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0056 - mae: 0.0056

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0056 - mae: 0.0056

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 4/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 5/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0052 - mae: 0.0052

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 6/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 7/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 8/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0052 - mae: 0.0052

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 9/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 10/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 11/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0052 - mae: 0.0052

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 12/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 13/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 14/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 15/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 16/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 17/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0052 - mae: 0.0052

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 18/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 19/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 20/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 21/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 22/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 23/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0052 - mae: 0.0052

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 24/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 25/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0052 - mae: 0.0052

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 26/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0052 - mae: 0.0052

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 27/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 28/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0052 - mae: 0.0052

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 29/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0052 - mae: 0.0052

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

================================================================================
Trial 4/15
{
  "filters_1": 32,
  "filters_2": 32,
  "filters_3": 96,
  "kernel_1": 3,
  "kernel_2": 5,
  "kernel_3": 3,
  "dilation_2": 1,
  "dilation_3": 2,
  "spatial_dropout": 0.15,
  "dense_1": 256,
  "dense_2": 32,
  "dropout_1": 0.1,
  "dropout_2": 0.2,
  "learning_rate": 0.0001,
  "batch_size": 64,
  "trial_id": 4
}
================================================================================
Epoch 1/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5:29 2s/step - loss: 0.9782 - mae: 0.9782

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.8321 - mae: 0.8321

 16/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.7578 - mae: 0.7578

 23/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.6975 - mae: 0.6975

 32/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.6328 - mae: 0.6328

 40/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.5841 - mae: 0.5841

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.5473 - mae: 0.5473

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.5106 - mae: 0.5106

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4787 - mae: 0.4787

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4509 - mae: 0.4509

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4236 - mae: 0.4236

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3973 - mae: 0.3973

102/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3702 - mae: 0.3702

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3525 - mae: 0.3525

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3350 - mae: 0.3350

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3208 - mae: 0.3208

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3066 - mae: 0.3066

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2938 - mae: 0.2938

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2822 - mae: 0.2822

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2726 - mae: 0.2726

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2637 - mae: 0.2637

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2554 - mae: 0.2554

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2478 - mae: 0.2478

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 0.0836 - mae: 0.0836 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.0000e-04

Epoch 2/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0105 - mae: 0.0105

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0080 - mae: 0.0080

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0077 - mae: 0.0077

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0075 - mae: 0.0075

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0073 - mae: 0.0073

 50/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0072 - mae: 0.0072

 60/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0071 - mae: 0.0071

 69/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0070 - mae: 0.0070

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0069 - mae: 0.0069

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0069 - mae: 0.0069

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0068 - mae: 0.0068

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0068 - mae: 0.0068

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0068 - mae: 0.0068

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0067 - mae: 0.0067

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0067 - mae: 0.0067

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0067 - mae: 0.0067

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0067 - mae: 0.0067

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0067 - mae: 0.0067

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0066 - mae: 0.0066

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0066 - mae: 0.0066

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0066 - mae: 0.0066

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0066 - mae: 0.0066

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0063 - mae: 0.0063 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.0000e-04

Epoch 3/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0057 - mae: 0.0057

 21/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0057 - mae: 0.0057

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0057 - mae: 0.0057

 49/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 58/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 76/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 86/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.0000e-04

Epoch 4/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0058 - mae: 0.0058

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0057 - mae: 0.0057

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 49/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 59/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 69/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.0000e-04

Epoch 5/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0057 - mae: 0.0057

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 86/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.0000e-04

Epoch 6/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0057 - mae: 0.0057

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 69/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 77/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 93/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.0000e-04

Epoch 7/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0057 - mae: 0.0057

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.0000e-04

Epoch 8/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 48/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-05

Epoch 9/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0057 - mae: 0.0057

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0060 - mae: 0.0060

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0058 - mae: 0.0058

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0057 - mae: 0.0057

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 50/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 60/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-05

Epoch 10/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0056 - mae: 0.0056

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 59/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 69/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-05

Epoch 11/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0057 - mae: 0.0057

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0061 - mae: 0.0061

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0059 - mae: 0.0059

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0057 - mae: 0.0057

 38/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 47/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-05

Epoch 12/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0057 - mae: 0.0057

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0057 - mae: 0.0057

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0057 - mae: 0.0057

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 38/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 86/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-05

Epoch 13/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0057 - mae: 0.0057

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 53/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 69/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 77/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 94/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-05

Epoch 14/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0057 - mae: 0.0057

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 76/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 86/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-05

Epoch 15/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0056 - mae: 0.0056

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 76/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 84/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 94/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-05

Epoch 16/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0057 - mae: 0.0057

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 38/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 48/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-05

================================================================================
Trial 5/15
{
  "filters_1": 96,
  "filters_2": 32,
  "filters_3": 128,
  "kernel_1": 3,
  "kernel_2": 3,
  "kernel_3": 3,
  "dilation_2": 2,
  "dilation_3": 2,
  "spatial_dropout": 0.05,
  "dense_1": 64,
  "dense_2": 128,
  "dropout_1": 0.2,
  "dropout_2": 0.2,
  "learning_rate": 0.0003,
  "batch_size": 256,
  "trial_id": 5
}
================================================================================
Epoch 1/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1:21 2s/step - loss: 1.3050 - mae: 1.3050

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 1.2402 - mae: 1.2402

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1.1857 - mae: 1.1857

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.1349 - mae: 1.1349

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.0876 - mae: 1.0876

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.0436 - mae: 1.0436

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1.0033 - mae: 1.0033

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.9665 - mae: 0.9665

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.9325 - mae: 0.9325

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.9011 - mae: 0.9011

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.8718 - mae: 0.8718

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.8444 - mae: 0.8444

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.8186 - mae: 0.8186

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.7943 - mae: 0.7943

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.7714 - mae: 0.7714

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.7498 - mae: 0.7498

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.7293 - mae: 0.7293

52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - loss: 0.3926 - mae: 0.3926 - val_loss: 0.0258 - val_mae: 0.0258 - learning_rate: 3.0000e-04

Epoch 2/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0346 - mae: 0.0346

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0279 - mae: 0.0279

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0256 - mae: 0.0256

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0240 - mae: 0.0240

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0226 - mae: 0.0226

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0216 - mae: 0.0216

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0207 - mae: 0.0207

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0199 - mae: 0.0199

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0192 - mae: 0.0192

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0186 - mae: 0.0186

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0180 - mae: 0.0180

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0175 - mae: 0.0175

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0170 - mae: 0.0170

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0166 - mae: 0.0166

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0162 - mae: 0.0162

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0158 - mae: 0.0158

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0155 - mae: 0.0155

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0103 - mae: 0.0103 - val_loss: 0.0107 - val_mae: 0.0107 - learning_rate: 3.0000e-04

Epoch 3/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0062 - mae: 0.0062

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0060 - mae: 0.0060

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0062 - mae: 0.0062

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0063 - mae: 0.0063

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0064 - mae: 0.0064

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0064 - mae: 0.0064

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0065 - mae: 0.0065

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0065 - mae: 0.0065

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0065 - mae: 0.0065

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0065 - mae: 0.0065

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0065 - mae: 0.0065

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0065 - mae: 0.0065

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0065 - mae: 0.0065

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0065 - mae: 0.0065

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0065 - mae: 0.0065

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0065 - mae: 0.0065

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0065 - mae: 0.0065

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0063 - mae: 0.0063 - val_loss: 0.0076 - val_mae: 0.0076 - learning_rate: 3.0000e-04

Epoch 4/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0056 - mae: 0.0056

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0056 - mae: 0.0056

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0057 - mae: 0.0057

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0057 - mae: 0.0057

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0058 - mae: 0.0058

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0058 - mae: 0.0058

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0058 - mae: 0.0058

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0058 - mae: 0.0058

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0059 - mae: 0.0059

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0059 - mae: 0.0059

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0059 - mae: 0.0059

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0059 - mae: 0.0059

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0059 - mae: 0.0059

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0059 - mae: 0.0059

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0059 - mae: 0.0059

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0059 - mae: 0.0059

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0059 - mae: 0.0059

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0061 - val_mae: 0.0061 - learning_rate: 3.0000e-04

Epoch 5/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0060 - mae: 0.0060

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0060 - mae: 0.0060

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0060 - mae: 0.0060

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0060 - mae: 0.0060

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0060 - mae: 0.0060

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0060 - mae: 0.0060

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0060 - mae: 0.0060

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0059 - mae: 0.0059

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0059 - mae: 0.0059

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0059 - mae: 0.0059

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0059 - mae: 0.0059

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0059 - mae: 0.0059

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0059 - mae: 0.0059

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0059 - mae: 0.0059

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0059 - mae: 0.0059

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0059 - mae: 0.0059

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0059 - mae: 0.0059

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0059 - mae: 0.0059

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0059 - mae: 0.0059

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0059 - mae: 0.0059

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0049 - val_mae: 0.0049 - learning_rate: 3.0000e-04

Epoch 6/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0058 - mae: 0.0058

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0057 - mae: 0.0057

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0057 - mae: 0.0057

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0057 - mae: 0.0057

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0045 - val_mae: 0.0045 - learning_rate: 3.0000e-04

Epoch 7/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0056 - mae: 0.0056

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0056 - mae: 0.0056

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0057 - mae: 0.0057

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0043 - val_mae: 0.0043 - learning_rate: 3.0000e-04

Epoch 8/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0043 - val_mae: 0.0043 - learning_rate: 3.0000e-04

Epoch 9/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 10/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 11/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 12/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 13/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 14/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 15/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 16/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 17/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 18/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0053 - mae: 0.0053

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0053 - mae: 0.0053

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 19/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0054 - mae: 0.0054

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 20/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 21/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 22/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0054 - mae: 0.0054

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 23/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 24/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 25/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 26/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0053 - mae: 0.0053

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 27/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 28/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0054 - mae: 0.0054

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 29/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 30/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0053 - mae: 0.0053

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 31/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0053 - mae: 0.0053

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0053 - mae: 0.0053

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0054 - mae: 0.0054

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 32/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0053 - mae: 0.0053

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 33/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0053 - mae: 0.0053

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 34/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0054 - mae: 0.0054

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0054 - mae: 0.0054

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 35/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0053 - mae: 0.0053

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 36/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 37/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0053 - mae: 0.0053

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0053 - mae: 0.0053

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0054 - mae: 0.0054

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 38/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 39/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0053 - mae: 0.0053

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 40/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 9.3750e-06

================================================================================
Trial 6/15
{
  "filters_1": 64,
  "filters_2": 96,
  "filters_3": 64,
  "kernel_1": 5,
  "kernel_2": 7,
  "kernel_3": 3,
  "dilation_2": 1,
  "dilation_3": 2,
  "spatial_dropout": 0.15,
  "dense_1": 128,
  "dense_2": 128,
  "dropout_1": 0.3,
  "dropout_2": 0.05,
  "learning_rate": 0.0003,
  "batch_size": 256,
  "trial_id": 6
}
================================================================================
Epoch 1/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1:22 2s/step - loss: 1.5462 - mae: 1.5462

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 1.4749 - mae: 1.4749

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 1.4128 - mae: 1.4128

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 1.3588 - mae: 1.3588

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 1.3081 - mae: 1.3081

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 1.2621 - mae: 1.2621

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 1.2199 - mae: 1.2199

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 1.1817 - mae: 1.1817

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 1.1472 - mae: 1.1472

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.1157 - mae: 1.1157

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.0868 - mae: 1.0868

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1.0604 - mae: 1.0604

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1.0360 - mae: 1.0360

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1.0134 - mae: 1.0134

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.9922 - mae: 0.9922

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.9723 - mae: 0.9723

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.9534 - mae: 0.9534

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.9356 - mae: 0.9356

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.9188 - mae: 0.9188

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.9027 - mae: 0.9027

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.8874 - mae: 0.8874

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.8728 - mae: 0.8728

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.8588 - mae: 0.8588

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.8453 - mae: 0.8453

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.8325 - mae: 0.8325

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.8201 - mae: 0.8201

52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.5130 - mae: 0.5130 - val_loss: 0.0533 - val_mae: 0.0533 - learning_rate: 3.0000e-04

Epoch 2/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.1818 - mae: 0.1818

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.1784 - mae: 0.1784

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.1761 - mae: 0.1761

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.1749 - mae: 0.1749

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.1732 - mae: 0.1732

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.1713 - mae: 0.1713

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.1694 - mae: 0.1694

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.1674 - mae: 0.1674

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.1655 - mae: 0.1655

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1636 - mae: 0.1636

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.1618 - mae: 0.1618

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1601 - mae: 0.1601

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1586 - mae: 0.1586

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1571 - mae: 0.1571

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1556 - mae: 0.1556

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1542 - mae: 0.1542

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1527 - mae: 0.1527

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1513 - mae: 0.1513

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1499 - mae: 0.1499

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1485 - mae: 0.1485

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1472 - mae: 0.1472

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1459 - mae: 0.1459

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1445 - mae: 0.1445

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1432 - mae: 0.1432

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1420 - mae: 0.1420

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.1407 - mae: 0.1407

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.1098 - mae: 0.1098 - val_loss: 0.0287 - val_mae: 0.0287 - learning_rate: 3.0000e-04

Epoch 3/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0612 - mae: 0.0612

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0590 - mae: 0.0590

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0583 - mae: 0.0583

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0578 - mae: 0.0578

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0571 - mae: 0.0571

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0564 - mae: 0.0564

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0558 - mae: 0.0558

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0551 - mae: 0.0551

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0546 - mae: 0.0546

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0541 - mae: 0.0541

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0536 - mae: 0.0536

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0532 - mae: 0.0532

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0528 - mae: 0.0528

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0524 - mae: 0.0524

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0520 - mae: 0.0520

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0516 - mae: 0.0516

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0512 - mae: 0.0512

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0509 - mae: 0.0509

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0505 - mae: 0.0505

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0501 - mae: 0.0501

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0497 - mae: 0.0497

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0494 - mae: 0.0494

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0490 - mae: 0.0490

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0486 - mae: 0.0486

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0483 - mae: 0.0483

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0479 - mae: 0.0479

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0389 - mae: 0.0389 - val_loss: 0.0110 - val_mae: 0.0110 - learning_rate: 3.0000e-04

Epoch 4/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0226 - mae: 0.0226

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0220 - mae: 0.0220

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0215 - mae: 0.0215

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0212 - mae: 0.0212

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0210 - mae: 0.0210

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0207 - mae: 0.0207

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0205 - mae: 0.0205

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0203 - mae: 0.0203

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0201 - mae: 0.0201

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0199 - mae: 0.0199

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0198 - mae: 0.0198

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0196 - mae: 0.0196

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0195 - mae: 0.0195

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0194 - mae: 0.0194

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0193 - mae: 0.0193

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0192 - mae: 0.0192

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0191 - mae: 0.0191

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0189 - mae: 0.0189

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0188 - mae: 0.0188

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0187 - mae: 0.0187

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0186 - mae: 0.0186

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0185 - mae: 0.0185

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0184 - mae: 0.0184

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0182 - mae: 0.0182

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0181 - mae: 0.0181

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0180 - mae: 0.0180

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0153 - mae: 0.0153 - val_loss: 0.0046 - val_mae: 0.0046 - learning_rate: 3.0000e-04

Epoch 5/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0101 - mae: 0.0101

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0098 - mae: 0.0098

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0098 - mae: 0.0098

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0098 - mae: 0.0098

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0097 - mae: 0.0097

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0097 - mae: 0.0097

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0096 - mae: 0.0096

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0095 - mae: 0.0095

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0095 - mae: 0.0095

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0094 - mae: 0.0094

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0094 - mae: 0.0094

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0094 - mae: 0.0094

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0094 - mae: 0.0094

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0093 - mae: 0.0093

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0093 - mae: 0.0093

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0093 - mae: 0.0093

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0093 - mae: 0.0093

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0093 - mae: 0.0093

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0092 - mae: 0.0092

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0092 - mae: 0.0092

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0092 - mae: 0.0092

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0092 - mae: 0.0092

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0091 - mae: 0.0091

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0091 - mae: 0.0091

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0091 - mae: 0.0091

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0091 - mae: 0.0091

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0085 - mae: 0.0085 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 6/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0075 - mae: 0.0075

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0073 - mae: 0.0073

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0072 - mae: 0.0072

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0071 - mae: 0.0071

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0071 - mae: 0.0071

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0071 - mae: 0.0071

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0071 - mae: 0.0071

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0071 - mae: 0.0071

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0071 - mae: 0.0071

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0071 - mae: 0.0071

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0071 - mae: 0.0071

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0071 - mae: 0.0071

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0071 - mae: 0.0071

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0071 - mae: 0.0071

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0071 - mae: 0.0071

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0071 - mae: 0.0071

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0071 - mae: 0.0071

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0071 - mae: 0.0071

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0071 - mae: 0.0071

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0071 - mae: 0.0071

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0071 - mae: 0.0071

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0071 - mae: 0.0071

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0071 - mae: 0.0071

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0071 - mae: 0.0071

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0071 - mae: 0.0071

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0071 - mae: 0.0071

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0070 - mae: 0.0070 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 7/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0068 - mae: 0.0068

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0066 - mae: 0.0066

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0065 - mae: 0.0065

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0065 - mae: 0.0065

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0064 - mae: 0.0064

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0064 - mae: 0.0064

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0064 - mae: 0.0064

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0064 - mae: 0.0064

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0064 - mae: 0.0064

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0064 - mae: 0.0064

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0064 - mae: 0.0064

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0064 - mae: 0.0064 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 8/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0065 - mae: 0.0065

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0063 - mae: 0.0063

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0062 - mae: 0.0062

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0061 - mae: 0.0061

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0061 - mae: 0.0061

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0061 - mae: 0.0061

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0061 - mae: 0.0061

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0061 - mae: 0.0061

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0061 - mae: 0.0061

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0061 - mae: 0.0061

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0061 - mae: 0.0061

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0061 - mae: 0.0061

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0061 - mae: 0.0061

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0061 - mae: 0.0061

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0061 - mae: 0.0061

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0061 - mae: 0.0061

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0061 - mae: 0.0061

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0061 - mae: 0.0061

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0061 - mae: 0.0061

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0061 - mae: 0.0061

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0061 - mae: 0.0061

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0061 - mae: 0.0061

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0061 - mae: 0.0061

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0061 - mae: 0.0061

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0061 - mae: 0.0061

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0061 - mae: 0.0061

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0061 - mae: 0.0061 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 9/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 0.0063 - mae: 0.0063

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0061 - mae: 0.0061

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0061 - mae: 0.0061

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0060 - mae: 0.0060

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0060 - mae: 0.0060

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0060 - mae: 0.0060

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0059 - mae: 0.0059

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0059 - mae: 0.0059

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0059 - mae: 0.0059

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0059 - mae: 0.0059

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0059 - mae: 0.0059

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0060 - mae: 0.0060 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 10/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0058 - mae: 0.0058

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0058 - mae: 0.0058

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0057 - mae: 0.0057

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0058 - mae: 0.0058

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0058 - mae: 0.0058

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0058 - mae: 0.0058

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0058 - mae: 0.0058

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0058 - mae: 0.0058

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0058 - mae: 0.0058

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0058 - mae: 0.0058

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0058 - mae: 0.0058

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0058 - mae: 0.0058

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0058 - mae: 0.0058

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0058 - mae: 0.0058

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0058 - mae: 0.0058

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0058 - mae: 0.0058

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 11/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0058 - mae: 0.0058

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0057 - mae: 0.0057

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 12/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0059 - mae: 0.0059

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0059 - mae: 0.0059

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0058 - mae: 0.0058

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0057 - mae: 0.0057

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0057 - mae: 0.0057

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0057 - mae: 0.0057

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0057 - mae: 0.0057

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0057 - mae: 0.0057

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0057 - mae: 0.0057

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0057 - mae: 0.0057

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 13/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 0.0057 - mae: 0.0057

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0057 - mae: 0.0057

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0056 - mae: 0.0056

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 14/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0056 - mae: 0.0056

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0056 - mae: 0.0056

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0056 - mae: 0.0056

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 15/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0056 - mae: 0.0056

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0056 - mae: 0.0056

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0056 - mae: 0.0056

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0056 - mae: 0.0056

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0056 - mae: 0.0056

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0056 - mae: 0.0056

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0056 - mae: 0.0056

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 16/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 17/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.0057 - mae: 0.0057

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0056 - mae: 0.0056

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0056 - mae: 0.0056

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0056 - mae: 0.0056

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0056 - mae: 0.0056

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0056 - mae: 0.0056

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0056 - mae: 0.0056

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0056 - mae: 0.0056

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0056 - mae: 0.0056

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0056 - mae: 0.0056

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0056 - mae: 0.0056

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0056 - mae: 0.0056

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 18/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 0.0056 - mae: 0.0056

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0056 - mae: 0.0056

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 19/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0057 - mae: 0.0057

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0057 - mae: 0.0057

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0056 - mae: 0.0056

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 20/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0058 - mae: 0.0058

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0057 - mae: 0.0057

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0056 - mae: 0.0056

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 21/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0056 - mae: 0.0056

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 22/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 0.0056 - mae: 0.0056

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

================================================================================
Trial 7/15
{
  "filters_1": 96,
  "filters_2": 64,
  "filters_3": 64,
  "kernel_1": 3,
  "kernel_2": 7,
  "kernel_3": 3,
  "dilation_2": 2,
  "dilation_3": 2,
  "spatial_dropout": 0.1,
  "dense_1": 256,
  "dense_2": 128,
  "dropout_1": 0.3,
  "dropout_2": 0.05,
  "learning_rate": 0.0001,
  "batch_size": 64,
  "trial_id": 7
}
================================================================================
Epoch 1/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5:30 2s/step - loss: 1.1569 - mae: 1.1569

  4/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 1.1401 - mae: 1.1401

  7/205 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: 1.1128 - mae: 1.1128

 11/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 1.0756 - mae: 1.0756

 15/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 1.0402 - mae: 1.0402

 19/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 1.0083 - mae: 1.0083

 23/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.9797 - mae: 0.9797

 27/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.9542 - mae: 0.9542

 31/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.9310 - mae: 0.9310

 36/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.9046 - mae: 0.9046

 40/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.8852 - mae: 0.8852

 44/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.8672 - mae: 0.8672

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.8465 - mae: 0.8465

 53/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.8311 - mae: 0.8311

 57/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.8167 - mae: 0.8167

 61/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.8031 - mae: 0.8031

 65/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.7902 - mae: 0.7902

 69/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.7780 - mae: 0.7780

 73/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.7664 - mae: 0.7664

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.7582 - mae: 0.7582

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.7475 - mae: 0.7475

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.7373 - mae: 0.7373

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.7275 - mae: 0.7275

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.7182 - mae: 0.7182

 96/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.7092 - mae: 0.7092

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.7005 - mae: 0.7005

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.6921 - mae: 0.6921

108/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.6840 - mae: 0.6840

112/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.6762 - mae: 0.6762

115/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.6705 - mae: 0.6705

119/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.6631 - mae: 0.6631

122/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.6577 - mae: 0.6577

125/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.6524 - mae: 0.6524

129/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.6455 - mae: 0.6455

132/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.6404 - mae: 0.6404

136/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.6339 - mae: 0.6339

139/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.6291 - mae: 0.6291

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6244 - mae: 0.6244

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6197 - mae: 0.6197

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6137 - mae: 0.6137

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6078 - mae: 0.6078

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6035 - mae: 0.6035

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.5978 - mae: 0.5978

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.5923 - mae: 0.5923

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.5868 - mae: 0.5868

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.5829 - mae: 0.5829

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.5789 - mae: 0.5789

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.5738 - mae: 0.5738

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.5700 - mae: 0.5700

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.5650 - mae: 0.5650

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.5613 - mae: 0.5613

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.5577 - mae: 0.5577

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.5542 - mae: 0.5542

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.5495 - mae: 0.5495

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.5460 - mae: 0.5460

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.5426 - mae: 0.5426

205/205 ━━━━━━━━━━━━━━━━━━━━ 5s 17ms/step - loss: 0.3127 - mae: 0.3127 - val_loss: 0.0096 - val_mae: 0.0096 - learning_rate: 1.0000e-04

Epoch 2/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0612 - mae: 0.0612

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0671 - mae: 0.0671

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0646 - mae: 0.0646

 12/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0630 - mae: 0.0630

 16/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0612 - mae: 0.0612

 20/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0597 - mae: 0.0597

 24/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0584 - mae: 0.0584

 28/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0573 - mae: 0.0573

 32/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0563 - mae: 0.0563

 35/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0555 - mae: 0.0555

 38/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0548 - mae: 0.0548

 42/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0540 - mae: 0.0540

 46/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0532 - mae: 0.0532

 50/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0524 - mae: 0.0524

 54/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0517 - mae: 0.0517

 58/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0510 - mae: 0.0510

 62/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0503 - mae: 0.0503

 67/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0495 - mae: 0.0495

 71/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0489 - mae: 0.0489

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0482 - mae: 0.0482

 81/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0475 - mae: 0.0475

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0469 - mae: 0.0469

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0464 - mae: 0.0464

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0458 - mae: 0.0458

 97/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0453 - mae: 0.0453

101/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0448 - mae: 0.0448

105/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0444 - mae: 0.0444

109/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0439 - mae: 0.0439

112/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0435 - mae: 0.0435

116/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0431 - mae: 0.0431

120/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0427 - mae: 0.0427

124/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0422 - mae: 0.0422

128/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0418 - mae: 0.0418

132/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0414 - mae: 0.0414

135/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0411 - mae: 0.0411

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0407 - mae: 0.0407

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0404 - mae: 0.0404

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0400 - mae: 0.0400

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0396 - mae: 0.0396

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0394 - mae: 0.0394

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0391 - mae: 0.0391

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0388 - mae: 0.0388

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0385 - mae: 0.0385

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0382 - mae: 0.0382

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0378 - mae: 0.0378

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0375 - mae: 0.0375

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0372 - mae: 0.0372

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0369 - mae: 0.0369

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0367 - mae: 0.0367

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0364 - mae: 0.0364

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0361 - mae: 0.0361

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0358 - mae: 0.0358

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0357 - mae: 0.0357

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0224 - mae: 0.0224 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 3/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 0.0097 - mae: 0.0097

  5/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0096 - mae: 0.0096

  9/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0096 - mae: 0.0096

 12/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0095 - mae: 0.0095

 15/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0094 - mae: 0.0094

 18/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0094 - mae: 0.0094

 22/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0094 - mae: 0.0094

 26/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0093 - mae: 0.0093

 29/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0093 - mae: 0.0093

 33/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0093 - mae: 0.0093

 37/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0093 - mae: 0.0093

 41/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0093 - mae: 0.0093

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0093 - mae: 0.0093

 48/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0093 - mae: 0.0093

 52/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0093 - mae: 0.0093

 56/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0092 - mae: 0.0092

 60/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0092 - mae: 0.0092

 63/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0092 - mae: 0.0092

 67/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0092 - mae: 0.0092

 71/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0091 - mae: 0.0091

 74/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0091 - mae: 0.0091

 77/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0091 - mae: 0.0091

 81/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0091 - mae: 0.0091

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0091 - mae: 0.0091

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0091 - mae: 0.0091

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0090 - mae: 0.0090

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0090 - mae: 0.0090

102/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0090 - mae: 0.0090

106/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0090 - mae: 0.0090

110/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0090 - mae: 0.0090

114/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0090 - mae: 0.0090

118/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0089 - mae: 0.0089

122/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0089 - mae: 0.0089

125/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0089 - mae: 0.0089

129/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0089 - mae: 0.0089

134/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0089 - mae: 0.0089

138/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0088 - mae: 0.0088

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0088 - mae: 0.0088

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0088 - mae: 0.0088

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0088 - mae: 0.0088

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0088 - mae: 0.0088

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0088 - mae: 0.0088

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0088 - mae: 0.0088

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0087 - mae: 0.0087

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0087 - mae: 0.0087

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0087 - mae: 0.0087

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0087 - mae: 0.0087

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0087 - mae: 0.0087

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0087 - mae: 0.0087

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0087 - mae: 0.0087

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0086 - mae: 0.0086

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0086 - mae: 0.0086

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0086 - mae: 0.0086

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0086 - mae: 0.0086

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0079 - mae: 0.0079 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.0000e-04

Epoch 4/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0059 - mae: 0.0059

  5/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0067 - mae: 0.0067

  8/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0068 - mae: 0.0068

 12/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0068 - mae: 0.0068

 16/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0068 - mae: 0.0068

 20/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0068 - mae: 0.0068

 24/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0067 - mae: 0.0067

 28/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0067 - mae: 0.0067

 32/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0067 - mae: 0.0067

 36/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0067 - mae: 0.0067

 40/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0067 - mae: 0.0067

 44/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0067 - mae: 0.0067

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0067 - mae: 0.0067

 53/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0067 - mae: 0.0067

 57/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0067 - mae: 0.0067

 61/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0067 - mae: 0.0067

 65/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0067 - mae: 0.0067

 69/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0067 - mae: 0.0067

 73/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0067 - mae: 0.0067

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0067 - mae: 0.0067

 81/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0067 - mae: 0.0067

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0067 - mae: 0.0067

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0067 - mae: 0.0067

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0067 - mae: 0.0067

 97/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0067 - mae: 0.0067

101/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0067 - mae: 0.0067

105/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0067 - mae: 0.0067

109/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0067 - mae: 0.0067

113/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0067 - mae: 0.0067

117/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0067 - mae: 0.0067

121/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0067 - mae: 0.0067

125/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0067 - mae: 0.0067

129/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0067 - mae: 0.0067

133/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0067 - mae: 0.0067

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0067 - mae: 0.0067

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0066 - mae: 0.0066 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.0000e-04

Epoch 5/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0060 - mae: 0.0060

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0067 - mae: 0.0067

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0067 - mae: 0.0067

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0066 - mae: 0.0066

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0066 - mae: 0.0066

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0065 - mae: 0.0065

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0065 - mae: 0.0065

 29/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0065 - mae: 0.0065

 34/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0065 - mae: 0.0065

 38/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0064 - mae: 0.0064

 42/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0064 - mae: 0.0064

 46/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0064 - mae: 0.0064

 51/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0064 - mae: 0.0064

 55/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0064 - mae: 0.0064

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

 75/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

 91/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

103/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

107/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

111/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

115/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

119/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

123/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

127/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

131/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0063 - mae: 0.0063

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0062 - mae: 0.0062

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0062 - mae: 0.0062

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0062 - mae: 0.0062

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0062 - mae: 0.0062

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0062 - mae: 0.0062

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0062 - mae: 0.0062

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0062 - mae: 0.0062

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 0.0061 - mae: 0.0061 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.0000e-04

Epoch 6/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0051 - mae: 0.0051

  5/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0054 - mae: 0.0054

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0057 - mae: 0.0057

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0057 - mae: 0.0057

 29/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0058 - mae: 0.0058

 33/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0058 - mae: 0.0058

 37/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0058 - mae: 0.0058

 41/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0058 - mae: 0.0058

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0058 - mae: 0.0058

 50/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0059 - mae: 0.0059

 54/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0059 - mae: 0.0059

 58/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0059 - mae: 0.0059

 62/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0059 - mae: 0.0059

 66/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0059 - mae: 0.0059

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0059 - mae: 0.0059

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

 91/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

103/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

107/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

111/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

116/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

120/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

124/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

128/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

132/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0059 - mae: 0.0059

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0059 - mae: 0.0059

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0059 - mae: 0.0059

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0059 - mae: 0.0059

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0059 - mae: 0.0059

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0059 - mae: 0.0059

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0060 - mae: 0.0060

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0060 - mae: 0.0060

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0060 - mae: 0.0060

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0060 - mae: 0.0060

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0060 - mae: 0.0060

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0060 - mae: 0.0060

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0060 - mae: 0.0060

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0060 - mae: 0.0060

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0060 - mae: 0.0060

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0060 - mae: 0.0060

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0060 - mae: 0.0060

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0060 - mae: 0.0060

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0060 - mae: 0.0060 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.0000e-04

Epoch 7/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 0.0055 - mae: 0.0055

  5/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0056 - mae: 0.0056

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0057 - mae: 0.0057

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

 30/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

 35/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0058 - mae: 0.0058

 39/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0058 - mae: 0.0058

 43/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0058 - mae: 0.0058

 47/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0058 - mae: 0.0058

 51/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0058 - mae: 0.0058

 55/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0058 - mae: 0.0058

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0058 - mae: 0.0058

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

 75/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

 86/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

 90/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

102/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

106/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

110/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

114/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

119/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

124/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

129/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0058 - mae: 0.0058

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.0000e-04

Epoch 8/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0070 - mae: 0.0070

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0064 - mae: 0.0064

 10/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0061 - mae: 0.0061

 14/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0060 - mae: 0.0060

 18/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0060 - mae: 0.0060

 22/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0059 - mae: 0.0059

 26/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0059 - mae: 0.0059

 30/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0059 - mae: 0.0059

 34/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

 38/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

 42/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

 46/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

 50/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

 54/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

 58/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0057 - mae: 0.0057

 62/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

 66/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

 86/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

 90/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

102/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

106/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

110/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

114/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

119/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

123/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

127/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

131/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.0000e-04

Epoch 9/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0050 - mae: 0.0050

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0053 - mae: 0.0053

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 22/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 26/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 30/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

 34/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

 38/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

 42/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

 47/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

 52/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

 56/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 68/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 97/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

101/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

105/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

109/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

113/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

117/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

121/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

125/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

129/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

132/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-05

Epoch 10/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0051 - mae: 0.0051

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 29/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 33/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 37/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 41/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 48/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 52/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 56/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0056 - mae: 0.0056

 60/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0056 - mae: 0.0056

 64/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 68/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 91/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

103/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

107/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

111/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

115/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

118/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

121/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

124/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

127/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

131/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

135/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-05

Epoch 11/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0056 - mae: 0.0056

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

 22/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0057 - mae: 0.0057

 26/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0057 - mae: 0.0057

 30/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0057 - mae: 0.0057

 34/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

 38/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

 42/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 53/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 57/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 61/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 69/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 73/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 81/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 97/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

101/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

105/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

109/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

113/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

117/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

121/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

125/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

129/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

133/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-05

Epoch 12/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0051 - mae: 0.0051

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 29/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0056 - mae: 0.0056

 33/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0056 - mae: 0.0056

 37/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0056 - mae: 0.0056

 41/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0056 - mae: 0.0056

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0056 - mae: 0.0056

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0056 - mae: 0.0056

 53/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0056 - mae: 0.0056

 58/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 62/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 81/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 97/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

101/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

105/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

109/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

113/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

117/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

121/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

125/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

129/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

132/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

136/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-05

Epoch 13/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0051 - mae: 0.0051

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0053 - mae: 0.0053

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 29/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

133/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-05

Epoch 14/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 0.0051 - mae: 0.0051

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 29/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 75/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

103/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-05

Epoch 15/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 0.0051 - mae: 0.0051

  4/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0052 - mae: 0.0052

  7/205 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: 0.0053 - mae: 0.0053

 10/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0054 - mae: 0.0054

 12/205 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 0.0054 - mae: 0.0054

 16/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0054 - mae: 0.0054

 20/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0055 - mae: 0.0055

 24/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0055 - mae: 0.0055

 31/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0055 - mae: 0.0055

 48/205 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-05

Epoch 16/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - loss: 0.0051 - mae: 0.0051

  5/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 29/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 86/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

103/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-05

Epoch 17/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0051 - mae: 0.0051

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 29/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 86/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-05

Epoch 18/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 0.0051 - mae: 0.0051

  5/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 24/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 32/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-05

Epoch 19/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0051 - mae: 0.0051

  4/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0053 - mae: 0.0053

  8/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0054 - mae: 0.0054

 12/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0055 - mae: 0.0055

 16/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 20/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 24/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 32/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 75/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

128/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

131/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

135/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-05

Epoch 20/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0051 - mae: 0.0051

  5/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0053 - mae: 0.0053

 10/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0054 - mae: 0.0054

 14/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0054 - mae: 0.0054

 18/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 22/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 26/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 29/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 32/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 42/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-05

Epoch 21/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - loss: 0.0051 - mae: 0.0051

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 26/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 43/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-05

Epoch 22/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5s 25ms/step - loss: 0.0051 - mae: 0.0051

  5/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0055 - mae: 0.0055

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0056 - mae: 0.0056

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0057 - mae: 0.0057

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0057 - mae: 0.0057

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0057 - mae: 0.0057

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0057 - mae: 0.0057

 29/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0057 - mae: 0.0057

 33/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 37/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 41/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 53/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 57/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 61/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 66/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 96/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

108/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

112/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

116/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

120/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

124/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

128/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

132/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-05

Epoch 23/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 0.0050 - mae: 0.0050

  5/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0055 - mae: 0.0055

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0057 - mae: 0.0057

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0057 - mae: 0.0057

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0057 - mae: 0.0057

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0057 - mae: 0.0057

 29/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0057 - mae: 0.0057

 33/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0057 - mae: 0.0057

 37/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 41/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 53/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 57/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0056 - mae: 0.0056

 62/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 66/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 86/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 90/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

102/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

107/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

111/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

115/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

119/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

123/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

127/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

131/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-05

Epoch 24/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 0.0050 - mae: 0.0050

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 22/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 26/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 43/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 75/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-05

Epoch 25/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 0.0053 - mae: 0.0053

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0054 - mae: 0.0054

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 29/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-05

Epoch 26/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - loss: 0.0051 - mae: 0.0051

  5/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 26/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 43/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 75/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

103/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-05

Epoch 27/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0050 - mae: 0.0050

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 29/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 86/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

103/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-06

Epoch 28/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 0.0050 - mae: 0.0050

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0054 - mae: 0.0054

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 13/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 16/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 19/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 21/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0055 - mae: 0.0055

 24/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 32/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0056 - mae: 0.0056

 35/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0056 - mae: 0.0056

 38/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0056 - mae: 0.0056

 41/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0056 - mae: 0.0056

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 86/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0056 - mae: 0.0056

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-06

Epoch 29/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  5/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0053 - mae: 0.0053

 12/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0054 - mae: 0.0054

 16/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0054 - mae: 0.0054

 20/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0054 - mae: 0.0054

 23/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0054 - mae: 0.0054

 28/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-06

Epoch 30/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0050 - mae: 0.0050

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0053 - mae: 0.0053

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0054 - mae: 0.0054

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-06

Epoch 31/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0050 - mae: 0.0050

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0059 - mae: 0.0059

 12/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0059 - mae: 0.0059

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0059 - mae: 0.0059

 24/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0058 - mae: 0.0058

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0058 - mae: 0.0058

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0058 - mae: 0.0058

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0058 - mae: 0.0058

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0057 - mae: 0.0057

 52/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0057 - mae: 0.0057

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0057 - mae: 0.0057

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0057 - mae: 0.0057

 68/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0057 - mae: 0.0057

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0057 - mae: 0.0057

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 86/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

103/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-06

Epoch 32/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0050 - mae: 0.0050

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0053 - mae: 0.0053

 10/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0054 - mae: 0.0054

 15/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0054 - mae: 0.0054

 20/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 48/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-06

Epoch 33/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0050 - mae: 0.0050

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0053 - mae: 0.0053

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-06

Epoch 34/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0050 - mae: 0.0050

  5/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0053 - mae: 0.0053

 10/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0054 - mae: 0.0054

 15/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055

 21/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 48/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-06

Epoch 35/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0052 - mae: 0.0052

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0053 - mae: 0.0053

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0054 - mae: 0.0054

 15/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0054 - mae: 0.0054

 19/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 24/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 32/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 42/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 86/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-06

Epoch 36/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0050 - mae: 0.0050

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0053 - mae: 0.0053

 12/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 75/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-06

Epoch 37/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0050 - mae: 0.0050

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0053 - mae: 0.0053

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0054 - mae: 0.0054

 16/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-06

================================================================================
Trial 8/15
{
  "filters_1": 96,
  "filters_2": 32,
  "filters_3": 128,
  "kernel_1": 5,
  "kernel_2": 3,
  "kernel_3": 5,
  "dilation_2": 1,
  "dilation_3": 2,
  "spatial_dropout": 0.15,
  "dense_1": 256,
  "dense_2": 64,
  "dropout_1": 0.2,
  "dropout_2": 0.05,
  "learning_rate": 0.0005,
  "batch_size": 256,
  "trial_id": 8
}
================================================================================
Epoch 1/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1:21 2s/step - loss: 1.4719 - mae: 1.4719

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 1.2793 - mae: 1.2793

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 1.1361 - mae: 1.1361

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 1.0627 - mae: 1.0627

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.9738 - mae: 0.9738

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.9007 - mae: 0.9007

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.8388 - mae: 0.8388

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7852 - mae: 0.7852

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7383 - mae: 0.7383

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.6970 - mae: 0.6970

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.6605 - mae: 0.6605

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.6278 - mae: 0.6278

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.5986 - mae: 0.5986

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.5722 - mae: 0.5722

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.5483 - mae: 0.5483

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.5266 - mae: 0.5266

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.5067 - mae: 0.5067

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.4884 - mae: 0.4884

52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - loss: 0.1920 - mae: 0.1920 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 2/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0065 - mae: 0.0065

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0066 - mae: 0.0066

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0066 - mae: 0.0066

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0066 - mae: 0.0066

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0066 - mae: 0.0066

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0065 - mae: 0.0065

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0065 - mae: 0.0065

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0065 - mae: 0.0065

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0065 - mae: 0.0065

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0065 - mae: 0.0065

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0064 - mae: 0.0064

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0064 - mae: 0.0064

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0064 - mae: 0.0064

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0064 - mae: 0.0064

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0064 - mae: 0.0064

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0064 - mae: 0.0064

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0064 - mae: 0.0064

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0063 - mae: 0.0063

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0062 - mae: 0.0062 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 3/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0060 - mae: 0.0060

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0060 - mae: 0.0060

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0060 - mae: 0.0060

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0060 - mae: 0.0060

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0060 - mae: 0.0060

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0060 - mae: 0.0060

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0060 - mae: 0.0060

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0060 - mae: 0.0060

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0060 - mae: 0.0060

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0060 - mae: 0.0060

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0059 - mae: 0.0059

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0059 - mae: 0.0059

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0059 - mae: 0.0059

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0059 - mae: 0.0059

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0059 - mae: 0.0059

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0059 - mae: 0.0059

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0059 - mae: 0.0059

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0059 - mae: 0.0059

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 4/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0056 - mae: 0.0056

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0056 - mae: 0.0056

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0056 - mae: 0.0056

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0056 - mae: 0.0056

14/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0056 - mae: 0.0056

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0057 - mae: 0.0057

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0057 - mae: 0.0057

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0057 - mae: 0.0057

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0057 - mae: 0.0057

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0057 - mae: 0.0057

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0057 - mae: 0.0057

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 5/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0056 - mae: 0.0056

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0056 - mae: 0.0056

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0057 - mae: 0.0057

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0057 - mae: 0.0057

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0057 - mae: 0.0057

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0057 - mae: 0.0057

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0057 - mae: 0.0057

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0057 - mae: 0.0057

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0057 - mae: 0.0057

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0057 - mae: 0.0057

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0057 - mae: 0.0057

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0057 - mae: 0.0057

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0057 - mae: 0.0057

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0057 - mae: 0.0057

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0057 - mae: 0.0057

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0057 - mae: 0.0057

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0057 - mae: 0.0057

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 6/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0056 - mae: 0.0056

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0056 - mae: 0.0056

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 7/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0056 - mae: 0.0056

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 8/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 9/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 10/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 11/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 12/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 13/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0057 - mae: 0.0057

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0056 - mae: 0.0056

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0056 - mae: 0.0056

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 14/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 15/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 16/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 17/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 18/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 19/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 20/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 21/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 22/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0061 - mae: 0.0061

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0057 - mae: 0.0057

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0057 - mae: 0.0057

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 23/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 24/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 25/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 26/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 27/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0056 - mae: 0.0056

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 28/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 29/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 30/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 31/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 32/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5625e-05

Epoch 33/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5625e-05

Epoch 34/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5625e-05

================================================================================
Trial 9/15
{
  "filters_1": 64,
  "filters_2": 32,
  "filters_3": 128,
  "kernel_1": 5,
  "kernel_2": 3,
  "kernel_3": 3,
  "dilation_2": 1,
  "dilation_3": 4,
  "spatial_dropout": 0.05,
  "dense_1": 128,
  "dense_2": 64,
  "dropout_1": 0.1,
  "dropout_2": 0.05,
  "learning_rate": 0.001,
  "batch_size": 128,
  "trial_id": 9
}
================================================================================
Epoch 1/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:41 2s/step - loss: 1.3535 - mae: 1.3535

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.9559 - mae: 0.9559

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.7688 - mae: 0.7688

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.6517 - mae: 0.6517

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.5692 - mae: 0.5692

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.5185 - mae: 0.5185

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4679 - mae: 0.4679

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4347 - mae: 0.4347

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.4066 - mae: 0.4066

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3767 - mae: 0.3767

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3514 - mae: 0.3514

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3297 - mae: 0.3297

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.3109 - mae: 0.3109

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2975 - mae: 0.2975

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2825 - mae: 0.2825

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2692 - mae: 0.2692

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2572 - mae: 0.2572

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2464 - mae: 0.2464

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2385 - mae: 0.2385

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2311 - mae: 0.2311

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2242 - mae: 0.2242

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2178 - mae: 0.2178

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2118 - mae: 0.2118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 0.0637 - mae: 0.0637 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 2/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0057 - mae: 0.0057

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0057 - mae: 0.0057

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0058 - mae: 0.0058

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0059 - mae: 0.0059

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0059 - mae: 0.0059

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0059 - mae: 0.0059

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0059 - mae: 0.0059

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0059 - mae: 0.0059

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0059 - mae: 0.0059

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 3/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0056 - mae: 0.0056

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0057 - mae: 0.0057

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 4/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0057 - mae: 0.0057

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0056 - mae: 0.0056

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0056 - mae: 0.0056

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0056 - mae: 0.0056

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 5/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 6/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0056 - mae: 0.0056

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0056 - mae: 0.0056

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 7/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0062 - mae: 0.0062

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0058 - mae: 0.0058

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0057 - mae: 0.0057

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 8/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 9/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 10/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0056 - mae: 0.0056

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 11/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 12/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 13/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 14/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0055 - mae: 0.0055

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 15/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 16/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0055 - mae: 0.0055

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0056 - mae: 0.0056

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0056 - mae: 0.0056

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 17/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 18/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 19/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 20/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 21/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 22/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

================================================================================
Trial 10/15
{
  "filters_1": 64,
  "filters_2": 64,
  "filters_3": 128,
  "kernel_1": 5,
  "kernel_2": 7,
  "kernel_3": 5,
  "dilation_2": 2,
  "dilation_3": 4,
  "spatial_dropout": 0.15,
  "dense_1": 128,
  "dense_2": 128,
  "dropout_1": 0.1,
  "dropout_2": 0.05,
  "learning_rate": 0.001,
  "batch_size": 256,
  "trial_id": 10
}
================================================================================
Epoch 1/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1:22 2s/step - loss: 1.3601 - mae: 1.3601

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 1.1739 - mae: 1.1739

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 1.0484 - mae: 1.0484

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.9564 - mae: 0.9564

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.8849 - mae: 0.8849

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.8269 - mae: 0.8269

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.7780 - mae: 0.7780

16/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.7169 - mae: 0.7169

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.6822 - mae: 0.6822

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.6513 - mae: 0.6513

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.6236 - mae: 0.6236

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.5986 - mae: 0.5986

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.5758 - mae: 0.5758

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.5550 - mae: 0.5550

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.5359 - mae: 0.5359

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.5182 - mae: 0.5182

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.5018 - mae: 0.5018

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.4866 - mae: 0.4866

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.4724 - mae: 0.4724

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.4591 - mae: 0.4591

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.4467 - mae: 0.4467

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.4350 - mae: 0.4350

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.4240 - mae: 0.4240

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.4136 - mae: 0.4136

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.4038 - mae: 0.4038

52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.1630 - mae: 0.1630 - val_loss: 0.0106 - val_mae: 0.0106 - learning_rate: 0.0010

Epoch 2/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0104 - mae: 0.0104

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0108 - mae: 0.0108

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0113 - mae: 0.0113

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0113 - mae: 0.0113

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0112 - mae: 0.0112

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0111 - mae: 0.0111

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0110 - mae: 0.0110

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0109 - mae: 0.0109

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0108 - mae: 0.0108

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0107 - mae: 0.0107

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0106 - mae: 0.0106

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0105 - mae: 0.0105

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0104 - mae: 0.0104

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0103 - mae: 0.0103

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0102 - mae: 0.0102

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0101 - mae: 0.0101

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0100 - mae: 0.0100

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0099 - mae: 0.0099

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0098 - mae: 0.0098

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0097 - mae: 0.0097

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0097 - mae: 0.0097

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0096 - mae: 0.0096

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0095 - mae: 0.0095

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0094 - mae: 0.0094

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0093 - mae: 0.0093

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0093 - mae: 0.0093

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0075 - mae: 0.0075 - val_loss: 0.0048 - val_mae: 0.0048 - learning_rate: 0.0010

Epoch 3/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0043 - val_mae: 0.0043 - learning_rate: 0.0010

Epoch 4/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 5/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 6/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 7/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 40ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 8/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 9/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 10/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 11/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 12/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 13/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 14/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 15/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 16/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 17/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 18/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 19/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 20/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 21/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 22/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 23/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 24/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 37ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 25/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 26/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 40ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 27/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 41ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 34ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 28/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 43ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 29/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 42ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 30/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 31/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 39ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 32/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 44ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 33/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 34/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 46ms/step - loss: 0.0055 - mae: 0.0055

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

================================================================================
Trial 11/15
{
  "filters_1": 32,
  "filters_2": 32,
  "filters_3": 96,
  "kernel_1": 3,
  "kernel_2": 5,
  "kernel_3": 5,
  "dilation_2": 1,
  "dilation_3": 2,
  "spatial_dropout": 0.2,
  "dense_1": 128,
  "dense_2": 32,
  "dropout_1": 0.1,
  "dropout_2": 0.05,
  "learning_rate": 0.0005,
  "batch_size": 64,
  "trial_id": 11
}
================================================================================
Epoch 1/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5:25 2s/step - loss: 1.3836 - mae: 1.3836

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 1.0959 - mae: 1.0959

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.8995 - mae: 0.8995

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.7930 - mae: 0.7930

 32/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.7096 - mae: 0.7096

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.6517 - mae: 0.6517

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.6033 - mae: 0.6033

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.5621 - mae: 0.5621

 56/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.5268 - mae: 0.5268

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.4915 - mae: 0.4915

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.4571 - mae: 0.4571

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4278 - mae: 0.4278

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3995 - mae: 0.3995

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3752 - mae: 0.3752

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3585 - mae: 0.3585

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3414 - mae: 0.3414

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3260 - mae: 0.3260

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3106 - mae: 0.3106

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2967 - mae: 0.2967

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2855 - mae: 0.2855

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2752 - mae: 0.2752

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2657 - mae: 0.2657

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2569 - mae: 0.2569

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2498 - mae: 0.2498

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2422 - mae: 0.2422

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2351 - mae: 0.2351

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2284 - mae: 0.2284

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 0.0660 - mae: 0.0660 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 2/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0058 - mae: 0.0058

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0059 - mae: 0.0059

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0060 - mae: 0.0060

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0059 - mae: 0.0059

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0059 - mae: 0.0059

 44/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

 52/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0059 - mae: 0.0059

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0059 - mae: 0.0059 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 3/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0072 - mae: 0.0072

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0060 - mae: 0.0060

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0059 - mae: 0.0059

 24/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0058 - mae: 0.0058

 32/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0058 - mae: 0.0058

 39/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0057 - mae: 0.0057

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0057 - mae: 0.0057

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0057 - mae: 0.0057

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 4/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 52/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 59/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 77/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 93/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 5/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 14/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0056 - mae: 0.0056

 40/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0056 - mae: 0.0056

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0056 - mae: 0.0056

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 6/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0056 - mae: 0.0056

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 58/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 7/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0056 - mae: 0.0056

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 48/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 8/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0056 - mae: 0.0056

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 48/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 9/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 38/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 47/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 10/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0055 - mae: 0.0055

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 38/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 47/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 11/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0055 - mae: 0.0055

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 33/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 44/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 84/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 93/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 12/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 38/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 47/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 83/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 13/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 38/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 47/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 14/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0055 - mae: 0.0055

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 37/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 47/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 84/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 93/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

102/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 15/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 16/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055

 11/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 52/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 86/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 17/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0055 - mae: 0.0055

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 52/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 86/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 18/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 37/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 47/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 76/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 94/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

103/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 19/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 53/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 72/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 20/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055

 11/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 33/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 44/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 77/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 21/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 32/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 83/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 22/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0053 - mae: 0.0053

 14/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 39/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 59/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

103/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 23/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 35/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 93/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 24/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0054 - mae: 0.0054

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 44/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 54/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 25/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 54/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 72/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 26/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 27/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0055 - mae: 0.0055

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 38/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 47/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 52/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 59/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 68/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 77/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 28/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 32/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 53/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 72/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 29/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 59/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 69/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 86/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 30/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 52/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 60/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 69/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 77/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 31/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0055 - mae: 0.0055

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 54/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 62/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 32/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 20/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 42/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 52/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 62/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5625e-05

Epoch 33/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0055 - mae: 0.0055

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 44/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 53/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 62/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5625e-05

Epoch 34/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0055 - mae: 0.0055

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 44/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 52/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

103/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5625e-05

Epoch 35/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - loss: 0.0055 - mae: 0.0055

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 86/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5625e-05

================================================================================
Trial 12/15
{
  "filters_1": 64,
  "filters_2": 96,
  "filters_3": 96,
  "kernel_1": 3,
  "kernel_2": 3,
  "kernel_3": 3,
  "dilation_2": 2,
  "dilation_3": 2,
  "spatial_dropout": 0.15,
  "dense_1": 256,
  "dense_2": 32,
  "dropout_1": 0.1,
  "dropout_2": 0.05,
  "learning_rate": 0.0003,
  "batch_size": 64,
  "trial_id": 12
}
================================================================================
Epoch 1/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5:28 2s/step - loss: 0.7390 - mae: 0.7390

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.5887 - mae: 0.5887

 12/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.4718 - mae: 0.4718

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.4050 - mae: 0.4050

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.3557 - mae: 0.3557

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.3181 - mae: 0.3181

 32/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2885 - mae: 0.2885

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2644 - mae: 0.2644

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2446 - mae: 0.2446

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2279 - mae: 0.2279

 52/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2136 - mae: 0.2136

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2012 - mae: 0.2012

 62/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.1904 - mae: 0.1904

 68/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.1791 - mae: 0.1791

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.1692 - mae: 0.1692

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.1618 - mae: 0.1618

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.1540 - mae: 0.1540

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1458 - mae: 0.1458

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1396 - mae: 0.1396

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.1340 - mae: 0.1340

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1297 - mae: 0.1297

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1249 - mae: 0.1249

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1205 - mae: 0.1205

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1165 - mae: 0.1165

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1128 - mae: 0.1128

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1099 - mae: 0.1099

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1071 - mae: 0.1071

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1046 - mae: 0.1046

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1016 - mae: 0.1016

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0989 - mae: 0.0989

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0964 - mae: 0.0964

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0940 - mae: 0.0940

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0921 - mae: 0.0921

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0902 - mae: 0.0902

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0885 - mae: 0.0885

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0869 - mae: 0.0869

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0850 - mae: 0.0850

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0832 - mae: 0.0832

205/205 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - loss: 0.0236 - mae: 0.0236 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 2/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0060 - mae: 0.0060

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0057 - mae: 0.0057

 14/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 54/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 3/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0058 - mae: 0.0058

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 4/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0060 - mae: 0.0060

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0057 - mae: 0.0057

 14/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0056 - mae: 0.0056

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0056 - mae: 0.0056

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 32/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 75/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 86/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 5/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 14/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 6/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 30/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 7/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0058 - mae: 0.0058

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0057 - mae: 0.0057

 16/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 8/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 12/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 48/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 9/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0058 - mae: 0.0058

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 10/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 11/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0058 - mae: 0.0058

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 16/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0056 - mae: 0.0056

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0056 - mae: 0.0056

 32/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 12/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 12/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 13/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 14/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0058 - mae: 0.0058

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 16/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 15/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 24/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 86/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 16/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 17/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0058 - mae: 0.0058

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0056 - mae: 0.0056

 16/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 48/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

103/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 18/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 48/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 19/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 24/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 20/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 12/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 21/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0057 - mae: 0.0057

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 22/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 24/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 23/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 24/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0058 - mae: 0.0058

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0056 - mae: 0.0056

 16/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 26/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055

 32/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 25/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0058 - mae: 0.0058

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 16/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0056 - mae: 0.0056

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

103/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 26/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 27/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 12/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 24/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

103/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 28/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0057 - mae: 0.0057

 12/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 29/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 16/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0056 - mae: 0.0056

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 30/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0057 - mae: 0.0057

 12/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 31/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0057 - mae: 0.0057

 12/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

103/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 32/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0057 - mae: 0.0057

 12/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 24/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 75/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 9.3750e-06

Epoch 33/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 9.3750e-06

Epoch 34/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0056 - mae: 0.0056

 16/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 9.3750e-06

Epoch 35/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0056 - mae: 0.0056

 16/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 21/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0056 - mae: 0.0056

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

103/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 9.3750e-06

Epoch 36/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0057 - mae: 0.0057

 12/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 9.3750e-06

Epoch 37/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 16/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0056 - mae: 0.0056

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 9.3750e-06

Epoch 38/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0057 - mae: 0.0057

 12/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 24/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 4.6875e-06

Epoch 39/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 15/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0056 - mae: 0.0056

 24/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0055 - mae: 0.0055

 29/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 4.6875e-06

Epoch 40/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0060 - mae: 0.0060

  6/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0057 - mae: 0.0057

 11/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 32/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 86/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 12ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 4.6875e-06

Epoch 41/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0060 - mae: 0.0060

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056

 24/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 75/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 4.6875e-06

================================================================================
Trial 13/15
{
  "filters_1": 64,
  "filters_2": 64,
  "filters_3": 128,
  "kernel_1": 5,
  "kernel_2": 3,
  "kernel_3": 3,
  "dilation_2": 1,
  "dilation_3": 4,
  "spatial_dropout": 0.2,
  "dense_1": 256,
  "dense_2": 32,
  "dropout_1": 0.3,
  "dropout_2": 0.1,
  "learning_rate": 0.0003,
  "batch_size": 128,
  "trial_id": 13
}
================================================================================
Epoch 1/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:44 2s/step - loss: 1.2404 - mae: 1.2404

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 1.0848 - mae: 1.0848

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.9769 - mae: 0.9769

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.9105 - mae: 0.9105

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.8524 - mae: 0.8524

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.8010 - mae: 0.8010

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.7552 - mae: 0.7552

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.7019 - mae: 0.7019

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.6558 - mae: 0.6558

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.6253 - mae: 0.6253

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.5891 - mae: 0.5891

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.5648 - mae: 0.5648

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.5356 - mae: 0.5356

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.5097 - mae: 0.5097

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.4864 - mae: 0.4864

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.4654 - mae: 0.4654

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.4463 - mae: 0.4463

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.4290 - mae: 0.4290

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.4170 - mae: 0.4170

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.4057 - mae: 0.4057

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.3917 - mae: 0.3917

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.3819 - mae: 0.3819

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.3726 - mae: 0.3726

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.3639 - mae: 0.3639

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.3556 - mae: 0.3556

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.3452 - mae: 0.3452

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.3355 - mae: 0.3355

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.3286 - mae: 0.3286

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.3199 - mae: 0.3199

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.1073 - mae: 0.1073 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 2/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0062 - mae: 0.0062

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0063 - mae: 0.0063

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0063 - mae: 0.0063

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0064 - mae: 0.0064

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0065 - mae: 0.0065

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0065 - mae: 0.0065

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0065 - mae: 0.0065

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0065 - mae: 0.0065

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0066 - mae: 0.0066

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0066 - mae: 0.0066

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0066 - mae: 0.0066

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0066 - mae: 0.0066

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0066 - mae: 0.0066

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0066 - mae: 0.0066

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0066 - mae: 0.0066

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0066 - mae: 0.0066

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0066 - mae: 0.0066

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0066 - mae: 0.0066

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0066 - mae: 0.0066

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0067 - mae: 0.0067

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0067 - mae: 0.0067

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0067 - mae: 0.0067

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0067 - mae: 0.0067

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0066 - mae: 0.0066

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0066 - mae: 0.0066

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0066 - mae: 0.0066

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0066 - mae: 0.0066

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0066 - mae: 0.0066

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0066 - mae: 0.0066

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0065 - mae: 0.0065 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 3/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0057 - mae: 0.0057

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0058 - mae: 0.0058

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0058 - mae: 0.0058

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0059 - mae: 0.0059

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0059 - mae: 0.0059

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0059 - mae: 0.0059

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0059 - mae: 0.0059

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0059 - mae: 0.0059

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0059 - mae: 0.0059

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0059 - mae: 0.0059

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0059 - mae: 0.0059

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0059 - mae: 0.0059

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0059 - mae: 0.0059

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0059 - mae: 0.0059

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0060 - mae: 0.0060

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0060 - mae: 0.0060

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0060 - mae: 0.0060

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0060 - mae: 0.0060

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0060 - mae: 0.0060

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0060 - mae: 0.0060

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0060 - mae: 0.0060

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0060 - mae: 0.0060

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0060 - mae: 0.0060

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0060 - mae: 0.0060

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0060 - mae: 0.0060 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 4/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0060 - mae: 0.0060

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0058 - mae: 0.0058

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0058 - mae: 0.0058

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0058 - mae: 0.0058

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0058 - mae: 0.0058

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0058 - mae: 0.0058

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0058 - mae: 0.0058

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0058 - mae: 0.0058

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0058 - mae: 0.0058

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0058 - mae: 0.0058

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0058 - mae: 0.0058

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0058 - mae: 0.0058

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0058 - mae: 0.0058

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 5/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0057 - mae: 0.0057

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 6/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0058 - mae: 0.0058

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0056 - mae: 0.0056

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 7/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 8/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 9/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 10/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 11/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 12/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 13/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 14/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0058 - mae: 0.0058

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0057 - mae: 0.0057

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0057 - mae: 0.0057

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 15/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 16/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0052 - mae: 0.0052

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 17/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 18/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 19/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 20/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 21/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 22/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0052 - mae: 0.0052

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 23/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0052 - mae: 0.0052

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 24/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 25/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 26/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 27/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 28/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 29/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 30/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 31/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Epoch 32/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 9.3750e-06

Epoch 33/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 9.3750e-06

Epoch 34/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0056 - mae: 0.0056

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0056 - mae: 0.0056

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0056 - mae: 0.0056

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0056 - mae: 0.0056

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 9.3750e-06

Epoch 35/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 29ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 9.3750e-06

================================================================================
Trial 14/15
{
  "filters_1": 32,
  "filters_2": 64,
  "filters_3": 128,
  "kernel_1": 5,
  "kernel_2": 7,
  "kernel_3": 5,
  "dilation_2": 2,
  "dilation_3": 4,
  "spatial_dropout": 0.15,
  "dense_1": 256,
  "dense_2": 64,
  "dropout_1": 0.3,
  "dropout_2": 0.2,
  "learning_rate": 0.001,
  "batch_size": 256,
  "trial_id": 14
}
================================================================================
Epoch 1/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1:22 2s/step - loss: 1.7898 - mae: 1.7898

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 1.5332 - mae: 1.5332

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 1.3481 - mae: 1.3481

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 1.2102 - mae: 1.2102

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 1.1016 - mae: 1.1016

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 1.0131 - mae: 1.0131

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.9064 - mae: 0.9064

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.8221 - mae: 0.8221

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7750 - mae: 0.7750

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.7147 - mae: 0.7147

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.6640 - mae: 0.6640

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.6209 - mae: 0.6209

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.5837 - mae: 0.5837

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.5512 - mae: 0.5512

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.5318 - mae: 0.5318

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.5053 - mae: 0.5053

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.4893 - mae: 0.4893

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.4744 - mae: 0.4744

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.4605 - mae: 0.4605

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.4413 - mae: 0.4413

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.4239 - mae: 0.4239

52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - loss: 0.1415 - mae: 0.1415 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 2/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0056 - mae: 0.0056

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0057 - mae: 0.0057

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0057 - mae: 0.0057

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0058 - mae: 0.0058

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0058 - mae: 0.0058

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0058 - mae: 0.0058

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0058 - mae: 0.0058

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0058 - mae: 0.0058

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0058 - mae: 0.0058

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0058 - mae: 0.0058

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0058 - mae: 0.0058

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0058 - mae: 0.0058

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0058 - mae: 0.0058

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0058 - mae: 0.0058

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0058 - mae: 0.0058

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0058 - mae: 0.0058

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0058 - mae: 0.0058

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0058 - mae: 0.0058

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0058 - mae: 0.0058

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0058 - mae: 0.0058

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 3/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0056 - mae: 0.0056

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0057 - mae: 0.0057

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0057 - mae: 0.0057

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0058 - mae: 0.0058

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0058 - mae: 0.0058

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0058 - mae: 0.0058

14/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0058 - mae: 0.0058

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0058 - mae: 0.0058

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0058 - mae: 0.0058

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 4/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0059 - mae: 0.0059

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0057 - mae: 0.0057

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0057 - mae: 0.0057

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0057 - mae: 0.0057

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0057 - mae: 0.0057

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0057 - mae: 0.0057

14/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0057 - mae: 0.0057

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0057 - mae: 0.0057

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0057 - mae: 0.0057

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 5/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0056 - mae: 0.0056

14/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 6/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 7/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 0.0010

Epoch 8/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 9/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 10/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 11/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 12/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 13/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 5.0000e-04

Epoch 14/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 15/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 16/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 37ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 17/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 18/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0056 - mae: 0.0056

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0056 - mae: 0.0056

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0056 - mae: 0.0056

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0056 - mae: 0.0056

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0056 - mae: 0.0056

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 19/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 2.5000e-04

Epoch 20/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 21/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 22/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 23/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0054 - mae: 0.0054

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 24/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 25/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 26/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 27/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 45ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0054 - mae: 0.0054

 5/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 28/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0054 - mae: 0.0054

 3/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 29/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0054 - mae: 0.0054

 6/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

================================================================================
Trial 15/15
{
  "filters_1": 64,
  "filters_2": 96,
  "filters_3": 64,
  "kernel_1": 3,
  "kernel_2": 5,
  "kernel_3": 3,
  "dilation_2": 2,
  "dilation_3": 4,
  "spatial_dropout": 0.1,
  "dense_1": 64,
  "dense_2": 128,
  "dropout_1": 0.1,
  "dropout_2": 0.05,
  "learning_rate": 0.0005,
  "batch_size": 128,
  "trial_id": 15
}
================================================================================
Epoch 1/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:50 2s/step - loss: 1.1587 - mae: 1.1587

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 1.0279 - mae: 1.0279

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.9545 - mae: 0.9545

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.8781 - mae: 0.8781

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.8181 - mae: 0.8181

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.7685 - mae: 0.7685

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.7264 - mae: 0.7264

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.6903 - mae: 0.6903

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.6587 - mae: 0.6587

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6307 - mae: 0.6307

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.6056 - mae: 0.6056

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.5828 - mae: 0.5828

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.5621 - mae: 0.5621

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.5431 - mae: 0.5431

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.5256 - mae: 0.5256

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.5094 - mae: 0.5094

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.4943 - mae: 0.4943

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.4802 - mae: 0.4802

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.4669 - mae: 0.4669

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.4545 - mae: 0.4545

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.4428 - mae: 0.4428

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.4317 - mae: 0.4317

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.4213 - mae: 0.4213

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.4114 - mae: 0.4114

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.4042 - mae: 0.4042

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.3952 - mae: 0.3952

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.3887 - mae: 0.3887

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.1722 - mae: 0.1722 - val_loss: 0.0148 - val_mae: 0.0148 - learning_rate: 5.0000e-04

Epoch 2/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0100 - mae: 0.0100

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0092 - mae: 0.0092

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0088 - mae: 0.0088

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0085 - mae: 0.0085

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0083 - mae: 0.0083

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0082 - mae: 0.0082

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0080 - mae: 0.0080

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0080 - mae: 0.0080

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0079 - mae: 0.0079

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0078 - mae: 0.0078

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0077 - mae: 0.0077

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0077 - mae: 0.0077

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0076 - mae: 0.0076

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0076 - mae: 0.0076

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0075 - mae: 0.0075

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0075 - mae: 0.0075

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0075 - mae: 0.0075

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0074 - mae: 0.0074

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0074 - mae: 0.0074

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0074 - mae: 0.0074

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0073 - mae: 0.0073

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0073 - mae: 0.0073

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0073 - mae: 0.0073

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0073 - mae: 0.0073

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0072 - mae: 0.0072

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0072 - mae: 0.0072

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0072 - mae: 0.0072

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0071 - mae: 0.0071

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0071 - mae: 0.0071

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0064 - mae: 0.0064 - val_loss: 0.0052 - val_mae: 0.0052 - learning_rate: 5.0000e-04

Epoch 3/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0061 - mae: 0.0061

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0059 - mae: 0.0059

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0059 - mae: 0.0059

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0059 - mae: 0.0059

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0058 - mae: 0.0058

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0058 - mae: 0.0058

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0058 - mae: 0.0058

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0058 - mae: 0.0058

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0044 - val_mae: 0.0044 - learning_rate: 5.0000e-04

Epoch 4/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0056 - mae: 0.0056

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0056 - mae: 0.0056

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0056 - mae: 0.0056

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0056 - mae: 0.0056

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0043 - val_mae: 0.0043 - learning_rate: 5.0000e-04

Epoch 5/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 6/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 7/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 8/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 9/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 10/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 11/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 12/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 13/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 14/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 15/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 16/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 17/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 18/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 19/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 20/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 21/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 22/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 23/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.2500e-04

Epoch 24/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 25/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 26/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 27/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 28/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 29/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 6.2500e-05

Epoch 30/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 31/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 32/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 33/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 34/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 35/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.1250e-05

Epoch 36/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5625e-05

Epoch 37/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5625e-05

Epoch 38/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5625e-05

Epoch 39/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5625e-05

Epoch 40/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5625e-05

Epoch 41/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5625e-05

Epoch 42/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.8125e-06

Epoch 43/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.8125e-06

Epoch 44/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0057 - mae: 0.0057

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.8125e-06

Epoch 45/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.8125e-06

Epoch 46/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.8125e-06

Epoch 47/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.8125e-06

Epoch 48/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.9063e-06

Epoch 49/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.9063e-06

Epoch 50/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.9063e-06

,trial_id,input_window,output_window,MAE_train,MAE_val,params,epochs_trained,filters_1,filters_2,filters_3,...,kernel_3,dilation_2,dilation_3,spatial_dropout,dense_1,dense_2,dropout_1,dropout_2,learning_rate,batch_size
0,2,30,5,0.005479,0.004137,81495,32,32,64,128,...,3,2,4,0.20,128,32,0.1,0.05,0.0010,128
1,6,30,5,0.005496,0.004137,105911,22,64,96,64,...,3,1,2,0.15,128,128,0.3,0.05,0.0003,256
2,3,30,5,0.005478,0.004138,80951,29,32,32,64,...,3,2,4,0.20,256,128,0.2,0.10,0.0010,128
3,1,30,5,0.005479,0.004138,78327,31,96,32,64,...,3,1,2,0.05,256,64,0.1,0.05,0.0010,64
4,10,30,5,0.005475,0.004141,130647,34,64,64,128,...,5,2,4,0.15,128,128,0.1,0.05,0.0010,256
5,12,30,5,0.005473,0.004141,110167,41,64,96,96,...,3,2,2,0.15,256,32,0.1,0.05,0.0003,64
6,4,30,5,0.005608,0.004141,75735,16,32,32,96,...,3,1,2,0.15,256,32,0.1,0.20,0.0001,64
7,8,30,5,0.005474,0.004141,125751,34,96,32,128,...,5,1,2,0.15,256,64,0.2,0.05,0.0005,256
8,14,30,5,0.005475,0.004142,143831,29,32,64,128,...,5,2,4,0.15,256,64,0.3,0.20,0.0010,256
9,13,30,5,0.005472,0.004143,120279,35,64,64,128,...,3,1,4,0.20,256,32,0.3,0.10,0.0003,128

Trials saved to: /Users/jchulvi/projects/Neural-Networks-Forecasting/data/cnn_search/cnn_hyperparameter_trials.csv
Best config saved to: /Users/jchulvi/projects/Neural-Networks-Forecasting/data/cnn_search/best_config.json

## Final test evaluation of the selected model

The selected model is loaded from disk and evaluated on the untouched test set. This gives the final result of the hyperparameter search.

In [6]:
best_model = keras.models.load_model(OUTPUT_DIR / "best_cnn_model.keras")

y_pred_train = best_model.predict(X_train, verbose=0)
y_pred_val = best_model.predict(X_val, verbose=0)
y_pred_test = best_model.predict(X_test, verbose=0)

best_result = {
    "model": "CNN_Optimized_RandomSearch",
    "selected_trial_id": best_trial_id,
    "input_window": INPUT_WINDOW,
    "output_window": OUTPUT_WINDOW,
    "MAE_train": mean_absolute_error(y_train, y_pred_train),
    "MAE_val": mean_absolute_error(y_val, y_pred_val),
    "MAE_test": mean_absolute_error(y_test, y_pred_test),
    "params": best_model.count_params(),
    "selection_metric": "MAE_val",
}

best_result_df = pd.DataFrame([best_result])
best_result_path = OUTPUT_DIR / "best_cnn_optimized_result.csv"
best_result_df.to_csv(best_result_path, index=False)

comparison_df = None
lr_path = PROJECT_ROOT / "data" / "lr_benchmark.csv"
if lr_path.exists():
    lr = pd.read_csv(lr_path)
    lr_match = lr[(lr["input_window"] == INPUT_WINDOW) & (lr["output_window"] == OUTPUT_WINDOW)]
    if len(lr_match) == 1:
        lr_row = lr_match.iloc[0]
        comparison_df = pd.DataFrame([
            {
                "model": "Linear_Regression_Benchmark",
                "input_window": INPUT_WINDOW,
                "output_window": OUTPUT_WINDOW,
                "MAE_train": lr_row["MAE_train"],
                "MAE_val": np.nan,
                "MAE_test": lr_row["MAE_test"],
                "params": np.nan,
            },
            best_result,
        ])
        comparison_df["improvement_abs_vs_lr"] = comparison_df["MAE_test"].iloc[0] - comparison_df["MAE_test"]
        comparison_df["improvement_pct_vs_lr"] = (
            comparison_df["improvement_abs_vs_lr"] / comparison_df["MAE_test"].iloc[0] * 100
        )
        comparison_path = OUTPUT_DIR / "best_cnn_optimized_vs_lr.csv"
        comparison_df.to_csv(comparison_path, index=False)
        print("Comparison saved to:", comparison_path)

print("Best result saved to:", best_result_path)
display(best_result_df)
if comparison_df is not None:
    display(comparison_df)

Comparison saved to: /Users/jchulvi/projects/Neural-Networks-Forecasting/data/cnn_search/best_cnn_optimized_vs_lr.csv
Best result saved to: /Users/jchulvi/projects/Neural-Networks-Forecasting/data/cnn_search/best_cnn_optimized_result.csv

,model,selected_trial_id,input_window,output_window,MAE_train,MAE_val,MAE_test,params,selection_metric
0,CNN_Optimized_RandomSearch,2,30,5,0.005479,0.004137,0.005598,81495,MAE_val

,model,input_window,output_window,MAE_train,MAE_val,MAE_test,params,selected_trial_id,selection_metric,improvement_abs_vs_lr,improvement_pct_vs_lr
0,Linear_Regression_Benchmark,30,5,0.005337,NaN,0.005877,NaN,NaN,NaN,0.000000,0.000000
1,CNN_Optimized_RandomSearch,30,5,0.005479,0.004137,0.005598,81495.0,2.0,MAE_val,0.000279,4.748022

## How to report this

This notebook supports the following statement in the report:

> A controlled random search was performed for the CNN model. The tested hyperparameters included the number of convolutional filters, kernel sizes, dilation rates, dropout levels, dense layer widths, learning rate and batch size. The model was selected using validation MAE, while the test set was reserved for final evaluation only.