# Hybrid CNN-RNN models for assigned windows

This notebook trains hybrid neural networks that combine **Conv1D** layers with **LSTM/GRU** layers.

Assigned windows:

| Input window | Output window |
|---:|---:|
| 10 | 30 |
| 10 | 90 |
| 30 | 1 |
| 30 | 5 |

The goal is to evaluate mixed architectures on the forecasting task and export results that can be used directly in the final report.

The test set is not used for model selection. For each run, the notebook uses:

1. train split for fitting the model,
2. validation split for early stopping and model comparison,
3. test split for final evaluation.

In [1]:
import os
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")

import sys
import json
from pathlib import Path
from datetime import datetime

# Locate project root from notebook execution directory.
_here = Path.cwd().resolve()
_candidates = [_here, *_here.parents]
PROJECT_ROOT = next(p for p in _candidates if (p / "util.py").exists())
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler

import keras
from keras import backend as K
from keras.models import Model
from keras.layers import (
    Input,
    Conv1D,
    BatchNormalization,
    SpatialDropout1D,
    LSTM,
    GRU,
    Bidirectional,
    Dense,
    Dropout,
)
from keras.callbacks import EarlyStopping, ReduceLROnPlateau

from util import get_train_test, RANDOM_SEED, plot_training_curve

try:
    from util import configure_mlflow
except ImportError:
    import mlflow

    def configure_mlflow(experiment_name: str):
        tracking_uri = f"sqlite:///{PROJECT_ROOT / 'model' / 'mlflow.db'}"
        mlflow.set_tracking_uri(tracking_uri)
        mlflow.set_experiment(experiment_name)
        return mlflow


np.random.seed(RANDOM_SEED)
keras.utils.set_random_seed(RANDOM_SEED)

DATA_OUT = PROJECT_ROOT / "data" / "mixtos" / "cnn_rnn_hybrid"
HISTORY_DIR = DATA_OUT / "history"
PLOTS_DIR = DATA_OUT / "plots"

DATA_OUT.mkdir(parents=True, exist_ok=True)
HISTORY_DIR.mkdir(parents=True, exist_ok=True)
PLOTS_DIR.mkdir(parents=True, exist_ok=True)

mlflow = configure_mlflow("hybrid_cnn_rnn_models")

FAST_DEV_RUN = os.getenv("FAST_DEV_RUN", "0") == "1"
LOG_MODEL_ARTIFACT = os.getenv("LOG_MODEL_ARTIFACT", "0") == "1"

print("PROJECT_ROOT:", PROJECT_ROOT)
print("FAST_DEV_RUN:", FAST_DEV_RUN)
print("LOG_MODEL_ARTIFACT:", LOG_MODEL_ARTIFACT)

2026/05/19 00:14:41 INFO mlflow.store.db.utils: Creating initial MLflow database tables...

2026/05/19 00:14:41 INFO mlflow.store.db.utils: Updating database tables

PROJECT_ROOT: /Users/jchulvi/projects/Neural-Networks-Forecasting
FAST_DEV_RUN: False
LOG_MODEL_ARTIFACT: False

## Configuration

The full run trains three hybrid architectures for each assigned window:

- `CNN_LSTM`
- `CNN_GRU`
- `CNN_BiGRU`

The hyperparameters are intentionally controlled and comparable across windows. This avoids an excessively large search while still producing a clean comparison between hybrid architectures.

A fast smoke test can be launched from terminal with:

```bash
FAST_DEV_RUN=1 jupyter nbconvert --to notebook --execute model/mixtos/cnn_rnn_hybrid/01_hybrid_cnn_rnn_grid.ipynb \
  --output 01_hybrid_cnn_rnn_grid_executed.ipynb \
  --output-dir model/mixtos/cnn_rnn_hybrid/outputs
```

In [2]:
WINDOWS = [
    (10, 30),
    (10, 90),
    (30, 1),
    (30, 5),
]

ARCHITECTURES = [
    {
        "architecture": "CNN_LSTM",
        "filters": 64,
        "kernel_size": 3,
        "rnn_units": 64,
        "dense_units": 64,
        "spatial_dropout": 0.10,
        "dropout": 0.15,
        "learning_rate": 3e-4,
        "batch_size": 128,
    },
    {
        "architecture": "CNN_GRU",
        "filters": 64,
        "kernel_size": 3,
        "rnn_units": 64,
        "dense_units": 64,
        "spatial_dropout": 0.10,
        "dropout": 0.15,
        "learning_rate": 3e-4,
        "batch_size": 128,
    },
    {
        "architecture": "CNN_BiGRU",
        "filters": 64,
        "kernel_size": 5,
        "rnn_units": 64,
        "dense_units": 64,
        "spatial_dropout": 0.10,
        "dropout": 0.20,
        "learning_rate": 3e-4,
        "batch_size": 128,
    },
]

MAX_EPOCHS = 80
EARLY_STOPPING_PATIENCE = 10
LR_PATIENCE = 5
VALIDATION_RATIO = 0.10

if FAST_DEV_RUN:
    WINDOWS = WINDOWS[:1]
    ARCHITECTURES = ARCHITECTURES[:1]
    MAX_EPOCHS = 2
    EARLY_STOPPING_PATIENCE = 1
    LR_PATIENCE = 1

print("Windows:", WINDOWS)
print("Architectures:", [cfg["architecture"] for cfg in ARCHITECTURES])
print("Max epochs:", MAX_EPOCHS)

Windows: [(10, 30), (10, 90), (30, 1), (30, 5)]
Architectures: ['CNN_LSTM', 'CNN_GRU', 'CNN_BiGRU']
Max epochs: 80

## Data preparation

The function `get_train_test` returns data with the sequence format required by recurrent and convolutional models:

```text
X: samples × input_window × assets
y: samples × assets
```

The validation set is taken from the end of the training set. Inputs are standardized using only the training split to avoid data leakage.

In [3]:
def split_train_val(X_train, y_train, val_ratio=VALIDATION_RATIO):
    val_size = int(len(X_train) * val_ratio)
    if val_size <= 0:
        raise ValueError("Validation split is empty. Increase the training size or validation ratio.")

    X_val = X_train[-val_size:]
    y_val = y_train[-val_size:]
    X_train_final = X_train[:-val_size]
    y_train_final = y_train[:-val_size]
    return X_train_final, y_train_final, X_val, y_val


def scale_X_only(X_train, X_val, X_test):
    """Scale only the inputs. The target remains in the original return scale."""
    n_train, window, n_assets = X_train.shape
    n_val = X_val.shape[0]
    n_test = X_test.shape[0]

    scaler = StandardScaler()

    X_train_2d = X_train.reshape(n_train, -1)
    X_val_2d = X_val.reshape(n_val, -1)
    X_test_2d = X_test.reshape(n_test, -1)

    X_train_scaled = scaler.fit_transform(X_train_2d).reshape(n_train, window, n_assets)
    X_val_scaled = scaler.transform(X_val_2d).reshape(n_val, window, n_assets)
    X_test_scaled = scaler.transform(X_test_2d).reshape(n_test, window, n_assets)

    return X_train_scaled, X_val_scaled, X_test_scaled


def load_window_data(input_window, output_window):
    d = get_train_test(
        input_window_size=input_window,
        output_window_size=output_window,
    )

    X_train_raw, y_train_raw = d.X_train, d.y_train
    X_test_raw, y_test = d.X_test, d.y_test

    X_train_raw, y_train, X_val_raw, y_val = split_train_val(X_train_raw, y_train_raw)
    X_train, X_val, X_test = scale_X_only(X_train_raw, X_val_raw, X_test_raw)

    return X_train, y_train, X_val, y_val, X_test, y_test

## Hybrid model builder

The hybrid models first use a convolutional layer to detect local temporal patterns. The recurrent block then models the sequential component of the window. The final dense layers map the learned representation to the 23 output assets.

In [4]:
def build_hybrid_model(input_window, n_assets, cfg):
    architecture = cfg["architecture"]

    inputs = Input(shape=(input_window, n_assets))

    x = Conv1D(
        filters=cfg["filters"],
        kernel_size=cfg["kernel_size"],
        padding="causal",
        activation="relu",
    )(inputs)
    x = BatchNormalization()(x)
    x = SpatialDropout1D(cfg["spatial_dropout"])(x)

    if architecture == "CNN_LSTM":
        x = LSTM(cfg["rnn_units"], return_sequences=False)(x)
    elif architecture == "CNN_GRU":
        x = GRU(cfg["rnn_units"], return_sequences=False)(x)
    elif architecture == "CNN_BiGRU":
        x = Bidirectional(GRU(cfg["rnn_units"], return_sequences=False))(x)
    else:
        raise ValueError(f"Unknown architecture: {architecture}")

    x = Dense(cfg["dense_units"], activation="relu")(x)
    x = Dropout(cfg["dropout"])(x)

    outputs = Dense(n_assets, activation="linear")(x)

    model = Model(inputs=inputs, outputs=outputs)
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=cfg["learning_rate"]),
        loss="mae",
        metrics=["mae"],
    )
    return model

## Training and MLflow logging

Each run is logged to MLflow with the window, architecture, hyperparameters, metrics and training curve. CSV files are also generated under `data/mixtos/cnn_rnn_hybrid/` for easier inclusion in the report.

In [5]:
def safe_run_name(architecture, input_window, output_window):
    return f"hybrid_{architecture}_input{input_window}_output{output_window}"


def delete_existing_mlflow_run(run_name):
    existing_runs = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing_runs.empty:
        for run_id in existing_runs["run_id"]:
            mlflow.delete_run(run_id)


def save_history_and_plot(history, run_name):
    history_df = pd.DataFrame(history.history)
    history_path = HISTORY_DIR / f"{run_name}_history.csv"
    plot_path = PLOTS_DIR / f"{run_name}_loss_curve.png"

    history_df.to_csv(history_path, index=False)

    fig = plot_training_curve(history)
    fig.savefig(plot_path, dpi=150, bbox_inches="tight")
    plt.close(fig)

    return history_path, plot_path


def train_one_model(input_window, output_window, cfg):
    K.clear_session()
    keras.utils.set_random_seed(RANDOM_SEED)

    run_name = safe_run_name(cfg["architecture"], input_window, output_window)
    delete_existing_mlflow_run(run_name)

    X_train, y_train, X_val, y_val, X_test, y_test = load_window_data(input_window, output_window)
    n_assets = X_train.shape[2]

    model = build_hybrid_model(input_window, n_assets, cfg)

    callbacks = [
        EarlyStopping(
            monitor="val_loss",
            patience=EARLY_STOPPING_PATIENCE,
            min_delta=1e-6,
            restore_best_weights=True,
        ),
        ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.5,
            patience=LR_PATIENCE,
            min_lr=1e-6,
        ),
    ]

    print()
    print("=" * 90)
    print(f"Training {run_name}")
    print("X_train:", X_train.shape, "y_train:", y_train.shape)
    print("X_val:  ", X_val.shape, "y_val:  ", y_val.shape)
    print("X_test: ", X_test.shape, "y_test: ", y_test.shape)
    print("Params:", model.count_params())

    history = model.fit(
        X_train,
        y_train,
        validation_data=(X_val, y_val),
        epochs=MAX_EPOCHS,
        batch_size=cfg["batch_size"],
        callbacks=callbacks,
        verbose=1,
        shuffle=True,
    )

    y_pred_train = model.predict(X_train, verbose=0)
    y_pred_val = model.predict(X_val, verbose=0)
    y_pred_test = model.predict(X_test, verbose=0)

    row = {
        "model": cfg["architecture"],
        "input_window": input_window,
        "output_window": output_window,
        "MAE_train": mean_absolute_error(y_train, y_pred_train),
        "MAE_val": mean_absolute_error(y_val, y_pred_val),
        "MAE_test": mean_absolute_error(y_test, y_pred_test),
        "params": model.count_params(),
        "epochs_trained": len(history.history["loss"]),
        "filters": cfg["filters"],
        "kernel_size": cfg["kernel_size"],
        "rnn_units": cfg["rnn_units"],
        "dense_units": cfg["dense_units"],
        "spatial_dropout": cfg["spatial_dropout"],
        "dropout": cfg["dropout"],
        "learning_rate": cfg["learning_rate"],
        "batch_size": cfg["batch_size"],
    }

    history_path, plot_path = save_history_and_plot(history, run_name)
    row["history_path"] = str(history_path.relative_to(PROJECT_ROOT))
    row["plot_path"] = str(plot_path.relative_to(PROJECT_ROOT))

    with mlflow.start_run(run_name=run_name):
        mlflow.set_tag("model_family", "Hybrid_CNN_RNN")
        mlflow.set_tag("model_name", cfg["architecture"])
        mlflow.log_params({
            "input_window_size": input_window,
            "output_window_size": output_window,
            "architecture": cfg["architecture"],
            "filters": cfg["filters"],
            "kernel_size": cfg["kernel_size"],
            "rnn_units": cfg["rnn_units"],
            "dense_units": cfg["dense_units"],
            "spatial_dropout": cfg["spatial_dropout"],
            "dropout": cfg["dropout"],
            "learning_rate": cfg["learning_rate"],
            "batch_size": cfg["batch_size"],
            "epochs_trained": row["epochs_trained"],
            "n_params": row["params"],
            "validation_ratio": VALIDATION_RATIO,
        })

        for epoch, (loss, val_loss) in enumerate(zip(history.history["loss"], history.history["val_loss"]), start=1):
            mlflow.log_metric("train_loss", float(loss), step=epoch)
            mlflow.log_metric("val_loss", float(val_loss), step=epoch)

        mlflow.log_metric("train_mae", float(row["MAE_train"]))
        mlflow.log_metric("val_mae", float(row["MAE_val"]))
        mlflow.log_metric("test_mae", float(row["MAE_test"]))
        mlflow.log_artifact(str(history_path), artifact_path="history")
        mlflow.log_artifact(str(plot_path), artifact_path="plots")

        if LOG_MODEL_ARTIFACT:
            mlflow.keras.log_model(model, name=f"{run_name}_model")

    print("Result:", json.dumps({k: v for k, v in row.items() if not k.endswith('_path')}, indent=2))
    return row

## Execute grid

The full run trains 12 models:

```text
4 windows × 3 architectures = 12 hybrid models
```

The best model for each window is selected by validation MAE.

In [6]:
rows = []

for input_window, output_window in WINDOWS:
    for cfg in ARCHITECTURES:
        row = train_one_model(input_window, output_window, cfg)
        rows.append(row)

        partial = pd.DataFrame(rows)
        partial.to_csv(DATA_OUT / "hybrid_all_results_partial.csv", index=False)

results = pd.DataFrame(rows)
results = results.sort_values(["input_window", "output_window", "MAE_val"]).reset_index(drop=True)
results_path = DATA_OUT / "hybrid_all_results.csv"
results.to_csv(results_path, index=False)

best_by_window = (
    results.sort_values("MAE_val")
    .groupby(["input_window", "output_window"], as_index=False)
    .first()
    .sort_values(["input_window", "output_window"])
)
best_path = DATA_OUT / "hybrid_best_by_window.csv"
best_by_window.to_csv(best_path, index=False)

print("All results saved to:", results_path)
print("Best by window saved to:", best_path)

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
pd.set_option("display.float_format", "{:.8f}".format)

display(results[[
    "model", "input_window", "output_window", "MAE_train", "MAE_val", "MAE_test", "params", "epochs_trained"
]])

display(best_by_window[[
    "model", "input_window", "output_window", "MAE_train", "MAE_val", "MAE_test", "params", "epochs_trained"
]])

==========================================================================================
Training hybrid_CNN_LSTM_input10_output30
X_train: (13086, 10, 23) y_train: (13086, 23)
X_val:   (1454, 10, 23) y_val:   (1454, 23)
X_test:  (1616, 10, 23) y_test:  (1616, 23)
Params: 43415
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:16 1s/step - loss: 0.1303 - mae: 0.1303

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1203 - mae: 0.1203

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1151 - mae: 0.1151

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1105 - mae: 0.1105

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1065 - mae: 0.1065

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1027 - mae: 0.1027

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0993 - mae: 0.0993

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0962 - mae: 0.0962

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0930 - mae: 0.0930

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0902 - mae: 0.0902

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0620 - mae: 0.0620 - val_loss: 0.0115 - val_mae: 0.0115 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0222 - mae: 0.0222

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0199 - mae: 0.0199

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0186 - mae: 0.0186

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0174 - mae: 0.0174

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0163 - mae: 0.0163

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0153 - mae: 0.0153

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0144 - mae: 0.0144

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0137 - mae: 0.0137

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0130 - mae: 0.0130

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0124 - mae: 0.0124

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0069 - mae: 0.0069 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0024 - mae: 0.0024

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0027 - mae: 0.0027

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0026 - mae: 0.0026

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0026 - mae: 0.0026

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0026 - mae: 0.0026

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0026 - mae: 0.0026

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0026 - mae: 0.0026

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0025 - mae: 0.0025

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0025 - mae: 0.0025

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0025 - mae: 0.0025

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0025 - mae: 0.0025

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0024 - mae: 0.0024 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0023 - mae: 0.0023

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0023 - mae: 0.0023 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0022 - mae: 0.0022

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0022 - mae: 0.0022

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0022 - mae: 0.0022

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0023 - mae: 0.0023

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0023 - mae: 0.0023

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0023 - mae: 0.0023

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0023 - mae: 0.0023

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0023 - mae: 0.0023

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0023 - mae: 0.0023

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0023 - mae: 0.0023

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Result: {
  "model": "CNN_LSTM",
  "input_window": 10,
  "output_window": 30,
  "MAE_train": 0.0022143203750876377,
  "MAE_val": 0.0017091305323815743,
  "MAE_test": 0.0023481380812438958,
  "params": 43415,
  "epochs_trained": 14,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_GRU_input10_output30
X_train: (13086, 10, 23) y_train: (13086, 23)
X_val:   (1454, 10, 23) y_val:   (1454, 23)
X_test:  (1616, 10, 23) y_test:  (1616, 23)
Params: 35351
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:32 1s/step - loss: 0.2283 - mae: 0.2283

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2207 - mae: 0.2207

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2133 - mae: 0.2133

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2060 - mae: 0.2060

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2001 - mae: 0.2001

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1947 - mae: 0.1947

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1897 - mae: 0.1897

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1845 - mae: 0.1845

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1797 - mae: 0.1797

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1750 - mae: 0.1750

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1711 - mae: 0.1711

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.1266 - mae: 0.1266 - val_loss: 0.0223 - val_mae: 0.0223 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0541 - mae: 0.0541

 10/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0515 - mae: 0.0515

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0493 - mae: 0.0493

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0464 - mae: 0.0464

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0437 - mae: 0.0437

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0408 - mae: 0.0408

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0385 - mae: 0.0385

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0361 - mae: 0.0361

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0342 - mae: 0.0342

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0323 - mae: 0.0323

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0308 - mae: 0.0308

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0150 - mae: 0.0150 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 10/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0026 - mae: 0.0026

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0026 - mae: 0.0026

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0026 - mae: 0.0026

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0026 - mae: 0.0026

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0026 - mae: 0.0026

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0026 - mae: 0.0026

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0025 - mae: 0.0025

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0025 - mae: 0.0025

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0025 - mae: 0.0025

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0025 - mae: 0.0025

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0025 - mae: 0.0025

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0024 - mae: 0.0024 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0023 - mae: 0.0023 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0023 - mae: 0.0023

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0023 - mae: 0.0023

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0023 - mae: 0.0023

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0023 - mae: 0.0023 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0022 - mae: 0.0022

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 10/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 16/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 17/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 10/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 18/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 19/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 20/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 21/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 22/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 23/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 10/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 24/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 25/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 26/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 27/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 28/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 29/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0022 - mae: 0.0022

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 30/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 31/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 32/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 33/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Epoch 34/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Epoch 35/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Epoch 36/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Epoch 37/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Epoch 38/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 2.3438e-06

Result: {
  "model": "CNN_GRU",
  "input_window": 10,
  "output_window": 30,
  "MAE_train": 0.0022016704136876802,
  "MAE_val": 0.001702837065127023,
  "MAE_test": 0.0023190932386777515,
  "params": 35351,
  "epochs_trained": 38,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_BiGRU_input10_output30
X_train: (13086, 10, 23) y_train: (13086, 23)
X_val:   (1454, 10, 23) y_val:   (1454, 23)
X_test:  (1616, 10, 23) y_test:  (1616, 23)
Params: 67351
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3:38 2s/step - loss: 0.2797 - mae: 0.2797

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2620 - mae: 0.2620

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2492 - mae: 0.2492

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2378 - mae: 0.2378

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2276 - mae: 0.2276

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2183 - mae: 0.2183

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2097 - mae: 0.2097

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2017 - mae: 0.2017

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1941 - mae: 0.1941

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1877 - mae: 0.1877

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1809 - mae: 0.1809

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1773 - mae: 0.1773

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1739 - mae: 0.1739

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.1043 - mae: 0.1043 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0133 - mae: 0.0133

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0144 - mae: 0.0144

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0140 - mae: 0.0140

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0137 - mae: 0.0137

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0134 - mae: 0.0134

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0131 - mae: 0.0131

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0128 - mae: 0.0128

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0125 - mae: 0.0125

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0122 - mae: 0.0122

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0117 - mae: 0.0117

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0114 - mae: 0.0114

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0112 - mae: 0.0112

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0110 - mae: 0.0110

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0108 - mae: 0.0108

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0106 - mae: 0.0106

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0104 - mae: 0.0104

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0102 - mae: 0.0102

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0100 - mae: 0.0100

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0098 - mae: 0.0098

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0097 - mae: 0.0097

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0066 - mae: 0.0066 - val_loss: 0.0019 - val_mae: 0.0019 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0036 - mae: 0.0036

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0042 - mae: 0.0042

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0040

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0038 - mae: 0.0038

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0037 - mae: 0.0037

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0037 - mae: 0.0037

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0036 - mae: 0.0036

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0036 - mae: 0.0036

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0035 - mae: 0.0035

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0035 - mae: 0.0035

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0035 - mae: 0.0035

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0034 - mae: 0.0034

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0034 - mae: 0.0034

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0034 - mae: 0.0034

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0034 - mae: 0.0034

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0033 - mae: 0.0033

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0033 - mae: 0.0033

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0033 - mae: 0.0033

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0033 - mae: 0.0033

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0033 - mae: 0.0033

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0033 - mae: 0.0033

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0029 - mae: 0.0029 - val_loss: 0.0018 - val_mae: 0.0018 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0024 - mae: 0.0024

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0028 - mae: 0.0028

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0027 - mae: 0.0027

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0027 - mae: 0.0027

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0027 - mae: 0.0027

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0027 - mae: 0.0027

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0026 - mae: 0.0026

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0025 - mae: 0.0025 - val_loss: 0.0018 - val_mae: 0.0018 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0023 - mae: 0.0023

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0025 - mae: 0.0025

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0025 - mae: 0.0025

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0023 - mae: 0.0023 - val_loss: 0.0018 - val_mae: 0.0018 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0024 - mae: 0.0024

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024 - mae: 0.0024

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0023 - mae: 0.0023 - val_loss: 0.0018 - val_mae: 0.0018 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0023 - mae: 0.0023

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0023 - mae: 0.0023 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0023 - mae: 0.0023

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0023 - mae: 0.0023 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0023 - mae: 0.0023

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0024 - mae: 0.0024

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0023 - mae: 0.0023

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 16/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 17/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 18/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 19/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 20/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 21/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 22/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0023 - mae: 0.0023

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 23/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 24/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 25/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 26/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 27/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 28/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 29/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 30/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0023 - mae: 0.0023

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 31/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 32/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0022

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0022 - mae: 0.0022

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0022 - mae: 0.0022

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0022 - mae: 0.0022

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 33/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 34/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Epoch 35/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Epoch 36/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Epoch 37/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Epoch 38/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Epoch 39/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 2.3438e-06

Epoch 40/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0022 - mae: 0.0022

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0022 - mae: 0.0022

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 2.3438e-06

Epoch 41/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 2.3438e-06

Epoch 42/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 2.3438e-06

Epoch 43/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 2.3438e-06

Epoch 44/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.1719e-06

Result: {
  "model": "CNN_BiGRU",
  "input_window": 10,
  "output_window": 30,
  "MAE_train": 0.002201630387401538,
  "MAE_val": 0.0017146198794259439,
  "MAE_test": 0.002333397317330835,
  "params": 67351,
  "epochs_trained": 44,
  "filters": 64,
  "kernel_size": 5,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.2,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_LSTM_input10_output90
X_train: (13038, 10, 23) y_train: (13038, 23)
X_val:   (1448, 10, 23) y_val:   (1448, 23)
X_test:  (1610, 10, 23) y_test:  (1610, 23)
Params: 43415
Epoch 1/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2:18 1s/step - loss: 0.1341 - mae: 0.1341

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1226 - mae: 0.1226

 23/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1166 - mae: 0.1166

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1114 - mae: 0.1114

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1070 - mae: 0.1070

 54/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1028 - mae: 0.1028

 64/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0993 - mae: 0.0993

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0961 - mae: 0.0961

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0932 - mae: 0.0932

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0903 - mae: 0.0903

102/102 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0616 - mae: 0.0616 - val_loss: 0.0103 - val_mae: 0.0103 - learning_rate: 3.0000e-04

Epoch 2/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0207 - mae: 0.0207

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0189 - mae: 0.0189

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0175 - mae: 0.0175

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0159 - mae: 0.0159

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0147 - mae: 0.0147

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0137 - mae: 0.0137

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0128 - mae: 0.0128

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0120 - mae: 0.0120

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0113 - mae: 0.0113

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0108 - mae: 0.0108

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0054 - mae: 0.0054 - val_loss: 9.4242e-04 - val_mae: 9.4242e-04 - learning_rate: 3.0000e-04

Epoch 3/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0015 - mae: 0.0015

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0015 - mae: 0.0015

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0015 - mae: 0.0015

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0015 - mae: 0.0015

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0015 - mae: 0.0015

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0015 - mae: 0.0015

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0015 - mae: 0.0015

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0015 - mae: 0.0015

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0015 - mae: 0.0015

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0015 - mae: 0.0015

102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0015 - mae: 0.0015

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0014 - mae: 0.0014 - val_loss: 9.3302e-04 - val_mae: 9.3302e-04 - learning_rate: 3.0000e-04

Epoch 4/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0014 - mae: 0.0014

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3577e-04 - val_mae: 9.3577e-04 - learning_rate: 3.0000e-04

Epoch 5/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 30/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 60/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 70/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3731e-04 - val_mae: 9.3731e-04 - learning_rate: 3.0000e-04

Epoch 6/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3442e-04 - val_mae: 9.3442e-04 - learning_rate: 3.0000e-04

Epoch 7/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3335e-04 - val_mae: 9.3335e-04 - learning_rate: 3.0000e-04

Epoch 8/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3829e-04 - val_mae: 9.3829e-04 - learning_rate: 1.5000e-04

Epoch 9/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 65/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3865e-04 - val_mae: 9.3865e-04 - learning_rate: 1.5000e-04

Epoch 10/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 60/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 70/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3817e-04 - val_mae: 9.3817e-04 - learning_rate: 1.5000e-04

Epoch 11/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3857e-04 - val_mae: 9.3857e-04 - learning_rate: 1.5000e-04

Epoch 12/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3810e-04 - val_mae: 9.3810e-04 - learning_rate: 1.5000e-04

Epoch 13/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3585e-04 - val_mae: 9.3585e-04 - learning_rate: 7.5000e-05

Result: {
  "model": "CNN_LSTM",
  "input_window": 10,
  "output_window": 90,
  "MAE_train": 0.0012814264584010443,
  "MAE_val": 0.000933023662799931,
  "MAE_test": 0.0013117766367061877,
  "params": 43415,
  "epochs_trained": 13,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_GRU_input10_output90
X_train: (13038, 10, 23) y_train: (13038, 23)
X_val:   (1448, 10, 23) y_val:   (1448, 23)
X_test:  (1610, 10, 23) y_test:  (1610, 23)
Params: 35351
Epoch 1/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2:30 1s/step - loss: 0.2390 - mae: 0.2390

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.2270 - mae: 0.2270

 23/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2176 - mae: 0.2176

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2094 - mae: 0.2094

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2024 - mae: 0.2024

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1961 - mae: 0.1961

 63/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1903 - mae: 0.1903

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1850 - mae: 0.1850

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1801 - mae: 0.1801

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1749 - mae: 0.1749

102/102 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.1273 - mae: 0.1273 - val_loss: 0.0221 - val_mae: 0.0221 - learning_rate: 3.0000e-04

Epoch 2/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0550 - mae: 0.0550

 10/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0536 - mae: 0.0536

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0506 - mae: 0.0506

 29/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0477 - mae: 0.0477

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0449 - mae: 0.0449

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0423 - mae: 0.0423

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0398 - mae: 0.0398

 65/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0376 - mae: 0.0376

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0356 - mae: 0.0356

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0335 - mae: 0.0335

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0318 - mae: 0.0318

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0150 - mae: 0.0150 - val_loss: 9.4162e-04 - val_mae: 9.4162e-04 - learning_rate: 3.0000e-04

Epoch 3/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0014 - mae: 0.0014

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0015 - mae: 0.0015

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0016 - mae: 0.0016

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0016 - mae: 0.0016

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0016 - mae: 0.0016

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0016 - mae: 0.0016

 60/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0016 - mae: 0.0016

 70/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0016 - mae: 0.0016

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0015 - mae: 0.0015

 89/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0015 - mae: 0.0015

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0015 - mae: 0.0015

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0015 - mae: 0.0015 - val_loss: 9.3636e-04 - val_mae: 9.3636e-04 - learning_rate: 3.0000e-04

Epoch 4/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 30/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 39/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3625e-04 - val_mae: 9.3625e-04 - learning_rate: 3.0000e-04

Epoch 5/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 30/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3627e-04 - val_mae: 9.3627e-04 - learning_rate: 3.0000e-04

Epoch 6/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3702e-04 - val_mae: 9.3702e-04 - learning_rate: 3.0000e-04

Epoch 7/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

  8/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 18/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3643e-04 - val_mae: 9.3643e-04 - learning_rate: 3.0000e-04

Epoch 8/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3816e-04 - val_mae: 9.3816e-04 - learning_rate: 1.5000e-04

Epoch 9/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3794e-04 - val_mae: 9.3794e-04 - learning_rate: 1.5000e-04

Epoch 10/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 30/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3925e-04 - val_mae: 9.3925e-04 - learning_rate: 1.5000e-04

Epoch 11/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0012 - mae: 0.0012

 10/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 30/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 39/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3850e-04 - val_mae: 9.3850e-04 - learning_rate: 1.5000e-04

Epoch 12/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3813e-04 - val_mae: 9.3813e-04 - learning_rate: 1.5000e-04

Epoch 13/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3455e-04 - val_mae: 9.3455e-04 - learning_rate: 7.5000e-05

Epoch 14/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3526e-04 - val_mae: 9.3526e-04 - learning_rate: 7.5000e-05

Epoch 15/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3560e-04 - val_mae: 9.3560e-04 - learning_rate: 7.5000e-05

Epoch 16/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3586e-04 - val_mae: 9.3586e-04 - learning_rate: 7.5000e-05

Epoch 17/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3595e-04 - val_mae: 9.3595e-04 - learning_rate: 7.5000e-05

Epoch 18/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3039e-04 - val_mae: 9.3039e-04 - learning_rate: 3.7500e-05

Epoch 19/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3063e-04 - val_mae: 9.3063e-04 - learning_rate: 3.7500e-05

Epoch 20/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3063e-04 - val_mae: 9.3063e-04 - learning_rate: 3.7500e-05

Epoch 21/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3077e-04 - val_mae: 9.3077e-04 - learning_rate: 3.7500e-05

Epoch 22/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 60/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 70/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3096e-04 - val_mae: 9.3096e-04 - learning_rate: 3.7500e-05

Epoch 23/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0012 - mae: 0.0012

 10/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 29/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2691e-04 - val_mae: 9.2691e-04 - learning_rate: 1.8750e-05

Epoch 24/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 30/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 69/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 89/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2682e-04 - val_mae: 9.2682e-04 - learning_rate: 1.8750e-05

Epoch 25/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 60/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 70/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2684e-04 - val_mae: 9.2684e-04 - learning_rate: 1.8750e-05

Epoch 26/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2709e-04 - val_mae: 9.2709e-04 - learning_rate: 1.8750e-05

Epoch 27/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 10/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 29/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 39/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2699e-04 - val_mae: 9.2699e-04 - learning_rate: 1.8750e-05

Epoch 28/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2594e-04 - val_mae: 9.2594e-04 - learning_rate: 9.3750e-06

Epoch 29/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 10/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 28/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2600e-04 - val_mae: 9.2600e-04 - learning_rate: 9.3750e-06

Epoch 30/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 10/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 30/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 60/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 70/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2593e-04 - val_mae: 9.2593e-04 - learning_rate: 9.3750e-06

Epoch 31/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2595e-04 - val_mae: 9.2595e-04 - learning_rate: 9.3750e-06

Epoch 32/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2594e-04 - val_mae: 9.2594e-04 - learning_rate: 9.3750e-06

Epoch 33/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0012 - mae: 0.0012

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 30/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0013 - mae: 0.0013

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 60/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 70/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 89/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2597e-04 - val_mae: 9.2597e-04 - learning_rate: 4.6875e-06

Result: {
  "model": "CNN_GRU",
  "input_window": 10,
  "output_window": 90,
  "MAE_train": 0.0012647034770073284,
  "MAE_val": 0.0009269096262917874,
  "MAE_test": 0.0012656627045105743,
  "params": 35351,
  "epochs_trained": 33,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_BiGRU_input10_output90
X_train: (13038, 10, 23) y_train: (13038, 23)
X_val:   (1448, 10, 23) y_val:   (1448, 23)
X_test:  (1610, 10, 23) y_test:  (1610, 23)
Params: 67351
Epoch 1/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 3:35 2s/step - loss: 0.2862 - mae: 0.2862

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2626 - mae: 0.2626

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2491 - mae: 0.2491

 25/102 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2424 - mae: 0.2424

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2326 - mae: 0.2326

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2249 - mae: 0.2249

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2158 - mae: 0.2158

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2073 - mae: 0.2073

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1994 - mae: 0.1994

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1919 - mae: 0.1919

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1848 - mae: 0.1848

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1789 - mae: 0.1789

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1754 - mae: 0.1754

102/102 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.1041 - mae: 0.1041 - val_loss: 0.0078 - val_mae: 0.0078 - learning_rate: 3.0000e-04

Epoch 2/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0138 - mae: 0.0138

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0130 - mae: 0.0130

 11/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0127 - mae: 0.0127

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0124 - mae: 0.0124

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0121 - mae: 0.0121

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0117 - mae: 0.0117

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0114 - mae: 0.0114

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0111 - mae: 0.0111

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0108 - mae: 0.0108

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0105 - mae: 0.0105

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0103 - mae: 0.0103

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0100 - mae: 0.0100

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0098 - mae: 0.0098

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0096 - mae: 0.0096

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0094 - mae: 0.0094

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0092 - mae: 0.0092

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0090 - mae: 0.0090

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0089 - mae: 0.0089

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0087 - mae: 0.0087

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0085 - mae: 0.0085

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0011 - val_mae: 0.0011 - learning_rate: 3.0000e-04

Epoch 3/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0020 - mae: 0.0020

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0021 - mae: 0.0021

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0021 - mae: 0.0021

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0021 - mae: 0.0021

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0021 - mae: 0.0021

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0021 - mae: 0.0021

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0021 - mae: 0.0021

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0021 - mae: 0.0021

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020 - mae: 0.0020

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020 - mae: 0.0020

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020 - mae: 0.0020

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020 - mae: 0.0020

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020 - mae: 0.0020

 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020 - mae: 0.0020

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0020 - mae: 0.0020

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0019 - mae: 0.0019 - val_loss: 0.0010 - val_mae: 0.0010 - learning_rate: 3.0000e-04

Epoch 4/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0015 - mae: 0.0015 - val_loss: 9.9605e-04 - val_mae: 9.9605e-04 - learning_rate: 3.0000e-04

Epoch 5/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014 - mae: 0.0014

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014 - mae: 0.0014

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014 - mae: 0.0014

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014 - mae: 0.0014

 70/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014 - mae: 0.0014

 75/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014 - mae: 0.0014

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014 - mae: 0.0014

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014 - mae: 0.0014

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014 - mae: 0.0014

 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014 - mae: 0.0014

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0014 - mae: 0.0014

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0014 - mae: 0.0014 - val_loss: 9.8178e-04 - val_mae: 9.8178e-04 - learning_rate: 3.0000e-04

Epoch 6/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0014 - mae: 0.0014 - val_loss: 9.7816e-04 - val_mae: 9.7816e-04 - learning_rate: 3.0000e-04

Epoch 7/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.6945e-04 - val_mae: 9.6945e-04 - learning_rate: 3.0000e-04

Epoch 8/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.6406e-04 - val_mae: 9.6406e-04 - learning_rate: 3.0000e-04

Epoch 9/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.6065e-04 - val_mae: 9.6065e-04 - learning_rate: 3.0000e-04

Epoch 10/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 63/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.6277e-04 - val_mae: 9.6277e-04 - learning_rate: 1.5000e-04

Epoch 11/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 75/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 89/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.6141e-04 - val_mae: 9.6141e-04 - learning_rate: 1.5000e-04

Epoch 12/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.5921e-04 - val_mae: 9.5921e-04 - learning_rate: 1.5000e-04

Epoch 13/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.5478e-04 - val_mae: 9.5478e-04 - learning_rate: 1.5000e-04

Epoch 14/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.5411e-04 - val_mae: 9.5411e-04 - learning_rate: 1.5000e-04

Epoch 15/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.5029e-04 - val_mae: 9.5029e-04 - learning_rate: 7.5000e-05

Epoch 16/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4977e-04 - val_mae: 9.4977e-04 - learning_rate: 7.5000e-05

Epoch 17/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 63/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4969e-04 - val_mae: 9.4969e-04 - learning_rate: 7.5000e-05

Epoch 18/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 30/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 34/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 39/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 44/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 54/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 64/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 69/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 89/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4911e-04 - val_mae: 9.4911e-04 - learning_rate: 7.5000e-05

Epoch 19/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4817e-04 - val_mae: 9.4817e-04 - learning_rate: 7.5000e-05

Epoch 20/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4240e-04 - val_mae: 9.4240e-04 - learning_rate: 3.7500e-05

Epoch 21/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4223e-04 - val_mae: 9.4223e-04 - learning_rate: 3.7500e-05

Epoch 22/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4173e-04 - val_mae: 9.4173e-04 - learning_rate: 3.7500e-05

Epoch 23/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4124e-04 - val_mae: 9.4124e-04 - learning_rate: 3.7500e-05

Epoch 24/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4111e-04 - val_mae: 9.4111e-04 - learning_rate: 3.7500e-05

Epoch 25/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3702e-04 - val_mae: 9.3702e-04 - learning_rate: 1.8750e-05

Epoch 26/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3632e-04 - val_mae: 9.3632e-04 - learning_rate: 1.8750e-05

Epoch 27/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3630e-04 - val_mae: 9.3630e-04 - learning_rate: 1.8750e-05

Epoch 28/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3651e-04 - val_mae: 9.3651e-04 - learning_rate: 1.8750e-05

Epoch 29/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3664e-04 - val_mae: 9.3664e-04 - learning_rate: 1.8750e-05

Epoch 30/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3537e-04 - val_mae: 9.3537e-04 - learning_rate: 9.3750e-06

Epoch 31/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3515e-04 - val_mae: 9.3515e-04 - learning_rate: 9.3750e-06

Epoch 32/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3516e-04 - val_mae: 9.3516e-04 - learning_rate: 9.3750e-06

Epoch 33/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3515e-04 - val_mae: 9.3515e-04 - learning_rate: 9.3750e-06

Epoch 34/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3514e-04 - val_mae: 9.3514e-04 - learning_rate: 9.3750e-06

Epoch 35/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3514e-04 - val_mae: 9.3514e-04 - learning_rate: 4.6875e-06

Epoch 36/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3514e-04 - val_mae: 9.3514e-04 - learning_rate: 4.6875e-06

Epoch 37/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3502e-04 - val_mae: 9.3502e-04 - learning_rate: 4.6875e-06

Epoch 38/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3502e-04 - val_mae: 9.3502e-04 - learning_rate: 4.6875e-06

Epoch 39/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3498e-04 - val_mae: 9.3498e-04 - learning_rate: 4.6875e-06

Epoch 40/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0012 - mae: 0.0012

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3504e-04 - val_mae: 9.3504e-04 - learning_rate: 2.3438e-06

Result: {
  "model": "CNN_BiGRU",
  "input_window": 10,
  "output_window": 90,
  "MAE_train": 0.0012646404469018391,
  "MAE_val": 0.0009353746982950887,
  "MAE_test": 0.0012971797958824807,
  "params": 67351,
  "epochs_trained": 40,
  "filters": 64,
  "kernel_size": 5,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.2,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_LSTM_input30_output1
X_train: (13094, 30, 23) y_train: (13094, 23)
X_val:   (1454, 30, 23) y_val:   (1454, 23)
X_test:  (1617, 30, 23) y_test:  (1617, 23)
Params: 43415
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:15 1s/step - loss: 0.1288 - mae: 0.1288

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.1255 - mae: 0.1255

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.1230 - mae: 0.1230

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.1205 - mae: 0.1205

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.1181 - mae: 0.1181

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.1160 - mae: 0.1160

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.1139 - mae: 0.1139

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.1120 - mae: 0.1120

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.1101 - mae: 0.1101

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1083 - mae: 0.1083

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1066 - mae: 0.1066

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1050 - mae: 0.1050

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1035 - mae: 0.1035

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1020 - mae: 0.1020

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1006 - mae: 0.1006

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0992 - mae: 0.0992

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0979 - mae: 0.0979

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0967 - mae: 0.0967

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0954 - mae: 0.0954

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0942 - mae: 0.0942

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0931 - mae: 0.0931

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0919 - mae: 0.0919

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0908 - mae: 0.0908

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0897 - mae: 0.0897

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0886 - mae: 0.0886

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0876 - mae: 0.0876

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.0611 - mae: 0.0611 - val_loss: 0.0132 - val_mae: 0.0132 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0202 - mae: 0.0202

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0202 - mae: 0.0202

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0198 - mae: 0.0198

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0194 - mae: 0.0194

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0191 - mae: 0.0191

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0188 - mae: 0.0188

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0185 - mae: 0.0185

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0182 - mae: 0.0182

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0179 - mae: 0.0179

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0177 - mae: 0.0177

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0175 - mae: 0.0175

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0173 - mae: 0.0173

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0171 - mae: 0.0171

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0169 - mae: 0.0169

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0168 - mae: 0.0168

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0166 - mae: 0.0166

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0165 - mae: 0.0165

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0163 - mae: 0.0163

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0162 - mae: 0.0162

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0161 - mae: 0.0161

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0160 - mae: 0.0160

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0159 - mae: 0.0159

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0158 - mae: 0.0158

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0157 - mae: 0.0157

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0156 - mae: 0.0156

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0155 - mae: 0.0155

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0135 - mae: 0.0135 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0123 - mae: 0.0123

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0121 - mae: 0.0121

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0121 - mae: 0.0121

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0121 - mae: 0.0121

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0123 - mae: 0.0123

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0121 - mae: 0.0121

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0120 - mae: 0.0120

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0123 - mae: 0.0123

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 16/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 17/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Result: {
  "model": "CNN_LSTM",
  "input_window": 30,
  "output_window": 1,
  "MAE_train": 0.011835777091607559,
  "MAE_val": 0.009027903009538922,
  "MAE_test": 0.012286345620947277,
  "params": 43415,
  "epochs_trained": 17,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_GRU_input30_output1
X_train: (13094, 30, 23) y_train: (13094, 23)
X_val:   (1454, 30, 23) y_val:   (1454, 23)
X_test:  (1617, 30, 23) y_test:  (1617, 23)
Params: 35351
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:31 1s/step - loss: 0.2322 - mae: 0.2322

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.2274 - mae: 0.2274

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2232 - mae: 0.2232

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2192 - mae: 0.2192

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2155 - mae: 0.2155

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2123 - mae: 0.2123

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2092 - mae: 0.2092

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2063 - mae: 0.2063

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.2042 - mae: 0.2042

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.2014 - mae: 0.2014

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1987 - mae: 0.1987

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1961 - mae: 0.1961

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1936 - mae: 0.1936

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1912 - mae: 0.1912

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1889 - mae: 0.1889

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1868 - mae: 0.1868

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1846 - mae: 0.1846

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1825 - mae: 0.1825

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1805 - mae: 0.1805

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1786 - mae: 0.1786

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1771 - mae: 0.1771

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1752 - mae: 0.1752

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1734 - mae: 0.1734

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1716 - mae: 0.1716

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1698 - mae: 0.1698

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1681 - mae: 0.1681

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.1238 - mae: 0.1238 - val_loss: 0.0258 - val_mae: 0.0258 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0559 - mae: 0.0559

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0537 - mae: 0.0537

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0523 - mae: 0.0523

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0510 - mae: 0.0510

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0497 - mae: 0.0497

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0488 - mae: 0.0488

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0477 - mae: 0.0477

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0465 - mae: 0.0465

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0454 - mae: 0.0454

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0443 - mae: 0.0443

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0433 - mae: 0.0433

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0423 - mae: 0.0423

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0413 - mae: 0.0413

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0404 - mae: 0.0404

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0395 - mae: 0.0395

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0387 - mae: 0.0387

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0379 - mae: 0.0379

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0372 - mae: 0.0372

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0365 - mae: 0.0365

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0358 - mae: 0.0358

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0352 - mae: 0.0352

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0346 - mae: 0.0346

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0341 - mae: 0.0341

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0335 - mae: 0.0335

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0330 - mae: 0.0330

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0326 - mae: 0.0326

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0208 - mae: 0.0208 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0125 - mae: 0.0125

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0123 - mae: 0.0123

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0122 - mae: 0.0122

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0122 - mae: 0.0122

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0122 - mae: 0.0122

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0121 - mae: 0.0121

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0121 - mae: 0.0121

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0121 - mae: 0.0121

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0121 - mae: 0.0121

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0121 - mae: 0.0121

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0121 - mae: 0.0121

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0120 - mae: 0.0120 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0121 - mae: 0.0121

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0121 - mae: 0.0121

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0120 - mae: 0.0120

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0120 - mae: 0.0120

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0120 - mae: 0.0120

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0120 - mae: 0.0120

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Result: {
  "model": "CNN_GRU",
  "input_window": 30,
  "output_window": 1,
  "MAE_train": 0.011887075655868383,
  "MAE_val": 0.009027155177978531,
  "MAE_test": 0.01232610185655333,
  "params": 35351,
  "epochs_trained": 12,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_BiGRU_input30_output1
X_train: (13094, 30, 23) y_train: (13094, 23)
X_val:   (1454, 30, 23) y_val:   (1454, 23)
X_test:  (1617, 30, 23) y_test:  (1617, 23)
Params: 67351
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3:39 2s/step - loss: 0.2805 - mae: 0.2805

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.2686 - mae: 0.2686

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.2605 - mae: 0.2605

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.2550 - mae: 0.2550

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.2501 - mae: 0.2501

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.2441 - mae: 0.2441

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.2386 - mae: 0.2386

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.2333 - mae: 0.2333

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.2284 - mae: 0.2284

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.2236 - mae: 0.2236

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.2191 - mae: 0.2191

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2159 - mae: 0.2159

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2127 - mae: 0.2127

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2086 - mae: 0.2086

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2047 - mae: 0.2047

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2009 - mae: 0.2009

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1973 - mae: 0.1973

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1946 - mae: 0.1946

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1911 - mae: 0.1911

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1877 - mae: 0.1877

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1844 - mae: 0.1844

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1812 - mae: 0.1812

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1782 - mae: 0.1782

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1752 - mae: 0.1752

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1730 - mae: 0.1730

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1716 - mae: 0.1716

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1702 - mae: 0.1702

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1688 - mae: 0.1688

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1675 - mae: 0.1675

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1662 - mae: 0.1662

103/103 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - loss: 0.0991 - mae: 0.0991 - val_loss: 0.0154 - val_mae: 0.0154 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0247 - mae: 0.0247

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0233 - mae: 0.0233

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0225 - mae: 0.0225

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0221 - mae: 0.0221

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0219 - mae: 0.0219

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0217 - mae: 0.0217

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0215 - mae: 0.0215

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0214 - mae: 0.0214

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0212 - mae: 0.0212

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0211 - mae: 0.0211

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0210 - mae: 0.0210

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0209 - mae: 0.0209

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0208 - mae: 0.0208

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0207 - mae: 0.0207

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0206 - mae: 0.0206

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0205 - mae: 0.0205

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0204 - mae: 0.0204

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0203 - mae: 0.0203

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0203 - mae: 0.0203

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0202 - mae: 0.0202

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0201 - mae: 0.0201

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0200 - mae: 0.0200

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0200 - mae: 0.0200

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0199 - mae: 0.0199

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0198 - mae: 0.0198

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0197 - mae: 0.0197

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0197 - mae: 0.0197

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0196 - mae: 0.0196

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0195 - mae: 0.0195

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0194 - mae: 0.0194

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0194 - mae: 0.0194

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0193 - mae: 0.0193

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0192 - mae: 0.0192

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0191 - mae: 0.0191

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0191 - mae: 0.0191

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0190 - mae: 0.0190

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0190 - mae: 0.0190

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0189 - mae: 0.0189

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0188 - mae: 0.0188

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0188 - mae: 0.0188

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0187 - mae: 0.0187

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0187 - mae: 0.0187

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0186 - mae: 0.0186

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0186 - mae: 0.0186

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0185 - mae: 0.0185

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0185 - mae: 0.0185

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0184 - mae: 0.0184

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0184 - mae: 0.0184

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0183 - mae: 0.0183

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0183 - mae: 0.0183

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0182 - mae: 0.0182

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0158 - mae: 0.0158 - val_loss: 0.0092 - val_mae: 0.0092 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0133 - mae: 0.0133

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0133 - mae: 0.0133

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0132 - mae: 0.0132

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0132 - mae: 0.0132

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0131 - mae: 0.0131

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0131 - mae: 0.0131

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0132 - mae: 0.0132

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0132 - mae: 0.0132

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0132 - mae: 0.0132

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0131 - mae: 0.0131

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0132 - mae: 0.0132

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0132 - mae: 0.0132

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0132 - mae: 0.0132

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0132 - mae: 0.0132

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0132 - mae: 0.0132

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0132 - mae: 0.0132

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0132 - mae: 0.0132

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0132 - mae: 0.0132

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0132 - mae: 0.0132

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0132 - mae: 0.0132

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0132 - mae: 0.0132

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0132 - mae: 0.0132

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0132 - mae: 0.0132

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0132 - mae: 0.0132

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0132 - mae: 0.0132

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0132 - mae: 0.0132

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0131 - mae: 0.0131

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0131 - mae: 0.0131

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0131 - mae: 0.0131

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0131 - mae: 0.0131

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0131 - mae: 0.0131

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0131 - mae: 0.0131

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0131 - mae: 0.0131

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0131 - mae: 0.0131

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0131 - mae: 0.0131

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0131 - mae: 0.0131

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0131 - mae: 0.0131

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0131 - mae: 0.0131

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0130 - mae: 0.0130

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0130 - mae: 0.0130

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0130 - mae: 0.0130

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0130 - mae: 0.0130

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0130 - mae: 0.0130

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0130 - mae: 0.0130

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0130 - mae: 0.0130

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0130 - mae: 0.0130

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0130 - mae: 0.0130

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0130 - mae: 0.0130

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0130 - mae: 0.0130

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0130 - mae: 0.0130

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0130 - mae: 0.0130

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0127 - mae: 0.0127 - val_loss: 0.0091 - val_mae: 0.0091 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0128 - mae: 0.0128

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0126 - mae: 0.0126

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0125 - mae: 0.0125

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0124 - mae: 0.0124

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0123 - mae: 0.0123

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0123 - mae: 0.0123

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0123 - mae: 0.0123

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0123 - mae: 0.0123

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0123 - mae: 0.0123

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0122 - mae: 0.0122

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0123 - mae: 0.0123

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0123 - mae: 0.0123

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0123 - mae: 0.0123

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0123 - mae: 0.0123

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0123 - mae: 0.0123

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0123 - mae: 0.0123

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0123 - mae: 0.0123

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0123 - mae: 0.0123

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0123 - mae: 0.0123

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0121 - mae: 0.0121 - val_loss: 0.0091 - val_mae: 0.0091 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0126 - mae: 0.0126

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0125 - mae: 0.0125

  5/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0123 - mae: 0.0123

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0122 - mae: 0.0122

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0122 - mae: 0.0122

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0121 - mae: 0.0121

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0121 - mae: 0.0121

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0121 - mae: 0.0121

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0121 - mae: 0.0121

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0121 - mae: 0.0121

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0121 - mae: 0.0121

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0121 - mae: 0.0121

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0121 - mae: 0.0121

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0121 - mae: 0.0121

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0121 - mae: 0.0121

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0121 - mae: 0.0121

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0121 - mae: 0.0121

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0121 - mae: 0.0121

 37/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0121 - mae: 0.0121

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0121 - mae: 0.0121

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0120 - mae: 0.0120 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0123 - mae: 0.0123

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0122 - mae: 0.0122

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0121 - mae: 0.0121

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0120 - mae: 0.0120

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0124 - mae: 0.0124

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0123 - mae: 0.0123

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0121 - mae: 0.0121

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0121 - mae: 0.0121

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0120 - mae: 0.0120

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0120 - mae: 0.0120

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0120 - mae: 0.0120

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0120 - mae: 0.0120

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0120 - mae: 0.0120

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0120 - mae: 0.0120

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0120 - mae: 0.0120

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 16/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 17/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 18/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 19/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.7500e-05

Epoch 20/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.7500e-05

Epoch 21/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.7500e-05

Epoch 22/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0122 - mae: 0.0122

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0121 - mae: 0.0121

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0119 - mae: 0.0119

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0119 - mae: 0.0119

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0119 - mae: 0.0119

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0119 - mae: 0.0119

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0119 - mae: 0.0119

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0119 - mae: 0.0119

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0119 - mae: 0.0119

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.7500e-05

Result: {
  "model": "CNN_BiGRU",
  "input_window": 30,
  "output_window": 1,
  "MAE_train": 0.01183115321017198,
  "MAE_val": 0.009030646602638243,
  "MAE_test": 0.012307256865644224,
  "params": 67351,
  "epochs_trained": 22,
  "filters": 64,
  "kernel_size": 5,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.2,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_LSTM_input30_output5
X_train: (13090, 30, 23) y_train: (13090, 23)
X_val:   (1454, 30, 23) y_val:   (1454, 23)
X_test:  (1617, 30, 23) y_test:  (1617, 23)
Params: 43415
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:15 1s/step - loss: 0.1250 - mae: 0.1250

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.1231 - mae: 0.1231

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.1214 - mae: 0.1214

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.1194 - mae: 0.1194

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.1172 - mae: 0.1172

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.1150 - mae: 0.1150

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.1129 - mae: 0.1129

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.1109 - mae: 0.1109

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.1091 - mae: 0.1091

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1073 - mae: 0.1073

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1056 - mae: 0.1056

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1040 - mae: 0.1040

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1025 - mae: 0.1025

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1010 - mae: 0.1010

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0996 - mae: 0.0996

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0982 - mae: 0.0982

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0969 - mae: 0.0969

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0956 - mae: 0.0956

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0944 - mae: 0.0944

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0931 - mae: 0.0931

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0920 - mae: 0.0920

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0908 - mae: 0.0908

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0897 - mae: 0.0897

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0885 - mae: 0.0885

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0875 - mae: 0.0875

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0864 - mae: 0.0864

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0591 - mae: 0.0591 - val_loss: 0.0092 - val_mae: 0.0092 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0153 - mae: 0.0153

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0147 - mae: 0.0147

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0145 - mae: 0.0145

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0142 - mae: 0.0142

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0139 - mae: 0.0139

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0135 - mae: 0.0135

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0132 - mae: 0.0132

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0128 - mae: 0.0128

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0125 - mae: 0.0125

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0122 - mae: 0.0122

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0120 - mae: 0.0120

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0117 - mae: 0.0117

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0115 - mae: 0.0115

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0113 - mae: 0.0113

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0111 - mae: 0.0111

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0109 - mae: 0.0109

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0108 - mae: 0.0108

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0107 - mae: 0.0107

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0105 - mae: 0.0105

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0104 - mae: 0.0104

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0102 - mae: 0.0102

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0101 - mae: 0.0101

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0100 - mae: 0.0100

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0099 - mae: 0.0099

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0098 - mae: 0.0098

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0097 - mae: 0.0097

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0096 - mae: 0.0096

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0073 - mae: 0.0073 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 16/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 17/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 18/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 19/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 20/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 21/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 22/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0053 - mae: 0.0053

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 23/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Result: {
  "model": "CNN_LSTM",
  "input_window": 30,
  "output_window": 5,
  "MAE_train": 0.005473467484852588,
  "MAE_val": 0.004141498578367115,
  "MAE_test": 0.0055978946986712545,
  "params": 43415,
  "epochs_trained": 23,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_GRU_input30_output5
X_train: (13090, 30, 23) y_train: (13090, 23)
X_val:   (1454, 30, 23) y_val:   (1454, 23)
X_test:  (1617, 30, 23) y_test:  (1617, 23)
Params: 35351
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:26 1s/step - loss: 0.2259 - mae: 0.2259

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.2229 - mae: 0.2229

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2200 - mae: 0.2200

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2173 - mae: 0.2173

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2141 - mae: 0.2141

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2108 - mae: 0.2108

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2077 - mae: 0.2077

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.2047 - mae: 0.2047

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.2019 - mae: 0.2019

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1993 - mae: 0.1993

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1967 - mae: 0.1967

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1942 - mae: 0.1942

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1919 - mae: 0.1919

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1896 - mae: 0.1896

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1874 - mae: 0.1874

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1852 - mae: 0.1852

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1831 - mae: 0.1831

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1811 - mae: 0.1811

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1791 - mae: 0.1791

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1772 - mae: 0.1772

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1753 - mae: 0.1753

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1734 - mae: 0.1734

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1716 - mae: 0.1716

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1698 - mae: 0.1698

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1681 - mae: 0.1681

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1664 - mae: 0.1664

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - loss: 0.1231 - mae: 0.1231 - val_loss: 0.0239 - val_mae: 0.0239 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0509 - mae: 0.0509

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0490 - mae: 0.0490

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0485 - mae: 0.0485

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0478 - mae: 0.0478

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0469 - mae: 0.0469

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0457 - mae: 0.0457

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0445 - mae: 0.0445

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0433 - mae: 0.0433

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0422 - mae: 0.0422

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0411 - mae: 0.0411

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0400 - mae: 0.0400

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0389 - mae: 0.0389

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0379 - mae: 0.0379

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0369 - mae: 0.0369

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0360 - mae: 0.0360

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0351 - mae: 0.0351

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0343 - mae: 0.0343

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0335 - mae: 0.0335

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0327 - mae: 0.0327

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0320 - mae: 0.0320

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0313 - mae: 0.0313

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0307 - mae: 0.0307

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0301 - mae: 0.0301

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0295 - mae: 0.0295

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0290 - mae: 0.0290

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0284 - mae: 0.0284

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0155 - mae: 0.0155 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0057 - mae: 0.0057

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 16/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 17/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 18/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 19/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 20/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 21/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0053 - mae: 0.0053

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0053 - mae: 0.0053

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 22/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 23/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0052 - mae: 0.0052

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Result: {
  "model": "CNN_GRU",
  "input_window": 30,
  "output_window": 5,
  "MAE_train": 0.00547366894507027,
  "MAE_val": 0.004141185470722008,
  "MAE_test": 0.005597538451621016,
  "params": 35351,
  "epochs_trained": 23,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_BiGRU_input30_output5
X_train: (13090, 30, 23) y_train: (13090, 23)
X_val:   (1454, 30, 23) y_val:   (1454, 23)
X_test:  (1617, 30, 23) y_test:  (1617, 23)
Params: 67351
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3:38 2s/step - loss: 0.2687 - mae: 0.2687

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.2624 - mae: 0.2624

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.2563 - mae: 0.2563

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2520 - mae: 0.2520

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2477 - mae: 0.2477

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2434 - mae: 0.2434

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2379 - mae: 0.2379

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.2325 - mae: 0.2325

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.2274 - mae: 0.2274

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.2227 - mae: 0.2227

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.2181 - mae: 0.2181

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2137 - mae: 0.2137

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2095 - mae: 0.2095

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2054 - mae: 0.2054

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.2015 - mae: 0.2015

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1977 - mae: 0.1977

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1950 - mae: 0.1950

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1923 - mae: 0.1923

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1888 - mae: 0.1888

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1854 - mae: 0.1854

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1821 - mae: 0.1821

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1789 - mae: 0.1789

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1758 - mae: 0.1758

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1728 - mae: 0.1728

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1706 - mae: 0.1706

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.1691 - mae: 0.1691

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1677 - mae: 0.1677

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1664 - mae: 0.1664

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.1650 - mae: 0.1650

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1637 - mae: 0.1637

103/103 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - loss: 0.0960 - mae: 0.0960 - val_loss: 0.0111 - val_mae: 0.0111 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0148 - mae: 0.0148

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0145 - mae: 0.0145

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0143 - mae: 0.0143

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0141 - mae: 0.0141

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0141 - mae: 0.0141

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0140 - mae: 0.0140

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0141 - mae: 0.0141

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0141 - mae: 0.0141

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0140 - mae: 0.0140

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0140 - mae: 0.0140

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0139 - mae: 0.0139

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0138 - mae: 0.0138

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0138 - mae: 0.0138

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0137 - mae: 0.0137

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0136 - mae: 0.0136

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0136 - mae: 0.0136

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0135 - mae: 0.0135

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0135 - mae: 0.0135

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0134 - mae: 0.0134

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0134 - mae: 0.0134

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0133 - mae: 0.0133

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0132 - mae: 0.0132

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0132 - mae: 0.0132

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0131 - mae: 0.0131

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0131 - mae: 0.0131

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0130 - mae: 0.0130

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0129 - mae: 0.0129

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0129 - mae: 0.0129

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0128 - mae: 0.0128

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0128 - mae: 0.0128

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0127 - mae: 0.0127

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0126 - mae: 0.0126

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0126 - mae: 0.0126

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0125 - mae: 0.0125

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0125 - mae: 0.0125

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0124 - mae: 0.0124

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0124 - mae: 0.0124

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0123 - mae: 0.0123

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0122 - mae: 0.0122

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0122 - mae: 0.0122

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0121 - mae: 0.0121

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0120 - mae: 0.0120

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0118 - mae: 0.0118

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0118 - mae: 0.0118

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0117 - mae: 0.0117

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0096 - mae: 0.0096 - val_loss: 0.0043 - val_mae: 0.0043 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0070 - mae: 0.0070

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0069 - mae: 0.0069

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0068 - mae: 0.0068

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0068 - mae: 0.0068

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0067 - mae: 0.0067

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0067 - mae: 0.0067

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0067 - mae: 0.0067

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0067 - mae: 0.0067

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0067 - mae: 0.0067

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0067 - mae: 0.0067

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0067 - mae: 0.0067

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0067 - mae: 0.0067

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0067 - mae: 0.0067

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0067 - mae: 0.0067

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0066 - mae: 0.0066

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0066 - mae: 0.0066

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0066 - mae: 0.0066

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0066 - mae: 0.0066

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0066 - mae: 0.0066

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0066 - mae: 0.0066

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0066 - mae: 0.0066

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0066 - mae: 0.0066

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0066 - mae: 0.0066

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0066 - mae: 0.0066

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0066 - mae: 0.0066

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0066 - mae: 0.0066

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0066 - mae: 0.0066

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0066 - mae: 0.0066

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0066 - mae: 0.0066

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0066 - mae: 0.0066

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0066 - mae: 0.0066

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0066 - mae: 0.0066

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0066 - mae: 0.0066

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0066 - mae: 0.0066

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0066 - mae: 0.0066

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0066 - mae: 0.0066

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0066 - mae: 0.0066

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0065 - mae: 0.0065

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0065 - mae: 0.0065

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0065 - mae: 0.0065

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0065 - mae: 0.0065

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0065 - mae: 0.0065

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0065 - mae: 0.0065

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0065 - mae: 0.0065

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0065 - mae: 0.0065

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0065 - mae: 0.0065

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0065 - mae: 0.0065

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0065 - mae: 0.0065

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0065 - mae: 0.0065

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0065 - mae: 0.0065

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0065 - mae: 0.0065

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0063 - mae: 0.0063 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - loss: 0.0054 - mae: 0.0054

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0056 - mae: 0.0056

  7/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0056 - mae: 0.0056

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0057 - mae: 0.0057

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0057 - mae: 0.0057

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0057 - mae: 0.0057

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0057 - mae: 0.0057

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0057 - mae: 0.0057

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0057 - mae: 0.0057

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0057 - mae: 0.0057

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0058 - mae: 0.0058

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0058 - mae: 0.0058

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0058 - mae: 0.0058

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0058 - mae: 0.0058

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0058 - mae: 0.0058

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0058 - mae: 0.0058

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0058 - mae: 0.0058

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0058 - mae: 0.0058

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0058 - mae: 0.0058

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0059 - mae: 0.0059

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0057 - mae: 0.0057

  5/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0056 - mae: 0.0056

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0056 - mae: 0.0056

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056

 37/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0056 - mae: 0.0056

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0055 - mae: 0.0055

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0055 - mae: 0.0055

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - loss: 0.0053 - mae: 0.0053

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.0000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0052 - mae: 0.0052

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0052 - mae: 0.0052

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0053 - mae: 0.0053

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0056 - mae: 0.0056

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0055 - mae: 0.0055

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0052 - mae: 0.0052

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.5000e-04

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0052 - mae: 0.0052

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0052 - mae: 0.0052

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 16/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0052 - mae: 0.0052

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 17/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0052 - mae: 0.0052

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 18/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0052 - mae: 0.0052

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 7.5000e-05

Epoch 19/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0052 - mae: 0.0052

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 20/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0052 - mae: 0.0052

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 31ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 21/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0052 - mae: 0.0052

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 22/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0052 - mae: 0.0052

  3/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 23/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0052 - mae: 0.0052

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0054 - mae: 0.0054

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 3.7500e-05

Epoch 24/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0057 - mae: 0.0057

  3/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0056 - mae: 0.0056

  5/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0055 - mae: 0.0055

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0055 - mae: 0.0055

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 23/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 27/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 29/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

 33/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 35/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.0054 - mae: 0.0054

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0041 - val_mae: 0.0041 - learning_rate: 1.8750e-05

Result: {
  "model": "CNN_BiGRU",
  "input_window": 30,
  "output_window": 5,
  "MAE_train": 0.005473948253192874,
  "MAE_val": 0.004141261894705137,
  "MAE_test": 0.005613878806800622,
  "params": 67351,
  "epochs_trained": 24,
  "filters": 64,
  "kernel_size": 5,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.2,
  "learning_rate": 0.0003,
  "batch_size": 128
}
All results saved to: /Users/jchulvi/projects/Neural-Networks-Forecasting/data/mixtos/cnn_rnn_hybrid/hybrid_all_results.csv
Best by window saved to: /Users/jchulvi/projects/Neural-Networks-Forecasting/data/mixtos/cnn_rnn_hybrid/hybrid_best_by_window.csv

        model  input_window  output_window  MAE_train    MAE_val   MAE_test  params  epochs_trained
0     CNN_GRU            10             30 0.00220167 0.00170284 0.00231909   35351              38
1    CNN_LSTM            10             30 0.00221432 0.00170913 0.00234814   43415              14
2   CNN_BiGRU            10             30 0.00220163 0.00171462 0.00233340   67351              44
3     CNN_GRU            10             90 0.00126470 0.00092691 0.00126566   35351              33
4    CNN_LSTM            10             90 0.00128143 0.00093302 0.00131178   43415              13
5   CNN_BiGRU            10             90 0.00126464 0.00093537 0.00129718   67351              40
6     CNN_GRU            30              1 0.01188708 0.00902716 0.01232610   35351              12
7    CNN_LSTM            30              1 0.01183578 0.00902790 0.01228635   43415              17
8   CNN_BiGRU            30              1 0.01183115 0.00903065 0.01230726   67351              22
9     CNN_GRU            30              5 0.00547367 0.00414119 0.00559754   35351              23
10  CNN_BiGRU            30              5 0.00547395 0.00414126 0.00561388   67351              24
11   CNN_LSTM            30              5 0.00547347 0.00414150 0.00559789   43415              23

     model  input_window  output_window  MAE_train    MAE_val   MAE_test  params  epochs_trained
0  CNN_GRU            10             30 0.00220167 0.00170284 0.00231909   35351              38
1  CNN_GRU            10             90 0.00126470 0.00092691 0.00126566   35351              33
2  CNN_GRU            30              1 0.01188708 0.00902716 0.01232610   35351              12
3  CNN_GRU            30              5 0.00547367 0.00414119 0.00559754   35351              23

## Comparison against linear regression benchmark

The repository already contains `data/lr_benchmark.csv`. The table below compares the selected best hybrid model for each assigned window against that benchmark.

A negative `delta_vs_lr` means that the hybrid model improves the linear regression benchmark.

In [7]:
lr_path = PROJECT_ROOT / "data" / "lr_benchmark.csv"

if lr_path.exists():
    lr = pd.read_csv(lr_path).rename(columns={
        "MAE_train": "LR_MAE_train",
        "MAE_test": "LR_MAE_test",
    })

    comparison = best_by_window.merge(
        lr[["input_window", "output_window", "LR_MAE_train", "LR_MAE_test"]],
        on=["input_window", "output_window"],
        how="left",
    )

    comparison["delta_vs_lr"] = comparison["MAE_test"] - comparison["LR_MAE_test"]
    comparison["pct_delta_vs_lr"] = 100 * comparison["delta_vs_lr"] / comparison["LR_MAE_test"]

    comparison_path = DATA_OUT / "hybrid_comparison_vs_lr.csv"
    comparison.to_csv(comparison_path, index=False)

    display(comparison[[
        "input_window", "output_window", "model", "MAE_test", "LR_MAE_test", "delta_vs_lr", "pct_delta_vs_lr", "params"
    ]])

    print("Comparison saved to:", comparison_path)
else:
    print("No lr_benchmark.csv found. Benchmark comparison skipped.")

   input_window  output_window    model   MAE_test  LR_MAE_test  delta_vs_lr  pct_delta_vs_lr  params
0            10             30  CNN_GRU 0.00231909   0.00235841  -0.00003932      -1.66720302   35351
1            10             90  CNN_GRU 0.00126566   0.00128239  -0.00001673      -1.30429316   35351
2            30              1  CNN_GRU 0.01232610   0.01292421  -0.00059811      -4.62780492   35351
3            30              5  CNN_GRU 0.00559754   0.00587674  -0.00027921      -4.75103472   35351

Comparison saved to: /Users/jchulvi/projects/Neural-Networks-Forecasting/data/mixtos/cnn_rnn_hybrid/hybrid_comparison_vs_lr.csv

## Test MAE matrix

This matrix is directly usable in the report to summarize the best hybrid model by window.

In [8]:
matrix = best_by_window.pivot(index="input_window", columns="output_window", values="MAE_test")
matrix_path = DATA_OUT / "hybrid_test_mae_matrix.csv"
matrix.to_csv(matrix_path)

display(matrix)
print("Matrix saved to:", matrix_path)

output_window         1          5          30         90
input_window
10                   NaN        NaN 0.00231909 0.00126566
30            0.01232610 0.00559754        NaN        NaN

Matrix saved to: /Users/jchulvi/projects/Neural-Networks-Forecasting/data/mixtos/cnn_rnn_hybrid/hybrid_test_mae_matrix.csv