# CNN hyperparameter search

This notebook performs a lightweight random search for the CNN model.

The selection rule is:

```text
choose the configuration with the lowest validation MAE
```

The test set is not used during hyperparameter selection. It is evaluated only once at the end using the best validation configuration.

In [1]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

from pathlib import Path
import sys
import json
import random

import numpy as np
import pandas as pd

from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler

import keras
from keras import backend as K
from keras.layers import (
    Input,
    Conv1D,
    BatchNormalization,
    SpatialDropout1D,
    GlobalAveragePooling1D,
    GlobalMaxPooling1D,
    Concatenate,
    Dense,
    Dropout,
)
from keras.models import Model
from keras.callbacks import EarlyStopping, ReduceLROnPlateau

def find_project_root(start=None):
    start = Path.cwd() if start is None else Path(start)
    for candidate in [start, *start.parents]:
        if (candidate / "util.py").exists() and (candidate / "data").exists():
            return candidate
    raise FileNotFoundError("Could not find project root containing util.py and data/")

PROJECT_ROOT = find_project_root()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from util import get_train_test, RANDOM_SEED

OUTPUT_DIR = PROJECT_ROOT / "model" / "CNN" / "outputs" / "cnn_hyperparameter_search_30_5"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

np.random.seed(RANDOM_SEED)
random.seed(RANDOM_SEED)
keras.utils.set_random_seed(RANDOM_SEED)

print("Project root:", PROJECT_ROOT)
print("Output dir:", OUTPUT_DIR)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1777829819.131211 1765399 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1777829819.131512 1765399 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1777829819.923866 1765399 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1777829819.924071 1765399 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

Project root: /home/hugo/Desktop/Neural-Networks-Forecasting
Output dir: /home/hugo/Desktop/Neural-Networks-Forecasting/model/CNN/outputs/cnn_hyperparameter_search_30_5

## Search configuration

The default search is centered on the validated `30 → 5` setup. Increase `N_TRIALS` for a more complete search or reduce it temporarily for a quick smoke test.

In [2]:
INPUT_WINDOW = 30
OUTPUT_WINDOW = 5
VALIDATION_RATIO = 0.10

N_TRIALS = 15
EPOCHS = 100

## Data preparation

As in the CNN Deep notebook, the scaler is fitted only on the training split and then applied to validation and test.

In [3]:
def split_train_val(X_train, y_train, val_ratio=0.10):
    val_size = int(len(X_train) * val_ratio)
    if val_size <= 0:
        raise ValueError("Validation split is empty. Increase training size or val_ratio.")

    X_val = X_train[-val_size:]
    y_val = y_train[-val_size:]
    X_train_final = X_train[:-val_size]
    y_train_final = y_train[:-val_size]
    return X_train_final, y_train_final, X_val, y_val


def scale_X_only(X_train, X_val, X_test):
    n_train, window, n_assets = X_train.shape
    n_val = X_val.shape[0]
    n_test = X_test.shape[0]

    scaler = StandardScaler()
    X_train_2d = X_train.reshape(n_train, -1)
    X_val_2d = X_val.reshape(n_val, -1)
    X_test_2d = X_test.reshape(n_test, -1)

    X_train_scaled = scaler.fit_transform(X_train_2d).reshape(n_train, window, n_assets)
    X_val_scaled = scaler.transform(X_val_2d).reshape(n_val, window, n_assets)
    X_test_scaled = scaler.transform(X_test_2d).reshape(n_test, window, n_assets)
    return X_train_scaled, X_val_scaled, X_test_scaled


d = get_train_test(INPUT_WINDOW, OUTPUT_WINDOW)

X_train_raw, y_train_raw = d.X_train, d.y_train
X_test_raw, y_test = d.X_test, d.y_test

X_train_raw, y_train, X_val_raw, y_val = split_train_val(
    X_train_raw, y_train_raw, val_ratio=VALIDATION_RATIO
)
X_train, X_val, X_test = scale_X_only(X_train_raw, X_val_raw, X_test_raw)

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)
print("X_val:  ", X_val.shape)
print("y_val:  ", y_val.shape)
print("X_test: ", X_test.shape)
print("y_test: ", y_test.shape)

X_train: (13082, 30, 23)
y_train: (13082, 23)
X_val:   (1453, 30, 23)
y_val:   (1453, 23)
X_test:  (1616, 30, 23)
y_test:  (1616, 23)

## Hyperparameter space

The search varies filters, kernel sizes, dilation, dropout, dense layer sizes, learning rate and batch size. This is a controlled random search, not an exhaustive grid search.

In [4]:
def sample_config(trial_id):
    cfg = {
        "filters_1": random.choice([32, 64, 96]),
        "filters_2": random.choice([32, 64, 96]),
        "filters_3": random.choice([64, 96, 128]),
        "kernel_1": random.choice([3, 5]),
        "kernel_2": random.choice([3, 5, 7]),
        "kernel_3": random.choice([3, 5]),
        "dilation_2": random.choice([1, 2]),
        "dilation_3": random.choice([2, 4]),
        "spatial_dropout": random.choice([0.05, 0.10, 0.15, 0.20]),
        "dense_1": random.choice([64, 128, 256]),
        "dense_2": random.choice([32, 64, 128]),
        "dropout_1": random.choice([0.10, 0.20, 0.30]),
        "dropout_2": random.choice([0.05, 0.10, 0.20]),
        "learning_rate": random.choice([1e-3, 5e-4, 3e-4, 1e-4]),
        "batch_size": random.choice([64, 128, 256]),
    }
    cfg["trial_id"] = trial_id
    return cfg


def build_model(input_window, n_assets, cfg):
    inputs = Input(shape=(input_window, n_assets))

    x = Conv1D(cfg["filters_1"], cfg["kernel_1"], padding="causal", activation="relu")(inputs)
    x = BatchNormalization()(x)
    x = SpatialDropout1D(cfg["spatial_dropout"])(x)

    x = Conv1D(
        cfg["filters_2"],
        cfg["kernel_2"],
        padding="causal",
        dilation_rate=cfg["dilation_2"],
        activation="relu",
    )(x)
    x = BatchNormalization()(x)
    x = SpatialDropout1D(cfg["spatial_dropout"])(x)

    x = Conv1D(
        cfg["filters_3"],
        cfg["kernel_3"],
        padding="causal",
        dilation_rate=cfg["dilation_3"],
        activation="relu",
    )(x)
    x = BatchNormalization()(x)

    avg_pool = GlobalAveragePooling1D()(x)
    max_pool = GlobalMaxPooling1D()(x)
    x = Concatenate()([avg_pool, max_pool])

    x = Dense(cfg["dense_1"], activation="relu")(x)
    x = Dropout(cfg["dropout_1"])(x)
    x = Dense(cfg["dense_2"], activation="relu")(x)
    x = Dropout(cfg["dropout_2"])(x)

    outputs = Dense(n_assets, activation="linear")(x)
    model = Model(inputs=inputs, outputs=outputs)

    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=cfg["learning_rate"]),
        loss="mae",
        metrics=["mae"],
    )
    return model

## Random search

Each trial is selected by validation MAE. During the search, partial results are saved to disk so the experiment can be inspected even if it is interrupted.

In [5]:
def train_trial(trial_id, cfg):
    K.clear_session()
    keras.utils.set_random_seed(RANDOM_SEED + trial_id)

    model = build_model(INPUT_WINDOW, X_train.shape[2], cfg)

    callbacks = [
        EarlyStopping(
            monitor="val_loss",
            patience=15,
            min_delta=1e-6,
            restore_best_weights=True,
        ),
        ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.5,
            patience=6,
            min_lr=1e-6,
        ),
    ]

    print("\n" + "=" * 80)
    print(f"Trial {trial_id}/{N_TRIALS}")
    print(json.dumps(cfg, indent=2))
    print("=" * 80)

    history = model.fit(
        X_train,
        y_train,
        validation_data=(X_val, y_val),
        epochs=EPOCHS,
        batch_size=cfg["batch_size"],
        callbacks=callbacks,
        verbose=1,
        shuffle=True,
    )

    y_pred_train = model.predict(X_train, verbose=0)
    y_pred_val = model.predict(X_val, verbose=0)

    row = {
        "trial_id": trial_id,
        "input_window": INPUT_WINDOW,
        "output_window": OUTPUT_WINDOW,
        "MAE_train": mean_absolute_error(y_train, y_pred_train),
        "MAE_val": mean_absolute_error(y_val, y_pred_val),
        "params": model.count_params(),
        "epochs_trained": len(history.history["loss"]),
        **cfg,
    }

    pd.DataFrame(history.history).to_csv(OUTPUT_DIR / f"trial_{trial_id:02d}_history.csv", index=False)
    return row, model


rows = []
best_val = float("inf")
best_trial_id = None
best_config = None

for trial_id in range(1, N_TRIALS + 1):
    cfg = sample_config(trial_id)
    row, model = train_trial(trial_id, cfg)
    rows.append(row)

    partial_df = pd.DataFrame(rows).sort_values("MAE_val")
    partial_df.to_csv(OUTPUT_DIR / "cnn_hyperparameter_trials_partial.csv", index=False)

    if row["MAE_val"] < best_val:
        best_val = row["MAE_val"]
        best_trial_id = trial_id
        best_config = cfg
        model.save(OUTPUT_DIR / "best_cnn_model.keras")
        with open(OUTPUT_DIR / "best_config.json", "w", encoding="utf-8") as f:
            json.dump(best_config, f, indent=2)
        print(f"New best model: trial {trial_id}, MAE_val={best_val:.10f}")

trials_df = pd.DataFrame(rows).sort_values("MAE_val").reset_index(drop=True)
trials_path = OUTPUT_DIR / "cnn_hyperparameter_trials.csv"
trials_df.to_csv(trials_path, index=False)

display(trials_df.head(10))
print("Trials saved to:", trials_path)
print("Best config saved to:", OUTPUT_DIR / "best_config.json")

================================================================================
Trial 1/15
{
  "filters_1": 96,
  "filters_2": 32,
  "filters_3": 64,
  "kernel_1": 5,
  "kernel_2": 3,
  "kernel_3": 3,
  "dilation_2": 1,
  "dilation_3": 2,
  "spatial_dropout": 0.05,
  "dense_1": 256,
  "dense_2": 64,
  "dropout_1": 0.1,
  "dropout_2": 0.05,
  "learning_rate": 0.001,
  "batch_size": 64,
  "trial_id": 1
}
================================================================================
Epoch 1/100

E0000 00:00:1777829822.288623 1765399 cuda_executor.cc:1737] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4:05 1s/step - loss: 1.0102 - mae: 1.0102

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.6114 - mae: 0.6114

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.4372 - mae: 0.4372

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.3448 - mae: 0.3448

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2876 - mae: 0.2876

 50/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2484 - mae: 0.2484

 60/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.2196 - mae: 0.2196

 69/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1995 - mae: 0.1995

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1816 - mae: 0.1816

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.1670 - mae: 0.1670

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1548 - mae: 0.1548

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1446 - mae: 0.1446

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1357 - mae: 0.1357

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1281 - mae: 0.1281

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1213 - mae: 0.1213

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1154 - mae: 0.1154

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1100 - mae: 0.1100

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1053 - mae: 0.1053

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.1009 - mae: 0.1009

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0970 - mae: 0.0970

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0934 - mae: 0.0934

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0245 - mae: 0.0245 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 2/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 3/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 4/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 5/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 42/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 6/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 32/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

103/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 7/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 8/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 32/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 42/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 52/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 9/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 10/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 11/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 12/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 13/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 14/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 15/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0053 - mae: 0.0053

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

128/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 16/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0049 - mae: 0.0049

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0053 - mae: 0.0053

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 17/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0053 - mae: 0.0053

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 18/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0053 - mae: 0.0053

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 49/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 58/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 19/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0053 - mae: 0.0053

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 39/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 48/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 20/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0053 - mae: 0.0053

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 60/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 21/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0053 - mae: 0.0053

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 59/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 22/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0053 - mae: 0.0053

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 59/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 23/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0053 - mae: 0.0053

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 24/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0053 - mae: 0.0053

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 60/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 25/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 0.0049 - mae: 0.0049

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0053 - mae: 0.0053

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 39/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 49/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 58/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 77/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 26/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0049 - mae: 0.0049

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0053 - mae: 0.0053

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 38/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 48/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 84/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 93/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 27/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0053 - mae: 0.0053

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 28/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0053 - mae: 0.0053

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 29/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0049 - mae: 0.0049

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0053 - mae: 0.0053

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 31/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0054 - mae: 0.0054

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

102/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

New best model: trial 1, MAE_val=0.0041506064

================================================================================
Trial 2/15
{
  "filters_1": 32,
  "filters_2": 64,
  "filters_3": 128,
  "kernel_1": 5,
  "kernel_2": 7,
  "kernel_3": 3,
  "dilation_2": 2,
  "dilation_3": 4,
  "spatial_dropout": 0.2,
  "dense_1": 128,
  "dense_2": 32,
  "dropout_1": 0.1,
  "dropout_2": 0.05,
  "learning_rate": 0.001,
  "batch_size": 128,
  "trial_id": 2
}
================================================================================
Epoch 1/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:02 1s/step - loss: 1.9583 - mae: 1.9583

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.3301 - mae: 1.3301

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0397 - mae: 1.0397

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8618 - mae: 0.8618

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.7402 - mae: 0.7402

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6517 - mae: 0.6517

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.5841 - mae: 0.5841

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.5307 - mae: 0.5307

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.4808 - mae: 0.4808

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.4404 - mae: 0.4404

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.4115 - mae: 0.4115

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3866 - mae: 0.3866

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3649 - mae: 0.3649

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3457 - mae: 0.3457

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3287 - mae: 0.3287

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3112 - mae: 0.3112

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2956 - mae: 0.2956

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0833 - mae: 0.0833 - val_loss: 0.0049 - val_mae: 0.0049 - learning_rate: 0.0010

Epoch 2/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0060 - mae: 0.0060

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0060 - mae: 0.0060

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0061 - mae: 0.0061

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0061 - mae: 0.0061

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0061 - mae: 0.0061

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0061 - mae: 0.0061

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0061 - mae: 0.0061

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0061 - mae: 0.0061

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0061 - mae: 0.0061

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0060 - mae: 0.0060

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0060 - mae: 0.0060

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0060 - mae: 0.0060

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0060 - mae: 0.0060

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0060 - mae: 0.0060

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 3/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 4/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 5/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0058 - mae: 0.0058

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 6/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 7/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 8/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 9/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0057 - mae: 0.0057

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 10/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 11/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 12/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0056 - mae: 0.0056

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0056 - mae: 0.0056

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0056 - mae: 0.0056

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 13/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0056 - mae: 0.0056

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0056 - mae: 0.0056

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0056 - mae: 0.0056

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0056 - mae: 0.0056

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0056 - mae: 0.0056

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0056 - mae: 0.0056

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 14/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 15/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 16/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 17/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 18/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

================================================================================
Trial 3/15
{
  "filters_1": 32,
  "filters_2": 32,
  "filters_3": 64,
  "kernel_1": 3,
  "kernel_2": 3,
  "kernel_3": 3,
  "dilation_2": 2,
  "dilation_3": 4,
  "spatial_dropout": 0.2,
  "dense_1": 256,
  "dense_2": 128,
  "dropout_1": 0.2,
  "dropout_2": 0.1,
  "learning_rate": 0.001,
  "batch_size": 128,
  "trial_id": 3
}
================================================================================
Epoch 1/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:08 1s/step - loss: 1.2103 - mae: 1.2103

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.8139 - mae: 0.8139

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6582 - mae: 0.6582

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5592 - mae: 0.5592

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4794 - mae: 0.4794

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.4275 - mae: 0.4275

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3868 - mae: 0.3868

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3540 - mae: 0.3540

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3268 - mae: 0.3268

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.3041 - mae: 0.3041

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2821 - mae: 0.2821

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2656 - mae: 0.2656

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2512 - mae: 0.2512

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2385 - mae: 0.2385

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.2256 - mae: 0.2256

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0721 - mae: 0.0721 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 2/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 3/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 4/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 5/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 6/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 7/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 8/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 9/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 10/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 11/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 12/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 13/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 14/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 15/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 16/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 17/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 18/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 19/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 20/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 21/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 22/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 23/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

================================================================================
Trial 4/15
{
  "filters_1": 32,
  "filters_2": 32,
  "filters_3": 96,
  "kernel_1": 3,
  "kernel_2": 5,
  "kernel_3": 3,
  "dilation_2": 1,
  "dilation_3": 2,
  "spatial_dropout": 0.15,
  "dense_1": 256,
  "dense_2": 32,
  "dropout_1": 0.1,
  "dropout_2": 0.2,
  "learning_rate": 0.0001,
  "batch_size": 64,
  "trial_id": 4
}
================================================================================
Epoch 1/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3:58 1s/step - loss: 0.8966 - mae: 0.8966

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.7947 - mae: 0.7947

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.7083 - mae: 0.7083

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6359 - mae: 0.6359

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5754 - mae: 0.5754

 50/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5253 - mae: 0.5253

 60/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4834 - mae: 0.4834

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4448 - mae: 0.4448

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4151 - mae: 0.4151

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3896 - mae: 0.3896

102/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3654 - mae: 0.3654

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3443 - mae: 0.3443

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3259 - mae: 0.3259

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3096 - mae: 0.3096

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2951 - mae: 0.2951

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2820 - mae: 0.2820

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2713 - mae: 0.2713

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2614 - mae: 0.2614

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2524 - mae: 0.2524

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2440 - mae: 0.2440

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0829 - mae: 0.0829 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 2/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0103 - mae: 0.0103

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0077 - mae: 0.0077

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0074 - mae: 0.0074

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0073 - mae: 0.0073

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0072 - mae: 0.0072

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0071 - mae: 0.0071

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0071 - mae: 0.0071

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0070 - mae: 0.0070

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0070 - mae: 0.0070

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0070 - mae: 0.0070

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0070 - mae: 0.0070

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0070 - mae: 0.0070

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0069 - mae: 0.0069

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0069 - mae: 0.0069

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0069 - mae: 0.0069

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0069 - mae: 0.0069

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0068 - mae: 0.0068

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0068 - mae: 0.0068

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0068 - mae: 0.0068

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0064 - mae: 0.0064 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 3/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0060 - mae: 0.0060

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0061 - mae: 0.0061

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0061 - mae: 0.0061

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0061 - mae: 0.0061

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0061 - mae: 0.0061

 68/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0061 - mae: 0.0061

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0061 - mae: 0.0061

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0061 - mae: 0.0061

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0060 - mae: 0.0060

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0060 - mae: 0.0060

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0060 - mae: 0.0060

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0060 - mae: 0.0060

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0060 - mae: 0.0060

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0060 - mae: 0.0060

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0060 - mae: 0.0060

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0060 - mae: 0.0060

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0059 - mae: 0.0059

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0059 - mae: 0.0059

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 4/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0057 - mae: 0.0057

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0057 - mae: 0.0057

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0057 - mae: 0.0057

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0057 - mae: 0.0057

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0057 - mae: 0.0057

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0057 - mae: 0.0057

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0057 - mae: 0.0057

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0057 - mae: 0.0057

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0057 - mae: 0.0057

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 5/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 24/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 68/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 6/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 7/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 8/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-05

Epoch 9/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-05

Epoch 10/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-05

Epoch 11/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 94/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-05

Epoch 12/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-05

Epoch 13/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0058 - mae: 0.0058

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055

 21/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 40/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-05

Epoch 14/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-05

Epoch 15/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-05

Epoch 16/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-05

Epoch 17/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-05

Epoch 18/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-05

Epoch 19/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-05

Epoch 20/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-05

Epoch 21/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-05

Epoch 22/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-05

Epoch 23/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 42/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 51/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 60/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-05

Epoch 24/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0058 - mae: 0.0058

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055

 22/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 32/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 43/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-05

Epoch 25/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-05

Epoch 26/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0058 - mae: 0.0058

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-06

================================================================================
Trial 5/15
{
  "filters_1": 96,
  "filters_2": 32,
  "filters_3": 128,
  "kernel_1": 3,
  "kernel_2": 3,
  "kernel_3": 3,
  "dilation_2": 2,
  "dilation_3": 2,
  "spatial_dropout": 0.05,
  "dense_1": 64,
  "dense_2": 128,
  "dropout_1": 0.2,
  "dropout_2": 0.2,
  "learning_rate": 0.0003,
  "batch_size": 256,
  "trial_id": 5
}
================================================================================
Epoch 1/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1:02 1s/step - loss: 1.3065 - mae: 1.3065

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.2256 - mae: 1.2256

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.1494 - mae: 1.1494

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0839 - mae: 1.0839

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0271 - mae: 1.0271

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.9764 - mae: 0.9764

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.9306 - mae: 0.9306

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.8893 - mae: 0.8893

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.8516 - mae: 0.8516

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.8171 - mae: 0.8171

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7852 - mae: 0.7852

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7556 - mae: 0.7556

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7281 - mae: 0.7281

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - loss: 0.3917 - mae: 0.3917 - val_loss: 0.0251 - val_mae: 0.0251 - learning_rate: 3.0000e-04

Epoch 2/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0272 - mae: 0.0272

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0245 - mae: 0.0245

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0226 - mae: 0.0226

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0212 - mae: 0.0212

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0199 - mae: 0.0199

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0189 - mae: 0.0189

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0181 - mae: 0.0181

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0174 - mae: 0.0174

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0167 - mae: 0.0167

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0160 - mae: 0.0160

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0156 - mae: 0.0156

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0151 - mae: 0.0151

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0104 - mae: 0.0104 - val_loss: 0.0114 - val_mae: 0.0114 - learning_rate: 3.0000e-04

Epoch 3/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0061 - mae: 0.0061

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0065 - mae: 0.0065

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064 - mae: 0.0064

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064 - mae: 0.0064

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064 - mae: 0.0064

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064 - mae: 0.0064

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064 - mae: 0.0064

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064 - mae: 0.0064

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064 - mae: 0.0064

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064 - mae: 0.0064

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064 - mae: 0.0064

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0064 - mae: 0.0064

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0063 - mae: 0.0063 - val_loss: 0.0081 - val_mae: 0.0081 - learning_rate: 3.0000e-04

Epoch 4/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0057 - mae: 0.0057

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0059 - mae: 0.0059

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0059 - mae: 0.0059

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0059 - mae: 0.0059

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0059 - mae: 0.0059

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0060 - mae: 0.0060

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0060 - mae: 0.0060

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0060 - mae: 0.0060

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0060 - mae: 0.0060

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0060 - mae: 0.0060

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0060 - mae: 0.0060 - val_loss: 0.0060 - val_mae: 0.0060 - learning_rate: 3.0000e-04

Epoch 5/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0058 - mae: 0.0058

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0049 - val_mae: 0.0049 - learning_rate: 3.0000e-04

Epoch 6/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0056 - mae: 0.0056

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0057 - mae: 0.0057

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0044 - val_mae: 0.0044 - learning_rate: 3.0000e-04

Epoch 7/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0043 - val_mae: 0.0043 - learning_rate: 3.0000e-04

Epoch 8/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 9/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 10/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 11/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 12/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 13/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 14/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 15/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0056 - mae: 0.0056

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 16/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0056 - mae: 0.0056

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 17/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 18/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 19/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 20/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 21/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 22/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 23/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 24/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 25/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 26/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 27/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 28/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 29/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 30/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 31/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 32/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 33/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 34/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 35/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 36/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 37/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 38/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 39/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 40/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 9.3750e-06

Epoch 41/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 9.3750e-06

Epoch 42/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 9.3750e-06

Epoch 43/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 9.3750e-06

Epoch 44/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 9.3750e-06

================================================================================
Trial 6/15
{
  "filters_1": 64,
  "filters_2": 96,
  "filters_3": 64,
  "kernel_1": 5,
  "kernel_2": 7,
  "kernel_3": 3,
  "dilation_2": 1,
  "dilation_3": 2,
  "spatial_dropout": 0.15,
  "dense_1": 128,
  "dense_2": 128,
  "dropout_1": 0.3,
  "dropout_2": 0.05,
  "learning_rate": 0.0003,
  "batch_size": 256,
  "trial_id": 6
}
================================================================================
Epoch 1/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1:01 1s/step - loss: 1.5474 - mae: 1.5474

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.4158 - mae: 1.4158

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.3122 - mae: 1.3122

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.2241 - mae: 1.2241

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.1525 - mae: 1.1525

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.0924 - mae: 1.0924

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.0415 - mae: 1.0415

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.9974 - mae: 0.9974

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.9585 - mae: 0.9585

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.9237 - mae: 0.9237

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.8924 - mae: 0.8924

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.8637 - mae: 0.8637

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.8374 - mae: 0.8374

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - loss: 0.5165 - mae: 0.5165 - val_loss: 0.0538 - val_mae: 0.0538 - learning_rate: 3.0000e-04

Epoch 2/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.1812 - mae: 0.1812

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1759 - mae: 0.1759

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1723 - mae: 0.1723

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1681 - mae: 0.1681

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1650 - mae: 0.1650

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1618 - mae: 0.1618

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1587 - mae: 0.1587

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1557 - mae: 0.1557

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1528 - mae: 0.1528

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1500 - mae: 0.1500

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1474 - mae: 0.1474

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1448 - mae: 0.1448

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.1423 - mae: 0.1423

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.1106 - mae: 0.1106 - val_loss: 0.0295 - val_mae: 0.0295 - learning_rate: 3.0000e-04

Epoch 3/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0635 - mae: 0.0635

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0584 - mae: 0.0584

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0572 - mae: 0.0572

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0561 - mae: 0.0561

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0554 - mae: 0.0554

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0545 - mae: 0.0545

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0537 - mae: 0.0537

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0530 - mae: 0.0530

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0522 - mae: 0.0522

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0514 - mae: 0.0514

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0506 - mae: 0.0506

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0499 - mae: 0.0499

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0491 - mae: 0.0491

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0395 - mae: 0.0395 - val_loss: 0.0121 - val_mae: 0.0121 - learning_rate: 3.0000e-04

Epoch 4/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0205 - mae: 0.0205

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0202 - mae: 0.0202

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0201 - mae: 0.0201

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0198 - mae: 0.0198

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0197 - mae: 0.0197

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0194 - mae: 0.0194

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0192 - mae: 0.0192

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0189 - mae: 0.0189

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0187 - mae: 0.0187

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0184 - mae: 0.0184

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0182 - mae: 0.0182

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0179 - mae: 0.0179

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0177 - mae: 0.0177

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0147 - mae: 0.0147 - val_loss: 0.0053 - val_mae: 0.0053 - learning_rate: 3.0000e-04

Epoch 5/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0106 - mae: 0.0106

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0098 - mae: 0.0098

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0096 - mae: 0.0096

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0095 - mae: 0.0095

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0094 - mae: 0.0094

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0093 - mae: 0.0093

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0093 - mae: 0.0093

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0092 - mae: 0.0092

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0092 - mae: 0.0092

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0091 - mae: 0.0091

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0091 - mae: 0.0091

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0090 - mae: 0.0090

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0090 - mae: 0.0090

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0084 - mae: 0.0084 - val_loss: 0.0043 - val_mae: 0.0043 - learning_rate: 3.0000e-04

Epoch 6/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0075 - mae: 0.0075

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0072 - mae: 0.0072

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0071 - mae: 0.0071

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0071 - mae: 0.0071

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0071 - mae: 0.0071

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0071 - mae: 0.0071

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0071 - mae: 0.0071

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0071 - mae: 0.0071

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0071 - mae: 0.0071

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0071 - mae: 0.0071

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0071 - mae: 0.0071

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0071 - mae: 0.0071

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0071 - mae: 0.0071

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0069 - mae: 0.0069 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 7/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0065 - mae: 0.0065

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0065 - mae: 0.0065

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0065 - mae: 0.0065

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0064 - mae: 0.0064

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0065 - mae: 0.0065

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0064 - mae: 0.0064

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0064 - mae: 0.0064

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0064 - mae: 0.0064

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0064 - mae: 0.0064

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0064 - mae: 0.0064

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0064 - mae: 0.0064

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0064 - mae: 0.0064

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0064 - mae: 0.0064

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0064 - mae: 0.0064 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 8/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0060 - mae: 0.0060

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0061 - mae: 0.0061

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0061 - mae: 0.0061

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0061 - mae: 0.0061

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0061 - mae: 0.0061

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0061 - mae: 0.0061

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0061 - mae: 0.0061

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0061 - mae: 0.0061

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0061 - mae: 0.0061

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0061 - mae: 0.0061

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0061 - mae: 0.0061

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0061 - mae: 0.0061

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0061 - mae: 0.0061

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0061 - mae: 0.0061

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0061 - mae: 0.0061 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 9/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0059 - mae: 0.0059

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0059 - mae: 0.0059 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 10/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0057 - mae: 0.0057

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 11/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0057 - mae: 0.0057

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 12/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 13/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0057 - mae: 0.0057

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 14/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0057 - mae: 0.0057

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0057 - mae: 0.0057

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 15/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0057 - mae: 0.0057

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 16/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 17/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 18/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 19/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 20/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 21/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 22/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 23/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 24/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 25/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 26/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 27/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 28/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 29/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 30/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 31/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 32/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 33/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 34/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

================================================================================
Trial 7/15
{
  "filters_1": 96,
  "filters_2": 64,
  "filters_3": 64,
  "kernel_1": 3,
  "kernel_2": 7,
  "kernel_3": 3,
  "dilation_2": 2,
  "dilation_3": 2,
  "spatial_dropout": 0.1,
  "dense_1": 256,
  "dense_2": 128,
  "dropout_1": 0.3,
  "dropout_2": 0.05,
  "learning_rate": 0.0001,
  "batch_size": 64,
  "trial_id": 7
}
================================================================================
Epoch 1/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4:04 1s/step - loss: 1.1181 - mae: 1.1181

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 1.0629 - mae: 1.0629

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 1.0010 - mae: 1.0010

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.9491 - mae: 0.9491

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.9052 - mae: 0.9052

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.8680 - mae: 0.8680

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.8354 - mae: 0.8354

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.8066 - mae: 0.8066

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.7810 - mae: 0.7810

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.7580 - mae: 0.7580

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.7370 - mae: 0.7370

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.7178 - mae: 0.7178

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.7000 - mae: 0.7000

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6834 - mae: 0.6834

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6679 - mae: 0.6679

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6533 - mae: 0.6533

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6395 - mae: 0.6395

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6265 - mae: 0.6265

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6141 - mae: 0.6141

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6024 - mae: 0.6024

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5897 - mae: 0.5897

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5790 - mae: 0.5790

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5688 - mae: 0.5688

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5589 - mae: 0.5589

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5494 - mae: 0.5494

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.5403 - mae: 0.5403

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 0.3111 - mae: 0.3111 - val_loss: 0.0092 - val_mae: 0.0092 - learning_rate: 1.0000e-04

Epoch 2/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0580 - mae: 0.0580

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0578 - mae: 0.0578

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0568 - mae: 0.0568

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0553 - mae: 0.0553

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0538 - mae: 0.0538

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0524 - mae: 0.0524

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0510 - mae: 0.0510

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0496 - mae: 0.0496

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0484 - mae: 0.0484

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0473 - mae: 0.0473

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0462 - mae: 0.0462

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0451 - mae: 0.0451

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0441 - mae: 0.0441

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0432 - mae: 0.0432

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0423 - mae: 0.0423

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0415 - mae: 0.0415

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0407 - mae: 0.0407

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0400 - mae: 0.0400

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0392 - mae: 0.0392

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0386 - mae: 0.0386

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0379 - mae: 0.0379

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0373 - mae: 0.0373

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0367 - mae: 0.0367

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0361 - mae: 0.0361

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0356 - mae: 0.0356

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0351 - mae: 0.0351

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0223 - mae: 0.0223 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 3/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0129 - mae: 0.0129

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0108 - mae: 0.0108

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0105 - mae: 0.0105

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0103 - mae: 0.0103

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0101 - mae: 0.0101

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0099 - mae: 0.0099

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0098 - mae: 0.0098

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0097 - mae: 0.0097

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0096 - mae: 0.0096

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0096 - mae: 0.0096

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0095 - mae: 0.0095

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0094 - mae: 0.0094

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0094 - mae: 0.0094

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0093 - mae: 0.0093

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0093 - mae: 0.0093

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0092 - mae: 0.0092

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0092 - mae: 0.0092

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0091 - mae: 0.0091

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0091 - mae: 0.0091

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0091 - mae: 0.0091

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0090 - mae: 0.0090

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0090 - mae: 0.0090

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0089 - mae: 0.0089

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0089 - mae: 0.0089

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0089 - mae: 0.0089

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0088 - mae: 0.0088

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0080 - mae: 0.0080 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 4/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: 0.0070 - mae: 0.0070

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0070 - mae: 0.0070

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0069 - mae: 0.0069

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0069 - mae: 0.0069

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0069 - mae: 0.0069

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0069 - mae: 0.0069

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0069 - mae: 0.0069

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0069 - mae: 0.0069

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0069 - mae: 0.0069

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0069 - mae: 0.0069

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0069 - mae: 0.0069

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0069 - mae: 0.0069

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0069 - mae: 0.0069

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0069 - mae: 0.0069

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0068 - mae: 0.0068

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0068 - mae: 0.0068

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0068 - mae: 0.0068

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0068 - mae: 0.0068

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0068 - mae: 0.0068

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0068 - mae: 0.0068

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0068 - mae: 0.0068

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0068 - mae: 0.0068

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0068 - mae: 0.0068

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0068 - mae: 0.0068

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0068 - mae: 0.0068

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0068 - mae: 0.0068

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0067 - mae: 0.0067 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 5/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0060 - mae: 0.0060

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0062 - mae: 0.0062

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0062 - mae: 0.0062

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0062 - mae: 0.0062

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0062 - mae: 0.0062

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0062 - mae: 0.0062

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0062 - mae: 0.0062

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0062 - mae: 0.0062

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0062 - mae: 0.0062

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0062 - mae: 0.0062

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0062 - mae: 0.0062

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0061 - mae: 0.0061 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 6/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0058 - mae: 0.0058

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0058 - mae: 0.0058

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0058 - mae: 0.0058

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0058 - mae: 0.0058

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0059 - mae: 0.0059

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0059 - mae: 0.0059

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0059 - mae: 0.0059

 58/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0059 - mae: 0.0059

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0059 - mae: 0.0059

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0060 - mae: 0.0060

 83/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0060 - mae: 0.0060

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0060 - mae: 0.0060

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0060 - mae: 0.0060

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0060 - mae: 0.0060

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0060 - mae: 0.0060

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0060 - mae: 0.0060

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0060 - mae: 0.0060

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0060 - mae: 0.0060

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0060 - mae: 0.0060

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0060 - mae: 0.0060

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0060 - mae: 0.0060

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0060 - mae: 0.0060

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0060 - mae: 0.0060

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0060 - mae: 0.0060

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0060 - mae: 0.0060

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0060 - mae: 0.0060

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0060 - mae: 0.0060 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 7/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0056 - mae: 0.0056

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 8/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0084 - mae: 0.0084

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0065 - mae: 0.0065

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0062 - mae: 0.0062

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0061 - mae: 0.0061

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0060 - mae: 0.0060

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0059 - mae: 0.0059

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0059 - mae: 0.0059

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0059 - mae: 0.0059

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0059 - mae: 0.0059

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.0000e-04

Epoch 9/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0058 - mae: 0.0058

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0057 - mae: 0.0057

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0057 - mae: 0.0057

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0057 - mae: 0.0057

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0057 - mae: 0.0057

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0057 - mae: 0.0057

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0057 - mae: 0.0057

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0057 - mae: 0.0057

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-05

Epoch 10/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0058 - mae: 0.0058

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 50/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 58/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-05

Epoch 11/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: 0.0056 - mae: 0.0056

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-05

Epoch 12/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0058 - mae: 0.0058

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-05

Epoch 13/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0056 - mae: 0.0056

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-05

Epoch 14/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0056 - mae: 0.0056

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-05

Epoch 15/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 20ms/step - loss: 0.0056 - mae: 0.0056

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0054 - mae: 0.0054

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-05

Epoch 16/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0057 - mae: 0.0057

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-05

Epoch 17/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0056 - mae: 0.0056

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

193/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-05

Epoch 18/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0056 - mae: 0.0056

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0054 - mae: 0.0054

 41/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 65/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-05

================================================================================
Trial 8/15
{
  "filters_1": 96,
  "filters_2": 32,
  "filters_3": 128,
  "kernel_1": 5,
  "kernel_2": 3,
  "kernel_3": 5,
  "dilation_2": 1,
  "dilation_3": 2,
  "spatial_dropout": 0.15,
  "dense_1": 256,
  "dense_2": 64,
  "dropout_1": 0.2,
  "dropout_2": 0.05,
  "learning_rate": 0.0005,
  "batch_size": 256,
  "trial_id": 8
}
================================================================================
Epoch 1/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1:00 1s/step - loss: 1.4880 - mae: 1.4880

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.2324 - mae: 1.2324

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.0661 - mae: 1.0661

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.9490 - mae: 0.9490

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.8583 - mae: 0.8583

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7842 - mae: 0.7842

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7225 - mae: 0.7225

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6704 - mae: 0.6704

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.6157 - mae: 0.6157

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5787 - mae: 0.5787

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5388 - mae: 0.5388

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.5111 - mae: 0.5111

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.4807 - mae: 0.4807

52/52 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.1905 - mae: 0.1905 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 2/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0070 - mae: 0.0070

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0069 - mae: 0.0069

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0070 - mae: 0.0070

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0070 - mae: 0.0070

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0069 - mae: 0.0069

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0069 - mae: 0.0069

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0069 - mae: 0.0069

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0068 - mae: 0.0068

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0068 - mae: 0.0068

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0068 - mae: 0.0068

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0067 - mae: 0.0067

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0067 - mae: 0.0067

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0067 - mae: 0.0067

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0063 - mae: 0.0063 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 3/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0060 - mae: 0.0060

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0060 - mae: 0.0060

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0059 - mae: 0.0059

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0059 - mae: 0.0059

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0059 - mae: 0.0059

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0059 - mae: 0.0059

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0059 - mae: 0.0059

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0059 - mae: 0.0059

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0059 - mae: 0.0059

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0059 - mae: 0.0059

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 4/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0064 - mae: 0.0064

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0060 - mae: 0.0060

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0059 - mae: 0.0059

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0059 - mae: 0.0059

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0059 - mae: 0.0059

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0059 - mae: 0.0059

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0058 - mae: 0.0058

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0058 - mae: 0.0058

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0058 - mae: 0.0058

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0058 - mae: 0.0058

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0058 - mae: 0.0058

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0058 - mae: 0.0058

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 5/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0056 - mae: 0.0056

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 6/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 7/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 8/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 9/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 10/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 11/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 12/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 13/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 14/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 15/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 16/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 17/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 18/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 19/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - loss: 0.0056 - mae: 0.0056

 6/52 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 20/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 21/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0055 - mae: 0.0055

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

================================================================================
Trial 9/15
{
  "filters_1": 64,
  "filters_2": 32,
  "filters_3": 128,
  "kernel_1": 5,
  "kernel_2": 3,
  "kernel_3": 3,
  "dilation_2": 1,
  "dilation_3": 4,
  "spatial_dropout": 0.05,
  "dense_1": 128,
  "dense_2": 64,
  "dropout_1": 0.1,
  "dropout_2": 0.05,
  "learning_rate": 0.001,
  "batch_size": 128,
  "trial_id": 9
}
================================================================================
Epoch 1/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:03 1s/step - loss: 1.4160 - mae: 1.4160

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8939 - mae: 0.8939

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6895 - mae: 0.6895

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.5688 - mae: 0.5688

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4877 - mae: 0.4877

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.4290 - mae: 0.4290

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.3844 - mae: 0.3844

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.3492 - mae: 0.3492

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.3206 - mae: 0.3206

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2969 - mae: 0.2969

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2769 - mae: 0.2769

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2597 - mae: 0.2597

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2449 - mae: 0.2449

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2318 - mae: 0.2318

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2202 - mae: 0.2202

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0644 - mae: 0.0644 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 2/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0057 - mae: 0.0057

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0058 - mae: 0.0058

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 3/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0056 - mae: 0.0056

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 4/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 5/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 6/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 7/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 8/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 9/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0057 - mae: 0.0057

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 10/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 11/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 12/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 13/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 14/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 15/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 16/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 17/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 18/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 19/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 20/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 21/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 22/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 23/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0057 - mae: 0.0057

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 24/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 25/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 26/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 27/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 28/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 29/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0060 - mae: 0.0060

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0056 - mae: 0.0056

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 30/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 31/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 32/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 33/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 34/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 35/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 36/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 37/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 38/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5625e-05

Epoch 39/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5625e-05

Epoch 40/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5625e-05

Epoch 41/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0057 - mae: 0.0057

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5625e-05

Epoch 42/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0057 - mae: 0.0057

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5625e-05

Epoch 43/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5625e-05

Epoch 44/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0057 - mae: 0.0057

  9/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.8125e-06

Epoch 45/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.8125e-06

Epoch 46/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.8125e-06

Epoch 47/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.8125e-06

Epoch 48/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.8125e-06

Epoch 49/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.8125e-06

Epoch 50/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.9063e-06

Epoch 51/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0057 - mae: 0.0057

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0054 - mae: 0.0054

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.9063e-06

================================================================================
Trial 10/15
{
  "filters_1": 64,
  "filters_2": 64,
  "filters_3": 128,
  "kernel_1": 5,
  "kernel_2": 7,
  "kernel_3": 5,
  "dilation_2": 2,
  "dilation_3": 4,
  "spatial_dropout": 0.15,
  "dense_1": 128,
  "dense_2": 128,
  "dropout_1": 0.1,
  "dropout_2": 0.05,
  "learning_rate": 0.001,
  "batch_size": 256,
  "trial_id": 10
}
================================================================================
Epoch 1/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1:09 1s/step - loss: 1.3982 - mae: 1.3982

 4/52 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 1.1153 - mae: 1.1153

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.9576 - mae: 0.9576

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8536 - mae: 0.8536

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7762 - mae: 0.7762

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.7145 - mae: 0.7145

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.6637 - mae: 0.6637

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.6209 - mae: 0.6209

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.5842 - mae: 0.5842

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.5523 - mae: 0.5523

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.5241 - mae: 0.5241

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.4992 - mae: 0.4992

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.4768 - mae: 0.4768

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.4566 - mae: 0.4566

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.4383 - mae: 0.4383

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.4163 - mae: 0.4163

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.4015 - mae: 0.4015

52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - loss: 0.1621 - mae: 0.1621 - val_loss: 0.0051 - val_mae: 0.0051 - learning_rate: 0.0010

Epoch 2/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0124 - mae: 0.0124

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0122 - mae: 0.0122

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0122 - mae: 0.0122

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0121 - mae: 0.0121

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0120 - mae: 0.0120

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0119 - mae: 0.0119

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0117 - mae: 0.0117

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0116 - mae: 0.0116

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0114 - mae: 0.0114

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0113 - mae: 0.0113

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0111 - mae: 0.0111

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0110 - mae: 0.0110

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0108 - mae: 0.0108

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0107 - mae: 0.0107

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0106 - mae: 0.0106

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0104 - mae: 0.0104

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0085 - mae: 0.0085 - val_loss: 0.0055 - val_mae: 0.0055 - learning_rate: 0.0010

Epoch 3/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0044 - val_mae: 0.0044 - learning_rate: 0.0010

Epoch 4/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 5/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 6/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 7/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 8/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0054 - mae: 0.0054

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 9/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 10/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 11/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 12/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 13/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 14/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 15/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 16/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 17/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 18/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 19/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 20/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 21/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 22/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 23/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0054 - mae: 0.0054

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0054 - mae: 0.0054

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0054 - mae: 0.0054

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0054 - mae: 0.0054

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 24/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 25/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 26/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 27/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 28/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0053 - mae: 0.0053

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 29/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 30/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0054 - mae: 0.0054

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 31/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 32/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0053 - mae: 0.0053

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 33/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 34/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

14/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 35/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

18/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 36/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 37/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0053 - mae: 0.0053

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 38/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0053 - mae: 0.0053

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

================================================================================
Trial 11/15
{
  "filters_1": 32,
  "filters_2": 32,
  "filters_3": 96,
  "kernel_1": 3,
  "kernel_2": 5,
  "kernel_3": 5,
  "dilation_2": 1,
  "dilation_3": 2,
  "spatial_dropout": 0.2,
  "dense_1": 128,
  "dense_2": 32,
  "dropout_1": 0.1,
  "dropout_2": 0.05,
  "learning_rate": 0.0005,
  "batch_size": 64,
  "trial_id": 11
}
================================================================================
Epoch 1/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4:00 1s/step - loss: 1.3199 - mae: 1.3199

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 1.0534 - mae: 1.0534

 20/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.8589 - mae: 0.8589

 30/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.7279 - mae: 0.7279

 41/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.6250 - mae: 0.6250

 52/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.5494 - mae: 0.5494

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4916 - mae: 0.4916

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4498 - mae: 0.4498

 84/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.4122 - mae: 0.4122

 94/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3837 - mae: 0.3837

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3571 - mae: 0.3571

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3363 - mae: 0.3363

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3164 - mae: 0.3164

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.3005 - mae: 0.3005

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2850 - mae: 0.2850

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2712 - mae: 0.2712

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2589 - mae: 0.2589

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2478 - mae: 0.2478

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2377 - mae: 0.2377

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.2285 - mae: 0.2285

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 0.0667 - mae: 0.0667 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 2/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0060 - mae: 0.0060

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0062 - mae: 0.0062

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0061 - mae: 0.0061

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0060 - mae: 0.0060

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0059 - mae: 0.0059

 57/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0059 - mae: 0.0059

 68/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0059 - mae: 0.0059

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0059 - mae: 0.0059

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0058 - mae: 0.0058

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0058 - mae: 0.0058

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0058 - mae: 0.0058

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0058 - mae: 0.0058

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0058 - mae: 0.0058

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0058 - mae: 0.0058

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0058 - mae: 0.0058

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0058 - mae: 0.0058

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0058 - mae: 0.0058

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0058 - mae: 0.0058

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0058 - mae: 0.0058

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 3/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0067 - mae: 0.0067

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0058 - mae: 0.0058

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0057 - mae: 0.0057

 33/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 44/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 77/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 4/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0069 - mae: 0.0069

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0058 - mae: 0.0058

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0057 - mae: 0.0057

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 5/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0063 - mae: 0.0063

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0057 - mae: 0.0057

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 6/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0060 - mae: 0.0060

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

167/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 7/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - loss: 0.0060 - mae: 0.0060

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 8/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 18ms/step - loss: 0.0060 - mae: 0.0060

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0056 - mae: 0.0056

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 9/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0060 - mae: 0.0060

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 23/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 34/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 56/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 67/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 10/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 0.0060 - mae: 0.0060

 12/205 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 0.0055 - mae: 0.0055

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 38/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 66/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 75/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 11/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - loss: 0.0060 - mae: 0.0060

 11/205 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 12/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5s 26ms/step - loss: 0.0060 - mae: 0.0060

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 95/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 13/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 0.0060 - mae: 0.0060

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 80/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 14/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0060 - mae: 0.0060

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

142/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 15/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0060 - mae: 0.0060

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

152/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 16/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0060 - mae: 0.0060

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 17/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 53/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 17/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0060 - mae: 0.0060

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 83/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 18/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0060 - mae: 0.0060

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 19/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 21ms/step - loss: 0.0060 - mae: 0.0060

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 73/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 82/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 20/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0060 - mae: 0.0060

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 72/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 81/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

135/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 21/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0060 - mae: 0.0060

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 45/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 62/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

165/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 22/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - loss: 0.0060 - mae: 0.0060

  9/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0056 - mae: 0.0056

 18/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 52/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 61/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 70/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 88/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

123/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

172/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 23/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - loss: 0.0060 - mae: 0.0060

 10/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0056 - mae: 0.0056

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 37/205 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0055 - mae: 0.0055

 46/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 55/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 63/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

121/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

================================================================================
Trial 12/15
{
  "filters_1": 64,
  "filters_2": 96,
  "filters_3": 96,
  "kernel_1": 3,
  "kernel_2": 3,
  "kernel_3": 3,
  "dilation_2": 2,
  "dilation_3": 2,
  "spatial_dropout": 0.15,
  "dense_1": 256,
  "dense_2": 32,
  "dropout_1": 0.1,
  "dropout_2": 0.05,
  "learning_rate": 0.0003,
  "batch_size": 64,
  "trial_id": 12
}
================================================================================
Epoch 1/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5:12 2s/step - loss: 0.6725 - mae: 0.6725

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.5358 - mae: 0.5358

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.4390 - mae: 0.4390

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.3715 - mae: 0.3715

 25/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.3229 - mae: 0.3229

 31/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2865 - mae: 0.2865

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.2542 - mae: 0.2542

 45/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.2292 - mae: 0.2292

 52/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.2092 - mae: 0.2092

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.1929 - mae: 0.1929

 66/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.1792 - mae: 0.1792

 73/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.1676 - mae: 0.1676

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.1576 - mae: 0.1576

 87/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1489 - mae: 0.1489

 94/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1413 - mae: 0.1413

101/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1345 - mae: 0.1345

107/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1292 - mae: 0.1292

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1237 - mae: 0.1237

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1194 - mae: 0.1194

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1147 - mae: 0.1147

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1111 - mae: 0.1111

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1072 - mae: 0.1072

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1036 - mae: 0.1036

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1007 - mae: 0.1007

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0976 - mae: 0.0976

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0950 - mae: 0.0950

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0923 - mae: 0.0923

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0897 - mae: 0.0897

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0874 - mae: 0.0874

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0851 - mae: 0.0851

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0830 - mae: 0.0830

205/205 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 0.0237 - mae: 0.0237 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 2/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 56/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 84/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

160/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

186/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 3/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

158/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

200/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 4/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

181/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

188/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 5/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 94/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

109/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

114/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 6/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0055 - mae: 0.0055

 39/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 44/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 54/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 59/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 69/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 79/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 86/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 92/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

131/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 7/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 8/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 9/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5s 25ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 10/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5s 25ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

116/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 11/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5s 25ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 21/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 40/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 54/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 61/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 68/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 75/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 82/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 89/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 96/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

103/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

110/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

117/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

124/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

130/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

137/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

156/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

170/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

177/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

191/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

198/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 12/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5s 26ms/step - loss: 0.0050 - mae: 0.0050

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0053 - mae: 0.0053

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 27/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 40/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 47/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 54/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 61/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 67/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 73/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 86/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 93/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

100/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

138/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 13/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5s 25ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 14/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 20/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 26/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 32/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 45/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 52/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 76/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 83/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 90/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 97/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

104/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

111/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

118/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

125/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

132/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

139/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

145/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

151/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

163/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 14/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5s 28ms/step - loss: 0.0050 - mae: 0.0050

  7/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0053 - mae: 0.0053

 13/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/205 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0054 - mae: 0.0054

 23/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

 28/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

 33/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

 38/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

 48/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

 53/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

 58/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0054 - mae: 0.0054

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0054 - mae: 0.0054

 69/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0054 - mae: 0.0054

 74/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0054 - mae: 0.0054

 80/205 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0054 - mae: 0.0054

 87/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

 94/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

101/205 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

108/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

115/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

122/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

129/205 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

136/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

143/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

150/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

157/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

171/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

178/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

185/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

192/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

199/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 15/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

146/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

153/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

166/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

173/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

180/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

187/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

194/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 16/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

202/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 17/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 18/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 19/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 20/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 21/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 22/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 23/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 24/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 35/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 56/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 84/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

144/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

149/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

159/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

164/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

174/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

179/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

184/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

195/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

201/205 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 25/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 5s 26ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 26/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 27/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 42/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 49/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 56/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 63/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 70/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 77/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 84/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 91/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 98/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

105/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

112/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

119/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

126/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

133/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

140/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

147/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

154/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

161/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

168/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

175/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

182/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

189/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

196/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

203/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 28/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 24ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

Epoch 29/100

  1/205 ━━━━━━━━━━━━━━━━━━━━ 4s 22ms/step - loss: 0.0050 - mae: 0.0050

  8/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0053 - mae: 0.0053

 15/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 22/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 29/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 36/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 43/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 50/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 57/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 64/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 71/205 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.0054 - mae: 0.0054

 78/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 85/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 92/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

 99/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

106/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

113/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

120/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

127/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

134/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

141/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

148/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

155/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

162/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

169/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

176/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

183/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

190/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

197/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

204/205 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0054 - mae: 0.0054

205/205 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.8750e-05

================================================================================
Trial 13/15
{
  "filters_1": 64,
  "filters_2": 64,
  "filters_3": 128,
  "kernel_1": 5,
  "kernel_2": 3,
  "kernel_3": 3,
  "dilation_2": 1,
  "dilation_3": 4,
  "spatial_dropout": 0.2,
  "dense_1": 256,
  "dense_2": 32,
  "dropout_1": 0.3,
  "dropout_2": 0.1,
  "learning_rate": 0.0003,
  "batch_size": 128,
  "trial_id": 13
}
================================================================================
Epoch 1/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:25 1s/step - loss: 1.2465 - mae: 1.2465

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 1.0775 - mae: 1.0775

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.9493 - mae: 0.9493

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.8497 - mae: 0.8497

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7686 - mae: 0.7686

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7018 - mae: 0.7018

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6462 - mae: 0.6462

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5993 - mae: 0.5993

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5593 - mae: 0.5593

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5249 - mae: 0.5249

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4949 - mae: 0.4949

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4685 - mae: 0.4685

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4451 - mae: 0.4451

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4243 - mae: 0.4243

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4056 - mae: 0.4056

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3887 - mae: 0.3887

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3733 - mae: 0.3733

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3592 - mae: 0.3592

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3464 - mae: 0.3464

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3345 - mae: 0.3345

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3235 - mae: 0.3235

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 0.1097 - mae: 0.1097 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 2/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0064 - mae: 0.0064

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0066 - mae: 0.0066

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0068 - mae: 0.0068

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0069 - mae: 0.0069

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0069 - mae: 0.0069

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0069 - mae: 0.0069

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0069 - mae: 0.0069

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0069 - mae: 0.0069

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0069 - mae: 0.0069

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0069 - mae: 0.0069

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0069 - mae: 0.0069

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0069 - mae: 0.0069

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0069 - mae: 0.0069

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0068 - mae: 0.0068

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0068 - mae: 0.0068

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0068 - mae: 0.0068

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0068 - mae: 0.0068

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0068 - mae: 0.0068

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0068 - mae: 0.0068

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0068 - mae: 0.0068

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0068 - mae: 0.0068

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0066 - mae: 0.0066 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 3/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0063 - mae: 0.0063

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0060 - mae: 0.0060

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0060 - mae: 0.0060

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0060 - mae: 0.0060 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 4/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0061 - mae: 0.0061

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0058 - mae: 0.0058

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 5/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0055 - mae: 0.0055

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 6/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0056 - mae: 0.0056

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 7/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0055 - mae: 0.0055

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 8/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0056 - mae: 0.0056

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 9/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0055 - mae: 0.0055

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 10/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 11/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 12/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 13/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 14/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 15/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0055 - mae: 0.0055

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 16/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0055 - mae: 0.0055

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 17/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.0055 - mae: 0.0055

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

================================================================================
Trial 14/15
{
  "filters_1": 32,
  "filters_2": 64,
  "filters_3": 128,
  "kernel_1": 5,
  "kernel_2": 7,
  "kernel_3": 5,
  "dilation_2": 2,
  "dilation_3": 4,
  "spatial_dropout": 0.15,
  "dense_1": 256,
  "dense_2": 64,
  "dropout_1": 0.3,
  "dropout_2": 0.2,
  "learning_rate": 0.001,
  "batch_size": 256,
  "trial_id": 14
}
================================================================================
Epoch 1/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1:13 1s/step - loss: 1.8218 - mae: 1.8218

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1.4553 - mae: 1.4553

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1.2348 - mae: 1.2348

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1.0795 - mae: 1.0795

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.9618 - mae: 0.9618

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.8693 - mae: 0.8693

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.7947 - mae: 0.7947

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.7331 - mae: 0.7331

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.6814 - mae: 0.6814

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.6373 - mae: 0.6373

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.5991 - mae: 0.5991

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.5659 - mae: 0.5659

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.5365 - mae: 0.5365

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.5105 - mae: 0.5105

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.4871 - mae: 0.4871

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.4661 - mae: 0.4661

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.4470 - mae: 0.4470

52/52 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - loss: 0.1458 - mae: 0.1458 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 2/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0056 - mae: 0.0056

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0059 - mae: 0.0059

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0059 - mae: 0.0059

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0059 - mae: 0.0059

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0059 - mae: 0.0059

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0058 - mae: 0.0058

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0058 - mae: 0.0058

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0059 - mae: 0.0059

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0058 - mae: 0.0058

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0058 - mae: 0.0058

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0058 - mae: 0.0058

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0058 - mae: 0.0058

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0058 - mae: 0.0058

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0058 - mae: 0.0058

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 3/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0068 - mae: 0.0068

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0062 - mae: 0.0062

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0061 - mae: 0.0061

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0061 - mae: 0.0061

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0060 - mae: 0.0060

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0060 - mae: 0.0060

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0060 - mae: 0.0060

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0059 - mae: 0.0059

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0059 - mae: 0.0059

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0059 - mae: 0.0059

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0059 - mae: 0.0059

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0059 - mae: 0.0059

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 4/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0064 - mae: 0.0064

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0060 - mae: 0.0060

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0059 - mae: 0.0059

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 5/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0062 - mae: 0.0062

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0059 - mae: 0.0059

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 6/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - loss: 0.0060 - mae: 0.0060

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0057 - mae: 0.0057

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 7/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 0.0010

Epoch 8/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 9/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0062 - mae: 0.0062

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0058 - mae: 0.0058

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0057 - mae: 0.0057

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 10/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 11/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 12/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0056 - mae: 0.0056

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 13/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 14/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 15/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

11/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 16/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 17/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

15/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 18/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 31ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

42/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 19/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 20/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 21/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 22/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0056 - mae: 0.0056

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0056 - mae: 0.0056

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 23/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0056 - mae: 0.0056

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 24/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 25/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

50/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 26/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 27/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 28/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

26/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

30/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

38/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 29/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

23/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

27/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

35/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

39/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 30/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 8/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 31/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 32/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

29/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

33/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

41/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

45/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 33/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

12/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

47/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 34/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 35/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 36/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

20/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

24/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 37/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 29ms/step - loss: 0.0056 - mae: 0.0056

 5/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

 9/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0055 - mae: 0.0055

17/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

21/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

32/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

36/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

44/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

48/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

51/52 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 38/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - loss: 0.0056 - mae: 0.0056

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5625e-05

Epoch 39/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 2s 39ms/step - loss: 0.0056 - mae: 0.0056

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5625e-05

Epoch 40/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 38ms/step - loss: 0.0056 - mae: 0.0056

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5625e-05

Epoch 41/100

 1/52 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - loss: 0.0056 - mae: 0.0056

 4/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 7/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

10/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

13/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

16/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

19/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

22/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

25/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

28/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

31/52 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0054 - mae: 0.0054

34/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

37/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

40/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0054 - mae: 0.0054

43/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

46/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

49/52 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

52/52 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5625e-05

================================================================================
Trial 15/15
{
  "filters_1": 64,
  "filters_2": 96,
  "filters_3": 64,
  "kernel_1": 3,
  "kernel_2": 5,
  "kernel_3": 3,
  "dilation_2": 2,
  "dilation_3": 4,
  "spatial_dropout": 0.1,
  "dense_1": 64,
  "dense_2": 128,
  "dropout_1": 0.1,
  "dropout_2": 0.05,
  "learning_rate": 0.0005,
  "batch_size": 128,
  "trial_id": 15
}
================================================================================
Epoch 1/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:29 1s/step - loss: 1.1375 - mae: 1.1375

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.9882 - mae: 0.9882

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.8832 - mae: 0.8832

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.8065 - mae: 0.8065

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7459 - mae: 0.7459

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6968 - mae: 0.6968

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6558 - mae: 0.6558

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6208 - mae: 0.6208

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5902 - mae: 0.5902

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5632 - mae: 0.5632

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5391 - mae: 0.5391

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.5173 - mae: 0.5173

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4974 - mae: 0.4974

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4792 - mae: 0.4792

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4625 - mae: 0.4625

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4470 - mae: 0.4470

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4327 - mae: 0.4327

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4193 - mae: 0.4193

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.4068 - mae: 0.4068

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3951 - mae: 0.3951

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.3842 - mae: 0.3842

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 0.1685 - mae: 0.1685 - val_loss: 0.0142 - val_mae: 0.0142 - learning_rate: 5.0000e-04

Epoch 2/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0074 - mae: 0.0074

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0072 - mae: 0.0072

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0073 - mae: 0.0073

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0073 - mae: 0.0073

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0073 - mae: 0.0073

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0073 - mae: 0.0073

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0073 - mae: 0.0073

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0073 - mae: 0.0073

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0073 - mae: 0.0073

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0073 - mae: 0.0073

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0072 - mae: 0.0072

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0072 - mae: 0.0072

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0072 - mae: 0.0072

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0071 - mae: 0.0071

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0071 - mae: 0.0071

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0071 - mae: 0.0071

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0071 - mae: 0.0071

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0070 - mae: 0.0070

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0070 - mae: 0.0070

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0070 - mae: 0.0070

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0070 - mae: 0.0070

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0065 - mae: 0.0065 - val_loss: 0.0051 - val_mae: 0.0051 - learning_rate: 5.0000e-04

Epoch 3/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0057 - mae: 0.0057

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0059 - mae: 0.0059

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0060 - mae: 0.0060

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0060 - mae: 0.0060

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0060 - mae: 0.0060

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0060 - mae: 0.0060

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0059 - mae: 0.0059

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0059 - mae: 0.0059

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0059 - mae: 0.0059

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0059 - mae: 0.0059

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0059 - mae: 0.0059

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0059 - mae: 0.0059

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0059 - mae: 0.0059

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0059 - mae: 0.0059

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0059 - mae: 0.0059

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0059 - mae: 0.0059

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0059 - mae: 0.0059

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0043 - val_mae: 0.0043 - learning_rate: 5.0000e-04

Epoch 4/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0059 - mae: 0.0059

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0057 - mae: 0.0057

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 5/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mae: 0.0056

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 6/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0054 - mae: 0.0054

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 7/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 8/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0054 - mae: 0.0054

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 9/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 10/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 11/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 5.0000e-04

Epoch 12/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 13/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 14/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 15/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 29ms/step - loss: 0.0053 - mae: 0.0053

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 16/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 17/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 2.5000e-04

Epoch 18/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 19/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0053 - mae: 0.0053

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 20/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 21/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 22/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 23/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.2500e-04

Epoch 24/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 25/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 26/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 27/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 28/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 29/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 6.2500e-05

Epoch 30/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 31/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 32/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0053 - mae: 0.0053

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

Epoch 33/100

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0053 - mae: 0.0053

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0054 - mae: 0.0054

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.1250e-05

,trial_id,input_window,output_window,MAE_train,MAE_val,params,epochs_trained,filters_1,filters_2,filters_3,...,kernel_3,dilation_2,dilation_3,spatial_dropout,dense_1,dense_2,dropout_1,dropout_2,learning_rate,batch_size
0,1,30,5,0.005476,0.004151,78327,29,96,32,64,...,3,1,2,0.05,256,64,0.1,0.05,0.0010,64
1,10,30,5,0.005474,0.004151,130647,38,64,64,128,...,5,2,4,0.15,128,128,0.1,0.05,0.0010,256
2,13,30,5,0.005475,0.004151,120279,17,64,64,128,...,3,1,4,0.20,256,32,0.3,0.10,0.0003,128
3,3,30,5,0.005478,0.004152,80951,23,32,32,64,...,3,2,4,0.20,256,128,0.2,0.10,0.0010,128
4,9,30,5,0.005473,0.004152,69559,51,64,32,128,...,3,1,4,0.05,128,64,0.1,0.05,0.0010,128
5,7,30,5,0.005474,0.004152,131927,18,96,64,64,...,3,2,2,0.10,256,128,0.3,0.05,0.0001,64
6,8,30,5,0.005476,0.004153,125751,21,96,32,128,...,5,1,2,0.15,256,64,0.2,0.05,0.0005,256
7,15,30,5,0.005474,0.004153,74231,33,64,96,64,...,3,2,4,0.10,64,128,0.1,0.05,0.0005,128
8,12,30,5,0.005474,0.004153,110167,29,64,96,96,...,3,2,2,0.15,256,32,0.1,0.05,0.0003,64
9,11,30,5,0.005478,0.004153,53079,23,32,32,96,...,5,1,2,0.20,128,32,0.1,0.05,0.0005,64

Trials saved to: /home/hugo/Desktop/Neural-Networks-Forecasting/model/CNN/outputs/cnn_hyperparameter_search_30_5/cnn_hyperparameter_trials.csv
Best config saved to: /home/hugo/Desktop/Neural-Networks-Forecasting/model/CNN/outputs/cnn_hyperparameter_search_30_5/best_config.json

## Final test evaluation of the selected model

The selected model is loaded from disk and evaluated on the untouched test set. This gives the final result of the hyperparameter search.

In [6]:
best_model = keras.models.load_model(OUTPUT_DIR / "best_cnn_model.keras")

y_pred_train = best_model.predict(X_train, verbose=0)
y_pred_val = best_model.predict(X_val, verbose=0)
y_pred_test = best_model.predict(X_test, verbose=0)

best_result = {
    "model": "CNN_Optimized_RandomSearch",
    "selected_trial_id": best_trial_id,
    "input_window": INPUT_WINDOW,
    "output_window": OUTPUT_WINDOW,
    "MAE_train": mean_absolute_error(y_train, y_pred_train),
    "MAE_val": mean_absolute_error(y_val, y_pred_val),
    "MAE_test": mean_absolute_error(y_test, y_pred_test),
    "params": best_model.count_params(),
    "selection_metric": "MAE_val",
}

best_result_df = pd.DataFrame([best_result])
best_result_path = OUTPUT_DIR / "best_cnn_optimized_result.csv"
best_result_df.to_csv(best_result_path, index=False)

comparison_df = None
lr_path = PROJECT_ROOT / "data" / "lr_benchmark.csv"
if lr_path.exists():
    lr = pd.read_csv(lr_path)
    lr_match = lr[(lr["input_window"] == INPUT_WINDOW) & (lr["output_window"] == OUTPUT_WINDOW)]
    if len(lr_match) == 1:
        lr_row = lr_match.iloc[0]
        comparison_df = pd.DataFrame([
            {
                "model": "Linear_Regression_Benchmark",
                "input_window": INPUT_WINDOW,
                "output_window": OUTPUT_WINDOW,
                "MAE_train": lr_row["MAE_train"],
                "MAE_val": np.nan,
                "MAE_test": lr_row["MAE_test"],
                "params": np.nan,
            },
            best_result,
        ])
        comparison_df["improvement_abs_vs_lr"] = comparison_df["MAE_test"].iloc[0] - comparison_df["MAE_test"]
        comparison_df["improvement_pct_vs_lr"] = (
            comparison_df["improvement_abs_vs_lr"] / comparison_df["MAE_test"].iloc[0] * 100
        )
        comparison_path = OUTPUT_DIR / "best_cnn_optimized_vs_lr.csv"
        comparison_df.to_csv(comparison_path, index=False)
        print("Comparison saved to:", comparison_path)

print("Best result saved to:", best_result_path)
display(best_result_df)
if comparison_df is not None:
    display(comparison_df)

Comparison saved to: /home/hugo/Desktop/Neural-Networks-Forecasting/model/CNN/outputs/cnn_hyperparameter_search_30_5/best_cnn_optimized_vs_lr.csv
Best result saved to: /home/hugo/Desktop/Neural-Networks-Forecasting/model/CNN/outputs/cnn_hyperparameter_search_30_5/best_cnn_optimized_result.csv

,model,selected_trial_id,input_window,output_window,MAE_train,MAE_val,MAE_test,params,selection_metric
0,CNN_Optimized_RandomSearch,1,30,5,0.005476,0.004151,0.005578,78327,MAE_val

,model,input_window,output_window,MAE_train,MAE_val,MAE_test,params,selected_trial_id,selection_metric,improvement_abs_vs_lr,improvement_pct_vs_lr
0,Linear_Regression_Benchmark,30,5,0.005337,NaN,0.005877,NaN,NaN,NaN,0.000000,0.000000
1,CNN_Optimized_RandomSearch,30,5,0.005476,0.004151,0.005578,78327.0,1.0,MAE_val,0.000299,5.083225

## How to report this

This notebook supports the following statement in the report:

> A controlled random search was performed for the CNN model. The tested hyperparameters included the number of convolutional filters, kernel sizes, dilation rates, dropout levels, dense layer widths, learning rate and batch size. The model was selected using validation MAE, while the test set was reserved for final evaluation only.