# Modelos Mixtos — Combinaciones Conv1D, LSTM, GRU y MLP

Este notebook explora combinaciones de capas **convolucionales** (Conv1D), **recurrentes** (LSTM, GRU) y **densas** (MLP) para la configuración fija:

- **Ventana de entrada:** 10 días
- **Ventana de salida:** 5 días

Arquitecturas evaluadas:
- `lstm` — LSTM apiladas
- `gru` — GRU apiladas
- `cnn_lstm` — Conv1D → LSTM
- `cnn_gru` — Conv1D → GRU

- `cnn_lstm_mlp` — Conv1D → LSTM → MLP

- `cnn_gru_mlp` — Conv1D → GRU → MLP

- `cnn_mlp` — Conv1D → MLP

La búsqueda se realiza en dos etapas:
1. **Etapa 1 — Arquitectura**: tipo de red × n_layers × units × dropout (84 combinaciones)
2. **Etapa 2 — Entrenamiento**: learning rate × batch size con la mejor arquitectura de la Etapa 1 (9 combinaciones)

In [1]:
import sys
import itertools
import mlflow
from pathlib import Path

# Busca util.py subiendo niveles desde el directorio actual
_here = Path.cwd()
PROJECT_ROOT = next(
    p for p in [_here, _here.parent, _here.parent.parent, _here.parent.parent.parent]
    if (p / 'util.py').exists()
)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

mlflow.set_tracking_uri(f"sqlite:///{PROJECT_ROOT / 'model' / 'mlflow.db'}")

EXPERIMENT_NAME = "Modelos_Mixtos_input10_output5"
mlflow.set_experiment(EXPERIMENT_NAME)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import keras
from keras.models import Sequential
from keras.layers import LSTM, GRU, Dense, Input, Conv1D, GlobalAveragePooling1D, Dropout
from keras.callbacks import EarlyStopping
from keras.optimizers import Adam

from sklearn.metrics import mean_absolute_error

from util import get_train_test, RANDOM_SEED, plot_training_curve

np.random.seed(RANDOM_SEED)
keras.utils.set_random_seed(RANDOM_SEED)

2026/05/10 20:06:34 INFO mlflow.tracking.fluent: Experiment with name 'Modelos_Mixtos_input10_output5' does not exist. Creating a new experiment.

## Carga de datos

In [2]:
INPUT_W  = 10
OUTPUT_W = 5

def load_seq_data(input_window_size, output_window_size):
    d = get_train_test(input_window_size=input_window_size, output_window_size=output_window_size)
    X_train, X_test = d.X_train, d.X_test
    y_train, y_test = d.y_train, d.y_test
    val_size         = int(0.10 * X_train.shape[0])
    X_val, y_val     = X_train[-val_size:], y_train[-val_size:]
    X_train, y_train = X_train[:-val_size], y_train[:-val_size]
    return X_train, y_train, X_val, y_val, X_test, y_test

X_tr, y_tr, X_val, y_val, X_te, y_te = load_seq_data(INPUT_W, OUTPUT_W)

print(f"X_tr:  {X_tr.shape}   y_tr:  {y_tr.shape}")
print(f"X_val: {X_val.shape}  y_val: {y_val.shape}")
print(f"X_te:  {X_te.shape}   y_te:  {y_te.shape}")

X_tr:  (13098, 10, 23)   y_tr:  (13098, 23)
X_val: (1455, 10, 23)  y_val: (1455, 23)
X_te:  (1618, 10, 23)   y_te:  (1618, 23)

## Arquitecturas implementadas

La función `build_model` construye el modelo según el argumento `arch`:

| `arch`     | Capas                                      |
|------------|--------------------------------------------|
| `lstm`     | Input → LSTM × n_layers → Dense            |
| `gru`      | Input → GRU × n_layers → Dense             |
| `cnn_lstm` | Input → Conv1D → LSTM × n_layers → Dense   |
| `cnn_gru`  | Input → Conv1D → GRU × n_layers → Dense    |

| `cnn_lstm_mlp` | Input → Conv1D → LSTM × n_layers → MLP → Dense |

| `cnn_gru_mlp`  | Input → Conv1D → GRU × n_layers → MLP → Dense  |

| `cnn_mlp`      | Input → Conv1D → GlobalAveragePooling1D → MLP × n_layers → Dense |

El `kernel_size` de Conv1D se fija a 3 (válido para input_w=10 con `padding="same"`).

In [3]:
KERNEL_SIZE = 3


def add_mlp_head(model, n_layers, units, dropout):
    for i in range(n_layers):
        layer_units = units if i == 0 else max(units // 2, 16)
        model.add(Dense(layer_units, activation="relu"))
        if dropout > 0:
            model.add(Dropout(dropout))


def build_model(arch, n_layers, units, dropout, lr=1e-3):
    keras.utils.set_random_seed(RANDOM_SEED)
    m = Sequential()
    m.add(Input(shape=(X_tr.shape[1], X_tr.shape[2])))

    if arch == "lstm":
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "gru":
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_lstm":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_gru":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_lstm_mlp":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))
        add_mlp_head(m, 2, units, dropout)

    elif arch == "cnn_gru_mlp":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))
        add_mlp_head(m, 2, units, dropout)

    elif arch == "cnn_mlp":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        m.add(GlobalAveragePooling1D())
        add_mlp_head(m, n_layers, units, dropout)

    else:
        raise ValueError(f"Arquitectura no soportada: {arch}")

    m.add(Dense(y_tr.shape[1]))
    m.compile(loss="mean_absolute_error", optimizer=Adam(learning_rate=lr))
    return m



def fit_eval(model, batch_size=128, epochs=200, patience=10, verbose=0):
    es = EarlyStopping(monitor="val_loss", patience=patience, restore_best_weights=True)
    h = model.fit(
        X_tr, y_tr,
        validation_data=(X_val, y_val),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=[es],
        verbose=verbose,
    )
    mae_tr  = mean_absolute_error(y_tr,  model.predict(X_tr,  verbose=0))
    mae_val = mean_absolute_error(y_val, model.predict(X_val, verbose=0))
    mae_te  = mean_absolute_error(y_te,  model.predict(X_te,  verbose=0))
    return mae_tr, mae_val, mae_te, h

## Etapa 1 — Búsqueda de arquitectura

Grid: `arch` × `n_layers` × `units` × `dropout` (learning rate y batch size fijos).

Criterio de selección: **MAE de validación mínimo**.

In [4]:
arch_grid = list(itertools.product(
    ["lstm", "gru", "cnn_lstm", "cnn_gru", "cnn_lstm_mlp", "cnn_gru_mlp", "cnn_mlp"],
    [1, 2],
    [32, 64, 128],
    [0.0, 0.2],
))

results_arch = []
batch_size_arch = 128

for arch, nl, u, dr in arch_grid:
    run_name = f"{EXPERIMENT_NAME}_arch_{arch}_layers{nl}_units{u}_drop{dr}"
    existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing.empty:
        mlflow.delete_run(existing.iloc[0].run_id)

    with mlflow.start_run(run_name=run_name):
        model = build_model(arch, nl, u, dr, lr=1e-3)
        mae_tr, mae_val, mae_te, h = fit_eval(model, batch_size=batch_size_arch)

        for epoch, (tl, vl) in enumerate(zip(h.history["loss"], h.history["val_loss"])):
            mlflow.log_metric("train_loss", tl, step=epoch)
            mlflow.log_metric("val_loss",   vl, step=epoch)

        fig = plot_training_curve(h)
        mlflow.log_figure(fig, "plots/loss_curve.png")
        plt.close(fig)

        mlflow.log_param("arch",               arch)
        mlflow.log_param("n_layers",           nl)
        mlflow.log_param("units",              u)
        mlflow.log_param("dropout",            dr)
        mlflow.log_param("kernel_size",        KERNEL_SIZE)
        mlflow.log_param("learning_rate",      1e-3)
        mlflow.log_param("batch_size",         batch_size_arch)
        mlflow.log_param("input_window_size",  INPUT_W)
        mlflow.log_param("output_window_size", OUTPUT_W)
        mlflow.log_param("n_params",           model.count_params())
        mlflow.log_param("epochs",             len(h.history["loss"]))

        mlflow.log_metric("train_mae", mae_tr)
        mlflow.log_metric("val_mae",   mae_val)
        mlflow.log_metric("test_mae",  mae_te)

        mlflow.keras.log_model(model, name="model")

        results_arch.append({
            "arch": arch, "n_layers": nl, "units": u, "dropout": dr,
            "MAE_train": mae_tr, "MAE_val": mae_val, "MAE_test": mae_te,
            "epochs": len(h.history["loss"]), "n_params": model.count_params(),
        })
        print(f"arch={arch:<10} layers={nl} units={u:>3} dropout={dr}  ->  val={mae_val:.6f} | train={mae_tr:.6f} | test={mae_te:.6f}")

results_arch_df = pd.DataFrame(results_arch).sort_values("MAE_val").reset_index(drop=True)

2026/05/10 20:06:41 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 32 dropout=0.0  ->  val=0.004218 | train=0.005497 | test=0.005657

2026/05/10 20:06:52 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 32 dropout=0.2  ->  val=0.004209 | train=0.005475 | test=0.005628

2026/05/10 20:07:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 64 dropout=0.0  ->  val=0.004237 | train=0.005476 | test=0.005640

2026/05/10 20:07:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 64 dropout=0.2  ->  val=0.004226 | train=0.005500 | test=0.005649

2026/05/10 20:07:35 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units=128 dropout=0.0  ->  val=0.004233 | train=0.005452 | test=0.005648

2026/05/10 20:07:52 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units=128 dropout=0.2  ->  val=0.004217 | train=0.005476 | test=0.005643

2026/05/10 20:08:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 32 dropout=0.0  ->  val=0.004200 | train=0.005465 | test=0.005628

2026/05/10 20:08:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 32 dropout=0.2  ->  val=0.004199 | train=0.005485 | test=0.005626

2026/05/10 20:08:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 64 dropout=0.0  ->  val=0.004220 | train=0.005469 | test=0.005635

2026/05/10 20:09:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 64 dropout=0.2  ->  val=0.004212 | train=0.005466 | test=0.005630

2026/05/10 20:09:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units=128 dropout=0.0  ->  val=0.004232 | train=0.005460 | test=0.005648

2026/05/10 20:10:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units=128 dropout=0.2  ->  val=0.004204 | train=0.005456 | test=0.005635

2026/05/10 20:11:12 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 32 dropout=0.0  ->  val=0.004214 | train=0.005450 | test=0.005639

2026/05/10 20:11:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 32 dropout=0.2  ->  val=0.004205 | train=0.005463 | test=0.005631

2026/05/10 20:11:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 64 dropout=0.0  ->  val=0.004235 | train=0.005478 | test=0.005640

2026/05/10 20:11:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 64 dropout=0.2  ->  val=0.004222 | train=0.005488 | test=0.005650

2026/05/10 20:12:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units=128 dropout=0.0  ->  val=0.004244 | train=0.005456 | test=0.005660

2026/05/10 20:12:47 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units=128 dropout=0.2  ->  val=0.004242 | train=0.005485 | test=0.005649

2026/05/10 20:13:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 32 dropout=0.0  ->  val=0.004229 | train=0.005492 | test=0.005649

2026/05/10 20:13:22 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 32 dropout=0.2  ->  val=0.004197 | train=0.005475 | test=0.005620

2026/05/10 20:13:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 64 dropout=0.0  ->  val=0.004210 | train=0.005439 | test=0.005639

2026/05/10 20:14:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 64 dropout=0.2  ->  val=0.004190 | train=0.005455 | test=0.005609

2026/05/10 20:15:00 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units=128 dropout=0.0  ->  val=0.004224 | train=0.005465 | test=0.005637

2026/05/10 20:15:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units=128 dropout=0.2  ->  val=0.004224 | train=0.005480 | test=0.005644

2026/05/10 20:15:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.0  ->  val=0.004172 | train=0.005445 | test=0.005620

2026/05/10 20:16:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.2  ->  val=0.004176 | train=0.005382 | test=0.005624

2026/05/10 20:16:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.0  ->  val=0.004180 | train=0.005449 | test=0.005630

2026/05/10 20:16:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.2  ->  val=0.004179 | train=0.005240 | test=0.005674

2026/05/10 20:17:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.0  ->  val=0.004178 | train=0.005456 | test=0.005620

2026/05/10 20:17:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.2  ->  val=0.004192 | train=0.005477 | test=0.005623

2026/05/10 20:17:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.0  ->  val=0.004210 | train=0.005482 | test=0.005637

2026/05/10 20:18:00 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.2  ->  val=0.004176 | train=0.005347 | test=0.005614

2026/05/10 20:18:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.0  ->  val=0.004225 | train=0.005501 | test=0.005633

2026/05/10 20:18:52 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.2  ->  val=0.004190 | train=0.005444 | test=0.005614

2026/05/10 20:19:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.0  ->  val=0.004194 | train=0.005471 | test=0.005616

2026/05/10 20:20:35 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.2  ->  val=0.004191 | train=0.005076 | test=0.005692

2026/05/10 20:20:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.0  ->  val=0.004185 | train=0.005456 | test=0.005624

2026/05/10 20:21:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.2  ->  val=0.004165 | train=0.005336 | test=0.005643

2026/05/10 20:21:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.0  ->  val=0.004206 | train=0.005403 | test=0.005671

2026/05/10 20:21:40 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.2  ->  val=0.004185 | train=0.005305 | test=0.005667

2026/05/10 20:22:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.0  ->  val=0.004213 | train=0.005437 | test=0.005655

2026/05/10 20:22:33 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.2  ->  val=0.004201 | train=0.005465 | test=0.005630

2026/05/10 20:22:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.0  ->  val=0.004184 | train=0.005380 | test=0.005640

2026/05/10 20:23:15 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.2  ->  val=0.004166 | train=0.005273 | test=0.005677

2026/05/10 20:23:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.0  ->  val=0.004210 | train=0.005478 | test=0.005643

2026/05/10 20:24:08 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.2  ->  val=0.004199 | train=0.005288 | test=0.005676

2026/05/10 20:24:57 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.0  ->  val=0.004245 | train=0.005435 | test=0.005655

2026/05/10 20:25:52 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.2  ->  val=0.004221 | train=0.005362 | test=0.005627

2026/05/10 20:26:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.0  ->  val=0.004169 | train=0.005448 | test=0.005602

2026/05/10 20:26:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.2  ->  val=0.004181 | train=0.005492 | test=0.005600

2026/05/10 20:26:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.0  ->  val=0.004182 | train=0.005482 | test=0.005612

2026/05/10 20:27:00 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.2  ->  val=0.004184 | train=0.005494 | test=0.005602

2026/05/10 20:27:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.0  ->  val=0.004170 | train=0.005421 | test=0.005610

2026/05/10 20:28:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.2  ->  val=0.004183 | train=0.005493 | test=0.005601

2026/05/10 20:28:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.0  ->  val=0.004178 | train=0.005492 | test=0.005599

2026/05/10 20:28:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.2  ->  val=0.004182 | train=0.005493 | test=0.005601

2026/05/10 20:29:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.0  ->  val=0.004182 | train=0.005494 | test=0.005601

2026/05/10 20:29:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.2  ->  val=0.004183 | train=0.005493 | test=0.005601

2026/05/10 20:30:29 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.0  ->  val=0.004178 | train=0.005490 | test=0.005601

2026/05/10 20:31:47 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.2  ->  val=0.004181 | train=0.005493 | test=0.005600

2026/05/10 20:32:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.0  ->  val=0.004177 | train=0.005489 | test=0.005597

2026/05/10 20:32:18 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.2  ->  val=0.004181 | train=0.005494 | test=0.005601

2026/05/10 20:32:35 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.0  ->  val=0.004172 | train=0.005413 | test=0.005618

2026/05/10 20:32:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.2  ->  val=0.004183 | train=0.005491 | test=0.005603

2026/05/10 20:33:14 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.0  ->  val=0.004191 | train=0.005492 | test=0.005605

2026/05/10 20:33:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.2  ->  val=0.004182 | train=0.005493 | test=0.005601

2026/05/10 20:34:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.0  ->  val=0.004182 | train=0.005488 | test=0.005602

2026/05/10 20:34:22 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.2  ->  val=0.004182 | train=0.005494 | test=0.005601

2026/05/10 20:34:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.0  ->  val=0.004172 | train=0.005492 | test=0.005601

2026/05/10 20:35:14 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.2  ->  val=0.004183 | train=0.005493 | test=0.005601

2026/05/10 20:36:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.0  ->  val=0.004166 | train=0.005468 | test=0.005599

2026/05/10 20:37:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.2  ->  val=0.004181 | train=0.005491 | test=0.005599

2026/05/10 20:37:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.0  ->  val=0.004175 | train=0.005493 | test=0.005608

2026/05/10 20:37:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.2  ->  val=0.004164 | train=0.005488 | test=0.005599

2026/05/10 20:37:25 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.0  ->  val=0.004173 | train=0.005398 | test=0.005598

2026/05/10 20:37:34 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.2  ->  val=0.004139 | train=0.005377 | test=0.005604

2026/05/10 20:37:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.0  ->  val=0.004165 | train=0.005443 | test=0.005617

2026/05/10 20:37:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.2  ->  val=0.004147 | train=0.005332 | test=0.005609

2026/05/10 20:38:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.0  ->  val=0.004162 | train=0.005449 | test=0.005607

2026/05/10 20:38:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.2  ->  val=0.004176 | train=0.005493 | test=0.005603

2026/05/10 20:38:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.0  ->  val=0.004176 | train=0.005491 | test=0.005602

2026/05/10 20:38:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.2  ->  val=0.004163 | train=0.005448 | test=0.005565

2026/05/10 20:38:37 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.0  ->  val=0.004165 | train=0.005465 | test=0.005615

2026/05/10 20:38:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.2  ->  val=0.004181 | train=0.005492 | test=0.005599

### Resultados — Etapa 1 (top 10)

In [5]:
results_arch_df.head(10)

,arch,n_layers,units,dropout,MAE_train,MAE_val,MAE_test,epochs,n_params
0,cnn_mlp,1,64,0.2,0.005377,0.004139,0.005604,21,10135
1,cnn_mlp,1,128,0.2,0.005332,0.004147,0.005609,21,28439
2,cnn_mlp,2,32,0.0,0.005449,0.004162,0.005607,29,4215
3,cnn_mlp,2,64,0.2,0.005448,0.004163,0.005565,30,11479
4,cnn_mlp,1,32,0.2,0.005488,0.004164,0.005599,11,4055
5,cnn_gru,1,32,0.2,0.005336,0.004165,0.005643,22,9335
6,cnn_mlp,1,128,0.0,0.005443,0.004165,0.005617,13,28439
7,cnn_mlp,2,128,0.0,0.005465,0.004165,0.005615,17,35223
8,cnn_gru_mlp,2,128,0.0,0.005468,0.004166,0.005599,14,233367
9,cnn_gru,2,32,0.2,0.005273,0.004166,0.005677,22,15671

## Etapa 2 — Hiperparámetros de entrenamiento

Se fija la arquitectura ganadora de la Etapa 1 y se busca sobre `learning_rate` × `batch_size`.

Criterio de selección: **MAE de validación mínimo**.

In [6]:
best_arch = results_arch_df.iloc[0]
print(f"Mejor arquitectura: arch={best_arch.arch}  n_layers={int(best_arch.n_layers)}  units={int(best_arch.units)}  dropout={best_arch.dropout}")
print(f"  MAE val = {best_arch.MAE_val:.6f}")

train_grid = list(itertools.product([1e-2, 1e-3, 1e-4], [64, 128, 256]))

results_train = []
for lr, bs in train_grid:
    run_name = f"{EXPERIMENT_NAME}_train_{best_arch.arch}_lr{lr:.0e}_batch{bs}"
    existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing.empty:
        mlflow.delete_run(existing.iloc[0].run_id)

    with mlflow.start_run(run_name=run_name):
        model = build_model(
            best_arch.arch, int(best_arch.n_layers), int(best_arch.units),
            float(best_arch.dropout), lr=lr,
        )
        mae_tr, mae_val, mae_te, h = fit_eval(model, batch_size=bs)

        for epoch, (tl, vl) in enumerate(zip(h.history["loss"], h.history["val_loss"])):
            mlflow.log_metric("train_loss", tl, step=epoch)
            mlflow.log_metric("val_loss",   vl, step=epoch)

        fig = plot_training_curve(h)
        mlflow.log_figure(fig, "plots/loss_curve.png")
        plt.close(fig)

        mlflow.log_param("arch",               best_arch.arch)
        mlflow.log_param("n_layers",           int(best_arch.n_layers))
        mlflow.log_param("units",              int(best_arch.units))
        mlflow.log_param("dropout",            float(best_arch.dropout))
        mlflow.log_param("kernel_size",        KERNEL_SIZE)
        mlflow.log_param("learning_rate",      lr)
        mlflow.log_param("batch_size",         bs)
        mlflow.log_param("input_window_size",  INPUT_W)
        mlflow.log_param("output_window_size", OUTPUT_W)
        mlflow.log_param("n_params",           model.count_params())
        mlflow.log_param("epochs",             len(h.history["loss"]))

        mlflow.log_metric("train_mae", mae_tr)
        mlflow.log_metric("val_mae",   mae_val)
        mlflow.log_metric("test_mae",  mae_te)

        mlflow.keras.log_model(model, name="model")

        results_train.append({
            "learning_rate": lr, "batch_size": bs,
            "MAE_train": mae_tr, "MAE_val": mae_val, "MAE_test": mae_te,
            "epochs": len(h.history["loss"]),
        })
        print(f"lr={lr:.0e} batch={bs:>3}  ->  val={mae_val:.6f} | train={mae_tr:.6f} | test={mae_te:.6f}")

results_train_df = pd.DataFrame(results_train).sort_values("MAE_val").reset_index(drop=True)

Mejor arquitectura: arch=cnn_mlp  n_layers=1  units=64  dropout=0.2
  MAE val = 0.004139

2026/05/10 20:38:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch= 64  ->  val=0.004269 | train=0.005590 | test=0.005688

2026/05/10 20:39:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch=128  ->  val=0.004194 | train=0.005517 | test=0.005620

2026/05/10 20:39:11 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch=256  ->  val=0.004262 | train=0.005566 | test=0.005657

2026/05/10 20:39:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch= 64  ->  val=0.004165 | train=0.005454 | test=0.005600

2026/05/10 20:39:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch=128  ->  val=0.004139 | train=0.005377 | test=0.005604

2026/05/10 20:39:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch=256  ->  val=0.004146 | train=0.005464 | test=0.005594

2026/05/10 20:39:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch= 64  ->  val=0.004142 | train=0.005457 | test=0.005591

2026/05/10 20:39:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch=128  ->  val=0.004142 | train=0.005461 | test=0.005590

2026/05/10 20:40:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch=256  ->  val=0.004140 | train=0.005444 | test=0.005593

In [7]:
results_train_df

   learning_rate  batch_size  MAE_train   MAE_val  MAE_test  epochs
0         0.0010         128   0.005377  0.004139  0.005604      21
1         0.0001         256   0.005444  0.004140  0.005593      35
2         0.0001         128   0.005461  0.004142  0.005590      21
3         0.0001          64   0.005457  0.004142  0.005591      18
4         0.0010         256   0.005464  0.004146  0.005594      17
5         0.0010          64   0.005454  0.004165  0.005600      17
6         0.0100         128   0.005517  0.004194  0.005620      13
7         0.0100         256   0.005566  0.004262  0.005657      17
8         0.0100          64   0.005590  0.004269  0.005688      16

## Modelo final y comparación con benchmarks

Se reentrena el modelo ganador con la configuración completa y se compara con la regresión lineal.

In [8]:
from util import load_benchmark

best_train = results_train_df.iloc[0]
print("Configuración ganadora:")
print(f"  arch          = {best_arch.arch}")
print(f"  n_layers      = {int(best_arch.n_layers)}")
print(f"  units         = {int(best_arch.units)}")
print(f"  dropout       = {float(best_arch.dropout)}")
print(f"  learning_rate = {best_train.learning_rate:.0e}")
print(f"  batch_size    = {int(best_train.batch_size)}")

final_model = build_model(
    best_arch.arch, int(best_arch.n_layers), int(best_arch.units),
    float(best_arch.dropout), lr=float(best_train.learning_rate),
)
mae_tr_f, mae_val_f, mae_te_f, hist_f = fit_eval(
    final_model, batch_size=int(best_train.batch_size), patience=20,
)

linreg_bench = load_benchmark("lr_benchmark")
linreg_row   = linreg_bench[
    (linreg_bench.input_window == INPUT_W) & (linreg_bench.output_window == OUTPUT_W)
].iloc[0]

run_name_final = f"{EXPERIMENT_NAME}_final"
existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name_final}"')
if not existing.empty:
    mlflow.delete_run(existing.iloc[0].run_id)

with mlflow.start_run(run_name=run_name_final):
    for epoch, (tl, vl) in enumerate(zip(hist_f.history["loss"], hist_f.history["val_loss"])):
        mlflow.log_metric("train_loss", tl, step=epoch)
        mlflow.log_metric("val_loss",   vl, step=epoch)

    fig_f = plot_training_curve(hist_f)
    mlflow.log_figure(fig_f, "plots/loss_curve.png")
    plt.close(fig_f)

    mlflow.log_param("arch",               best_arch.arch)
    mlflow.log_param("n_layers",           int(best_arch.n_layers))
    mlflow.log_param("units",              int(best_arch.units))
    mlflow.log_param("dropout",            float(best_arch.dropout))
    mlflow.log_param("kernel_size",        KERNEL_SIZE)
    mlflow.log_param("learning_rate",      float(best_train.learning_rate))
    mlflow.log_param("batch_size",         int(best_train.batch_size))
    mlflow.log_param("input_window_size",  INPUT_W)
    mlflow.log_param("output_window_size", OUTPUT_W)
    mlflow.log_param("n_params",           final_model.count_params())
    mlflow.log_param("epochs",             len(hist_f.history["loss"]))
    mlflow.log_metric("train_mae",         mae_tr_f)
    mlflow.log_metric("val_mae",           mae_val_f)
    mlflow.log_metric("test_mae",          mae_te_f)
    mlflow.keras.log_model(final_model, name="model")

summary = pd.DataFrame([
    {"modelo": "Regresión lineal",                 "MAE_train": linreg_row.MAE_train, "MAE_test": linreg_row.MAE_test},
    {"modelo": f"Mejor mixto ({best_arch.arch})",  "MAE_train": mae_tr_f,             "MAE_test": mae_te_f},
])
summary["Δ vs lin.reg. (test)"] = summary["MAE_test"] - linreg_row.MAE_test
display(summary)

Configuración ganadora:
  arch          = cnn_mlp
  n_layers      = 1
  units         = 64
  dropout       = 0.2
  learning_rate = 1e-03
  batch_size    = 128

2026/05/10 20:40:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

                  modelo  MAE_train  MAE_test  Δ vs lin.reg. (test)
0       Regresión lineal   0.005418  0.005698              0.000000
1  Mejor mixto (cnn_mlp)   0.005377  0.005604             -0.000094

## Top-10 configuraciones por etapa

In [9]:
fig, axes = plt.subplots(1, 2, figsize=(16, 5))

def plot_top(ax, df, label_cols, title, top=10):
    top_df = df.head(top).iloc[::-1]
    labels = top_df[label_cols].astype(str).agg(" · ".join, axis=1)
    ypos = np.arange(len(top_df))
    ax.barh(ypos - 0.2, top_df["MAE_val"],   height=0.4, label="MAE val",   color="steelblue")
    ax.barh(ypos + 0.2, top_df["MAE_train"], height=0.4, label="MAE train", color="lightgray")
    ax.set_yticks(ypos)
    ax.set_yticklabels(labels, fontsize=9)
    ax.set_xlabel("MAE")
    ax.set_title(title)
    ax.legend(loc="lower right")
    ax.grid(True, axis="x", alpha=0.3)

plot_top(axes[0], results_arch_df,  ["arch", "n_layers", "units", "dropout"],
         "Etapa 1 — arquitectura (top 10)")
plot_top(axes[1], results_train_df, ["learning_rate", "batch_size"],
         "Etapa 2 — entrenamiento (top 9)")

plt.tight_layout()
plt.show()

/var/folders/py/c5_xfbqn469g5_844mv32gt40000gn/T/ipykernel_49748/3018486118.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()