# Modelos Mixtos — Combinaciones Conv1D, LSTM, GRU y MLP

Este notebook explora combinaciones de capas **convolucionales** (Conv1D), **recurrentes** (LSTM, GRU) y **densas** (MLP) para la configuración fija:

- **Ventana de entrada:** 5 días
- **Ventana de salida:** 1 día

Arquitecturas evaluadas:
- `lstm` — LSTM apiladas
- `gru` — GRU apiladas
- `cnn_lstm` — Conv1D → LSTM
- `cnn_gru` — Conv1D → GRU

- `cnn_lstm_mlp` — Conv1D → LSTM → MLP

- `cnn_gru_mlp` — Conv1D → GRU → MLP

- `cnn_mlp` — Conv1D → MLP

La búsqueda se realiza en dos etapas:
1. **Etapa 1 — Arquitectura**: tipo de red × n_layers × units × dropout (84 combinaciones)
2. **Etapa 2 — Entrenamiento**: learning rate × batch size con la mejor arquitectura de la Etapa 1 (9 combinaciones)

In [1]:
import sys
import itertools
import mlflow
from pathlib import Path

# Busca util.py subiendo niveles desde el directorio actual
_here = Path.cwd()
PROJECT_ROOT = next(
    p for p in [_here, _here.parent, _here.parent.parent, _here.parent.parent.parent]
    if (p / 'util.py').exists()
)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

mlflow.set_tracking_uri(f"sqlite:///{PROJECT_ROOT / 'model' / 'mlflow.db'}")

EXPERIMENT_NAME = "Modelos_Mixtos_input5_output1"
mlflow.set_experiment(EXPERIMENT_NAME)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import keras
from keras.models import Sequential
from keras.layers import LSTM, GRU, Dense, Input, Conv1D, GlobalAveragePooling1D, Dropout
from keras.callbacks import EarlyStopping
from keras.optimizers import Adam

from sklearn.metrics import mean_absolute_error

from util import get_train_test, RANDOM_SEED, plot_training_curve

np.random.seed(RANDOM_SEED)
keras.utils.set_random_seed(RANDOM_SEED)

## Carga de datos

In [2]:
INPUT_W  = 5
OUTPUT_W = 1

def load_seq_data(input_window_size, output_window_size):
    d = get_train_test(input_window_size=input_window_size, output_window_size=output_window_size)
    X_train, X_test = d.X_train, d.X_test
    y_train, y_test = d.y_train, d.y_test
    val_size         = int(0.10 * X_train.shape[0])
    X_val, y_val     = X_train[-val_size:], y_train[-val_size:]
    X_train, y_train = X_train[:-val_size], y_train[:-val_size]
    return X_train, y_train, X_val, y_val, X_test, y_test

X_tr, y_tr, X_val, y_val, X_te, y_te = load_seq_data(INPUT_W, OUTPUT_W)

print(f"X_tr:  {X_tr.shape}   y_tr:  {y_tr.shape}")
print(f"X_val: {X_val.shape}  y_val: {y_val.shape}")
print(f"X_te:  {X_te.shape}   y_te:  {y_te.shape}")

X_tr:  (13106, 5, 23)   y_tr:  (13106, 23)
X_val: (1456, 5, 23)  y_val: (1456, 23)
X_te:  (1618, 5, 23)   y_te:  (1618, 23)

## Arquitecturas implementadas

La función `build_model` construye el modelo según el argumento `arch`:

| `arch`     | Capas                                      |
|------------|--------------------------------------------|
| `lstm`     | Input → LSTM × n_layers → Dense            |
| `gru`      | Input → GRU × n_layers → Dense             |
| `cnn_lstm` | Input → Conv1D → LSTM × n_layers → Dense   |
| `cnn_gru`  | Input → Conv1D → GRU × n_layers → Dense    |

| `cnn_lstm_mlp` | Input → Conv1D → LSTM × n_layers → MLP → Dense |

| `cnn_gru_mlp`  | Input → Conv1D → GRU × n_layers → MLP → Dense  |

| `cnn_mlp`      | Input → Conv1D → GlobalAveragePooling1D → MLP × n_layers → Dense |

El `kernel_size` de Conv1D se fija a 3 (válido para input_w=5 con `padding="same"`).

In [3]:
KERNEL_SIZE = 3


def add_mlp_head(model, n_layers, units, dropout):
    for i in range(n_layers):
        layer_units = units if i == 0 else max(units // 2, 16)
        model.add(Dense(layer_units, activation="relu"))
        if dropout > 0:
            model.add(Dropout(dropout))


def build_model(arch, n_layers, units, dropout, lr=1e-3):
    keras.utils.set_random_seed(RANDOM_SEED)
    m = Sequential()
    m.add(Input(shape=(X_tr.shape[1], X_tr.shape[2])))

    if arch == "lstm":
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "gru":
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_lstm":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_gru":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_lstm_mlp":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))
        add_mlp_head(m, 2, units, dropout)

    elif arch == "cnn_gru_mlp":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))
        add_mlp_head(m, 2, units, dropout)

    elif arch == "cnn_mlp":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        m.add(GlobalAveragePooling1D())
        add_mlp_head(m, n_layers, units, dropout)

    else:
        raise ValueError(f"Arquitectura no soportada: {arch}")

    m.add(Dense(y_tr.shape[1]))
    m.compile(loss="mean_absolute_error", optimizer=Adam(learning_rate=lr))
    return m



def fit_eval(model, batch_size=128, epochs=200, patience=10, verbose=0):
    es = EarlyStopping(monitor="val_loss", patience=patience, restore_best_weights=True)
    h = model.fit(
        X_tr, y_tr,
        validation_data=(X_val, y_val),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=[es],
        verbose=verbose,
    )
    mae_tr  = mean_absolute_error(y_tr,  model.predict(X_tr,  verbose=0))
    mae_val = mean_absolute_error(y_val, model.predict(X_val, verbose=0))
    mae_te  = mean_absolute_error(y_te,  model.predict(X_te,  verbose=0))
    return mae_tr, mae_val, mae_te, h

## Etapa 1 — Búsqueda de arquitectura

Grid: `arch` × `n_layers` × `units` × `dropout` (learning rate y batch size fijos).

Criterio de selección: **MAE de validación mínimo**.

In [4]:
arch_grid = list(itertools.product(
    ["lstm", "gru", "cnn_lstm", "cnn_gru", "cnn_lstm_mlp", "cnn_gru_mlp", "cnn_mlp"],
    [1, 2],
    [32, 64, 128],
    [0.0, 0.2],
))

results_arch = []
batch_size_arch = 128

for arch, nl, u, dr in arch_grid:
    run_name = f"{EXPERIMENT_NAME}_arch_{arch}_layers{nl}_units{u}_drop{dr}"
    existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing.empty:
        mlflow.delete_run(existing.iloc[0].run_id)

    with mlflow.start_run(run_name=run_name):
        model = build_model(arch, nl, u, dr, lr=1e-3)
        mae_tr, mae_val, mae_te, h = fit_eval(model, batch_size=batch_size_arch)

        for epoch, (tl, vl) in enumerate(zip(h.history["loss"], h.history["val_loss"])):
            mlflow.log_metric("train_loss", tl, step=epoch)
            mlflow.log_metric("val_loss",   vl, step=epoch)

        fig = plot_training_curve(h)
        mlflow.log_figure(fig, "plots/loss_curve.png")
        plt.close(fig)

        mlflow.log_param("arch",               arch)
        mlflow.log_param("n_layers",           nl)
        mlflow.log_param("units",              u)
        mlflow.log_param("dropout",            dr)
        mlflow.log_param("kernel_size",        KERNEL_SIZE)
        mlflow.log_param("learning_rate",      1e-3)
        mlflow.log_param("batch_size",         batch_size_arch)
        mlflow.log_param("input_window_size",  INPUT_W)
        mlflow.log_param("output_window_size", OUTPUT_W)
        mlflow.log_param("n_params",           model.count_params())
        mlflow.log_param("epochs",             len(h.history["loss"]))

        mlflow.log_metric("train_mae", mae_tr)
        mlflow.log_metric("val_mae",   mae_val)
        mlflow.log_metric("test_mae",  mae_te)

        mlflow.keras.log_model(model, name="model")

        results_arch.append({
            "arch": arch, "n_layers": nl, "units": u, "dropout": dr,
            "MAE_train": mae_tr, "MAE_val": mae_val, "MAE_test": mae_te,
            "epochs": len(h.history["loss"]), "n_params": model.count_params(),
        })
        print(f"arch={arch:<10} layers={nl} units={u:>3} dropout={dr}  ->  val={mae_val:.6f} | train={mae_tr:.6f} | test={mae_te:.6f}")

results_arch_df = pd.DataFrame(results_arch).sort_values("MAE_val").reset_index(drop=True)

2026/05/10 17:58:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 32 dropout=0.0  ->  val=0.009065 | train=0.011833 | test=0.012258

2026/05/10 17:58:25 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 32 dropout=0.2  ->  val=0.009058 | train=0.011845 | test=0.012251

2026/05/10 17:58:37 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 64 dropout=0.0  ->  val=0.009071 | train=0.011816 | test=0.012278

2026/05/10 17:58:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 64 dropout=0.2  ->  val=0.009061 | train=0.011816 | test=0.012270

2026/05/10 17:59:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units=128 dropout=0.0  ->  val=0.009082 | train=0.011826 | test=0.012289

2026/05/10 17:59:23 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units=128 dropout=0.2  ->  val=0.009070 | train=0.011815 | test=0.012275

2026/05/10 17:59:35 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 32 dropout=0.0  ->  val=0.009050 | train=0.011847 | test=0.012242

2026/05/10 17:59:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 32 dropout=0.2  ->  val=0.009044 | train=0.011857 | test=0.012237

2026/05/10 18:00:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 64 dropout=0.0  ->  val=0.009054 | train=0.011845 | test=0.012246

2026/05/10 18:00:22 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 64 dropout=0.2  ->  val=0.009052 | train=0.011838 | test=0.012244

2026/05/10 18:00:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units=128 dropout=0.0  ->  val=0.009059 | train=0.011836 | test=0.012252

2026/05/10 18:01:27 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units=128 dropout=0.2  ->  val=0.009046 | train=0.011825 | test=0.012253

2026/05/10 18:01:40 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 32 dropout=0.0  ->  val=0.009078 | train=0.011814 | test=0.012286

2026/05/10 18:01:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 32 dropout=0.2  ->  val=0.009068 | train=0.011830 | test=0.012275

2026/05/10 18:02:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 64 dropout=0.0  ->  val=0.009088 | train=0.011827 | test=0.012312

2026/05/10 18:02:18 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 64 dropout=0.2  ->  val=0.009070 | train=0.011831 | test=0.012287

2026/05/10 18:02:47 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units=128 dropout=0.0  ->  val=0.009085 | train=0.011793 | test=0.012311

2026/05/10 18:03:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units=128 dropout=0.2  ->  val=0.009079 | train=0.011825 | test=0.012294

2026/05/10 18:03:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 32 dropout=0.0  ->  val=0.009069 | train=0.011840 | test=0.012265

2026/05/10 18:03:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 32 dropout=0.2  ->  val=0.009053 | train=0.011817 | test=0.012258

2026/05/10 18:04:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 64 dropout=0.0  ->  val=0.009075 | train=0.011812 | test=0.012286

2026/05/10 18:04:29 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 64 dropout=0.2  ->  val=0.009056 | train=0.011825 | test=0.012264

2026/05/10 18:05:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units=128 dropout=0.0  ->  val=0.009071 | train=0.011812 | test=0.012287

2026/05/10 18:06:00 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units=128 dropout=0.2  ->  val=0.009056 | train=0.011822 | test=0.012270

2026/05/10 18:06:10 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.0  ->  val=0.009060 | train=0.011861 | test=0.012247

2026/05/10 18:06:20 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.2  ->  val=0.009050 | train=0.011842 | test=0.012236

2026/05/10 18:06:32 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.0  ->  val=0.009077 | train=0.011865 | test=0.012273

2026/05/10 18:06:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.2  ->  val=0.009066 | train=0.011858 | test=0.012258

2026/05/10 18:07:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.0  ->  val=0.009073 | train=0.011868 | test=0.012280

2026/05/10 18:07:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.2  ->  val=0.009054 | train=0.011856 | test=0.012255

2026/05/10 18:07:29 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.0  ->  val=0.009050 | train=0.011867 | test=0.012241

2026/05/10 18:07:41 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.2  ->  val=0.009048 | train=0.011866 | test=0.012242

2026/05/10 18:07:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.0  ->  val=0.009070 | train=0.011887 | test=0.012265

2026/05/10 18:08:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.2  ->  val=0.009055 | train=0.011869 | test=0.012242

2026/05/10 18:08:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.0  ->  val=0.009059 | train=0.011874 | test=0.012246

2026/05/10 18:09:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.2  ->  val=0.009061 | train=0.011862 | test=0.012251

2026/05/10 18:09:15 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.0  ->  val=0.009077 | train=0.011917 | test=0.012276

2026/05/10 18:09:27 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.2  ->  val=0.009058 | train=0.011845 | test=0.012242

2026/05/10 18:09:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.0  ->  val=0.009100 | train=0.011846 | test=0.012297

2026/05/10 18:09:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.2  ->  val=0.009080 | train=0.011856 | test=0.012270

2026/05/10 18:10:10 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.0  ->  val=0.009155 | train=0.011907 | test=0.012313

2026/05/10 18:10:33 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.2  ->  val=0.009120 | train=0.011786 | test=0.012242

2026/05/10 18:10:47 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.0  ->  val=0.009073 | train=0.011856 | test=0.012265

2026/05/10 18:11:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.2  ->  val=0.009061 | train=0.011874 | test=0.012256

2026/05/10 18:11:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.0  ->  val=0.009081 | train=0.011859 | test=0.012273

2026/05/10 18:11:34 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.2  ->  val=0.009066 | train=0.011882 | test=0.012263

2026/05/10 18:12:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.0  ->  val=0.009107 | train=0.011889 | test=0.012288

2026/05/10 18:12:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.2  ->  val=0.009084 | train=0.011890 | test=0.012274

2026/05/10 18:12:37 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.0  ->  val=0.009040 | train=0.011846 | test=0.012239

2026/05/10 18:12:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.2  ->  val=0.009038 | train=0.011847 | test=0.012235

2026/05/10 18:13:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.0  ->  val=0.009041 | train=0.011844 | test=0.012229

2026/05/10 18:13:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.2  ->  val=0.009036 | train=0.011847 | test=0.012233

2026/05/10 18:13:32 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.0  ->  val=0.009043 | train=0.011857 | test=0.012233

2026/05/10 18:13:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.2  ->  val=0.009037 | train=0.011849 | test=0.012235

2026/05/10 18:14:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.0  ->  val=0.009040 | train=0.011845 | test=0.012237

2026/05/10 18:14:33 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.2  ->  val=0.009037 | train=0.011843 | test=0.012234

2026/05/10 18:14:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.0  ->  val=0.009041 | train=0.011844 | test=0.012238

2026/05/10 18:15:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.2  ->  val=0.009037 | train=0.011852 | test=0.012235

2026/05/10 18:16:00 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.0  ->  val=0.009038 | train=0.011845 | test=0.012234

2026/05/10 18:16:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.2  ->  val=0.009039 | train=0.011846 | test=0.012238

2026/05/10 18:16:47 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.0  ->  val=0.009037 | train=0.011841 | test=0.012212

2026/05/10 18:17:00 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.2  ->  val=0.009040 | train=0.011840 | test=0.012227

2026/05/10 18:17:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.0  ->  val=0.009048 | train=0.011840 | test=0.012213

2026/05/10 18:17:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.2  ->  val=0.009040 | train=0.011839 | test=0.012205

2026/05/10 18:17:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.0  ->  val=0.009049 | train=0.011851 | test=0.012218

2026/05/10 18:18:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.2  ->  val=0.009036 | train=0.011846 | test=0.012205

2026/05/10 18:18:27 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.0  ->  val=0.009038 | train=0.011843 | test=0.012233

2026/05/10 18:18:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.2  ->  val=0.009042 | train=0.011842 | test=0.012238

2026/05/10 18:18:59 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.0  ->  val=0.009037 | train=0.011838 | test=0.012233

2026/05/10 18:19:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.2  ->  val=0.009038 | train=0.011849 | test=0.012237

2026/05/10 18:19:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.0  ->  val=0.009038 | train=0.011846 | test=0.012234

2026/05/10 18:20:25 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.2  ->  val=0.009036 | train=0.011844 | test=0.012233

2026/05/10 18:20:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.0  ->  val=0.009036 | train=0.011793 | test=0.012210

2026/05/10 18:20:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.2  ->  val=0.009036 | train=0.011808 | test=0.012218

2026/05/10 18:20:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.0  ->  val=0.009037 | train=0.011834 | test=0.012231

2026/05/10 18:21:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.2  ->  val=0.009036 | train=0.011836 | test=0.012224

2026/05/10 18:21:10 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.0  ->  val=0.009037 | train=0.011841 | test=0.012232

2026/05/10 18:21:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.2  ->  val=0.009034 | train=0.011834 | test=0.012219

2026/05/10 18:21:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.0  ->  val=0.009038 | train=0.011854 | test=0.012236

2026/05/10 18:21:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.2  ->  val=0.009033 | train=0.011796 | test=0.012254

2026/05/10 18:21:50 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.0  ->  val=0.009045 | train=0.011846 | test=0.012239

2026/05/10 18:22:00 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.2  ->  val=0.009037 | train=0.011837 | test=0.012214

2026/05/10 18:22:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.0  ->  val=0.009047 | train=0.011852 | test=0.012239

2026/05/10 18:22:20 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.2  ->  val=0.009038 | train=0.011837 | test=0.012218

### Resultados — Etapa 1 (top 10)

In [5]:
results_arch_df.head(10)

,arch,n_layers,units,dropout,MAE_train,MAE_val,MAE_test,epochs,n_params
0,cnn_mlp,2,32,0.2,0.011796,0.009033,0.012254,58,4215
1,cnn_mlp,1,128,0.2,0.011834,0.009034,0.012219,18,28439
2,cnn_gru_mlp,2,128,0.2,0.011844,0.009036,0.012233,13,233367
3,cnn_lstm_mlp,1,64,0.2,0.011847,0.009036,0.012233,17,44503
4,cnn_gru_mlp,1,128,0.2,0.011846,0.009036,0.012205,22,134295
5,cnn_mlp,1,64,0.2,0.011836,0.009036,0.012224,19,10135
6,cnn_mlp,1,32,0.2,0.011808,0.009036,0.012218,27,4055
7,cnn_mlp,1,32,0.0,0.011793,0.009036,0.012210,34,4055
8,cnn_gru_mlp,2,64,0.0,0.011838,0.009037,0.012233,13,61399
9,cnn_mlp,1,128,0.0,0.011841,0.009037,0.012232,13,28439

## Etapa 2 — Hiperparámetros de entrenamiento

Se fija la arquitectura ganadora de la Etapa 1 y se busca sobre `learning_rate` × `batch_size`.

Criterio de selección: **MAE de validación mínimo**.

In [6]:
best_arch = results_arch_df.iloc[0]
print(f"Mejor arquitectura: arch={best_arch.arch}  n_layers={int(best_arch.n_layers)}  units={int(best_arch.units)}  dropout={best_arch.dropout}")
print(f"  MAE val = {best_arch.MAE_val:.6f}")

train_grid = list(itertools.product([1e-2, 1e-3, 1e-4], [64, 128, 256]))

results_train = []
for lr, bs in train_grid:
    run_name = f"{EXPERIMENT_NAME}_train_{best_arch.arch}_lr{lr:.0e}_batch{bs}"
    existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing.empty:
        mlflow.delete_run(existing.iloc[0].run_id)

    with mlflow.start_run(run_name=run_name):
        model = build_model(
            best_arch.arch, int(best_arch.n_layers), int(best_arch.units),
            float(best_arch.dropout), lr=lr,
        )
        mae_tr, mae_val, mae_te, h = fit_eval(model, batch_size=bs)

        for epoch, (tl, vl) in enumerate(zip(h.history["loss"], h.history["val_loss"])):
            mlflow.log_metric("train_loss", tl, step=epoch)
            mlflow.log_metric("val_loss",   vl, step=epoch)

        fig = plot_training_curve(h)
        mlflow.log_figure(fig, "plots/loss_curve.png")
        plt.close(fig)

        mlflow.log_param("arch",               best_arch.arch)
        mlflow.log_param("n_layers",           int(best_arch.n_layers))
        mlflow.log_param("units",              int(best_arch.units))
        mlflow.log_param("dropout",            float(best_arch.dropout))
        mlflow.log_param("kernel_size",        KERNEL_SIZE)
        mlflow.log_param("learning_rate",      lr)
        mlflow.log_param("batch_size",         bs)
        mlflow.log_param("input_window_size",  INPUT_W)
        mlflow.log_param("output_window_size", OUTPUT_W)
        mlflow.log_param("n_params",           model.count_params())
        mlflow.log_param("epochs",             len(h.history["loss"]))

        mlflow.log_metric("train_mae", mae_tr)
        mlflow.log_metric("val_mae",   mae_val)
        mlflow.log_metric("test_mae",  mae_te)

        mlflow.keras.log_model(model, name="model")

        results_train.append({
            "learning_rate": lr, "batch_size": bs,
            "MAE_train": mae_tr, "MAE_val": mae_val, "MAE_test": mae_te,
            "epochs": len(h.history["loss"]),
        })
        print(f"lr={lr:.0e} batch={bs:>3}  ->  val={mae_val:.6f} | train={mae_tr:.6f} | test={mae_te:.6f}")

results_train_df = pd.DataFrame(results_train).sort_values("MAE_val").reset_index(drop=True)

Mejor arquitectura: arch=cnn_mlp  n_layers=2  units=32  dropout=0.2
  MAE val = 0.009033

2026/05/10 18:22:29 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch= 64  ->  val=0.009355 | train=0.012206 | test=0.012483

2026/05/10 18:22:37 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch=128  ->  val=0.009187 | train=0.012012 | test=0.012347

2026/05/10 18:22:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch=256  ->  val=0.009108 | train=0.011962 | test=0.012293

2026/05/10 18:22:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch= 64  ->  val=0.009038 | train=0.011863 | test=0.012232

2026/05/10 18:23:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch=128  ->  val=0.009033 | train=0.011796 | test=0.012254

2026/05/10 18:23:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch=256  ->  val=0.009039 | train=0.011845 | test=0.012235

2026/05/10 18:23:33 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch= 64  ->  val=0.009032 | train=0.011795 | test=0.012213

2026/05/10 18:23:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch=128  ->  val=0.009039 | train=0.011829 | test=0.012235

2026/05/10 18:23:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch=256  ->  val=0.009039 | train=0.011828 | test=0.012236

In [7]:
results_train_df

   learning_rate  batch_size  MAE_train   MAE_val  MAE_test  epochs
0         0.0001          64   0.011795  0.009032  0.012213      89
1         0.0010         128   0.011796  0.009033  0.012254      58
2         0.0010          64   0.011863  0.009038  0.012232      15
3         0.0001         256   0.011828  0.009039  0.012236      26
4         0.0001         128   0.011829  0.009039  0.012235      30
5         0.0010         256   0.011845  0.009039  0.012235      12
6         0.0100         256   0.011962  0.009108  0.012293      11
7         0.0100         128   0.012012  0.009187  0.012347      11
8         0.0100          64   0.012206  0.009355  0.012483      15

## Modelo final y comparación con benchmarks

Se reentrena el modelo ganador con la configuración completa y se compara con la regresión lineal.

In [8]:
from util import load_benchmark

best_train = results_train_df.iloc[0]
print("Configuración ganadora:")
print(f"  arch          = {best_arch.arch}")
print(f"  n_layers      = {int(best_arch.n_layers)}")
print(f"  units         = {int(best_arch.units)}")
print(f"  dropout       = {float(best_arch.dropout)}")
print(f"  learning_rate = {best_train.learning_rate:.0e}")
print(f"  batch_size    = {int(best_train.batch_size)}")

final_model = build_model(
    best_arch.arch, int(best_arch.n_layers), int(best_arch.units),
    float(best_arch.dropout), lr=float(best_train.learning_rate),
)
mae_tr_f, mae_val_f, mae_te_f, hist_f = fit_eval(
    final_model, batch_size=int(best_train.batch_size), patience=20,
)

linreg_bench = load_benchmark("lr_benchmark")
linreg_row   = linreg_bench[
    (linreg_bench.input_window == INPUT_W) & (linreg_bench.output_window == OUTPUT_W)
].iloc[0]

run_name_final = f"{EXPERIMENT_NAME}_final"
existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name_final}"')
if not existing.empty:
    mlflow.delete_run(existing.iloc[0].run_id)

with mlflow.start_run(run_name=run_name_final):
    for epoch, (tl, vl) in enumerate(zip(hist_f.history["loss"], hist_f.history["val_loss"])):
        mlflow.log_metric("train_loss", tl, step=epoch)
        mlflow.log_metric("val_loss",   vl, step=epoch)

    fig_f = plot_training_curve(hist_f, show=True)
    mlflow.log_figure(fig_f, "plots/loss_curve.png")
    plt.close(fig_f)

    mlflow.log_param("arch",               best_arch.arch)
    mlflow.log_param("n_layers",           int(best_arch.n_layers))
    mlflow.log_param("units",              int(best_arch.units))
    mlflow.log_param("dropout",            float(best_arch.dropout))
    mlflow.log_param("kernel_size",        KERNEL_SIZE)
    mlflow.log_param("learning_rate",      float(best_train.learning_rate))
    mlflow.log_param("batch_size",         int(best_train.batch_size))
    mlflow.log_param("input_window_size",  INPUT_W)
    mlflow.log_param("output_window_size", OUTPUT_W)
    mlflow.log_param("n_params",           final_model.count_params())
    mlflow.log_param("epochs",             len(hist_f.history["loss"]))
    mlflow.log_metric("train_mae",         mae_tr_f)
    mlflow.log_metric("val_mae",           mae_val_f)
    mlflow.log_metric("test_mae",          mae_te_f)
    mlflow.keras.log_model(final_model, name="model")

summary = pd.DataFrame([
    {"modelo": "Regresión lineal",                 "MAE_train": linreg_row.MAE_train, "MAE_test": linreg_row.MAE_test},
    {"modelo": f"Mejor mixto ({best_arch.arch})",  "MAE_train": mae_tr_f,             "MAE_test": mae_te_f},
])
summary["Δ vs lin.reg. (test)"] = summary["MAE_test"] - linreg_row.MAE_test
display(summary)

Configuración ganadora:
  arch          = cnn_mlp
  n_layers      = 2
  units         = 32
  dropout       = 0.2
  learning_rate = 1e-04
  batch_size    = 64

/Users/jchulvi/projects/Neural-Networks-Forecasting/util.py:221: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
2026/05/10 18:24:15 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

                  modelo  MAE_train  MAE_test  Δ vs lin.reg. (test)
0       Regresión lineal   0.011821  0.012384              0.000000
1  Mejor mixto (cnn_mlp)   0.011795  0.012213             -0.000171

## Top-10 configuraciones por etapa

In [9]:
fig, axes = plt.subplots(1, 2, figsize=(16, 5))

def plot_top(ax, df, label_cols, title, top=10):
    top_df = df.head(top).iloc[::-1]
    labels = top_df[label_cols].astype(str).agg(" · ".join, axis=1)
    ypos = np.arange(len(top_df))
    ax.barh(ypos - 0.2, top_df["MAE_val"],   height=0.4, label="MAE val",   color="steelblue")
    ax.barh(ypos + 0.2, top_df["MAE_train"], height=0.4, label="MAE train", color="lightgray")
    ax.set_yticks(ypos)
    ax.set_yticklabels(labels, fontsize=9)
    ax.set_xlabel("MAE")
    ax.set_title(title)
    ax.legend(loc="lower right")
    ax.grid(True, axis="x", alpha=0.3)

plot_top(axes[0], results_arch_df,  ["arch", "n_layers", "units", "dropout"],
         "Etapa 1 — arquitectura (top 10)")
plot_top(axes[1], results_train_df, ["learning_rate", "batch_size"],
         "Etapa 2 — entrenamiento (top 9)")

plt.tight_layout()
plt.show()

/var/folders/py/c5_xfbqn469g5_844mv32gt40000gn/T/ipykernel_58637/3018486118.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()