# Modelos Mixtos — Combinaciones Conv1D, LSTM, GRU y MLP

Este notebook explora combinaciones de capas **convolucionales** (Conv1D), **recurrentes** (LSTM, GRU) y **densas** (MLP) para la configuración fija:

- **Ventana de entrada:** 30 días
- **Ventana de salida:** 90 días

Arquitecturas evaluadas:
- `lstm` — LSTM apiladas
- `gru` — GRU apiladas
- `cnn_lstm` — Conv1D → LSTM
- `cnn_gru` — Conv1D → GRU

- `cnn_lstm_mlp` — Conv1D → LSTM → MLP

- `cnn_gru_mlp` — Conv1D → GRU → MLP

- `cnn_mlp` — Conv1D → MLP

**Adaptación para input_w=30:** con 30 pasos temporales, `kernel_size=7` cubriría ~23% de la
ventana, lo que sobredimensiona el campo receptivo de la Conv1D. Se limita el grid a
`kernel_size ∈ {3, 5}` (10% y 17% de la ventana respectivamente).

La búsqueda se realiza en dos etapas:
1. **Etapa 1 — Arquitectura**: tipo de red × n_layers × units × dropout (× kernel_size para CNN) — 144 combinaciones
2. **Etapa 2 — Entrenamiento**: learning rate × batch size con la mejor arquitectura de la Etapa 1 (9 combinaciones)

In [1]:
import sys
import itertools
import mlflow
from pathlib import Path

# Busca util.py subiendo niveles desde el directorio actual
_here = Path.cwd()
PROJECT_ROOT = next(
    p for p in [_here, _here.parent, _here.parent.parent, _here.parent.parent.parent]
    if (p / 'util.py').exists()
)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

mlflow.set_tracking_uri(f"sqlite:///{PROJECT_ROOT / 'model' / 'mlflow.db'}")

EXPERIMENT_NAME = "Modelos_Mixtos_input30_output90"
mlflow.set_experiment(EXPERIMENT_NAME)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import keras
from keras.models import Sequential
from keras.layers import LSTM, GRU, Dense, Input, Conv1D, GlobalAveragePooling1D, Dropout
from keras.callbacks import EarlyStopping
from keras.optimizers import Adam

from sklearn.metrics import mean_absolute_error

from util import get_train_test, RANDOM_SEED, plot_training_curve

np.random.seed(RANDOM_SEED)
keras.utils.set_random_seed(RANDOM_SEED)

2026/05/10 23:52:38 INFO mlflow.tracking.fluent: Experiment with name 'Modelos_Mixtos_input30_output90' does not exist. Creating a new experiment.

## Carga de datos

In [2]:
INPUT_W  = 30
OUTPUT_W = 90

def load_seq_data(input_window_size, output_window_size):
    d = get_train_test(input_window_size=input_window_size, output_window_size=output_window_size)
    X_train, X_test = d.X_train, d.X_test
    y_train, y_test = d.y_train, d.y_test
    val_size         = int(0.10 * X_train.shape[0])
    X_val, y_val     = X_train[-val_size:], y_train[-val_size:]
    X_train, y_train = X_train[:-val_size], y_train[:-val_size]
    return X_train, y_train, X_val, y_val, X_test, y_test

X_tr, y_tr, X_val, y_val, X_te, y_te = load_seq_data(INPUT_W, OUTPUT_W)

print(f"X_tr:  {X_tr.shape}   y_tr:  {y_tr.shape}")
print(f"X_val: {X_val.shape}  y_val: {y_val.shape}")
print(f"X_te:  {X_te.shape}   y_te:  {y_te.shape}")

X_tr:  (13014, 30, 23)   y_tr:  (13014, 23)
X_val: (1445, 30, 23)  y_val: (1445, 23)
X_te:  (1607, 30, 23)   y_te:  (1607, 23)

## Arquitecturas implementadas

La función `build_model` construye el modelo según el argumento `arch`:

| `arch`     | Capas                                      |
|------------|--------------------------------------------|
| `lstm`     | Input → LSTM × n_layers → Dense            |
| `gru`      | Input → GRU × n_layers → Dense             |
| `cnn_lstm` | Input → Conv1D → LSTM × n_layers → Dense   |
| `cnn_gru`  | Input → Conv1D → GRU × n_layers → Dense    |

| `cnn_lstm_mlp` | Input → Conv1D → LSTM × n_layers → MLP → Dense |

| `cnn_gru_mlp`  | Input → Conv1D → GRU × n_layers → MLP → Dense  |

| `cnn_mlp`      | Input → Conv1D → GlobalAveragePooling1D → MLP × n_layers → Dense |

Para las variantes CNN, `kernel_size ∈ {3, 5}` se busca en el grid. Con 30 pasos de entrada,
estos valores cubren el 10% y el 17% de la ventana respectivamente, manteniéndose en un rango
razonable para detectar patrones locales sin sobredimensionar el campo receptivo.

In [3]:
def add_mlp_head(model, n_layers, units, dropout):
    for i in range(n_layers):
        layer_units = units if i == 0 else max(units // 2, 16)
        model.add(Dense(layer_units, activation="relu"))
        if dropout > 0:
            model.add(Dropout(dropout))


def build_model(arch, n_layers, units, dropout, kernel_size=3, lr=1e-3):
    keras.utils.set_random_seed(RANDOM_SEED)
    m = Sequential()
    m.add(Input(shape=(X_tr.shape[1], X_tr.shape[2])))

    if arch == "lstm":
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "gru":
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_lstm":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_gru":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_lstm_mlp":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))
        add_mlp_head(m, 2, units, dropout)

    elif arch == "cnn_gru_mlp":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))
        add_mlp_head(m, 2, units, dropout)

    elif arch == "cnn_mlp":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        m.add(GlobalAveragePooling1D())
        add_mlp_head(m, n_layers, units, dropout)

    else:
        raise ValueError(f"Arquitectura no soportada: {arch}")

    m.add(Dense(y_tr.shape[1]))
    m.compile(loss="mean_absolute_error", optimizer=Adam(learning_rate=lr))
    return m



def fit_eval(model, batch_size=128, epochs=200, patience=10, verbose=0):
    es = EarlyStopping(monitor="val_loss", patience=patience, restore_best_weights=True)
    h = model.fit(
        X_tr, y_tr,
        validation_data=(X_val, y_val),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=[es],
        verbose=verbose,
    )
    mae_tr  = mean_absolute_error(y_tr,  model.predict(X_tr,  verbose=0))
    mae_val = mean_absolute_error(y_val, model.predict(X_val, verbose=0))
    mae_te  = mean_absolute_error(y_te,  model.predict(X_te,  verbose=0))
    return mae_tr, mae_val, mae_te, h

## Etapa 1 — Búsqueda de arquitectura

Grid:
- **LSTM / GRU**: `arch` × `n_layers` × `units` × `dropout` → 24 combinaciones
- **CNN / CNN-RNN / CNN-RNN-MLP**: `arch` × `n_layers` × `units` × `dropout` × `kernel_size` → 120 combinaciones

Total: **144 combinaciones**. Learning rate y batch size fijos en esta etapa.

Criterio de selección: **MAE de validación mínimo**.

In [4]:
pure_rnn_combos = [
    (arch, nl, u, dr, None)
    for arch, nl, u, dr in itertools.product(
        ["lstm", "gru"], [1, 2], [32, 64, 128], [0.0, 0.2]
    )
]
cnn_combos = [
    (arch, nl, u, dr, ks)
    for arch, nl, u, dr, ks in itertools.product(
        ["cnn_lstm", "cnn_gru", "cnn_lstm_mlp", "cnn_gru_mlp", "cnn_mlp"], [1, 2], [32, 64, 128], [0.0, 0.2], [3, 5]
    )
]
arch_grid = pure_rnn_combos + cnn_combos
print(f"Total combinaciones Etapa 1: {len(arch_grid)}  (RNN puras: {len(pure_rnn_combos)}, CNN: {len(cnn_combos)})")

results_arch = []
batch_size_arch = 128

for arch, nl, u, dr, ks in arch_grid:
    ks_eff = ks if ks is not None else 0  # 0 = no aplica (RNN pura)
    run_name = (
        f"{EXPERIMENT_NAME}_arch_{arch}_layers{nl}_units{u}_drop{dr}"
        + (f"_ks{ks_eff}" if ks is not None else "")
    )
    existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing.empty:
        mlflow.delete_run(existing.iloc[0].run_id)

    with mlflow.start_run(run_name=run_name):
        model = build_model(arch, nl, u, dr, kernel_size=ks_eff if ks is not None else 3, lr=1e-3)
        mae_tr, mae_val, mae_te, h = fit_eval(model, batch_size=batch_size_arch)

        for epoch, (tl, vl) in enumerate(zip(h.history["loss"], h.history["val_loss"])):
            mlflow.log_metric("train_loss", tl, step=epoch)
            mlflow.log_metric("val_loss",   vl, step=epoch)

        fig = plot_training_curve(h)
        mlflow.log_figure(fig, "plots/loss_curve.png")
        plt.close(fig)

        mlflow.log_param("arch",               arch)
        mlflow.log_param("n_layers",           nl)
        mlflow.log_param("units",              u)
        mlflow.log_param("dropout",            dr)
        mlflow.log_param("kernel_size",        ks_eff)
        mlflow.log_param("learning_rate",      1e-3)
        mlflow.log_param("batch_size",         batch_size_arch)
        mlflow.log_param("input_window_size",  INPUT_W)
        mlflow.log_param("output_window_size", OUTPUT_W)
        mlflow.log_param("n_params",           model.count_params())
        mlflow.log_param("epochs",             len(h.history["loss"]))

        mlflow.log_metric("train_mae", mae_tr)
        mlflow.log_metric("val_mae",   mae_val)
        mlflow.log_metric("test_mae",  mae_te)

        mlflow.keras.log_model(model, name="model")

        results_arch.append({
            "arch": arch, "n_layers": nl, "units": u, "dropout": dr, "kernel_size": ks_eff,
            "MAE_train": mae_tr, "MAE_val": mae_val, "MAE_test": mae_te,
            "epochs": len(h.history["loss"]), "n_params": model.count_params(),
        })
        ks_str = f" ks={ks_eff}" if ks is not None else ""
        print(f"arch={arch:<10} layers={nl} units={u:>3} dropout={dr}{ks_str}  ->  val={mae_val:.6f} | train={mae_tr:.6f} | test={mae_te:.6f}")

results_arch_df = pd.DataFrame(results_arch).sort_values("MAE_val").reset_index(drop=True)

Total combinaciones Etapa 1: 144  (RNN puras: 24, CNN: 120)

2026/05/10 23:52:50 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 32 dropout=0.0  ->  val=0.000943 | train=0.001265 | test=0.001292

2026/05/10 23:53:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 32 dropout=0.2  ->  val=0.000936 | train=0.001264 | test=0.001293

2026/05/10 23:53:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 64 dropout=0.0  ->  val=0.000947 | train=0.001261 | test=0.001312

2026/05/10 23:53:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 64 dropout=0.2  ->  val=0.000942 | train=0.001262 | test=0.001300

2026/05/10 23:54:47 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units=128 dropout=0.0  ->  val=0.000950 | train=0.001250 | test=0.001345

2026/05/10 23:55:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units=128 dropout=0.2  ->  val=0.000946 | train=0.001254 | test=0.001300

2026/05/10 23:55:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 32 dropout=0.0  ->  val=0.000954 | train=0.001271 | test=0.001296

2026/05/10 23:56:23 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 32 dropout=0.2  ->  val=0.000946 | train=0.001263 | test=0.001302

2026/05/10 23:57:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 64 dropout=0.0  ->  val=0.000952 | train=0.001243 | test=0.001339

2026/05/10 23:58:22 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 64 dropout=0.2  ->  val=0.000940 | train=0.001258 | test=0.001304

2026/05/11 00:01:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units=128 dropout=0.0  ->  val=0.000951 | train=0.001245 | test=0.001336

2026/05/11 00:03:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units=128 dropout=0.2  ->  val=0.000948 | train=0.001257 | test=0.001311

2026/05/11 00:04:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 32 dropout=0.0  ->  val=0.000973 | train=0.001277 | test=0.001306

2026/05/11 00:04:23 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 32 dropout=0.2  ->  val=0.000966 | train=0.001301 | test=0.001316

2026/05/11 00:04:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 64 dropout=0.0  ->  val=0.000961 | train=0.001275 | test=0.001300

2026/05/11 00:05:47 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 64 dropout=0.2  ->  val=0.000950 | train=0.001269 | test=0.001315

2026/05/11 00:07:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units=128 dropout=0.0  ->  val=0.000965 | train=0.001274 | test=0.001340

2026/05/11 00:08:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units=128 dropout=0.2  ->  val=0.000944 | train=0.001264 | test=0.001310

2026/05/11 00:09:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 32 dropout=0.0  ->  val=0.000944 | train=0.001268 | test=0.001308

2026/05/11 00:09:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 32 dropout=0.2  ->  val=0.000939 | train=0.001267 | test=0.001282

2026/05/11 00:10:35 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 64 dropout=0.0  ->  val=0.000957 | train=0.001278 | test=0.001299

2026/05/11 00:11:37 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 64 dropout=0.2  ->  val=0.000957 | train=0.001274 | test=0.001296

2026/05/11 00:33:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units=128 dropout=0.0  ->  val=0.000952 | train=0.001263 | test=0.001355

2026/05/11 01:08:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units=128 dropout=0.2  ->  val=0.000953 | train=0.001267 | test=0.001283

2026/05/11 01:08:37 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.000941 | train=0.001220 | test=0.001332

2026/05/11 01:24:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.000954 | train=0.001250 | test=0.001326

2026/05/11 01:25:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.000929 | train=0.001233 | test=0.001342

2026/05/11 01:25:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.000942 | train=0.001165 | test=0.001327

2026/05/11 01:26:10 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.000943 | train=0.001153 | test=0.001347

2026/05/11 01:41:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.000950 | train=0.001246 | test=0.001332

2026/05/11 01:42:12 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.000927 | train=0.001068 | test=0.001346

2026/05/11 01:49:14 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.000948 | train=0.001189 | test=0.001318

2026/05/11 01:50:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.0 ks=3  ->  val=0.000995 | train=0.001140 | test=0.001384

2026/05/11 01:50:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.0 ks=5  ->  val=0.000995 | train=0.001270 | test=0.001362

2026/05/11 01:51:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.2 ks=3  ->  val=0.000976 | train=0.001284 | test=0.001321

2026/05/11 01:52:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.2 ks=5  ->  val=0.000942 | train=0.000892 | test=0.001371

2026/05/11 01:53:18 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.000985 | train=0.001259 | test=0.001328

2026/05/11 01:53:40 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.000963 | train=0.001228 | test=0.001345

2026/05/11 01:54:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.000958 | train=0.001275 | test=0.001280

2026/05/11 01:54:29 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.000950 | train=0.001107 | test=0.001337

2026/05/11 01:55:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.000985 | train=0.001264 | test=0.001312

2026/05/11 01:55:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.001001 | train=0.001256 | test=0.001345

2026/05/11 01:56:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.000948 | train=0.001245 | test=0.001301

2026/05/11 01:57:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.000943 | train=0.001033 | test=0.001296

2026/05/11 01:59:33 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.0 ks=3  ->  val=0.001003 | train=0.001255 | test=0.001373

2026/05/11 02:01:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.0 ks=5  ->  val=0.001008 | train=0.001139 | test=0.001348

2026/05/11 02:03:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.2 ks=3  ->  val=0.000963 | train=0.001043 | test=0.001325

2026/05/11 02:05:35 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.2 ks=5  ->  val=0.000979 | train=0.001250 | test=0.001334

2026/05/11 02:05:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.000945 | train=0.001208 | test=0.001338

2026/05/11 02:06:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.000970 | train=0.001250 | test=0.001341

2026/05/11 02:06:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.000935 | train=0.001153 | test=0.001350

2026/05/11 02:07:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.000934 | train=0.001163 | test=0.001310

2026/05/11 02:07:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.000966 | train=0.001189 | test=0.001390

2026/05/11 02:08:22 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.000974 | train=0.001105 | test=0.001404

2026/05/11 02:08:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.000938 | train=0.001202 | test=0.001358

2026/05/11 02:09:34 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.000950 | train=0.001042 | test=0.001400

2026/05/11 02:10:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.0 ks=3  ->  val=0.000978 | train=0.001183 | test=0.001357

2026/05/11 02:11:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.0 ks=5  ->  val=0.000982 | train=0.001256 | test=0.001359

2026/05/11 02:13:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.2 ks=3  ->  val=0.000968 | train=0.001052 | test=0.001344

2026/05/11 02:14:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.2 ks=5  ->  val=0.000972 | train=0.001276 | test=0.001335

2026/05/11 02:14:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.000952 | train=0.001282 | test=0.001306

2026/05/11 02:15:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.000942 | train=0.001277 | test=0.001300

2026/05/11 02:15:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.000943 | train=0.001219 | test=0.001326

2026/05/11 02:16:18 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.000949 | train=0.001285 | test=0.001310

2026/05/11 02:17:10 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.000992 | train=0.001226 | test=0.001332

2026/05/11 02:17:59 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.000972 | train=0.001249 | test=0.001350

2026/05/11 02:18:52 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.000957 | train=0.001261 | test=0.001335

2026/05/11 02:20:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.000963 | train=0.001055 | test=0.001310

2026/05/11 02:22:18 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.0 ks=3  ->  val=0.000983 | train=0.001202 | test=0.001372

2026/05/11 02:24:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.0 ks=5  ->  val=0.001004 | train=0.001213 | test=0.001379

2026/05/11 02:28:00 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.2 ks=3  ->  val=0.000949 | train=0.000996 | test=0.001349

2026/05/11 02:31:12 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.2 ks=5  ->  val=0.000977 | train=0.001046 | test=0.001381

2026/05/11 02:31:37 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.000940 | train=0.001273 | test=0.001278

2026/05/11 02:32:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.000939 | train=0.001273 | test=0.001278

2026/05/11 02:32:41 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.000942 | train=0.001274 | test=0.001278

2026/05/11 02:33:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.000941 | train=0.001272 | test=0.001278

2026/05/11 02:33:27 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.000937 | train=0.001272 | test=0.001274

2026/05/11 02:33:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.000943 | train=0.001268 | test=0.001276

2026/05/11 02:34:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.000940 | train=0.001271 | test=0.001276

2026/05/11 02:35:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.000941 | train=0.001273 | test=0.001279

2026/05/11 02:36:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.0 ks=3  ->  val=0.000954 | train=0.001272 | test=0.001285

2026/05/11 02:37:57 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.0 ks=5  ->  val=0.000944 | train=0.001273 | test=0.001286

2026/05/11 02:39:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.2 ks=3  ->  val=0.000940 | train=0.001271 | test=0.001275

2026/05/11 02:40:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.2 ks=5  ->  val=0.000941 | train=0.001271 | test=0.001277

2026/05/11 02:42:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.000941 | train=0.001275 | test=0.001279

2026/05/11 02:42:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.000941 | train=0.001271 | test=0.001277

2026/05/11 02:43:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.000940 | train=0.001274 | test=0.001279

2026/05/11 02:44:15 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.000940 | train=0.001272 | test=0.001276

2026/05/11 02:45:15 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.000934 | train=0.001266 | test=0.001291

2026/05/11 02:46:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.000941 | train=0.001268 | test=0.001285

2026/05/11 02:47:40 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.000940 | train=0.001274 | test=0.001277

2026/05/11 02:48:29 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.000941 | train=0.001273 | test=0.001277

2026/05/11 03:24:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.0 ks=3  ->  val=0.000944 | train=0.001263 | test=0.001276

2026/05/11 03:26:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.0 ks=5  ->  val=0.000958 | train=0.001265 | test=0.001284

2026/05/11 03:28:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.2 ks=3  ->  val=0.000936 | train=0.001269 | test=0.001276

2026/05/11 03:36:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.2 ks=5  ->  val=0.000939 | train=0.001272 | test=0.001276

2026/05/11 03:37:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.000934 | train=0.001271 | test=0.001276

2026/05/11 03:37:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.000938 | train=0.001269 | test=0.001277

2026/05/11 03:37:52 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.000940 | train=0.001273 | test=0.001278

2026/05/11 03:55:22 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.000940 | train=0.001273 | test=0.001274

2026/05/11 03:55:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.000938 | train=0.001274 | test=0.001279

2026/05/11 03:56:14 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.000936 | train=0.001226 | test=0.001301

2026/05/11 04:28:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.000939 | train=0.001273 | test=0.001276

2026/05/11 04:29:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.000941 | train=0.001273 | test=0.001278

2026/05/11 04:45:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.0 ks=3  ->  val=0.000952 | train=0.001275 | test=0.001276

2026/05/11 05:01:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.0 ks=5  ->  val=0.000948 | train=0.001275 | test=0.001281

2026/05/11 05:03:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.2 ks=3  ->  val=0.000941 | train=0.001273 | test=0.001280

2026/05/11 05:03:59 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.2 ks=5  ->  val=0.000939 | train=0.001274 | test=0.001282

2026/05/11 05:04:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.000940 | train=0.001273 | test=0.001278

2026/05/11 05:05:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.000941 | train=0.001274 | test=0.001281

2026/05/11 05:05:50 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.000938 | train=0.001271 | test=0.001279

2026/05/11 05:07:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.000939 | train=0.001274 | test=0.001277

2026/05/11 05:08:18 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.000939 | train=0.001211 | test=0.001292

2026/05/11 05:09:32 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.000939 | train=0.001270 | test=0.001273

2026/05/11 05:10:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.000940 | train=0.001270 | test=0.001275

2026/05/11 05:12:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.000940 | train=0.001273 | test=0.001277

2026/05/11 05:14:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.0 ks=3  ->  val=0.000947 | train=0.001267 | test=0.001280

2026/05/11 05:16:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.0 ks=5  ->  val=0.000934 | train=0.001264 | test=0.001281

2026/05/11 05:35:08 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.2 ks=3  ->  val=0.000941 | train=0.001272 | test=0.001278

2026/05/11 06:57:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.2 ks=5  ->  val=0.000941 | train=0.001274 | test=0.001278

2026/05/11 06:57:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.000948 | train=0.001278 | test=0.001300

2026/05/11 06:58:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.000943 | train=0.001232 | test=0.001323

2026/05/11 06:58:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.000941 | train=0.001270 | test=0.001287

2026/05/11 06:58:20 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.000940 | train=0.001271 | test=0.001289

2026/05/11 06:58:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.000939 | train=0.001260 | test=0.001337

2026/05/11 07:08:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.000946 | train=0.001207 | test=0.001343

2026/05/11 07:08:25 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.000938 | train=0.001267 | test=0.001299

2026/05/11 07:08:32 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.000939 | train=0.001254 | test=0.001295

2026/05/11 07:08:40 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.0 ks=3  ->  val=0.000973 | train=0.001189 | test=0.001324

2026/05/11 07:08:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.0 ks=5  ->  val=0.000957 | train=0.001216 | test=0.001311

2026/05/11 07:08:57 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.2 ks=3  ->  val=0.000938 | train=0.001255 | test=0.001296

2026/05/11 07:24:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.2 ks=5  ->  val=0.000941 | train=0.001253 | test=0.001293

2026/05/11 07:24:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.000940 | train=0.001274 | test=0.001279

2026/05/11 07:25:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.000941 | train=0.001274 | test=0.001281

2026/05/11 07:25:12 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.000938 | train=0.001271 | test=0.001281

2026/05/11 07:25:22 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.000930 | train=0.001261 | test=0.001329

2026/05/11 07:42:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.000940 | train=0.001272 | test=0.001281

2026/05/11 07:42:15 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.000939 | train=0.001270 | test=0.001276

2026/05/11 07:42:22 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.000937 | train=0.001270 | test=0.001271

2026/05/11 07:42:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.000938 | train=0.001268 | test=0.001271

2026/05/11 07:42:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.0 ks=3  ->  val=0.000956 | train=0.001258 | test=0.001285

2026/05/11 07:42:47 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.0 ks=5  ->  val=0.000956 | train=0.001247 | test=0.001273

2026/05/11 07:59:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.2 ks=3  ->  val=0.000942 | train=0.001272 | test=0.001278

2026/05/11 07:59:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.2 ks=5  ->  val=0.000938 | train=0.001274 | test=0.001274

### Resultados — Etapa 1 (top 10)

In [5]:
results_arch_df.head(10)

,arch,n_layers,units,dropout,kernel_size,MAE_train,MAE_val,MAE_test,epochs,n_params
0,cnn_lstm,1,64,0.2,3,0.001068,0.000927,0.001346,18,38999
1,cnn_lstm,1,32,0.2,3,0.001233,0.000929,0.001342,17,11319
2,cnn_mlp,2,32,0.2,5,0.001261,0.000930,0.001329,30,5687
3,cnn_gru,1,32,0.2,5,0.001163,0.000934,0.001310,21,10807
4,cnn_gru_mlp,1,32,0.0,3,0.001271,0.000934,0.001276,12,10551
5,cnn_lstm_mlp,2,64,0.0,3,0.001266,0.000934,0.001291,13,77527
6,cnn_gru_mlp,2,128,0.0,5,0.001264,0.000934,0.001281,12,239255
7,cnn_gru,1,32,0.2,3,0.001153,0.000935,0.001350,25,9335
8,cnn_gru_mlp,1,64,0.0,5,0.001226,0.000936,0.001301,16,39383
9,cnn_lstm_mlp,2,128,0.2,3,0.001269,0.000936,0.001276,12,298391

## Etapa 2 — Hiperparámetros de entrenamiento

Se fija la arquitectura ganadora de la Etapa 1 y se busca sobre `learning_rate` × `batch_size`.

Criterio de selección: **MAE de validación mínimo**.

In [6]:
best_arch = results_arch_df.iloc[0]
best_ks   = int(best_arch.kernel_size)
print(f"Mejor arquitectura: arch={best_arch.arch}  n_layers={int(best_arch.n_layers)}  units={int(best_arch.units)}  dropout={best_arch.dropout}  kernel_size={best_ks}")
print(f"  MAE val = {best_arch.MAE_val:.6f}")

train_grid = list(itertools.product([1e-2, 1e-3, 1e-4], [64, 128, 256]))

results_train = []
for lr, bs in train_grid:
    run_name = f"{EXPERIMENT_NAME}_train_{best_arch.arch}_lr{lr:.0e}_batch{bs}"
    existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing.empty:
        mlflow.delete_run(existing.iloc[0].run_id)

    with mlflow.start_run(run_name=run_name):
        model = build_model(
            best_arch.arch, int(best_arch.n_layers), int(best_arch.units),
            float(best_arch.dropout), kernel_size=best_ks, lr=lr,
        )
        mae_tr, mae_val, mae_te, h = fit_eval(model, batch_size=bs)

        for epoch, (tl, vl) in enumerate(zip(h.history["loss"], h.history["val_loss"])):
            mlflow.log_metric("train_loss", tl, step=epoch)
            mlflow.log_metric("val_loss",   vl, step=epoch)

        fig = plot_training_curve(h)
        mlflow.log_figure(fig, "plots/loss_curve.png")
        plt.close(fig)

        mlflow.log_param("arch",               best_arch.arch)
        mlflow.log_param("n_layers",           int(best_arch.n_layers))
        mlflow.log_param("units",              int(best_arch.units))
        mlflow.log_param("dropout",            float(best_arch.dropout))
        mlflow.log_param("kernel_size",        best_ks)
        mlflow.log_param("learning_rate",      lr)
        mlflow.log_param("batch_size",         bs)
        mlflow.log_param("input_window_size",  INPUT_W)
        mlflow.log_param("output_window_size", OUTPUT_W)
        mlflow.log_param("n_params",           model.count_params())
        mlflow.log_param("epochs",             len(h.history["loss"]))

        mlflow.log_metric("train_mae", mae_tr)
        mlflow.log_metric("val_mae",   mae_val)
        mlflow.log_metric("test_mae",  mae_te)

        mlflow.keras.log_model(model, name="model")

        results_train.append({
            "learning_rate": lr, "batch_size": bs,
            "MAE_train": mae_tr, "MAE_val": mae_val, "MAE_test": mae_te,
            "epochs": len(h.history["loss"]),
        })
        print(f"lr={lr:.0e} batch={bs:>3}  ->  val={mae_val:.6f} | train={mae_tr:.6f} | test={mae_te:.6f}")

results_train_df = pd.DataFrame(results_train).sort_values("MAE_val").reset_index(drop=True)

Mejor arquitectura: arch=cnn_lstm  n_layers=1  units=64  dropout=0.2  kernel_size=3
  MAE val = 0.000927

2026/05/11 08:00:00 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch= 64  ->  val=0.001039 | train=0.001200 | test=0.001434

2026/05/11 08:00:41 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch=128  ->  val=0.001020 | train=0.001193 | test=0.001411

2026/05/11 08:08:41 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch=256  ->  val=0.000977 | train=0.001180 | test=0.001390

2026/05/11 08:25:41 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch= 64  ->  val=0.000939 | train=0.001143 | test=0.001334

2026/05/11 08:31:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch=128  ->  val=0.000927 | train=0.001068 | test=0.001346

2026/05/11 08:31:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch=256  ->  val=0.000957 | train=0.001265 | test=0.001303

2026/05/11 08:47:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch= 64  ->  val=0.000938 | train=0.001258 | test=0.001300

2026/05/11 09:03:32 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch=128  ->  val=0.000937 | train=0.001169 | test=0.001306

2026/05/11 09:09:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch=256  ->  val=0.000933 | train=0.001265 | test=0.001291

In [7]:
results_train_df

   learning_rate  batch_size  MAE_train   MAE_val  MAE_test  epochs
0         0.0010         128   0.001068  0.000927  0.001346      18
1         0.0001         256   0.001265  0.000933  0.001291      23
2         0.0001         128   0.001169  0.000937  0.001306      28
3         0.0001          64   0.001258  0.000938  0.001300      16
4         0.0010          64   0.001143  0.000939  0.001334      14
5         0.0010         256   0.001265  0.000957  0.001303      13
6         0.0100         256   0.001180  0.000977  0.001390      35
7         0.0100         128   0.001193  0.001020  0.001411      25
8         0.0100          64   0.001200  0.001039  0.001434      20

## Modelo final y comparación con benchmarks

Se reentrena el modelo ganador con la configuración completa y se compara con la regresión lineal.

In [8]:
from util import load_benchmark

best_train = results_train_df.iloc[0]
print("Configuración ganadora:")
print(f"  arch          = {best_arch.arch}")
print(f"  n_layers      = {int(best_arch.n_layers)}")
print(f"  units         = {int(best_arch.units)}")
print(f"  dropout       = {float(best_arch.dropout)}")
print(f"  kernel_size   = {best_ks}")
print(f"  learning_rate = {best_train.learning_rate:.0e}")
print(f"  batch_size    = {int(best_train.batch_size)}")

final_model = build_model(
    best_arch.arch, int(best_arch.n_layers), int(best_arch.units),
    float(best_arch.dropout), kernel_size=best_ks, lr=float(best_train.learning_rate),
)
mae_tr_f, mae_val_f, mae_te_f, hist_f = fit_eval(
    final_model, batch_size=int(best_train.batch_size), patience=20,
)

linreg_bench = load_benchmark("lr_benchmark")
linreg_row   = linreg_bench[
    (linreg_bench.input_window == INPUT_W) & (linreg_bench.output_window == OUTPUT_W)
].iloc[0]

run_name_final = f"{EXPERIMENT_NAME}_final"
existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name_final}"')
if not existing.empty:
    mlflow.delete_run(existing.iloc[0].run_id)

with mlflow.start_run(run_name=run_name_final):
    for epoch, (tl, vl) in enumerate(zip(hist_f.history["loss"], hist_f.history["val_loss"])):
        mlflow.log_metric("train_loss", tl, step=epoch)
        mlflow.log_metric("val_loss",   vl, step=epoch)

    fig_f = plot_training_curve(hist_f)
    mlflow.log_figure(fig_f, "plots/loss_curve.png")
    plt.close(fig_f)

    mlflow.log_param("arch",               best_arch.arch)
    mlflow.log_param("n_layers",           int(best_arch.n_layers))
    mlflow.log_param("units",              int(best_arch.units))
    mlflow.log_param("dropout",            float(best_arch.dropout))
    mlflow.log_param("kernel_size",        best_ks)
    mlflow.log_param("learning_rate",      float(best_train.learning_rate))
    mlflow.log_param("batch_size",         int(best_train.batch_size))
    mlflow.log_param("input_window_size",  INPUT_W)
    mlflow.log_param("output_window_size", OUTPUT_W)
    mlflow.log_param("n_params",           final_model.count_params())
    mlflow.log_param("epochs",             len(hist_f.history["loss"]))
    mlflow.log_metric("train_mae",         mae_tr_f)
    mlflow.log_metric("val_mae",           mae_val_f)
    mlflow.log_metric("test_mae",          mae_te_f)
    mlflow.keras.log_model(final_model, name="model")

summary = pd.DataFrame([
    {"modelo": "Regresión lineal",                 "MAE_train": linreg_row.MAE_train, "MAE_test": linreg_row.MAE_test},
    {"modelo": f"Mejor mixto ({best_arch.arch})",  "MAE_train": mae_tr_f,             "MAE_test": mae_te_f},
])
summary["Δ vs lin.reg. (test)"] = summary["MAE_test"] - linreg_row.MAE_test
display(summary)

Configuración ganadora:
  arch          = cnn_lstm
  n_layers      = 1
  units         = 64
  dropout       = 0.2
  kernel_size   = 3
  learning_rate = 1e-03
  batch_size    = 128

2026/05/11 09:25:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

                   modelo  MAE_train  MAE_test  Δ vs lin.reg. (test)
0        Regresión lineal   0.001235  0.001351              0.000000
1  Mejor mixto (cnn_lstm)   0.001068  0.001346             -0.000006

## Top-10 configuraciones por etapa

In [9]:
fig, axes = plt.subplots(1, 2, figsize=(16, 5))

def plot_top(ax, df, label_cols, title, top=10):
    top_df = df.head(top).iloc[::-1]
    labels = top_df[label_cols].astype(str).agg(" · ".join, axis=1)
    ypos = np.arange(len(top_df))
    ax.barh(ypos - 0.2, top_df["MAE_val"],   height=0.4, label="MAE val",   color="steelblue")
    ax.barh(ypos + 0.2, top_df["MAE_train"], height=0.4, label="MAE train", color="lightgray")
    ax.set_yticks(ypos)
    ax.set_yticklabels(labels, fontsize=9)
    ax.set_xlabel("MAE")
    ax.set_title(title)
    ax.legend(loc="lower right")
    ax.grid(True, axis="x", alpha=0.3)

arch_label_cols = ["arch", "n_layers", "units", "dropout", "kernel_size"]
plot_top(axes[0], results_arch_df,  arch_label_cols,
         "Etapa 1 — arquitectura (top 10)")
plot_top(axes[1], results_train_df, ["learning_rate", "batch_size"],
         "Etapa 2 — entrenamiento (top 9)")

plt.tight_layout()
plt.show()

/var/folders/py/c5_xfbqn469g5_844mv32gt40000gn/T/ipykernel_3030/3707942946.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()