# Modelos Mixtos — Combinaciones Conv1D, LSTM, GRU y MLP

Este notebook explora combinaciones de capas **convolucionales** (Conv1D), **recurrentes** (LSTM, GRU) y **densas** (MLP) para la configuración fija:

- **Ventana de entrada:** 5 días
- **Ventana de salida:** 90 días

Arquitecturas evaluadas:
- `lstm` — LSTM apiladas
- `gru` — GRU apiladas
- `cnn_lstm` — Conv1D → LSTM
- `cnn_gru` — Conv1D → GRU

- `cnn_lstm_mlp` — Conv1D → LSTM → MLP

- `cnn_gru_mlp` — Conv1D → GRU → MLP

- `cnn_mlp` — Conv1D → MLP

La búsqueda se realiza en dos etapas:
1. **Etapa 1 — Arquitectura**: tipo de red × n_layers × units × dropout (84 combinaciones)
2. **Etapa 2 — Entrenamiento**: learning rate × batch size con la mejor arquitectura de la Etapa 1 (9 combinaciones)

In [1]:
import sys
import itertools
import mlflow
from pathlib import Path

# Busca util.py subiendo niveles desde el directorio actual
_here = Path.cwd()
PROJECT_ROOT = next(
    p for p in [_here, _here.parent, _here.parent.parent, _here.parent.parent.parent]
    if (p / 'util.py').exists()
)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

mlflow.set_tracking_uri(f"sqlite:///{PROJECT_ROOT / 'model' / 'mlflow.db'}")

EXPERIMENT_NAME = "Modelos_Mixtos_input5_output90"
mlflow.set_experiment(EXPERIMENT_NAME)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import keras
from keras.models import Sequential
from keras.layers import LSTM, GRU, Dense, Input, Conv1D, GlobalAveragePooling1D, Dropout
from keras.callbacks import EarlyStopping
from keras.optimizers import Adam

from sklearn.metrics import mean_absolute_error

from util import get_train_test, RANDOM_SEED, plot_training_curve

np.random.seed(RANDOM_SEED)
keras.utils.set_random_seed(RANDOM_SEED)

2026/05/10 19:08:20 INFO mlflow.tracking.fluent: Experiment with name 'Modelos_Mixtos_input5_output90' does not exist. Creating a new experiment.

## Carga de datos

In [2]:
INPUT_W  = 5
OUTPUT_W = 90

def load_seq_data(input_window_size, output_window_size):
    d = get_train_test(input_window_size=input_window_size, output_window_size=output_window_size)
    X_train, X_test = d.X_train, d.X_test
    y_train, y_test = d.y_train, d.y_test
    val_size         = int(0.10 * X_train.shape[0])
    X_val, y_val     = X_train[-val_size:], y_train[-val_size:]
    X_train, y_train = X_train[:-val_size], y_train[:-val_size]
    return X_train, y_train, X_val, y_val, X_test, y_test

X_tr, y_tr, X_val, y_val, X_te, y_te = load_seq_data(INPUT_W, OUTPUT_W)

print(f"X_tr:  {X_tr.shape}   y_tr:  {y_tr.shape}")
print(f"X_val: {X_val.shape}  y_val: {y_val.shape}")
print(f"X_te:  {X_te.shape}   y_te:  {y_te.shape}")

X_tr:  (13033, 5, 23)   y_tr:  (13033, 23)
X_val: (1448, 5, 23)  y_val: (1448, 23)
X_te:  (1610, 5, 23)   y_te:  (1610, 23)

## Arquitecturas implementadas

La función `build_model` construye el modelo según el argumento `arch`:

| `arch`     | Capas                                      |
|------------|--------------------------------------------|
| `lstm`     | Input → LSTM × n_layers → Dense            |
| `gru`      | Input → GRU × n_layers → Dense             |
| `cnn_lstm` | Input → Conv1D → LSTM × n_layers → Dense   |
| `cnn_gru`  | Input → Conv1D → GRU × n_layers → Dense    |

| `cnn_lstm_mlp` | Input → Conv1D → LSTM × n_layers → MLP → Dense |

| `cnn_gru_mlp`  | Input → Conv1D → GRU × n_layers → MLP → Dense  |

| `cnn_mlp`      | Input → Conv1D → GlobalAveragePooling1D → MLP × n_layers → Dense |

El `kernel_size` de Conv1D se fija a 3 (válido para input_w=5 con `padding="same"`).

In [3]:
KERNEL_SIZE = 3


def add_mlp_head(model, n_layers, units, dropout):
    for i in range(n_layers):
        layer_units = units if i == 0 else max(units // 2, 16)
        model.add(Dense(layer_units, activation="relu"))
        if dropout > 0:
            model.add(Dropout(dropout))


def build_model(arch, n_layers, units, dropout, lr=1e-3):
    keras.utils.set_random_seed(RANDOM_SEED)
    m = Sequential()
    m.add(Input(shape=(X_tr.shape[1], X_tr.shape[2])))

    if arch == "lstm":
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "gru":
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_lstm":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_gru":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_lstm_mlp":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))
        add_mlp_head(m, 2, units, dropout)

    elif arch == "cnn_gru_mlp":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))
        add_mlp_head(m, 2, units, dropout)

    elif arch == "cnn_mlp":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        m.add(GlobalAveragePooling1D())
        add_mlp_head(m, n_layers, units, dropout)

    else:
        raise ValueError(f"Arquitectura no soportada: {arch}")

    m.add(Dense(y_tr.shape[1]))
    m.compile(loss="mean_absolute_error", optimizer=Adam(learning_rate=lr))
    return m



def fit_eval(model, batch_size=128, epochs=200, patience=10, verbose=0):
    es = EarlyStopping(monitor="val_loss", patience=patience, restore_best_weights=True)
    h = model.fit(
        X_tr, y_tr,
        validation_data=(X_val, y_val),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=[es],
        verbose=verbose,
    )
    mae_tr  = mean_absolute_error(y_tr,  model.predict(X_tr,  verbose=0))
    mae_val = mean_absolute_error(y_val, model.predict(X_val, verbose=0))
    mae_te  = mean_absolute_error(y_te,  model.predict(X_te,  verbose=0))
    return mae_tr, mae_val, mae_te, h

## Etapa 1 — Búsqueda de arquitectura

Grid: `arch` × `n_layers` × `units` × `dropout` (learning rate y batch size fijos).

Criterio de selección: **MAE de validación mínimo**.

In [4]:
arch_grid = list(itertools.product(
    ["lstm", "gru", "cnn_lstm", "cnn_gru", "cnn_lstm_mlp", "cnn_gru_mlp", "cnn_mlp"],
    [1, 2],
    [32, 64, 128],
    [0.0, 0.2],
))

results_arch = []
batch_size_arch = 128

for arch, nl, u, dr in arch_grid:
    run_name = f"{EXPERIMENT_NAME}_arch_{arch}_layers{nl}_units{u}_drop{dr}"
    existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing.empty:
        mlflow.delete_run(existing.iloc[0].run_id)

    with mlflow.start_run(run_name=run_name):
        model = build_model(arch, nl, u, dr, lr=1e-3)
        mae_tr, mae_val, mae_te, h = fit_eval(model, batch_size=batch_size_arch)

        for epoch, (tl, vl) in enumerate(zip(h.history["loss"], h.history["val_loss"])):
            mlflow.log_metric("train_loss", tl, step=epoch)
            mlflow.log_metric("val_loss",   vl, step=epoch)

        fig = plot_training_curve(h)
        mlflow.log_figure(fig, "plots/loss_curve.png")
        plt.close(fig)

        mlflow.log_param("arch",               arch)
        mlflow.log_param("n_layers",           nl)
        mlflow.log_param("units",              u)
        mlflow.log_param("dropout",            dr)
        mlflow.log_param("kernel_size",        KERNEL_SIZE)
        mlflow.log_param("learning_rate",      1e-3)
        mlflow.log_param("batch_size",         batch_size_arch)
        mlflow.log_param("input_window_size",  INPUT_W)
        mlflow.log_param("output_window_size", OUTPUT_W)
        mlflow.log_param("n_params",           model.count_params())
        mlflow.log_param("epochs",             len(h.history["loss"]))

        mlflow.log_metric("train_mae", mae_tr)
        mlflow.log_metric("val_mae",   mae_val)
        mlflow.log_metric("test_mae",  mae_te)

        mlflow.keras.log_model(model, name="model")

        results_arch.append({
            "arch": arch, "n_layers": nl, "units": u, "dropout": dr,
            "MAE_train": mae_tr, "MAE_val": mae_val, "MAE_test": mae_te,
            "epochs": len(h.history["loss"]), "n_params": model.count_params(),
        })
        print(f"arch={arch:<10} layers={nl} units={u:>3} dropout={dr}  ->  val={mae_val:.6f} | train={mae_tr:.6f} | test={mae_te:.6f}")

results_arch_df = pd.DataFrame(results_arch).sort_values("MAE_val").reset_index(drop=True)

2026/05/10 19:08:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 32 dropout=0.0  ->  val=0.000931 | train=0.001269 | test=0.001286

2026/05/10 19:08:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 32 dropout=0.2  ->  val=0.000929 | train=0.001269 | test=0.001275

2026/05/10 19:08:50 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 64 dropout=0.0  ->  val=0.000940 | train=0.001268 | test=0.001290

2026/05/10 19:09:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 64 dropout=0.2  ->  val=0.000941 | train=0.001277 | test=0.001287

2026/05/10 19:09:18 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units=128 dropout=0.0  ->  val=0.000948 | train=0.001271 | test=0.001284

2026/05/10 19:09:29 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units=128 dropout=0.2  ->  val=0.000947 | train=0.001289 | test=0.001290

2026/05/10 19:09:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 32 dropout=0.0  ->  val=0.000937 | train=0.001266 | test=0.001290

2026/05/10 19:10:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 32 dropout=0.2  ->  val=0.000949 | train=0.001270 | test=0.001274

2026/05/10 19:10:14 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 64 dropout=0.0  ->  val=0.000952 | train=0.001274 | test=0.001288

2026/05/10 19:10:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 64 dropout=0.2  ->  val=0.000941 | train=0.001267 | test=0.001277

2026/05/10 19:10:59 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units=128 dropout=0.0  ->  val=0.000939 | train=0.001282 | test=0.001288

2026/05/10 19:11:34 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units=128 dropout=0.2  ->  val=0.000939 | train=0.001272 | test=0.001287

2026/05/10 19:11:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 32 dropout=0.0  ->  val=0.000932 | train=0.001275 | test=0.001293

2026/05/10 19:11:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 32 dropout=0.2  ->  val=0.000936 | train=0.001274 | test=0.001288

2026/05/10 19:12:08 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 64 dropout=0.0  ->  val=0.000937 | train=0.001267 | test=0.001281

2026/05/10 19:12:18 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 64 dropout=0.2  ->  val=0.000940 | train=0.001283 | test=0.001279

2026/05/10 19:12:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units=128 dropout=0.0  ->  val=0.000949 | train=0.001316 | test=0.001325

2026/05/10 19:12:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units=128 dropout=0.2  ->  val=0.000954 | train=0.001307 | test=0.001301

2026/05/10 19:12:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 32 dropout=0.0  ->  val=0.000961 | train=0.001279 | test=0.001290

2026/05/10 19:13:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 32 dropout=0.2  ->  val=0.000951 | train=0.001277 | test=0.001283

2026/05/10 19:13:22 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 64 dropout=0.0  ->  val=0.000948 | train=0.001277 | test=0.001286

2026/05/10 19:13:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 64 dropout=0.2  ->  val=0.000954 | train=0.001285 | test=0.001281

2026/05/10 19:14:18 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units=128 dropout=0.0  ->  val=0.000934 | train=0.001270 | test=0.001280

2026/05/10 19:14:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units=128 dropout=0.2  ->  val=0.000951 | train=0.001304 | test=0.001304

2026/05/10 19:14:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.0  ->  val=0.000961 | train=0.001249 | test=0.001322

2026/05/10 19:14:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.2  ->  val=0.000955 | train=0.001263 | test=0.001313

2026/05/10 19:15:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.0  ->  val=0.000957 | train=0.001275 | test=0.001320

2026/05/10 19:15:14 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.2  ->  val=0.000962 | train=0.001278 | test=0.001319

2026/05/10 19:15:27 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.0  ->  val=0.000965 | train=0.001269 | test=0.001336

2026/05/10 19:15:41 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.2  ->  val=0.000950 | train=0.001278 | test=0.001323

2026/05/10 19:15:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.0  ->  val=0.000938 | train=0.001276 | test=0.001281

2026/05/10 19:16:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.2  ->  val=0.000947 | train=0.001277 | test=0.001277

2026/05/10 19:16:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.0  ->  val=0.000975 | train=0.001280 | test=0.001296

2026/05/10 19:16:33 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.2  ->  val=0.000949 | train=0.001170 | test=0.001343

2026/05/10 19:16:52 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.0  ->  val=0.000951 | train=0.001284 | test=0.001303

2026/05/10 19:17:12 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.2  ->  val=0.000949 | train=0.001273 | test=0.001273

2026/05/10 19:17:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.0  ->  val=0.000955 | train=0.001281 | test=0.001305

2026/05/10 19:17:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.2  ->  val=0.000953 | train=0.001289 | test=0.001305

2026/05/10 19:17:40 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.0  ->  val=0.000954 | train=0.001272 | test=0.001320

2026/05/10 19:17:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.2  ->  val=0.000949 | train=0.001268 | test=0.001317

2026/05/10 19:18:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.0  ->  val=0.000944 | train=0.001276 | test=0.001318

2026/05/10 19:18:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.2  ->  val=0.000958 | train=0.001269 | test=0.001289

2026/05/10 19:18:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.0  ->  val=0.000956 | train=0.001282 | test=0.001288

2026/05/10 19:18:40 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.2  ->  val=0.000940 | train=0.001271 | test=0.001283

2026/05/10 19:18:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.0  ->  val=0.000953 | train=0.001258 | test=0.001334

2026/05/10 19:19:08 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.2  ->  val=0.000954 | train=0.001288 | test=0.001315

2026/05/10 19:19:29 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.0  ->  val=0.000983 | train=0.001229 | test=0.001369

2026/05/10 19:19:59 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.2  ->  val=0.000957 | train=0.001200 | test=0.001343

2026/05/10 19:20:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.0  ->  val=0.000929 | train=0.001273 | test=0.001269

2026/05/10 19:20:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.2  ->  val=0.000933 | train=0.001272 | test=0.001264

2026/05/10 19:20:25 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.0  ->  val=0.000932 | train=0.001270 | test=0.001268

2026/05/10 19:20:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.2  ->  val=0.000933 | train=0.001273 | test=0.001268

2026/05/10 19:20:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.0  ->  val=0.000939 | train=0.001270 | test=0.001277

2026/05/10 19:21:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.2  ->  val=0.000931 | train=0.001269 | test=0.001262

2026/05/10 19:21:15 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.0  ->  val=0.000932 | train=0.001274 | test=0.001273

2026/05/10 19:21:27 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.2  ->  val=0.000936 | train=0.001273 | test=0.001276

2026/05/10 19:21:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.0  ->  val=0.000922 | train=0.001273 | test=0.001267

2026/05/10 19:21:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.2  ->  val=0.000936 | train=0.001274 | test=0.001274

2026/05/10 19:22:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.0  ->  val=0.000950 | train=0.001278 | test=0.001274

2026/05/10 19:22:34 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.2  ->  val=0.000936 | train=0.001270 | test=0.001267

2026/05/10 19:22:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.0  ->  val=0.000926 | train=0.001271 | test=0.001267

2026/05/10 19:22:52 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.2  ->  val=0.000929 | train=0.001271 | test=0.001261

2026/05/10 19:23:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.0  ->  val=0.000931 | train=0.001270 | test=0.001266

2026/05/10 19:23:12 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.2  ->  val=0.000932 | train=0.001272 | test=0.001267

2026/05/10 19:23:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.0  ->  val=0.000934 | train=0.001272 | test=0.001270

2026/05/10 19:23:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.2  ->  val=0.000937 | train=0.001273 | test=0.001273

2026/05/10 19:23:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.0  ->  val=0.000933 | train=0.001270 | test=0.001264

2026/05/10 19:24:00 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.2  ->  val=0.000935 | train=0.001274 | test=0.001270

2026/05/10 19:24:14 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.0  ->  val=0.000928 | train=0.001273 | test=0.001267

2026/05/10 19:24:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.2  ->  val=0.000937 | train=0.001273 | test=0.001275

2026/05/10 19:24:50 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.0  ->  val=0.000938 | train=0.001273 | test=0.001278

2026/05/10 19:25:11 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.2  ->  val=0.000932 | train=0.001272 | test=0.001268

2026/05/10 19:25:18 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.0  ->  val=0.000930 | train=0.001276 | test=0.001285

2026/05/10 19:25:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.2  ->  val=0.000923 | train=0.001273 | test=0.001275

2026/05/10 19:25:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.0  ->  val=0.000935 | train=0.001272 | test=0.001288

2026/05/10 19:25:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.2  ->  val=0.000932 | train=0.001272 | test=0.001279

2026/05/10 19:25:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.0  ->  val=0.000935 | train=0.001270 | test=0.001268

2026/05/10 19:25:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.2  ->  val=0.000933 | train=0.001274 | test=0.001274

2026/05/10 19:25:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.0  ->  val=0.000937 | train=0.001273 | test=0.001275

2026/05/10 19:26:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.2  ->  val=0.000934 | train=0.001271 | test=0.001271

2026/05/10 19:26:11 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.0  ->  val=0.000930 | train=0.001275 | test=0.001268

2026/05/10 19:26:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.2  ->  val=0.000936 | train=0.001273 | test=0.001276

2026/05/10 19:26:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.0  ->  val=0.000933 | train=0.001273 | test=0.001275

2026/05/10 19:26:33 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.2  ->  val=0.000924 | train=0.001270 | test=0.001262

### Resultados — Etapa 1 (top 10)

In [5]:
results_arch_df.head(10)

,arch,n_layers,units,dropout,MAE_train,MAE_val,MAE_test,epochs,n_params
0,cnn_lstm_mlp,2,64,0.0,0.001273,0.000922,0.001267,11,77527
1,cnn_mlp,1,32,0.2,0.001273,0.000923,0.001275,12,4055
2,cnn_mlp,2,128,0.2,0.001270,0.000924,0.001262,11,35223
3,cnn_gru_mlp,1,32,0.0,0.001271,0.000926,0.001267,11,10551
4,cnn_gru_mlp,2,64,0.0,0.001273,0.000928,0.001267,11,61399
5,lstm,1,32,0.2,0.001269,0.000929,0.001275,31,7927
6,cnn_gru_mlp,1,32,0.2,0.001271,0.000929,0.001261,11,10551
7,cnn_lstm_mlp,1,32,0.0,0.001273,0.000929,0.001269,12,12535
8,cnn_mlp,2,64,0.0,0.001275,0.000930,0.001268,11,11479
9,cnn_mlp,1,32,0.0,0.001276,0.000930,0.001285,12,4055

## Etapa 2 — Hiperparámetros de entrenamiento

Se fija la arquitectura ganadora de la Etapa 1 y se busca sobre `learning_rate` × `batch_size`.

Criterio de selección: **MAE de validación mínimo**.

In [6]:
best_arch = results_arch_df.iloc[0]
print(f"Mejor arquitectura: arch={best_arch.arch}  n_layers={int(best_arch.n_layers)}  units={int(best_arch.units)}  dropout={best_arch.dropout}")
print(f"  MAE val = {best_arch.MAE_val:.6f}")

train_grid = list(itertools.product([1e-2, 1e-3, 1e-4], [64, 128, 256]))

results_train = []
for lr, bs in train_grid:
    run_name = f"{EXPERIMENT_NAME}_train_{best_arch.arch}_lr{lr:.0e}_batch{bs}"
    existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing.empty:
        mlflow.delete_run(existing.iloc[0].run_id)

    with mlflow.start_run(run_name=run_name):
        model = build_model(
            best_arch.arch, int(best_arch.n_layers), int(best_arch.units),
            float(best_arch.dropout), lr=lr,
        )
        mae_tr, mae_val, mae_te, h = fit_eval(model, batch_size=bs)

        for epoch, (tl, vl) in enumerate(zip(h.history["loss"], h.history["val_loss"])):
            mlflow.log_metric("train_loss", tl, step=epoch)
            mlflow.log_metric("val_loss",   vl, step=epoch)

        fig = plot_training_curve(h)
        mlflow.log_figure(fig, "plots/loss_curve.png")
        plt.close(fig)

        mlflow.log_param("arch",               best_arch.arch)
        mlflow.log_param("n_layers",           int(best_arch.n_layers))
        mlflow.log_param("units",              int(best_arch.units))
        mlflow.log_param("dropout",            float(best_arch.dropout))
        mlflow.log_param("kernel_size",        KERNEL_SIZE)
        mlflow.log_param("learning_rate",      lr)
        mlflow.log_param("batch_size",         bs)
        mlflow.log_param("input_window_size",  INPUT_W)
        mlflow.log_param("output_window_size", OUTPUT_W)
        mlflow.log_param("n_params",           model.count_params())
        mlflow.log_param("epochs",             len(h.history["loss"]))

        mlflow.log_metric("train_mae", mae_tr)
        mlflow.log_metric("val_mae",   mae_val)
        mlflow.log_metric("test_mae",  mae_te)

        mlflow.keras.log_model(model, name="model")

        results_train.append({
            "learning_rate": lr, "batch_size": bs,
            "MAE_train": mae_tr, "MAE_val": mae_val, "MAE_test": mae_te,
            "epochs": len(h.history["loss"]),
        })
        print(f"lr={lr:.0e} batch={bs:>3}  ->  val={mae_val:.6f} | train={mae_tr:.6f} | test={mae_te:.6f}")

results_train_df = pd.DataFrame(results_train).sort_values("MAE_val").reset_index(drop=True)

Mejor arquitectura: arch=cnn_lstm_mlp  n_layers=2  units=64  dropout=0.0
  MAE val = 0.000922

2026/05/10 19:26:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch= 64  ->  val=0.001061 | train=0.001376 | test=0.001363

2026/05/10 19:27:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch=128  ->  val=0.000968 | train=0.001324 | test=0.001325

2026/05/10 19:27:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch=256  ->  val=0.000940 | train=0.001288 | test=0.001302

2026/05/10 19:28:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch= 64  ->  val=0.000942 | train=0.001284 | test=0.001269

2026/05/10 19:28:14 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch=128  ->  val=0.000922 | train=0.001273 | test=0.001267

2026/05/10 19:28:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch=256  ->  val=0.000931 | train=0.001270 | test=0.001266

2026/05/10 19:28:41 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch= 64  ->  val=0.000936 | train=0.001267 | test=0.001265

2026/05/10 19:28:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch=128  ->  val=0.000930 | train=0.001267 | test=0.001267

2026/05/10 19:29:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch=256  ->  val=0.000933 | train=0.001266 | test=0.001264

In [7]:
results_train_df

   learning_rate  batch_size  MAE_train   MAE_val  MAE_test  epochs
0         0.0010         128   0.001273  0.000922  0.001267      11
1         0.0001         128   0.001267  0.000930  0.001267      11
2         0.0010         256   0.001270  0.000931  0.001266      11
3         0.0001         256   0.001266  0.000933  0.001264      11
4         0.0001          64   0.001267  0.000936  0.001265      11
5         0.0100         256   0.001288  0.000940  0.001302      12
6         0.0010          64   0.001284  0.000942  0.001269      52
7         0.0100         128   0.001324  0.000968  0.001325      11
8         0.0100          64   0.001376  0.001061  0.001363      20

## Modelo final y comparación con benchmarks

Se reentrena el modelo ganador con la configuración completa y se compara con la regresión lineal.

In [8]:
from util import load_benchmark

best_train = results_train_df.iloc[0]
print("Configuración ganadora:")
print(f"  arch          = {best_arch.arch}")
print(f"  n_layers      = {int(best_arch.n_layers)}")
print(f"  units         = {int(best_arch.units)}")
print(f"  dropout       = {float(best_arch.dropout)}")
print(f"  learning_rate = {best_train.learning_rate:.0e}")
print(f"  batch_size    = {int(best_train.batch_size)}")

final_model = build_model(
    best_arch.arch, int(best_arch.n_layers), int(best_arch.units),
    float(best_arch.dropout), lr=float(best_train.learning_rate),
)
mae_tr_f, mae_val_f, mae_te_f, hist_f = fit_eval(
    final_model, batch_size=int(best_train.batch_size), patience=20,
)

linreg_bench = load_benchmark("lr_benchmark")
linreg_row   = linreg_bench[
    (linreg_bench.input_window == INPUT_W) & (linreg_bench.output_window == OUTPUT_W)
].iloc[0]

run_name_final = f"{EXPERIMENT_NAME}_final"
existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name_final}"')
if not existing.empty:
    mlflow.delete_run(existing.iloc[0].run_id)

with mlflow.start_run(run_name=run_name_final):
    for epoch, (tl, vl) in enumerate(zip(hist_f.history["loss"], hist_f.history["val_loss"])):
        mlflow.log_metric("train_loss", tl, step=epoch)
        mlflow.log_metric("val_loss",   vl, step=epoch)

    fig_f = plot_training_curve(hist_f)
    mlflow.log_figure(fig_f, "plots/loss_curve.png")
    plt.close(fig_f)

    mlflow.log_param("arch",               best_arch.arch)
    mlflow.log_param("n_layers",           int(best_arch.n_layers))
    mlflow.log_param("units",              int(best_arch.units))
    mlflow.log_param("dropout",            float(best_arch.dropout))
    mlflow.log_param("kernel_size",        KERNEL_SIZE)
    mlflow.log_param("learning_rate",      float(best_train.learning_rate))
    mlflow.log_param("batch_size",         int(best_train.batch_size))
    mlflow.log_param("input_window_size",  INPUT_W)
    mlflow.log_param("output_window_size", OUTPUT_W)
    mlflow.log_param("n_params",           final_model.count_params())
    mlflow.log_param("epochs",             len(hist_f.history["loss"]))
    mlflow.log_metric("train_mae",         mae_tr_f)
    mlflow.log_metric("val_mae",           mae_val_f)
    mlflow.log_metric("test_mae",          mae_te_f)
    mlflow.keras.log_model(final_model, name="model")

summary = pd.DataFrame([
    {"modelo": "Regresión lineal",                 "MAE_train": linreg_row.MAE_train, "MAE_test": linreg_row.MAE_test},
    {"modelo": f"Mejor mixto ({best_arch.arch})",  "MAE_train": mae_tr_f,             "MAE_test": mae_te_f},
])
summary["Δ vs lin.reg. (test)"] = summary["MAE_test"] - linreg_row.MAE_test
display(summary)

Configuración ganadora:
  arch          = cnn_lstm_mlp
  n_layers      = 2
  units         = 64
  dropout       = 0.0
  learning_rate = 1e-03
  batch_size    = 128

2026/05/10 19:29:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

                       modelo  MAE_train  MAE_test  Δ vs lin.reg. (test)
0            Regresión lineal   0.001263  0.001271              0.000000
1  Mejor mixto (cnn_lstm_mlp)   0.001273  0.001267             -0.000004

## Top-10 configuraciones por etapa

In [9]:
fig, axes = plt.subplots(1, 2, figsize=(16, 5))

def plot_top(ax, df, label_cols, title, top=10):
    top_df = df.head(top).iloc[::-1]
    labels = top_df[label_cols].astype(str).agg(" · ".join, axis=1)
    ypos = np.arange(len(top_df))
    ax.barh(ypos - 0.2, top_df["MAE_val"],   height=0.4, label="MAE val",   color="steelblue")
    ax.barh(ypos + 0.2, top_df["MAE_train"], height=0.4, label="MAE train", color="lightgray")
    ax.set_yticks(ypos)
    ax.set_yticklabels(labels, fontsize=9)
    ax.set_xlabel("MAE")
    ax.set_title(title)
    ax.legend(loc="lower right")
    ax.grid(True, axis="x", alpha=0.3)

plot_top(axes[0], results_arch_df,  ["arch", "n_layers", "units", "dropout"],
         "Etapa 1 — arquitectura (top 10)")
plot_top(axes[1], results_train_df, ["learning_rate", "batch_size"],
         "Etapa 2 — entrenamiento (top 9)")

plt.tight_layout()
plt.show()

/var/folders/py/c5_xfbqn469g5_844mv32gt40000gn/T/ipykernel_34614/3018486118.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()