# Modelos Mixtos — Combinaciones Conv1D, LSTM, GRU y MLP

Este notebook explora combinaciones de capas **convolucionales** (Conv1D), **recurrentes** (LSTM, GRU) y **densas** (MLP) para la configuración fija:

- **Ventana de entrada:** 90 días
- **Ventana de salida:** 30 días

Arquitecturas evaluadas:
- `lstm` — LSTM apiladas
- `gru` — GRU apiladas
- `cnn_lstm` — Conv1D → LSTM
- `cnn_gru` — Conv1D → GRU

- `cnn_lstm_mlp` — Conv1D → LSTM → MLP

- `cnn_gru_mlp` — Conv1D → GRU → MLP

- `cnn_mlp` — Conv1D → MLP

**Adaptación para input_w=90:** a diferencia del caso input_w=5 (donde `kernel_size=3` era fijo),
con 90 pasos temporales el tamaño del kernel Conv1D es un hiperparámetro relevante. Se añade
`kernel_size ∈ {3, 5, 7}` al grid de la Etapa 1 **solo para las variantes CNN**.

La búsqueda se realiza en dos etapas:
1. **Etapa 1 — Arquitectura**: tipo de red × n_layers × units × dropout (× kernel_size para CNN) — 204 combinaciones
2. **Etapa 2 — Entrenamiento**: learning rate × batch size con la mejor arquitectura de la Etapa 1 (9 combinaciones)

In [1]:
import sys
import itertools
import mlflow
from pathlib import Path

# Busca util.py subiendo niveles desde el directorio actual
_here = Path.cwd()
PROJECT_ROOT = next(
    p for p in [_here, _here.parent, _here.parent.parent, _here.parent.parent.parent]
    if (p / 'util.py').exists()
)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

mlflow.set_tracking_uri(f"sqlite:///{PROJECT_ROOT / 'model' / 'mlflow.db'}")

EXPERIMENT_NAME = "Modelos_Mixtos_input90_output30"
mlflow.set_experiment(EXPERIMENT_NAME)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import keras
from keras.models import Sequential
from keras.layers import LSTM, GRU, Dense, Input, Conv1D, GlobalAveragePooling1D, Dropout
from keras.callbacks import EarlyStopping
from keras.optimizers import Adam

from sklearn.metrics import mean_absolute_error

from util import get_train_test, RANDOM_SEED, plot_training_curve

np.random.seed(RANDOM_SEED)
keras.utils.set_random_seed(RANDOM_SEED)

2026/05/12 00:26:43 INFO mlflow.tracking.fluent: Experiment with name 'Modelos_Mixtos_input90_output30' does not exist. Creating a new experiment.

## Carga de datos

In [2]:
INPUT_W  = 90
OUTPUT_W = 30

def load_seq_data(input_window_size, output_window_size):
    d = get_train_test(input_window_size=input_window_size, output_window_size=output_window_size)
    X_train, X_test = d.X_train, d.X_test
    y_train, y_test = d.y_train, d.y_test
    val_size         = int(0.10 * X_train.shape[0])
    X_val, y_val     = X_train[-val_size:], y_train[-val_size:]
    X_train, y_train = X_train[:-val_size], y_train[:-val_size]
    return X_train, y_train, X_val, y_val, X_test, y_test

X_tr, y_tr, X_val, y_val, X_te, y_te = load_seq_data(INPUT_W, OUTPUT_W)

print(f"X_tr:  {X_tr.shape}   y_tr:  {y_tr.shape}")
print(f"X_val: {X_val.shape}  y_val: {y_val.shape}")
print(f"X_te:  {X_te.shape}   y_te:  {y_te.shape}")

X_tr:  (13014, 90, 23)   y_tr:  (13014, 23)
X_val: (1445, 90, 23)  y_val: (1445, 23)
X_te:  (1607, 90, 23)   y_te:  (1607, 23)

## Arquitecturas implementadas

La función `build_model` construye el modelo según el argumento `arch`:

| `arch`     | Capas                                      |
|------------|--------------------------------------------|
| `lstm`     | Input → LSTM × n_layers → Dense            |
| `gru`      | Input → GRU × n_layers → Dense             |
| `cnn_lstm` | Input → Conv1D → LSTM × n_layers → Dense   |
| `cnn_gru`  | Input → Conv1D → GRU × n_layers → Dense    |

| `cnn_lstm_mlp` | Input → Conv1D → LSTM × n_layers → MLP → Dense |

| `cnn_gru_mlp`  | Input → Conv1D → GRU × n_layers → MLP → Dense  |

| `cnn_mlp`      | Input → Conv1D → GlobalAveragePooling1D → MLP × n_layers → Dense |

Para las variantes CNN, `kernel_size` es ahora un hiperparámetro explorado en el grid
(valores: 3, 5, 7). Con 90 pasos de entrada, kernels más grandes capturan patrones de
frecuencia más baja (semanal ≈ 5, quincenal ≈ 7).

In [3]:
def add_mlp_head(model, n_layers, units, dropout):
    for i in range(n_layers):
        layer_units = units if i == 0 else max(units // 2, 16)
        model.add(Dense(layer_units, activation="relu"))
        if dropout > 0:
            model.add(Dropout(dropout))


def build_model(arch, n_layers, units, dropout, kernel_size=5, lr=1e-3):
    keras.utils.set_random_seed(RANDOM_SEED)
    m = Sequential()
    m.add(Input(shape=(X_tr.shape[1], X_tr.shape[2])))

    if arch == "lstm":
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "gru":
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_lstm":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_gru":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_lstm_mlp":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))
        add_mlp_head(m, 2, units, dropout)

    elif arch == "cnn_gru_mlp":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))
        add_mlp_head(m, 2, units, dropout)

    elif arch == "cnn_mlp":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        m.add(GlobalAveragePooling1D())
        add_mlp_head(m, n_layers, units, dropout)

    else:
        raise ValueError(f"Arquitectura no soportada: {arch}")

    m.add(Dense(y_tr.shape[1]))
    m.compile(loss="mean_absolute_error", optimizer=Adam(learning_rate=lr))
    return m



def fit_eval(model, batch_size=128, epochs=200, patience=10, verbose=0):
    es = EarlyStopping(monitor="val_loss", patience=patience, restore_best_weights=True)
    h = model.fit(
        X_tr, y_tr,
        validation_data=(X_val, y_val),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=[es],
        verbose=verbose,
    )
    mae_tr  = mean_absolute_error(y_tr,  model.predict(X_tr,  verbose=0))
    mae_val = mean_absolute_error(y_val, model.predict(X_val, verbose=0))
    mae_te  = mean_absolute_error(y_te,  model.predict(X_te,  verbose=0))
    return mae_tr, mae_val, mae_te, h

## Etapa 1 — Búsqueda de arquitectura

Grid:
- **LSTM / GRU**: `arch` × `n_layers` × `units` × `dropout` → 24 combinaciones
- **CNN / CNN-RNN / CNN-RNN-MLP**: `arch` × `n_layers` × `units` × `dropout` × `kernel_size` → 180 combinaciones

Total: **204 combinaciones**. Learning rate y batch size fijos en esta etapa.

Criterio de selección: **MAE de validación mínimo**.

In [4]:
pure_rnn_combos = [
    (arch, nl, u, dr, None)
    for arch, nl, u, dr in itertools.product(
        ["lstm", "gru"], [1, 2], [32, 64, 128], [0.0, 0.2]
    )
]
cnn_combos = [
    (arch, nl, u, dr, ks)
    for arch, nl, u, dr, ks in itertools.product(
        ["cnn_lstm", "cnn_gru", "cnn_lstm_mlp", "cnn_gru_mlp", "cnn_mlp"], [1, 2], [32, 64, 128], [0.0, 0.2], [3, 5, 7]
    )
]
arch_grid = pure_rnn_combos + cnn_combos
print(f"Total combinaciones Etapa 1: {len(arch_grid)}  (RNN puras: {len(pure_rnn_combos)}, CNN: {len(cnn_combos)})")

results_arch = []
batch_size_arch = 128

for arch, nl, u, dr, ks in arch_grid:
    ks_eff = ks if ks is not None else 0  # 0 = no aplica (RNN pura)
    run_name = (
        f"{EXPERIMENT_NAME}_arch_{arch}_layers{nl}_units{u}_drop{dr}"
        + (f"_ks{ks_eff}" if ks is not None else "")
    )
    existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing.empty:
        mlflow.delete_run(existing.iloc[0].run_id)

    with mlflow.start_run(run_name=run_name):
        model = build_model(arch, nl, u, dr, kernel_size=ks_eff if ks is not None else 5, lr=1e-3)
        mae_tr, mae_val, mae_te, h = fit_eval(model, batch_size=batch_size_arch)

        for epoch, (tl, vl) in enumerate(zip(h.history["loss"], h.history["val_loss"])):
            mlflow.log_metric("train_loss", tl, step=epoch)
            mlflow.log_metric("val_loss",   vl, step=epoch)

        fig = plot_training_curve(h)
        mlflow.log_figure(fig, "plots/loss_curve.png")
        plt.close(fig)

        mlflow.log_param("arch",               arch)
        mlflow.log_param("n_layers",           nl)
        mlflow.log_param("units",              u)
        mlflow.log_param("dropout",            dr)
        mlflow.log_param("kernel_size",        ks_eff)
        mlflow.log_param("learning_rate",      1e-3)
        mlflow.log_param("batch_size",         batch_size_arch)
        mlflow.log_param("input_window_size",  INPUT_W)
        mlflow.log_param("output_window_size", OUTPUT_W)
        mlflow.log_param("n_params",           model.count_params())
        mlflow.log_param("epochs",             len(h.history["loss"]))

        mlflow.log_metric("train_mae", mae_tr)
        mlflow.log_metric("val_mae",   mae_val)
        mlflow.log_metric("test_mae",  mae_te)

        mlflow.keras.log_model(model, name="model")

        results_arch.append({
            "arch": arch, "n_layers": nl, "units": u, "dropout": dr, "kernel_size": ks_eff,
            "MAE_train": mae_tr, "MAE_val": mae_val, "MAE_test": mae_te,
            "epochs": len(h.history["loss"]), "n_params": model.count_params(),
        })
        ks_str = f" ks={ks_eff}" if ks is not None else ""
        print(f"arch={arch:<10} layers={nl} units={u:>3} dropout={dr}{ks_str}  ->  val={mae_val:.6f} | train={mae_tr:.6f} | test={mae_te:.6f}")

results_arch_df = pd.DataFrame(results_arch).sort_values("MAE_val").reset_index(drop=True)

Total combinaciones Etapa 1: 204  (RNN puras: 24, CNN: 180)

2026/05/12 00:27:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 32 dropout=0.0  ->  val=0.001704 | train=0.002158 | test=0.002389

2026/05/12 00:28:23 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 32 dropout=0.2  ->  val=0.001703 | train=0.002167 | test=0.002350

2026/05/12 00:29:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 64 dropout=0.0  ->  val=0.001718 | train=0.002155 | test=0.002396

2026/05/12 00:30:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 64 dropout=0.2  ->  val=0.001718 | train=0.002176 | test=0.002363

2026/05/12 00:32:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units=128 dropout=0.0  ->  val=0.001725 | train=0.002164 | test=0.002406

2026/05/12 00:50:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units=128 dropout=0.2  ->  val=0.001718 | train=0.002173 | test=0.002387

2026/05/12 01:22:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 32 dropout=0.0  ->  val=0.001714 | train=0.002126 | test=0.002389

2026/05/12 01:39:14 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 32 dropout=0.2  ->  val=0.001719 | train=0.002177 | test=0.002360

2026/05/12 02:03:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 64 dropout=0.0  ->  val=0.001711 | train=0.002167 | test=0.002389

2026/05/12 02:06:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 64 dropout=0.2  ->  val=0.001722 | train=0.002151 | test=0.002370

2026/05/12 02:11:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units=128 dropout=0.0  ->  val=0.001740 | train=0.002178 | test=0.002399

2026/05/12 02:18:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units=128 dropout=0.2  ->  val=0.001711 | train=0.002156 | test=0.002369

2026/05/12 02:19:23 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 32 dropout=0.0  ->  val=0.001718 | train=0.002194 | test=0.002353

2026/05/12 02:19:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 32 dropout=0.2  ->  val=0.001720 | train=0.002205 | test=0.002352

2026/05/12 02:22:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 64 dropout=0.0  ->  val=0.001718 | train=0.002175 | test=0.002385

2026/05/12 02:24:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 64 dropout=0.2  ->  val=0.001716 | train=0.002178 | test=0.002368

2026/05/12 03:01:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units=128 dropout=0.0  ->  val=0.001724 | train=0.002169 | test=0.002413

2026/05/12 03:05:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units=128 dropout=0.2  ->  val=0.001729 | train=0.002191 | test=0.002374

2026/05/12 03:07:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 32 dropout=0.0  ->  val=0.001715 | train=0.002172 | test=0.002376

2026/05/12 03:09:00 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 32 dropout=0.2  ->  val=0.001720 | train=0.002186 | test=0.002342

2026/05/12 03:12:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 64 dropout=0.0  ->  val=0.001729 | train=0.002181 | test=0.002367

2026/05/12 03:16:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 64 dropout=0.2  ->  val=0.001717 | train=0.002176 | test=0.002356

2026/05/12 03:27:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units=128 dropout=0.0  ->  val=0.001722 | train=0.002158 | test=0.002384

2026/05/12 05:29:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units=128 dropout=0.2  ->  val=0.001717 | train=0.002173 | test=0.002359

2026/05/12 05:38:11 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.001723 | train=0.002204 | test=0.002348

2026/05/12 05:38:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.001733 | train=0.002201 | test=0.002364

2026/05/12 05:55:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.0 ks=7  ->  val=0.001730 | train=0.002212 | test=0.002372

2026/05/12 05:55:32 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.001722 | train=0.002205 | test=0.002346

2026/05/12 05:57:00 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.001722 | train=0.002201 | test=0.002344

2026/05/12 05:57:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.2 ks=7  ->  val=0.001721 | train=0.002192 | test=0.002342

2026/05/12 06:30:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.001746 | train=0.002214 | test=0.002393

2026/05/12 06:46:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.001748 | train=0.002205 | test=0.002405

2026/05/12 07:03:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.0 ks=7  ->  val=0.001757 | train=0.002193 | test=0.002405

2026/05/12 07:04:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.001724 | train=0.002050 | test=0.002393

2026/05/12 07:05:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.001723 | train=0.002198 | test=0.002358

2026/05/12 07:06:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.2 ks=7  ->  val=0.001729 | train=0.002193 | test=0.002356

2026/05/12 07:09:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.0 ks=3  ->  val=0.001785 | train=0.002043 | test=0.002497

2026/05/12 07:11:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.0 ks=5  ->  val=0.001780 | train=0.001973 | test=0.002450

2026/05/12 07:14:20 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.0 ks=7  ->  val=0.001769 | train=0.001969 | test=0.002492

2026/05/12 07:16:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.2 ks=3  ->  val=0.001754 | train=0.002199 | test=0.002392

2026/05/12 07:18:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.2 ks=5  ->  val=0.001757 | train=0.002093 | test=0.002409

2026/05/12 07:21:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.2 ks=7  ->  val=0.001750 | train=0.002162 | test=0.002389

2026/05/12 07:21:57 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.001767 | train=0.002225 | test=0.002386

2026/05/12 07:22:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.001754 | train=0.002211 | test=0.002393

2026/05/12 07:23:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.0 ks=7  ->  val=0.001763 | train=0.002197 | test=0.002393

2026/05/12 07:24:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.001726 | train=0.002200 | test=0.002333

2026/05/12 07:25:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.001728 | train=0.002186 | test=0.002341

2026/05/12 07:26:47 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.2 ks=7  ->  val=0.001730 | train=0.002178 | test=0.002354

2026/05/12 07:55:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.001742 | train=0.002150 | test=0.002385

2026/05/12 08:16:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.001762 | train=0.002021 | test=0.002447

2026/05/12 08:40:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.0 ks=7  ->  val=0.001787 | train=0.002005 | test=0.002408

2026/05/12 09:31:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.001729 | train=0.001963 | test=0.002388

2026/05/12 09:45:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.001746 | train=0.002197 | test=0.002355

2026/05/12 09:47:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.2 ks=7  ->  val=0.001748 | train=0.002187 | test=0.002357

2026/05/12 09:51:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.0 ks=3  ->  val=0.001730 | train=0.002039 | test=0.002427

2026/05/12 09:54:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.0 ks=5  ->  val=0.001811 | train=0.002148 | test=0.002425

2026/05/12 09:58:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.0 ks=7  ->  val=0.001781 | train=0.002070 | test=0.002419

2026/05/12 10:03:29 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.2 ks=3  ->  val=0.001753 | train=0.001842 | test=0.002441

2026/05/12 10:07:20 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.2 ks=5  ->  val=0.001786 | train=0.002014 | test=0.002390

2026/05/12 10:11:27 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.2 ks=7  ->  val=0.001747 | train=0.001801 | test=0.002444

2026/05/12 10:12:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.001735 | train=0.002200 | test=0.002350

2026/05/12 10:12:35 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.001726 | train=0.002187 | test=0.002348

2026/05/12 10:13:08 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.0 ks=7  ->  val=0.001737 | train=0.002197 | test=0.002364

2026/05/12 10:13:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.001728 | train=0.002201 | test=0.002338

2026/05/12 10:14:14 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.001733 | train=0.002213 | test=0.002346

2026/05/12 10:15:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.2 ks=7  ->  val=0.001738 | train=0.001967 | test=0.002384

2026/05/12 10:15:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.001743 | train=0.002239 | test=0.002394

2026/05/12 10:16:50 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.001770 | train=0.002242 | test=0.002409

2026/05/12 10:17:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.0 ks=7  ->  val=0.001774 | train=0.002234 | test=0.002413

2026/05/12 10:19:34 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.001735 | train=0.001870 | test=0.002510

2026/05/12 10:21:08 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.001728 | train=0.001881 | test=0.002394

2026/05/12 10:22:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.2 ks=7  ->  val=0.001750 | train=0.002073 | test=0.002398

2026/05/12 10:24:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.0 ks=3  ->  val=0.001758 | train=0.002109 | test=0.002402

2026/05/12 10:26:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.0 ks=5  ->  val=0.001773 | train=0.002231 | test=0.002415

2026/05/12 10:28:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.0 ks=7  ->  val=0.001757 | train=0.002223 | test=0.002425

2026/05/12 10:31:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.2 ks=3  ->  val=0.001731 | train=0.001812 | test=0.002471

2026/05/12 10:33:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.2 ks=5  ->  val=0.001746 | train=0.002212 | test=0.002360

2026/05/12 10:36:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.2 ks=7  ->  val=0.001745 | train=0.001631 | test=0.002486

2026/05/12 10:38:08 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.001740 | train=0.001898 | test=0.002441

2026/05/12 10:39:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.001768 | train=0.002205 | test=0.002371

2026/05/12 10:40:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.0 ks=7  ->  val=0.001753 | train=0.002215 | test=0.002376

2026/05/12 10:41:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.001724 | train=0.002186 | test=0.002340

2026/05/12 10:42:23 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.001727 | train=0.002187 | test=0.002351

2026/05/12 10:43:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.2 ks=7  ->  val=0.001704 | train=0.001939 | test=0.002355

2026/05/12 10:45:34 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.001750 | train=0.002200 | test=0.002399

2026/05/12 10:47:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.001778 | train=0.002081 | test=0.002422

2026/05/12 10:49:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.0 ks=7  ->  val=0.001791 | train=0.002231 | test=0.002424

2026/05/12 10:52:12 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.001723 | train=0.001981 | test=0.002448

2026/05/12 10:54:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.001725 | train=0.002196 | test=0.002364

2026/05/12 10:57:10 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.2 ks=7  ->  val=0.001739 | train=0.001815 | test=0.002427

2026/05/12 11:01:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.0 ks=3  ->  val=0.001784 | train=0.002057 | test=0.002407

2026/05/12 11:04:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.0 ks=5  ->  val=0.001800 | train=0.002230 | test=0.002437

2026/05/12 11:07:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.0 ks=7  ->  val=0.001806 | train=0.002069 | test=0.002444

2026/05/12 11:14:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.2 ks=3  ->  val=0.001753 | train=0.001723 | test=0.002444

2026/05/12 11:19:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.2 ks=5  ->  val=0.001770 | train=0.001917 | test=0.002450

2026/05/12 11:24:52 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.2 ks=7  ->  val=0.001747 | train=0.001732 | test=0.002389

2026/05/12 11:25:25 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.001715 | train=0.002193 | test=0.002334

2026/05/12 11:25:52 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.001713 | train=0.002207 | test=0.002329

2026/05/12 11:26:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.0 ks=7  ->  val=0.001718 | train=0.002192 | test=0.002337

2026/05/12 11:27:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.001721 | train=0.002208 | test=0.002335

2026/05/12 11:27:32 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.001719 | train=0.002206 | test=0.002329

2026/05/12 11:28:20 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.2 ks=7  ->  val=0.001721 | train=0.002207 | test=0.002334

2026/05/12 11:29:10 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.001712 | train=0.002202 | test=0.002325

2026/05/12 11:30:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.001718 | train=0.002204 | test=0.002336

2026/05/12 11:30:57 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.0 ks=7  ->  val=0.001714 | train=0.002205 | test=0.002331

2026/05/12 11:31:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.001712 | train=0.002203 | test=0.002326

2026/05/12 11:32:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.001712 | train=0.002205 | test=0.002327

2026/05/12 11:33:33 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.2 ks=7  ->  val=0.001711 | train=0.002205 | test=0.002328

2026/05/12 11:35:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.0 ks=3  ->  val=0.001712 | train=0.002204 | test=0.002331

2026/05/12 11:37:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.0 ks=5  ->  val=0.001719 | train=0.002166 | test=0.002346

2026/05/12 11:39:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.0 ks=7  ->  val=0.001725 | train=0.002182 | test=0.002353

2026/05/12 11:41:14 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.2 ks=3  ->  val=0.001715 | train=0.002205 | test=0.002327

2026/05/12 11:43:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.2 ks=5  ->  val=0.001712 | train=0.002208 | test=0.002332

2026/05/12 11:44:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.2 ks=7  ->  val=0.001712 | train=0.002206 | test=0.002330

2026/05/12 11:45:34 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.001718 | train=0.002205 | test=0.002330

2026/05/12 11:46:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.001718 | train=0.002204 | test=0.002325

2026/05/12 11:47:08 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.0 ks=7  ->  val=0.001720 | train=0.002206 | test=0.002330

2026/05/12 11:47:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.001717 | train=0.002205 | test=0.002330

2026/05/12 11:48:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.001718 | train=0.002205 | test=0.002331

2026/05/12 11:49:32 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.2 ks=7  ->  val=0.001716 | train=0.002206 | test=0.002333

2026/05/12 11:51:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.001721 | train=0.002209 | test=0.002329

2026/05/12 11:52:37 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.001724 | train=0.002209 | test=0.002328

2026/05/12 11:54:10 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.0 ks=7  ->  val=0.001717 | train=0.002203 | test=0.002327

2026/05/12 11:55:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.001715 | train=0.002205 | test=0.002330

2026/05/12 11:57:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.001715 | train=0.002205 | test=0.002333

2026/05/12 11:59:12 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.2 ks=7  ->  val=0.001717 | train=0.002206 | test=0.002331

2026/05/12 12:03:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.0 ks=3  ->  val=0.001716 | train=0.002025 | test=0.002389

2026/05/12 12:06:34 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.0 ks=5  ->  val=0.001724 | train=0.002211 | test=0.002348

2026/05/12 12:10:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.0 ks=7  ->  val=0.001709 | train=0.002188 | test=0.002353

2026/05/12 12:13:23 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.2 ks=3  ->  val=0.001711 | train=0.002202 | test=0.002326

2026/05/12 12:16:41 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.2 ks=5  ->  val=0.001715 | train=0.002205 | test=0.002329

2026/05/12 12:20:00 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.2 ks=7  ->  val=0.001714 | train=0.002203 | test=0.002334

2026/05/12 12:20:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.001718 | train=0.002204 | test=0.002332

2026/05/12 12:20:59 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.001718 | train=0.002206 | test=0.002335

2026/05/12 12:21:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.0 ks=7  ->  val=0.001717 | train=0.002205 | test=0.002335

2026/05/12 12:21:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.001717 | train=0.002207 | test=0.002330

2026/05/12 12:22:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.001716 | train=0.002206 | test=0.002330

2026/05/12 12:22:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.2 ks=7  ->  val=0.001719 | train=0.002208 | test=0.002332

2026/05/12 12:24:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.001720 | train=0.002165 | test=0.002334

2026/05/12 12:25:08 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.001715 | train=0.002198 | test=0.002334

2026/05/12 12:26:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.0 ks=7  ->  val=0.001715 | train=0.002204 | test=0.002329

2026/05/12 12:26:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.001716 | train=0.002205 | test=0.002327

2026/05/12 12:27:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.001715 | train=0.002205 | test=0.002328

2026/05/12 12:28:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.2 ks=7  ->  val=0.001711 | train=0.002204 | test=0.002326

2026/05/12 12:30:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.0 ks=3  ->  val=0.001718 | train=0.002200 | test=0.002328

2026/05/12 12:32:22 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.0 ks=5  ->  val=0.001721 | train=0.002194 | test=0.002331

2026/05/12 12:34:00 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.0 ks=7  ->  val=0.001749 | train=0.002218 | test=0.002340

2026/05/12 12:35:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.2 ks=3  ->  val=0.001711 | train=0.002202 | test=0.002325

2026/05/12 12:37:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.2 ks=5  ->  val=0.001714 | train=0.002202 | test=0.002326

2026/05/12 12:38:57 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.2 ks=7  ->  val=0.001714 | train=0.002203 | test=0.002327

2026/05/12 12:40:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.001719 | train=0.002206 | test=0.002327

2026/05/12 12:41:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.001719 | train=0.002207 | test=0.002333

2026/05/12 12:42:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.0 ks=7  ->  val=0.001721 | train=0.002207 | test=0.002332

2026/05/12 12:43:18 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.001712 | train=0.002205 | test=0.002329

2026/05/12 12:44:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.001718 | train=0.002207 | test=0.002331

2026/05/12 12:45:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.2 ks=7  ->  val=0.001718 | train=0.002207 | test=0.002331

2026/05/12 12:47:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.001719 | train=0.002208 | test=0.002333

2026/05/12 12:48:37 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.001723 | train=0.002220 | test=0.002346

2026/05/12 12:50:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.0 ks=7  ->  val=0.001723 | train=0.002202 | test=0.002339

2026/05/12 12:52:15 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.001718 | train=0.002207 | test=0.002336

2026/05/12 12:53:59 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.001720 | train=0.002207 | test=0.002335

2026/05/12 12:55:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.2 ks=7  ->  val=0.001718 | train=0.002206 | test=0.002332

2026/05/12 12:59:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.0 ks=3  ->  val=0.001717 | train=0.002190 | test=0.002324

2026/05/12 13:02:25 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.0 ks=5  ->  val=0.001721 | train=0.002195 | test=0.002335

2026/05/12 13:06:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.0 ks=7  ->  val=0.001738 | train=0.002198 | test=0.002349

2026/05/12 13:09:12 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.2 ks=3  ->  val=0.001713 | train=0.002203 | test=0.002329

2026/05/12 13:12:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.2 ks=5  ->  val=0.001716 | train=0.002204 | test=0.002334

2026/05/12 13:15:32 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.2 ks=7  ->  val=0.001714 | train=0.002204 | test=0.002332

2026/05/12 13:15:40 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.001711 | train=0.002195 | test=0.002342

2026/05/12 13:15:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.001735 | train=0.002168 | test=0.002377

2026/05/12 13:15:57 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.0 ks=7  ->  val=0.001734 | train=0.002158 | test=0.002374

2026/05/12 13:16:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.001709 | train=0.002202 | test=0.002324

2026/05/12 13:16:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.001711 | train=0.002196 | test=0.002324

2026/05/12 13:16:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.2 ks=7  ->  val=0.001707 | train=0.002202 | test=0.002322

2026/05/12 13:16:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.001702 | train=0.002149 | test=0.002363

2026/05/12 13:16:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.001709 | train=0.002157 | test=0.002359

2026/05/12 13:16:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.0 ks=7  ->  val=0.001699 | train=0.002161 | test=0.002358

2026/05/12 13:16:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.001706 | train=0.002203 | test=0.002333

2026/05/12 13:17:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.001705 | train=0.002202 | test=0.002330

2026/05/12 13:17:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.2 ks=7  ->  val=0.001706 | train=0.002201 | test=0.002328

2026/05/12 13:17:23 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.0 ks=3  ->  val=0.001720 | train=0.002148 | test=0.002349

2026/05/12 13:17:34 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.0 ks=5  ->  val=0.001742 | train=0.002165 | test=0.002359

2026/05/12 13:17:47 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.0 ks=7  ->  val=0.001736 | train=0.002075 | test=0.002371

2026/05/12 13:17:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.2 ks=3  ->  val=0.001711 | train=0.002199 | test=0.002324

2026/05/12 13:18:08 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.2 ks=5  ->  val=0.001710 | train=0.002198 | test=0.002327

2026/05/12 13:18:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.2 ks=7  ->  val=0.001708 | train=0.002157 | test=0.002343

2026/05/12 13:18:29 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.001721 | train=0.002204 | test=0.002331

2026/05/12 13:18:37 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.001717 | train=0.002205 | test=0.002329

2026/05/12 13:18:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.0 ks=7  ->  val=0.001716 | train=0.002205 | test=0.002322

2026/05/12 13:18:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.001712 | train=0.002203 | test=0.002325

2026/05/12 13:19:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.001710 | train=0.002206 | test=0.002329

2026/05/12 13:19:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.2 ks=7  ->  val=0.001710 | train=0.002204 | test=0.002326

2026/05/12 13:19:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.001710 | train=0.002207 | test=0.002330

2026/05/12 13:19:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.001710 | train=0.002206 | test=0.002327

2026/05/12 13:19:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.0 ks=7  ->  val=0.001701 | train=0.002197 | test=0.002324

2026/05/12 13:19:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.001710 | train=0.002205 | test=0.002324

2026/05/12 13:19:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.001710 | train=0.002200 | test=0.002320

2026/05/12 13:20:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.2 ks=7  ->  val=0.001705 | train=0.002200 | test=0.002321

2026/05/12 13:20:12 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.0 ks=3  ->  val=0.001733 | train=0.002206 | test=0.002347

2026/05/12 13:20:23 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.0 ks=5  ->  val=0.001729 | train=0.002199 | test=0.002352

2026/05/12 13:20:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.0 ks=7  ->  val=0.001749 | train=0.002204 | test=0.002361

2026/05/12 13:20:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.2 ks=3  ->  val=0.001710 | train=0.002201 | test=0.002321

2026/05/12 13:20:57 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.2 ks=5  ->  val=0.001711 | train=0.002202 | test=0.002324

2026/05/12 13:21:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.2 ks=7  ->  val=0.001714 | train=0.002201 | test=0.002327

### Resultados — Etapa 1 (top 10)

In [5]:
results_arch_df.head(10)

,arch,n_layers,units,dropout,kernel_size,MAE_train,MAE_val,MAE_test,epochs,n_params
0,cnn_mlp,1,64,0.0,7,0.002161,0.001699,0.002358,11,16023
1,cnn_mlp,2,64,0.0,7,0.002197,0.001701,0.002324,11,17367
2,cnn_mlp,1,64,0.0,3,0.002149,0.001702,0.002363,13,10135
3,lstm,1,32,0.2,0,0.002167,0.001703,0.002350,31,7927
4,lstm,1,32,0.0,0,0.002158,0.001704,0.002389,29,7927
5,cnn_gru,2,32,0.2,7,0.001939,0.001704,0.002355,19,18615
6,cnn_mlp,2,64,0.2,7,0.002200,0.001705,0.002321,11,17367
7,cnn_mlp,1,64,0.2,5,0.002202,0.001705,0.002330,11,13079
8,cnn_mlp,1,64,0.2,7,0.002201,0.001706,0.002328,11,16023
9,cnn_mlp,1,64,0.2,3,0.002203,0.001706,0.002333,11,10135

## Etapa 2 — Hiperparámetros de entrenamiento

Se fija la arquitectura ganadora de la Etapa 1 y se busca sobre `learning_rate` × `batch_size`.

Criterio de selección: **MAE de validación mínimo**.

In [6]:
best_arch = results_arch_df.iloc[0]
best_ks   = int(best_arch.kernel_size)
print(f"Mejor arquitectura: arch={best_arch.arch}  n_layers={int(best_arch.n_layers)}  units={int(best_arch.units)}  dropout={best_arch.dropout}  kernel_size={best_ks}")
print(f"  MAE val = {best_arch.MAE_val:.6f}")

train_grid = list(itertools.product([1e-2, 1e-3, 1e-4], [64, 128, 256]))

results_train = []
for lr, bs in train_grid:
    run_name = f"{EXPERIMENT_NAME}_train_{best_arch.arch}_lr{lr:.0e}_batch{bs}"
    existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing.empty:
        mlflow.delete_run(existing.iloc[0].run_id)

    with mlflow.start_run(run_name=run_name):
        model = build_model(
            best_arch.arch, int(best_arch.n_layers), int(best_arch.units),
            float(best_arch.dropout), kernel_size=best_ks, lr=lr,
        )
        mae_tr, mae_val, mae_te, h = fit_eval(model, batch_size=bs)

        for epoch, (tl, vl) in enumerate(zip(h.history["loss"], h.history["val_loss"])):
            mlflow.log_metric("train_loss", tl, step=epoch)
            mlflow.log_metric("val_loss",   vl, step=epoch)

        fig = plot_training_curve(h)
        mlflow.log_figure(fig, "plots/loss_curve.png")
        plt.close(fig)

        mlflow.log_param("arch",               best_arch.arch)
        mlflow.log_param("n_layers",           int(best_arch.n_layers))
        mlflow.log_param("units",              int(best_arch.units))
        mlflow.log_param("dropout",            float(best_arch.dropout))
        mlflow.log_param("kernel_size",        best_ks)
        mlflow.log_param("learning_rate",      lr)
        mlflow.log_param("batch_size",         bs)
        mlflow.log_param("input_window_size",  INPUT_W)
        mlflow.log_param("output_window_size", OUTPUT_W)
        mlflow.log_param("n_params",           model.count_params())
        mlflow.log_param("epochs",             len(h.history["loss"]))

        mlflow.log_metric("train_mae", mae_tr)
        mlflow.log_metric("val_mae",   mae_val)
        mlflow.log_metric("test_mae",  mae_te)

        mlflow.keras.log_model(model, name="model")

        results_train.append({
            "learning_rate": lr, "batch_size": bs,
            "MAE_train": mae_tr, "MAE_val": mae_val, "MAE_test": mae_te,
            "epochs": len(h.history["loss"]),
        })
        print(f"lr={lr:.0e} batch={bs:>3}  ->  val={mae_val:.6f} | train={mae_tr:.6f} | test={mae_te:.6f}")

results_train_df = pd.DataFrame(results_train).sort_values("MAE_val").reset_index(drop=True)

Mejor arquitectura: arch=cnn_mlp  n_layers=1  units=64  dropout=0.0  kernel_size=7
  MAE val = 0.001699

2026/05/12 13:21:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch= 64  ->  val=0.001814 | train=0.002276 | test=0.002413

2026/05/12 13:21:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch=128  ->  val=0.001790 | train=0.002239 | test=0.002418

2026/05/12 13:21:37 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch=256  ->  val=0.001746 | train=0.002225 | test=0.002350

2026/05/12 13:21:47 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch= 64  ->  val=0.001721 | train=0.002077 | test=0.002395

2026/05/12 13:21:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch=128  ->  val=0.001699 | train=0.002161 | test=0.002358

2026/05/12 13:22:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch=256  ->  val=0.001714 | train=0.002150 | test=0.002360

2026/05/12 13:22:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch= 64  ->  val=0.001725 | train=0.002140 | test=0.002364

2026/05/12 13:22:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch=128  ->  val=0.001721 | train=0.002127 | test=0.002363

2026/05/12 13:22:41 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch=256  ->  val=0.001719 | train=0.002094 | test=0.002357

In [7]:
results_train_df

   learning_rate  batch_size  MAE_train   MAE_val  MAE_test  epochs
0         0.0010         128   0.002161  0.001699  0.002358      11
1         0.0010         256   0.002150  0.001714  0.002360      12
2         0.0001         256   0.002094  0.001719  0.002357      27
3         0.0001         128   0.002127  0.001721  0.002363      18
4         0.0010          64   0.002077  0.001721  0.002395      12
5         0.0001          64   0.002140  0.001725  0.002364      14
6         0.0100         256   0.002225  0.001746  0.002350      11
7         0.0100         128   0.002239  0.001790  0.002418      11
8         0.0100          64   0.002276  0.001814  0.002413      11

## Modelo final y comparación con benchmarks

Se reentrena el modelo ganador con la configuración completa y se compara con la regresión lineal.

In [8]:
from util import load_benchmark

best_train = results_train_df.iloc[0]
print("Configuración ganadora:")
print(f"  arch          = {best_arch.arch}")
print(f"  n_layers      = {int(best_arch.n_layers)}")
print(f"  units         = {int(best_arch.units)}")
print(f"  dropout       = {float(best_arch.dropout)}")
print(f"  kernel_size   = {best_ks}")
print(f"  learning_rate = {best_train.learning_rate:.0e}")
print(f"  batch_size    = {int(best_train.batch_size)}")

final_model = build_model(
    best_arch.arch, int(best_arch.n_layers), int(best_arch.units),
    float(best_arch.dropout), kernel_size=best_ks, lr=float(best_train.learning_rate),
)
mae_tr_f, mae_val_f, mae_te_f, hist_f = fit_eval(
    final_model, batch_size=int(best_train.batch_size), patience=20,
)

linreg_bench = load_benchmark("lr_benchmark")
linreg_row   = linreg_bench[
    (linreg_bench.input_window == INPUT_W) & (linreg_bench.output_window == OUTPUT_W)
].iloc[0]

run_name_final = f"{EXPERIMENT_NAME}_final"
existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name_final}"')
if not existing.empty:
    mlflow.delete_run(existing.iloc[0].run_id)

with mlflow.start_run(run_name=run_name_final):
    for epoch, (tl, vl) in enumerate(zip(hist_f.history["loss"], hist_f.history["val_loss"])):
        mlflow.log_metric("train_loss", tl, step=epoch)
        mlflow.log_metric("val_loss",   vl, step=epoch)

    fig_f = plot_training_curve(hist_f)
    mlflow.log_figure(fig_f, "plots/loss_curve.png")
    plt.close(fig_f)

    mlflow.log_param("arch",               best_arch.arch)
    mlflow.log_param("n_layers",           int(best_arch.n_layers))
    mlflow.log_param("units",              int(best_arch.units))
    mlflow.log_param("dropout",            float(best_arch.dropout))
    mlflow.log_param("kernel_size",        best_ks)
    mlflow.log_param("learning_rate",      float(best_train.learning_rate))
    mlflow.log_param("batch_size",         int(best_train.batch_size))
    mlflow.log_param("input_window_size",  INPUT_W)
    mlflow.log_param("output_window_size", OUTPUT_W)
    mlflow.log_param("n_params",           final_model.count_params())
    mlflow.log_param("epochs",             len(hist_f.history["loss"]))
    mlflow.log_metric("train_mae",         mae_tr_f)
    mlflow.log_metric("val_mae",           mae_val_f)
    mlflow.log_metric("test_mae",          mae_te_f)
    mlflow.keras.log_model(final_model, name="model")

summary = pd.DataFrame([
    {"modelo": "Regresión lineal",                 "MAE_train": linreg_row.MAE_train, "MAE_test": linreg_row.MAE_test},
    {"modelo": f"Mejor mixto ({best_arch.arch})",  "MAE_train": mae_tr_f,             "MAE_test": mae_te_f},
])
summary["Δ vs lin.reg. (test)"] = summary["MAE_test"] - linreg_row.MAE_test
display(summary)

Configuración ganadora:
  arch          = cnn_mlp
  n_layers      = 1
  units         = 64
  dropout       = 0.0
  kernel_size   = 7
  learning_rate = 1e-03
  batch_size    = 128

2026/05/12 13:22:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

                  modelo  MAE_train  MAE_test  Δ vs lin.reg. (test)
0       Regresión lineal   0.002027  0.002628               0.00000
1  Mejor mixto (cnn_mlp)   0.002161  0.002358              -0.00027

## Top-10 configuraciones por etapa

In [9]:
fig, axes = plt.subplots(1, 2, figsize=(16, 5))

def plot_top(ax, df, label_cols, title, top=10):
    top_df = df.head(top).iloc[::-1]
    labels = top_df[label_cols].astype(str).agg(" · ".join, axis=1)
    ypos = np.arange(len(top_df))
    ax.barh(ypos - 0.2, top_df["MAE_val"],   height=0.4, label="MAE val",   color="steelblue")
    ax.barh(ypos + 0.2, top_df["MAE_train"], height=0.4, label="MAE train", color="lightgray")
    ax.set_yticks(ypos)
    ax.set_yticklabels(labels, fontsize=9)
    ax.set_xlabel("MAE")
    ax.set_title(title)
    ax.legend(loc="lower right")
    ax.grid(True, axis="x", alpha=0.3)

arch_label_cols = ["arch", "n_layers", "units", "dropout", "kernel_size"]
plot_top(axes[0], results_arch_df,  arch_label_cols,
         "Etapa 1 — arquitectura (top 10)")
plot_top(axes[1], results_train_df, ["learning_rate", "batch_size"],
         "Etapa 2 — entrenamiento (top 9)")

plt.tight_layout()
plt.show()

/var/folders/py/c5_xfbqn469g5_844mv32gt40000gn/T/ipykernel_4896/3707942946.py:23: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()