# Modelos Mixtos — Combinaciones Conv1D, LSTM, GRU y MLP

Este notebook explora combinaciones de capas **convolucionales** (Conv1D), **recurrentes** (LSTM, GRU) y **densas** (MLP) para la configuración fija:

- **Ventana de entrada:** 90 días
- **Ventana de salida:** 1 día

Arquitecturas evaluadas:
- `lstm` — LSTM apiladas
- `gru` — GRU apiladas
- `cnn_lstm` — Conv1D → LSTM
- `cnn_gru` — Conv1D → GRU

- `cnn_lstm_mlp` — Conv1D → LSTM → MLP

- `cnn_gru_mlp` — Conv1D → GRU → MLP

- `cnn_mlp` — Conv1D → MLP

**Adaptación para input_w=90:** a diferencia del caso input_w=5 (donde `kernel_size=3` era fijo),
con 90 pasos temporales el tamaño del kernel Conv1D es un hiperparámetro relevante. Se añade
`kernel_size ∈ {3, 5, 7}` al grid de la Etapa 1 **solo para las variantes CNN**.

La búsqueda se realiza en dos etapas:
1. **Etapa 1 — Arquitectura**: tipo de red × n_layers × units × dropout (× kernel_size para CNN) — 204 combinaciones
2. **Etapa 2 — Entrenamiento**: learning rate × batch size con la mejor arquitectura de la Etapa 1 (9 combinaciones)

In [1]:
import sys
import itertools
import mlflow
from pathlib import Path

# Busca util.py subiendo niveles desde el directorio actual
_here = Path.cwd()
PROJECT_ROOT = next(
    p for p in [_here, _here.parent, _here.parent.parent, _here.parent.parent.parent]
    if (p / 'util.py').exists()
)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

mlflow.set_tracking_uri(f"sqlite:///{PROJECT_ROOT / 'model' / 'mlflow.db'}")

EXPERIMENT_NAME = "Modelos_Mixtos_input90_output1"
mlflow.set_experiment(EXPERIMENT_NAME)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import keras
from keras.models import Sequential
from keras.layers import LSTM, GRU, Dense, Input, Conv1D, GlobalAveragePooling1D, Dropout
from keras.callbacks import EarlyStopping
from keras.optimizers import Adam

from sklearn.metrics import mean_absolute_error

from util import get_train_test, RANDOM_SEED, plot_training_curve

np.random.seed(RANDOM_SEED)
keras.utils.set_random_seed(RANDOM_SEED)

## Carga de datos

In [2]:
INPUT_W  = 90
OUTPUT_W = 1

def load_seq_data(input_window_size, output_window_size):
    d = get_train_test(input_window_size=input_window_size, output_window_size=output_window_size)
    X_train, X_test = d.X_train, d.X_test
    y_train, y_test = d.y_train, d.y_test
    val_size         = int(0.10 * X_train.shape[0])
    X_val, y_val     = X_train[-val_size:], y_train[-val_size:]
    X_train, y_train = X_train[:-val_size], y_train[:-val_size]
    return X_train, y_train, X_val, y_val, X_test, y_test

X_tr, y_tr, X_val, y_val, X_te, y_te = load_seq_data(INPUT_W, OUTPUT_W)

print(f"X_tr:  {X_tr.shape}   y_tr:  {y_tr.shape}")
print(f"X_val: {X_val.shape}  y_val: {y_val.shape}")
print(f"X_te:  {X_te.shape}   y_te:  {y_te.shape}")

X_tr:  (13037, 90, 23)   y_tr:  (13037, 23)
X_val: (1448, 90, 23)  y_val: (1448, 23)
X_te:  (1610, 90, 23)   y_te:  (1610, 23)

## Arquitecturas implementadas

La función `build_model` construye el modelo según el argumento `arch`:

| `arch`     | Capas                                      |
|------------|--------------------------------------------|
| `lstm`     | Input → LSTM × n_layers → Dense            |
| `gru`      | Input → GRU × n_layers → Dense             |
| `cnn_lstm` | Input → Conv1D → LSTM × n_layers → Dense   |
| `cnn_gru`  | Input → Conv1D → GRU × n_layers → Dense    |

| `cnn_lstm_mlp` | Input → Conv1D → LSTM × n_layers → MLP → Dense |

| `cnn_gru_mlp`  | Input → Conv1D → GRU × n_layers → MLP → Dense  |

| `cnn_mlp`      | Input → Conv1D → GlobalAveragePooling1D → MLP × n_layers → Dense |

Para las variantes CNN, `kernel_size` es ahora un hiperparámetro explorado en el grid
(valores: 3, 5, 7). Con 90 pasos de entrada, kernels más grandes capturan patrones de
frecuencia más baja (semanal ≈ 5, quincenal ≈ 7).

In [3]:
def add_mlp_head(model, n_layers, units, dropout):
    for i in range(n_layers):
        layer_units = units if i == 0 else max(units // 2, 16)
        model.add(Dense(layer_units, activation="relu"))
        if dropout > 0:
            model.add(Dropout(dropout))


def build_model(arch, n_layers, units, dropout, kernel_size=5, lr=1e-3):
    keras.utils.set_random_seed(RANDOM_SEED)
    m = Sequential()
    m.add(Input(shape=(X_tr.shape[1], X_tr.shape[2])))

    if arch == "lstm":
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "gru":
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_lstm":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_gru":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_lstm_mlp":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))
        add_mlp_head(m, 2, units, dropout)

    elif arch == "cnn_gru_mlp":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))
        add_mlp_head(m, 2, units, dropout)

    elif arch == "cnn_mlp":
        m.add(Conv1D(units, kernel_size=kernel_size, activation="relu", padding="same"))
        m.add(GlobalAveragePooling1D())
        add_mlp_head(m, n_layers, units, dropout)

    else:
        raise ValueError(f"Arquitectura no soportada: {arch}")

    m.add(Dense(y_tr.shape[1]))
    m.compile(loss="mean_absolute_error", optimizer=Adam(learning_rate=lr))
    return m



def fit_eval(model, batch_size=128, epochs=200, patience=10, verbose=0):
    es = EarlyStopping(monitor="val_loss", patience=patience, restore_best_weights=True)
    h = model.fit(
        X_tr, y_tr,
        validation_data=(X_val, y_val),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=[es],
        verbose=verbose,
    )
    mae_tr  = mean_absolute_error(y_tr,  model.predict(X_tr,  verbose=0))
    mae_val = mean_absolute_error(y_val, model.predict(X_val, verbose=0))
    mae_te  = mean_absolute_error(y_te,  model.predict(X_te,  verbose=0))
    return mae_tr, mae_val, mae_te, h

## Etapa 1 — Búsqueda de arquitectura

Grid:
- **LSTM / GRU**: `arch` × `n_layers` × `units` × `dropout` → 24 combinaciones
- **CNN / CNN-RNN / CNN-RNN-MLP**: `arch` × `n_layers` × `units` × `dropout` × `kernel_size` → 180 combinaciones

Total: **204 combinaciones**. Learning rate y batch size fijos en esta etapa.

Criterio de selección: **MAE de validación mínimo**.

In [4]:
pure_rnn_combos = [
    (arch, nl, u, dr, None)
    for arch, nl, u, dr in itertools.product(
        ["lstm", "gru"], [1, 2], [32, 64, 128], [0.0, 0.2]
    )
]
cnn_combos = [
    (arch, nl, u, dr, ks)
    for arch, nl, u, dr, ks in itertools.product(
        ["cnn_lstm", "cnn_gru", "cnn_lstm_mlp", "cnn_gru_mlp", "cnn_mlp"], [1, 2], [32, 64, 128], [0.0, 0.2], [3, 5, 7]
    )
]
arch_grid = pure_rnn_combos + cnn_combos
print(f"Total combinaciones Etapa 1: {len(arch_grid)}  (RNN puras: {len(pure_rnn_combos)}, CNN: {len(cnn_combos)})")

results_arch = []
batch_size_arch = 128

for arch, nl, u, dr, ks in arch_grid:
    ks_eff = ks if ks is not None else 0  # 0 = no aplica (RNN pura)
    run_name = (
        f"{EXPERIMENT_NAME}_arch_{arch}_layers{nl}_units{u}_drop{dr}"
        + (f"_ks{ks_eff}" if ks is not None else "")
    )
    existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing.empty:
        mlflow.delete_run(existing.iloc[0].run_id)

    with mlflow.start_run(run_name=run_name):
        model = build_model(arch, nl, u, dr, kernel_size=ks_eff if ks is not None else 5, lr=1e-3)
        mae_tr, mae_val, mae_te, h = fit_eval(model, batch_size=batch_size_arch)

        for epoch, (tl, vl) in enumerate(zip(h.history["loss"], h.history["val_loss"])):
            mlflow.log_metric("train_loss", tl, step=epoch)
            mlflow.log_metric("val_loss",   vl, step=epoch)

        fig = plot_training_curve(h)
        mlflow.log_figure(fig, "plots/loss_curve.png")
        plt.close(fig)

        mlflow.log_param("arch",               arch)
        mlflow.log_param("n_layers",           nl)
        mlflow.log_param("units",              u)
        mlflow.log_param("dropout",            dr)
        mlflow.log_param("kernel_size",        ks_eff)
        mlflow.log_param("learning_rate",      1e-3)
        mlflow.log_param("batch_size",         batch_size_arch)
        mlflow.log_param("input_window_size",  INPUT_W)
        mlflow.log_param("output_window_size", OUTPUT_W)
        mlflow.log_param("n_params",           model.count_params())
        mlflow.log_param("epochs",             len(h.history["loss"]))

        mlflow.log_metric("train_mae", mae_tr)
        mlflow.log_metric("val_mae",   mae_val)
        mlflow.log_metric("test_mae",  mae_te)

        mlflow.keras.log_model(model, name="model")

        results_arch.append({
            "arch": arch, "n_layers": nl, "units": u, "dropout": dr, "kernel_size": ks_eff,
            "MAE_train": mae_tr, "MAE_val": mae_val, "MAE_test": mae_te,
            "epochs": len(h.history["loss"]), "n_params": model.count_params(),
        })
        ks_str = f" ks={ks_eff}" if ks is not None else ""
        print(f"arch={arch:<10} layers={nl} units={u:>3} dropout={dr}{ks_str}  ->  val={mae_val:.6f} | train={mae_tr:.6f} | test={mae_te:.6f}")

results_arch_df = pd.DataFrame(results_arch).sort_values("MAE_val").reset_index(drop=True)

Total combinaciones Etapa 1: 204  (RNN puras: 24, CNN: 180)

2026/05/11 09:43:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 32 dropout=0.0  ->  val=0.009106 | train=0.011863 | test=0.012300

2026/05/11 09:43:57 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 32 dropout=0.2  ->  val=0.009095 | train=0.011859 | test=0.012291

2026/05/11 10:00:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 64 dropout=0.0  ->  val=0.009115 | train=0.011840 | test=0.012319

2026/05/11 10:10:11 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 64 dropout=0.2  ->  val=0.009104 | train=0.011865 | test=0.012307

2026/05/11 10:19:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units=128 dropout=0.0  ->  val=0.009124 | train=0.011828 | test=0.012341

2026/05/11 10:21:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units=128 dropout=0.2  ->  val=0.009105 | train=0.011827 | test=0.012317

2026/05/11 10:22:27 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 32 dropout=0.0  ->  val=0.009066 | train=0.011865 | test=0.012268

2026/05/11 10:23:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 32 dropout=0.2  ->  val=0.009064 | train=0.011864 | test=0.012270

2026/05/11 10:25:35 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 64 dropout=0.0  ->  val=0.009085 | train=0.011850 | test=0.012296

2026/05/11 10:27:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 64 dropout=0.2  ->  val=0.009078 | train=0.011858 | test=0.012287

2026/05/11 10:32:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units=128 dropout=0.0  ->  val=0.009088 | train=0.011840 | test=0.012317

2026/05/11 10:39:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units=128 dropout=0.2  ->  val=0.009083 | train=0.011839 | test=0.012292

2026/05/11 10:39:34 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 32 dropout=0.0  ->  val=0.009115 | train=0.011862 | test=0.012326

2026/05/11 10:40:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 32 dropout=0.2  ->  val=0.009106 | train=0.011874 | test=0.012314

2026/05/11 10:40:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 64 dropout=0.0  ->  val=0.009121 | train=0.011862 | test=0.012337

2026/05/11 10:41:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 64 dropout=0.2  ->  val=0.009106 | train=0.011874 | test=0.012326

2026/05/11 10:44:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units=128 dropout=0.0  ->  val=0.009134 | train=0.011835 | test=0.012356

2026/05/11 10:47:50 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units=128 dropout=0.2  ->  val=0.009125 | train=0.011838 | test=0.012343

2026/05/11 10:48:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 32 dropout=0.0  ->  val=0.009074 | train=0.011860 | test=0.012288

2026/05/11 10:49:59 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 32 dropout=0.2  ->  val=0.009066 | train=0.011848 | test=0.012278

2026/05/11 10:52:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 64 dropout=0.0  ->  val=0.009111 | train=0.011834 | test=0.012321

2026/05/11 10:54:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 64 dropout=0.2  ->  val=0.009089 | train=0.011858 | test=0.012291

2026/05/11 11:04:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units=128 dropout=0.0  ->  val=0.009115 | train=0.011815 | test=0.012342

2026/05/11 11:10:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units=128 dropout=0.2  ->  val=0.009103 | train=0.011862 | test=0.012313

2026/05/11 11:10:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.009074 | train=0.011831 | test=0.012280

2026/05/11 11:11:14 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.009066 | train=0.011836 | test=0.012289

2026/05/11 11:11:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.0 ks=7  ->  val=0.009082 | train=0.011870 | test=0.012297

2026/05/11 11:12:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.009067 | train=0.011833 | test=0.012273

2026/05/11 11:13:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.009065 | train=0.011792 | test=0.012281

2026/05/11 11:13:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.2 ks=7  ->  val=0.009065 | train=0.011797 | test=0.012288

2026/05/11 11:15:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.009092 | train=0.011800 | test=0.012301

2026/05/11 11:16:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.009081 | train=0.011797 | test=0.012308

2026/05/11 11:17:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.0 ks=7  ->  val=0.009079 | train=0.011764 | test=0.012297

2026/05/11 11:19:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.009075 | train=0.011680 | test=0.012304

2026/05/11 11:21:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.009070 | train=0.011808 | test=0.012291

2026/05/11 11:22:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.2 ks=7  ->  val=0.009075 | train=0.011812 | test=0.012287

2026/05/11 11:25:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.0 ks=3  ->  val=0.009101 | train=0.011709 | test=0.012300

2026/05/11 11:28:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.0 ks=5  ->  val=0.009105 | train=0.011745 | test=0.012309

2026/05/11 11:31:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.0 ks=7  ->  val=0.009103 | train=0.011693 | test=0.012319

2026/05/11 11:33:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.2 ks=3  ->  val=0.009076 | train=0.011798 | test=0.012296

2026/05/11 11:36:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.2 ks=5  ->  val=0.009089 | train=0.011781 | test=0.012296

2026/05/11 11:39:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.2 ks=7  ->  val=0.009081 | train=0.011695 | test=0.012293

2026/05/11 11:40:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.009058 | train=0.011860 | test=0.012261

2026/05/11 11:41:50 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.009068 | train=0.011851 | test=0.012273

2026/05/11 11:42:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.0 ks=7  ->  val=0.009067 | train=0.011847 | test=0.012273

2026/05/11 11:44:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.009060 | train=0.011830 | test=0.012262

2026/05/11 11:46:11 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.009061 | train=0.011828 | test=0.012260

2026/05/11 11:47:20 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.2 ks=7  ->  val=0.009061 | train=0.011855 | test=0.012269

2026/05/11 11:49:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.009083 | train=0.011838 | test=0.012289

2026/05/11 11:52:15 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.009094 | train=0.011834 | test=0.012291

2026/05/11 11:54:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.0 ks=7  ->  val=0.009093 | train=0.011893 | test=0.012293

2026/05/11 11:57:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.009072 | train=0.011814 | test=0.012276

2026/05/11 12:00:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.009079 | train=0.011811 | test=0.012274

2026/05/11 12:03:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.2 ks=7  ->  val=0.009066 | train=0.011817 | test=0.012268

2026/05/11 12:08:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.0 ks=3  ->  val=0.009066 | train=0.011841 | test=0.012276

2026/05/11 12:13:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.0 ks=5  ->  val=0.009089 | train=0.011846 | test=0.012290

2026/05/11 12:19:33 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.0 ks=7  ->  val=0.009073 | train=0.011751 | test=0.012276

2026/05/11 12:25:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.2 ks=3  ->  val=0.009069 | train=0.011833 | test=0.012273

2026/05/11 12:33:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.2 ks=5  ->  val=0.009063 | train=0.011608 | test=0.012383

2026/05/11 12:38:59 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.2 ks=7  ->  val=0.009064 | train=0.011817 | test=0.012278

2026/05/11 12:39:37 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.009077 | train=0.011844 | test=0.012270

2026/05/11 12:40:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.009073 | train=0.011891 | test=0.012278

2026/05/11 12:40:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.0 ks=7  ->  val=0.009070 | train=0.011809 | test=0.012261

2026/05/11 12:41:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.009069 | train=0.011823 | test=0.012265

2026/05/11 12:42:32 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.009067 | train=0.011668 | test=0.012261

2026/05/11 12:43:20 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.2 ks=7  ->  val=0.009060 | train=0.011773 | test=0.012245

2026/05/11 12:44:23 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.009099 | train=0.011854 | test=0.012310

2026/05/11 12:45:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.009096 | train=0.011825 | test=0.012309

2026/05/11 12:46:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.0 ks=7  ->  val=0.009089 | train=0.011838 | test=0.012285

2026/05/11 12:48:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.009081 | train=0.011794 | test=0.012294

2026/05/11 12:49:20 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.009079 | train=0.011791 | test=0.012282

2026/05/11 12:50:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.2 ks=7  ->  val=0.009080 | train=0.011744 | test=0.012283

2026/05/11 12:52:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.0 ks=3  ->  val=0.009119 | train=0.011851 | test=0.012299

2026/05/11 12:55:33 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.0 ks=5  ->  val=0.009112 | train=0.011744 | test=0.012316

2026/05/11 12:57:40 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.0 ks=7  ->  val=0.009112 | train=0.011882 | test=0.012306

2026/05/11 13:01:37 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.2 ks=3  ->  val=0.009106 | train=0.011595 | test=0.012321

2026/05/11 13:11:27 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.2 ks=5  ->  val=0.009108 | train=0.011558 | test=0.012380

2026/05/11 13:23:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.2 ks=7  ->  val=0.009102 | train=0.011850 | test=0.012294

2026/05/11 13:27:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.009080 | train=0.011842 | test=0.012292

2026/05/11 13:35:33 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.009085 | train=0.011836 | test=0.012300

2026/05/11 13:39:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.0 ks=7  ->  val=0.009083 | train=0.011806 | test=0.012302

2026/05/11 13:40:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.009070 | train=0.011840 | test=0.012275

2026/05/11 13:42:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.009060 | train=0.011741 | test=0.012266

2026/05/11 13:43:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.2 ks=7  ->  val=0.009062 | train=0.011848 | test=0.012268

2026/05/11 13:45:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.009087 | train=0.011834 | test=0.012305

2026/05/11 13:47:18 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.009102 | train=0.011898 | test=0.012316

2026/05/11 13:48:57 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.0 ks=7  ->  val=0.009118 | train=0.011907 | test=0.012329

2026/05/11 13:50:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.009082 | train=0.011901 | test=0.012295

2026/05/11 13:53:27 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.009093 | train=0.011793 | test=0.012292

2026/05/11 13:55:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.2 ks=7  ->  val=0.009094 | train=0.011817 | test=0.012292

2026/05/11 14:00:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.0 ks=3  ->  val=0.009116 | train=0.011829 | test=0.012308

2026/05/11 14:04:15 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.0 ks=5  ->  val=0.009108 | train=0.011825 | test=0.012322

2026/05/11 14:07:50 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.0 ks=7  ->  val=0.009112 | train=0.011875 | test=0.012309

2026/05/11 14:11:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.2 ks=3  ->  val=0.009090 | train=0.011867 | test=0.012281

2026/05/11 14:15:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.2 ks=5  ->  val=0.009080 | train=0.011843 | test=0.012277

2026/05/11 14:19:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.2 ks=7  ->  val=0.009097 | train=0.011905 | test=0.012285

2026/05/11 14:19:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.009060 | train=0.011859 | test=0.012269

2026/05/11 14:20:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.009064 | train=0.011866 | test=0.012272

2026/05/11 14:20:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.0 ks=7  ->  val=0.009063 | train=0.011873 | test=0.012273

2026/05/11 14:21:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.009069 | train=0.011867 | test=0.012272

2026/05/11 14:22:18 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.009064 | train=0.011866 | test=0.012267

2026/05/11 14:23:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.2 ks=7  ->  val=0.009063 | train=0.011863 | test=0.012274

2026/05/11 14:23:59 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.009065 | train=0.011864 | test=0.012270

2026/05/11 14:25:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.009069 | train=0.011862 | test=0.012275

2026/05/11 14:26:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.0 ks=7  ->  val=0.009063 | train=0.011857 | test=0.012273

2026/05/11 14:26:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.009067 | train=0.011861 | test=0.012275

2026/05/11 14:28:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.009062 | train=0.011865 | test=0.012272

2026/05/11 14:29:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.2 ks=7  ->  val=0.009067 | train=0.011864 | test=0.012274

2026/05/11 14:33:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.0 ks=3  ->  val=0.009060 | train=0.011823 | test=0.012252

2026/05/11 14:35:41 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.0 ks=5  ->  val=0.009071 | train=0.011863 | test=0.012259

2026/05/11 14:37:37 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.0 ks=7  ->  val=0.009070 | train=0.011872 | test=0.012272

2026/05/11 14:40:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.2 ks=3  ->  val=0.009066 | train=0.011860 | test=0.012272

2026/05/11 14:42:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.2 ks=5  ->  val=0.009068 | train=0.011867 | test=0.012274

2026/05/11 14:50:54 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.2 ks=7  ->  val=0.009050 | train=0.011792 | test=0.012228

2026/05/11 14:51:41 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.009070 | train=0.011865 | test=0.012275

2026/05/11 14:52:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.009065 | train=0.011861 | test=0.012273

2026/05/11 14:53:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.0 ks=7  ->  val=0.009063 | train=0.011863 | test=0.012272

2026/05/11 14:54:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.009066 | train=0.011865 | test=0.012273

2026/05/11 14:55:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.009067 | train=0.011867 | test=0.012272

2026/05/11 14:56:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.2 ks=7  ->  val=0.009067 | train=0.011866 | test=0.012276

2026/05/11 14:59:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.009066 | train=0.011863 | test=0.012271

2026/05/11 15:01:15 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.009065 | train=0.011862 | test=0.012271

2026/05/11 15:04:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.0 ks=7  ->  val=0.009066 | train=0.011863 | test=0.012270

2026/05/11 15:06:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.009065 | train=0.011863 | test=0.012274

2026/05/11 15:09:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.009069 | train=0.011866 | test=0.012271

2026/05/11 15:10:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.2 ks=7  ->  val=0.009063 | train=0.011862 | test=0.012274

2026/05/11 15:18:25 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.0 ks=3  ->  val=0.009066 | train=0.011862 | test=0.012272

2026/05/11 15:29:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.0 ks=5  ->  val=0.009063 | train=0.011863 | test=0.012272

2026/05/11 15:33:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.0 ks=7  ->  val=0.009072 | train=0.011870 | test=0.012274

2026/05/11 15:38:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.2 ks=3  ->  val=0.009067 | train=0.011866 | test=0.012275

2026/05/11 15:42:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.2 ks=5  ->  val=0.009065 | train=0.011869 | test=0.012270

2026/05/11 15:45:57 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.2 ks=7  ->  val=0.009066 | train=0.011864 | test=0.012272

2026/05/11 15:46:27 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.009066 | train=0.011865 | test=0.012273

2026/05/11 15:47:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.009067 | train=0.011835 | test=0.012279

2026/05/11 15:47:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.0 ks=7  ->  val=0.009067 | train=0.011859 | test=0.012272

2026/05/11 15:48:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.009066 | train=0.011859 | test=0.012268

2026/05/11 15:49:32 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.009067 | train=0.011861 | test=0.012274

2026/05/11 15:50:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.2 ks=7  ->  val=0.009066 | train=0.011860 | test=0.012273

2026/05/11 15:51:41 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.009064 | train=0.011852 | test=0.012249

2026/05/11 15:52:34 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.009063 | train=0.011865 | test=0.012278

2026/05/11 15:53:59 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.0 ks=7  ->  val=0.009067 | train=0.011846 | test=0.012266

2026/05/11 15:54:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.009066 | train=0.011868 | test=0.012269

2026/05/11 15:56:11 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.009065 | train=0.011864 | test=0.012270

2026/05/11 15:57:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.2 ks=7  ->  val=0.009067 | train=0.011861 | test=0.012272

2026/05/11 15:59:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.0 ks=3  ->  val=0.009062 | train=0.011858 | test=0.012260

2026/05/11 16:00:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.0 ks=5  ->  val=0.009066 | train=0.011863 | test=0.012278

2026/05/11 16:02:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.0 ks=7  ->  val=0.009065 | train=0.011864 | test=0.012271

2026/05/11 16:05:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.2 ks=3  ->  val=0.009062 | train=0.011852 | test=0.012255

2026/05/11 16:07:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.2 ks=5  ->  val=0.009063 | train=0.011855 | test=0.012235

2026/05/11 16:09:25 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.2 ks=7  ->  val=0.009065 | train=0.011860 | test=0.012272

2026/05/11 16:12:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.009063 | train=0.011862 | test=0.012270

2026/05/11 16:12:52 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.009066 | train=0.011863 | test=0.012272

2026/05/11 16:14:20 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.0 ks=7  ->  val=0.009066 | train=0.011865 | test=0.012271

2026/05/11 16:15:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.009067 | train=0.011866 | test=0.012273

2026/05/11 16:16:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.009066 | train=0.011866 | test=0.012272

2026/05/11 16:17:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.2 ks=7  ->  val=0.009064 | train=0.011864 | test=0.012271

2026/05/11 16:19:40 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.009062 | train=0.011864 | test=0.012272

2026/05/11 16:21:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.009068 | train=0.011866 | test=0.012272

2026/05/11 16:26:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.0 ks=7  ->  val=0.009064 | train=0.011852 | test=0.012245

2026/05/11 16:28:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.009071 | train=0.011867 | test=0.012274

2026/05/11 16:32:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.009068 | train=0.011866 | test=0.012272

2026/05/11 16:34:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.2 ks=7  ->  val=0.009066 | train=0.011864 | test=0.012272

2026/05/11 16:41:22 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.0 ks=3  ->  val=0.009054 | train=0.011845 | test=0.012269

2026/05/11 16:46:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.0 ks=5  ->  val=0.009060 | train=0.011866 | test=0.012274

2026/05/11 16:54:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.0 ks=7  ->  val=0.009066 | train=0.011862 | test=0.012269

2026/05/11 16:59:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.2 ks=3  ->  val=0.009062 | train=0.011862 | test=0.012273

2026/05/11 17:06:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.2 ks=5  ->  val=0.009071 | train=0.011871 | test=0.012273

2026/05/11 17:10:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.2 ks=7  ->  val=0.009069 | train=0.011866 | test=0.012271

2026/05/11 17:10:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.0 ks=3  ->  val=0.009065 | train=0.011881 | test=0.012282

2026/05/11 17:10:29 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.0 ks=5  ->  val=0.009067 | train=0.011864 | test=0.012275

2026/05/11 17:10:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.0 ks=7  ->  val=0.009068 | train=0.011870 | test=0.012277

2026/05/11 17:10:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.2 ks=3  ->  val=0.009064 | train=0.011860 | test=0.012273

2026/05/11 17:10:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.2 ks=5  ->  val=0.009065 | train=0.011861 | test=0.012275

2026/05/11 17:11:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.2 ks=7  ->  val=0.009067 | train=0.011865 | test=0.012275

2026/05/11 17:11:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.0 ks=3  ->  val=0.009064 | train=0.011861 | test=0.012269

2026/05/11 17:11:27 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.0 ks=5  ->  val=0.009058 | train=0.011859 | test=0.012267

2026/05/11 17:11:44 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.0 ks=7  ->  val=0.009050 | train=0.011843 | test=0.012270

2026/05/11 17:11:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.2 ks=3  ->  val=0.009065 | train=0.011864 | test=0.012277

2026/05/11 17:12:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.2 ks=5  ->  val=0.009063 | train=0.011865 | test=0.012271

2026/05/11 17:12:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.2 ks=7  ->  val=0.009067 | train=0.011865 | test=0.012273

2026/05/11 17:12:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.0 ks=3  ->  val=0.009065 | train=0.011861 | test=0.012271

2026/05/11 17:12:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.0 ks=5  ->  val=0.009063 | train=0.011863 | test=0.012271

2026/05/11 17:13:01 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.0 ks=7  ->  val=0.009071 | train=0.011865 | test=0.012276

2026/05/11 17:13:11 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.2 ks=3  ->  val=0.009070 | train=0.011870 | test=0.012276

2026/05/11 17:13:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.2 ks=5  ->  val=0.009065 | train=0.011864 | test=0.012272

2026/05/11 17:13:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.2 ks=7  ->  val=0.009068 | train=0.011869 | test=0.012270

2026/05/11 17:13:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.0 ks=3  ->  val=0.009065 | train=0.011864 | test=0.012271

2026/05/11 17:14:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.0 ks=5  ->  val=0.009068 | train=0.011872 | test=0.012272

2026/05/11 17:14:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.0 ks=7  ->  val=0.009069 | train=0.011862 | test=0.012275

2026/05/11 17:14:27 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.2 ks=3  ->  val=0.009061 | train=0.011864 | test=0.012269

2026/05/11 17:14:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.2 ks=5  ->  val=0.009063 | train=0.011861 | test=0.012271

2026/05/11 17:14:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.2 ks=7  ->  val=0.009065 | train=0.011865 | test=0.012269

2026/05/11 17:14:57 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.0 ks=3  ->  val=0.009070 | train=0.011866 | test=0.012276

2026/05/11 17:15:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.0 ks=5  ->  val=0.009058 | train=0.011856 | test=0.012268

2026/05/11 17:15:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.0 ks=7  ->  val=0.009067 | train=0.011865 | test=0.012272

2026/05/11 17:15:35 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.2 ks=3  ->  val=0.009066 | train=0.011865 | test=0.012273

2026/05/11 17:15:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.2 ks=5  ->  val=0.009064 | train=0.011860 | test=0.012274

2026/05/11 17:16:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.2 ks=7  ->  val=0.009063 | train=0.011860 | test=0.012269

2026/05/11 17:16:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.0 ks=3  ->  val=0.009063 | train=0.011859 | test=0.012272

2026/05/11 17:16:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.0 ks=5  ->  val=0.009060 | train=0.011869 | test=0.012276

2026/05/11 17:17:07 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.0 ks=7  ->  val=0.009049 | train=0.011839 | test=0.012267

2026/05/11 17:17:18 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.2 ks=3  ->  val=0.009065 | train=0.011862 | test=0.012273

2026/05/11 17:17:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.2 ks=5  ->  val=0.009064 | train=0.011862 | test=0.012270

2026/05/11 17:17:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.2 ks=7  ->  val=0.009066 | train=0.011866 | test=0.012275

### Resultados — Etapa 1 (top 10)

In [5]:
results_arch_df.head(10)

,arch,n_layers,units,dropout,kernel_size,MAE_train,MAE_val,MAE_test,epochs,n_params
0,cnn_mlp,2,128,0.0,7,0.011839,0.009049,0.012267,48,46999
1,cnn_mlp,1,64,0.0,7,0.011843,0.009050,0.012270,31,16023
2,cnn_lstm_mlp,1,128,0.2,7,0.011792,0.009050,0.012228,58,178583
3,cnn_gru_mlp,2,128,0.0,3,0.011845,0.009054,0.012269,25,233367
4,cnn_mlp,1,64,0.0,5,0.011859,0.009058,0.012267,13,13079
5,cnn_lstm,2,32,0.0,3,0.011860,0.009058,0.012261,15,19639
6,cnn_mlp,2,64,0.0,5,0.011856,0.009058,0.012268,29,14423
7,cnn_lstm_mlp,1,128,0.0,3,0.011823,0.009060,0.012252,21,166807
8,cnn_gru,2,32,0.2,5,0.011741,0.009060,0.012266,23,17143
9,cnn_mlp,2,128,0.0,5,0.011869,0.009060,0.012276,11,41111

## Etapa 2 — Hiperparámetros de entrenamiento

Se fija la arquitectura ganadora de la Etapa 1 y se busca sobre `learning_rate` × `batch_size`.

Criterio de selección: **MAE de validación mínimo**.

In [6]:
best_arch = results_arch_df.iloc[0]
best_ks   = int(best_arch.kernel_size)
print(f"Mejor arquitectura: arch={best_arch.arch}  n_layers={int(best_arch.n_layers)}  units={int(best_arch.units)}  dropout={best_arch.dropout}  kernel_size={best_ks}")
print(f"  MAE val = {best_arch.MAE_val:.6f}")

train_grid = list(itertools.product([1e-2, 1e-3, 1e-4], [64, 128, 256]))

results_train = []
for lr, bs in train_grid:
    run_name = f"{EXPERIMENT_NAME}_train_{best_arch.arch}_lr{lr:.0e}_batch{bs}"
    existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing.empty:
        mlflow.delete_run(existing.iloc[0].run_id)

    with mlflow.start_run(run_name=run_name):
        model = build_model(
            best_arch.arch, int(best_arch.n_layers), int(best_arch.units),
            float(best_arch.dropout), kernel_size=best_ks, lr=lr,
        )
        mae_tr, mae_val, mae_te, h = fit_eval(model, batch_size=bs)

        for epoch, (tl, vl) in enumerate(zip(h.history["loss"], h.history["val_loss"])):
            mlflow.log_metric("train_loss", tl, step=epoch)
            mlflow.log_metric("val_loss",   vl, step=epoch)

        fig = plot_training_curve(h)
        mlflow.log_figure(fig, "plots/loss_curve.png")
        plt.close(fig)

        mlflow.log_param("arch",               best_arch.arch)
        mlflow.log_param("n_layers",           int(best_arch.n_layers))
        mlflow.log_param("units",              int(best_arch.units))
        mlflow.log_param("dropout",            float(best_arch.dropout))
        mlflow.log_param("kernel_size",        best_ks)
        mlflow.log_param("learning_rate",      lr)
        mlflow.log_param("batch_size",         bs)
        mlflow.log_param("input_window_size",  INPUT_W)
        mlflow.log_param("output_window_size", OUTPUT_W)
        mlflow.log_param("n_params",           model.count_params())
        mlflow.log_param("epochs",             len(h.history["loss"]))

        mlflow.log_metric("train_mae", mae_tr)
        mlflow.log_metric("val_mae",   mae_val)
        mlflow.log_metric("test_mae",  mae_te)

        mlflow.keras.log_model(model, name="model")

        results_train.append({
            "learning_rate": lr, "batch_size": bs,
            "MAE_train": mae_tr, "MAE_val": mae_val, "MAE_test": mae_te,
            "epochs": len(h.history["loss"]),
        })
        print(f"lr={lr:.0e} batch={bs:>3}  ->  val={mae_val:.6f} | train={mae_tr:.6f} | test={mae_te:.6f}")

results_train_df = pd.DataFrame(results_train).sort_values("MAE_val").reset_index(drop=True)

Mejor arquitectura: arch=cnn_mlp  n_layers=2  units=128  dropout=0.0  kernel_size=7
  MAE val = 0.009049

2026/05/11 17:18:12 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch= 64  ->  val=0.009352 | train=0.012147 | test=0.012515

2026/05/11 17:18:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch=128  ->  val=0.009151 | train=0.011970 | test=0.012325

2026/05/11 17:18:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch=256  ->  val=0.009120 | train=0.011919 | test=0.012312

2026/05/11 17:19:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch= 64  ->  val=0.009052 | train=0.011865 | test=0.012261

2026/05/11 17:19:40 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch=128  ->  val=0.009049 | train=0.011839 | test=0.012267

2026/05/11 17:19:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch=256  ->  val=0.009045 | train=0.011852 | test=0.012264

2026/05/11 17:20:08 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch= 64  ->  val=0.009043 | train=0.011849 | test=0.012258

2026/05/11 17:20:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch=128  ->  val=0.009040 | train=0.011819 | test=0.012267

2026/05/11 17:21:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch=256  ->  val=0.009038 | train=0.011823 | test=0.012262

In [7]:
results_train_df

   learning_rate  batch_size  MAE_train   MAE_val  MAE_test  epochs
0         0.0001         256   0.011823  0.009038  0.012262      77
1         0.0001         128   0.011819  0.009040  0.012267      69
2         0.0001          64   0.011849  0.009043  0.012258      12
3         0.0010         256   0.011852  0.009045  0.012264      11
4         0.0010         128   0.011839  0.009049  0.012267      48
5         0.0010          64   0.011865  0.009052  0.012261      18
6         0.0100         256   0.011919  0.009120  0.012312      22
7         0.0100         128   0.011970  0.009151  0.012325      11
8         0.0100          64   0.012147  0.009352  0.012515      12

## Modelo final y comparación con benchmarks

Se reentrena el modelo ganador con la configuración completa y se compara con la regresión lineal.

In [8]:
from util import load_benchmark

best_train = results_train_df.iloc[0]
print("Configuración ganadora:")
print(f"  arch          = {best_arch.arch}")
print(f"  n_layers      = {int(best_arch.n_layers)}")
print(f"  units         = {int(best_arch.units)}")
print(f"  dropout       = {float(best_arch.dropout)}")
print(f"  kernel_size   = {best_ks}")
print(f"  learning_rate = {best_train.learning_rate:.0e}")
print(f"  batch_size    = {int(best_train.batch_size)}")

final_model = build_model(
    best_arch.arch, int(best_arch.n_layers), int(best_arch.units),
    float(best_arch.dropout), kernel_size=best_ks, lr=float(best_train.learning_rate),
)
mae_tr_f, mae_val_f, mae_te_f, hist_f = fit_eval(
    final_model, batch_size=int(best_train.batch_size), patience=20,
)

linreg_bench = load_benchmark("lr_benchmark")
linreg_row   = linreg_bench[
    (linreg_bench.input_window == INPUT_W) & (linreg_bench.output_window == OUTPUT_W)
].iloc[0]

run_name_final = f"{EXPERIMENT_NAME}_final"
existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name_final}"')
if not existing.empty:
    mlflow.delete_run(existing.iloc[0].run_id)

with mlflow.start_run(run_name=run_name_final):
    for epoch, (tl, vl) in enumerate(zip(hist_f.history["loss"], hist_f.history["val_loss"])):
        mlflow.log_metric("train_loss", tl, step=epoch)
        mlflow.log_metric("val_loss",   vl, step=epoch)

    fig_f = plot_training_curve(hist_f, show=True)
    mlflow.log_figure(fig_f, "plots/loss_curve.png")
    plt.close(fig_f)

    mlflow.log_param("arch",               best_arch.arch)
    mlflow.log_param("n_layers",           int(best_arch.n_layers))
    mlflow.log_param("units",              int(best_arch.units))
    mlflow.log_param("dropout",            float(best_arch.dropout))
    mlflow.log_param("kernel_size",        best_ks)
    mlflow.log_param("learning_rate",      float(best_train.learning_rate))
    mlflow.log_param("batch_size",         int(best_train.batch_size))
    mlflow.log_param("input_window_size",  INPUT_W)
    mlflow.log_param("output_window_size", OUTPUT_W)
    mlflow.log_param("n_params",           final_model.count_params())
    mlflow.log_param("epochs",             len(hist_f.history["loss"]))
    mlflow.log_metric("train_mae",         mae_tr_f)
    mlflow.log_metric("val_mae",           mae_val_f)
    mlflow.log_metric("test_mae",          mae_te_f)
    mlflow.keras.log_model(final_model, name="model")

summary = pd.DataFrame([
    {"modelo": "Regresión lineal",                 "MAE_train": linreg_row.MAE_train, "MAE_test": linreg_row.MAE_test},
    {"modelo": f"Mejor mixto ({best_arch.arch})",  "MAE_train": mae_tr_f,             "MAE_test": mae_te_f},
])
summary["Δ vs lin.reg. (test)"] = summary["MAE_test"] - linreg_row.MAE_test
display(summary)

Configuración ganadora:
  arch          = cnn_mlp
  n_layers      = 2
  units         = 128
  dropout       = 0.0
  kernel_size   = 7
  learning_rate = 1e-04
  batch_size    = 256

/Users/jchulvi/projects/Neural-Networks-Forecasting/util.py:221: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
2026/05/11 17:22:53 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

                  modelo  MAE_train  MAE_test  Δ vs lin.reg. (test)
0       Regresión lineal   0.011191  0.014095              0.000000
1  Mejor mixto (cnn_mlp)   0.011815  0.012273             -0.001823

## Top-10 configuraciones por etapa

In [9]:
fig, axes = plt.subplots(1, 2, figsize=(16, 5))

def plot_top(ax, df, label_cols, title, top=10):
    top_df = df.head(top).iloc[::-1]
    labels = top_df[label_cols].astype(str).agg(" · ".join, axis=1)
    ypos = np.arange(len(top_df))
    ax.barh(ypos - 0.2, top_df["MAE_val"],   height=0.4, label="MAE val",   color="steelblue")
    ax.barh(ypos + 0.2, top_df["MAE_train"], height=0.4, label="MAE train", color="lightgray")
    ax.set_yticks(ypos)
    ax.set_yticklabels(labels, fontsize=9)
    ax.set_xlabel("MAE")
    ax.set_title(title)
    ax.legend(loc="lower right")
    ax.grid(True, axis="x", alpha=0.3)

# Para Etapa 1 incluimos kernel_size en la etiqueta de las CNN (0 = no aplica)
arch_label_cols = ["arch", "n_layers", "units", "dropout", "kernel_size"]
plot_top(axes[0], results_arch_df,  arch_label_cols,
         "Etapa 1 — arquitectura (top 10)")
plot_top(axes[1], results_train_df, ["learning_rate", "batch_size"],
         "Etapa 2 — entrenamiento (top 9)")

plt.tight_layout()
plt.show()

/var/folders/py/c5_xfbqn469g5_844mv32gt40000gn/T/ipykernel_30664/2599696556.py:24: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()