# Modelos Mixtos — Combinaciones Conv1D, LSTM, GRU y MLP

Este notebook explora combinaciones de capas **convolucionales** (Conv1D), **recurrentes** (LSTM, GRU) y **densas** (MLP) para la configuración fija:

- **Ventana de entrada:** 5 días
- **Ventana de salida:** 30 días

Arquitecturas evaluadas:
- `lstm` — LSTM apiladas
- `gru` — GRU apiladas
- `cnn_lstm` — Conv1D → LSTM
- `cnn_gru` — Conv1D → GRU

- `cnn_lstm_mlp` — Conv1D → LSTM → MLP

- `cnn_gru_mlp` — Conv1D → GRU → MLP

- `cnn_mlp` — Conv1D → MLP

La búsqueda se realiza en dos etapas:
1. **Etapa 1 — Arquitectura**: tipo de red × n_layers × units × dropout (84 combinaciones)
2. **Etapa 2 — Entrenamiento**: learning rate × batch size con la mejor arquitectura de la Etapa 1 (9 combinaciones)

In [1]:
import sys
import itertools
import mlflow
from pathlib import Path

# Busca util.py subiendo niveles desde el directorio actual
_here = Path.cwd()
PROJECT_ROOT = next(
    p for p in [_here, _here.parent, _here.parent.parent, _here.parent.parent.parent]
    if (p / 'util.py').exists()
)
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

mlflow.set_tracking_uri(f"sqlite:///{PROJECT_ROOT / 'model' / 'mlflow.db'}")

EXPERIMENT_NAME = "Modelos_Mixtos_input5_output30"
mlflow.set_experiment(EXPERIMENT_NAME)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import keras
from keras.models import Sequential
from keras.layers import LSTM, GRU, Dense, Input, Conv1D, GlobalAveragePooling1D, Dropout
from keras.callbacks import EarlyStopping
from keras.optimizers import Adam

from sklearn.metrics import mean_absolute_error

from util import get_train_test, RANDOM_SEED, plot_training_curve

np.random.seed(RANDOM_SEED)
keras.utils.set_random_seed(RANDOM_SEED)

## Carga de datos

In [2]:
INPUT_W  = 5
OUTPUT_W = 30

def load_seq_data(input_window_size, output_window_size):
    d = get_train_test(input_window_size=input_window_size, output_window_size=output_window_size)
    X_train, X_test = d.X_train, d.X_test
    y_train, y_test = d.y_train, d.y_test
    val_size         = int(0.10 * X_train.shape[0])
    X_val, y_val     = X_train[-val_size:], y_train[-val_size:]
    X_train, y_train = X_train[:-val_size], y_train[:-val_size]
    return X_train, y_train, X_val, y_val, X_test, y_test

X_tr, y_tr, X_val, y_val, X_te, y_te = load_seq_data(INPUT_W, OUTPUT_W)

print(f"X_tr:  {X_tr.shape}   y_tr:  {y_tr.shape}")
print(f"X_val: {X_val.shape}  y_val: {y_val.shape}")
print(f"X_te:  {X_te.shape}   y_te:  {y_te.shape}")

X_tr:  (13082, 5, 23)   y_tr:  (13082, 23)
X_val: (1453, 5, 23)  y_val: (1453, 23)
X_te:  (1616, 5, 23)   y_te:  (1616, 23)

## Arquitecturas implementadas

La función `build_model` construye el modelo según el argumento `arch`:

| `arch`     | Capas                                      |
|------------|--------------------------------------------|
| `lstm`     | Input → LSTM × n_layers → Dense            |
| `gru`      | Input → GRU × n_layers → Dense             |
| `cnn_lstm` | Input → Conv1D → LSTM × n_layers → Dense   |
| `cnn_gru`  | Input → Conv1D → GRU × n_layers → Dense    |

| `cnn_lstm_mlp` | Input → Conv1D → LSTM × n_layers → MLP → Dense |

| `cnn_gru_mlp`  | Input → Conv1D → GRU × n_layers → MLP → Dense  |

| `cnn_mlp`      | Input → Conv1D → GlobalAveragePooling1D → MLP × n_layers → Dense |

El `kernel_size` de Conv1D se fija a 3 (válido para input_w=5 con `padding="same"`).

In [3]:
KERNEL_SIZE = 3


def add_mlp_head(model, n_layers, units, dropout):
    for i in range(n_layers):
        layer_units = units if i == 0 else max(units // 2, 16)
        model.add(Dense(layer_units, activation="relu"))
        if dropout > 0:
            model.add(Dropout(dropout))


def build_model(arch, n_layers, units, dropout, lr=1e-3):
    keras.utils.set_random_seed(RANDOM_SEED)
    m = Sequential()
    m.add(Input(shape=(X_tr.shape[1], X_tr.shape[2])))

    if arch == "lstm":
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "gru":
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_lstm":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_gru":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))

    elif arch == "cnn_lstm_mlp":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(LSTM(units, return_sequences=(i < n_layers - 1), dropout=dropout))
        add_mlp_head(m, 2, units, dropout)

    elif arch == "cnn_gru_mlp":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        for i in range(n_layers):
            m.add(GRU(units, return_sequences=(i < n_layers - 1), dropout=dropout))
        add_mlp_head(m, 2, units, dropout)

    elif arch == "cnn_mlp":
        m.add(Conv1D(units, kernel_size=KERNEL_SIZE, activation="relu", padding="same"))
        m.add(GlobalAveragePooling1D())
        add_mlp_head(m, n_layers, units, dropout)

    else:
        raise ValueError(f"Arquitectura no soportada: {arch}")

    m.add(Dense(y_tr.shape[1]))
    m.compile(loss="mean_absolute_error", optimizer=Adam(learning_rate=lr))
    return m



def fit_eval(model, batch_size=128, epochs=200, patience=10, verbose=0):
    es = EarlyStopping(monitor="val_loss", patience=patience, restore_best_weights=True)
    h = model.fit(
        X_tr, y_tr,
        validation_data=(X_val, y_val),
        epochs=epochs,
        batch_size=batch_size,
        callbacks=[es],
        verbose=verbose,
    )
    mae_tr  = mean_absolute_error(y_tr,  model.predict(X_tr,  verbose=0))
    mae_val = mean_absolute_error(y_val, model.predict(X_val, verbose=0))
    mae_te  = mean_absolute_error(y_te,  model.predict(X_te,  verbose=0))
    return mae_tr, mae_val, mae_te, h

## Etapa 1 — Búsqueda de arquitectura

Grid: `arch` × `n_layers` × `units` × `dropout` (learning rate y batch size fijos).

Criterio de selección: **MAE de validación mínimo**.

In [4]:
arch_grid = list(itertools.product(
    ["lstm", "gru", "cnn_lstm", "cnn_gru", "cnn_lstm_mlp", "cnn_gru_mlp", "cnn_mlp"],
    [1, 2],
    [32, 64, 128],
    [0.0, 0.2],
))

results_arch = []
batch_size_arch = 128

for arch, nl, u, dr in arch_grid:
    run_name = f"{EXPERIMENT_NAME}_arch_{arch}_layers{nl}_units{u}_drop{dr}"
    existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing.empty:
        mlflow.delete_run(existing.iloc[0].run_id)

    with mlflow.start_run(run_name=run_name):
        model = build_model(arch, nl, u, dr, lr=1e-3)
        mae_tr, mae_val, mae_te, h = fit_eval(model, batch_size=batch_size_arch)

        for epoch, (tl, vl) in enumerate(zip(h.history["loss"], h.history["val_loss"])):
            mlflow.log_metric("train_loss", tl, step=epoch)
            mlflow.log_metric("val_loss",   vl, step=epoch)

        fig = plot_training_curve(h)
        mlflow.log_figure(fig, "plots/loss_curve.png")
        plt.close(fig)

        mlflow.log_param("arch",               arch)
        mlflow.log_param("n_layers",           nl)
        mlflow.log_param("units",              u)
        mlflow.log_param("dropout",            dr)
        mlflow.log_param("kernel_size",        KERNEL_SIZE)
        mlflow.log_param("learning_rate",      1e-3)
        mlflow.log_param("batch_size",         batch_size_arch)
        mlflow.log_param("input_window_size",  INPUT_W)
        mlflow.log_param("output_window_size", OUTPUT_W)
        mlflow.log_param("n_params",           model.count_params())
        mlflow.log_param("epochs",             len(h.history["loss"]))

        mlflow.log_metric("train_mae", mae_tr)
        mlflow.log_metric("val_mae",   mae_val)
        mlflow.log_metric("test_mae",  mae_te)

        mlflow.keras.log_model(model, name="model")

        results_arch.append({
            "arch": arch, "n_layers": nl, "units": u, "dropout": dr,
            "MAE_train": mae_tr, "MAE_val": mae_val, "MAE_test": mae_te,
            "epochs": len(h.history["loss"]), "n_params": model.count_params(),
        })
        print(f"arch={arch:<10} layers={nl} units={u:>3} dropout={dr}  ->  val={mae_val:.6f} | train={mae_tr:.6f} | test={mae_te:.6f}")

results_arch_df = pd.DataFrame(results_arch).sort_values("MAE_val").reset_index(drop=True)

2026/05/10 18:46:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 32 dropout=0.0  ->  val=0.001716 | train=0.002220 | test=0.002365

2026/05/10 18:46:11 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 32 dropout=0.2  ->  val=0.001715 | train=0.002218 | test=0.002358

2026/05/10 18:46:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 64 dropout=0.0  ->  val=0.001726 | train=0.002221 | test=0.002367

2026/05/10 18:46:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units= 64 dropout=0.2  ->  val=0.001725 | train=0.002220 | test=0.002361

2026/05/10 18:46:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units=128 dropout=0.0  ->  val=0.001723 | train=0.002215 | test=0.002353

2026/05/10 18:47:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=1 units=128 dropout=0.2  ->  val=0.001722 | train=0.002211 | test=0.002349

2026/05/10 18:47:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 32 dropout=0.0  ->  val=0.001723 | train=0.002215 | test=0.002347

2026/05/10 18:47:28 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 32 dropout=0.2  ->  val=0.001721 | train=0.002222 | test=0.002355

2026/05/10 18:47:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 64 dropout=0.0  ->  val=0.001719 | train=0.002206 | test=0.002354

2026/05/10 18:47:59 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units= 64 dropout=0.2  ->  val=0.001717 | train=0.002210 | test=0.002343

2026/05/10 18:48:23 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units=128 dropout=0.0  ->  val=0.001717 | train=0.002211 | test=0.002355

2026/05/10 18:49:12 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=lstm       layers=2 units=128 dropout=0.2  ->  val=0.001710 | train=0.002209 | test=0.002336

2026/05/10 18:49:22 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 32 dropout=0.0  ->  val=0.001729 | train=0.002213 | test=0.002363

2026/05/10 18:49:33 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 32 dropout=0.2  ->  val=0.001717 | train=0.002215 | test=0.002354

2026/05/10 18:49:47 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 64 dropout=0.0  ->  val=0.001722 | train=0.002218 | test=0.002380

2026/05/10 18:49:57 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units= 64 dropout=0.2  ->  val=0.001735 | train=0.002226 | test=0.002370

2026/05/10 18:50:09 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units=128 dropout=0.0  ->  val=0.001735 | train=0.002245 | test=0.002390

2026/05/10 18:50:23 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=1 units=128 dropout=0.2  ->  val=0.001726 | train=0.002234 | test=0.002374

2026/05/10 18:50:36 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 32 dropout=0.0  ->  val=0.001727 | train=0.002214 | test=0.002367

2026/05/10 18:50:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 32 dropout=0.2  ->  val=0.001716 | train=0.002208 | test=0.002349

2026/05/10 18:51:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 64 dropout=0.0  ->  val=0.001729 | train=0.002225 | test=0.002377

2026/05/10 18:51:32 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units= 64 dropout=0.2  ->  val=0.001713 | train=0.002213 | test=0.002344

2026/05/10 18:52:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units=128 dropout=0.0  ->  val=0.001720 | train=0.002221 | test=0.002352

2026/05/10 18:52:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=gru        layers=2 units=128 dropout=0.2  ->  val=0.001711 | train=0.002224 | test=0.002347

2026/05/10 18:52:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.0  ->  val=0.001702 | train=0.002204 | test=0.002353

2026/05/10 18:52:55 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 32 dropout=0.2  ->  val=0.001705 | train=0.002210 | test=0.002350

2026/05/10 18:53:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.0  ->  val=0.001724 | train=0.002196 | test=0.002371

2026/05/10 18:53:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units= 64 dropout=0.2  ->  val=0.001718 | train=0.002195 | test=0.002361

2026/05/10 18:53:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.0  ->  val=0.001741 | train=0.002187 | test=0.002390

2026/05/10 18:53:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=1 units=128 dropout=0.2  ->  val=0.001742 | train=0.002225 | test=0.002367

2026/05/10 18:53:52 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.0  ->  val=0.001734 | train=0.002239 | test=0.002353

2026/05/10 18:54:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 32 dropout=0.2  ->  val=0.001711 | train=0.002161 | test=0.002352

2026/05/10 18:54:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.0  ->  val=0.001730 | train=0.002244 | test=0.002381

2026/05/10 18:54:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units= 64 dropout=0.2  ->  val=0.001717 | train=0.002236 | test=0.002356

2026/05/10 18:54:51 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.0  ->  val=0.001761 | train=0.002179 | test=0.002412

2026/05/10 18:55:15 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm   layers=2 units=128 dropout=0.2  ->  val=0.001739 | train=0.002174 | test=0.002386

2026/05/10 18:55:24 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.0  ->  val=0.001722 | train=0.002198 | test=0.002341

2026/05/10 18:55:35 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 32 dropout=0.2  ->  val=0.001704 | train=0.002185 | test=0.002346

2026/05/10 18:55:46 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.0  ->  val=0.001749 | train=0.002159 | test=0.002421

2026/05/10 18:55:57 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units= 64 dropout=0.2  ->  val=0.001742 | train=0.002191 | test=0.002376

2026/05/10 18:56:12 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.0  ->  val=0.001750 | train=0.002168 | test=0.002444

2026/05/10 18:56:27 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=1 units=128 dropout=0.2  ->  val=0.001749 | train=0.002166 | test=0.002394

2026/05/10 18:56:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.0  ->  val=0.001711 | train=0.002231 | test=0.002356

2026/05/10 18:56:52 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 32 dropout=0.2  ->  val=0.001709 | train=0.002184 | test=0.002362

2026/05/10 18:57:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.0  ->  val=0.001764 | train=0.002176 | test=0.002391

2026/05/10 18:57:29 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units= 64 dropout=0.2  ->  val=0.001731 | train=0.002069 | test=0.002428

2026/05/10 18:57:49 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.0  ->  val=0.001772 | train=0.002235 | test=0.002413

2026/05/10 18:58:11 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru    layers=2 units=128 dropout=0.2  ->  val=0.001737 | train=0.002205 | test=0.002368

2026/05/10 18:58:20 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.0  ->  val=0.001713 | train=0.002225 | test=0.002334

2026/05/10 18:58:31 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 32 dropout=0.2  ->  val=0.001714 | train=0.002225 | test=0.002331

2026/05/10 18:58:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.0  ->  val=0.001712 | train=0.002224 | test=0.002334

2026/05/10 18:58:58 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units= 64 dropout=0.2  ->  val=0.001713 | train=0.002225 | test=0.002332

2026/05/10 18:59:11 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.0  ->  val=0.001709 | train=0.002224 | test=0.002335

2026/05/10 18:59:35 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=1 units=128 dropout=0.2  ->  val=0.001714 | train=0.002225 | test=0.002334

2026/05/10 18:59:47 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.0  ->  val=0.001713 | train=0.002224 | test=0.002332

2026/05/10 19:00:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 32 dropout=0.2  ->  val=0.001713 | train=0.002225 | test=0.002334

2026/05/10 19:00:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.0  ->  val=0.001715 | train=0.002224 | test=0.002336

2026/05/10 19:00:45 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units= 64 dropout=0.2  ->  val=0.001714 | train=0.002225 | test=0.002333

2026/05/10 19:01:05 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.0  ->  val=0.001720 | train=0.002221 | test=0.002335

2026/05/10 19:01:30 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_lstm_mlp layers=2 units=128 dropout=0.2  ->  val=0.001713 | train=0.002225 | test=0.002332

2026/05/10 19:01:40 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.0  ->  val=0.001714 | train=0.002226 | test=0.002335

2026/05/10 19:01:52 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 32 dropout=0.2  ->  val=0.001713 | train=0.002223 | test=0.002331

2026/05/10 19:02:04 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.0  ->  val=0.001709 | train=0.002165 | test=0.002355

2026/05/10 19:02:21 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units= 64 dropout=0.2  ->  val=0.001714 | train=0.002225 | test=0.002332

2026/05/10 19:02:39 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.0  ->  val=0.001717 | train=0.002192 | test=0.002350

2026/05/10 19:03:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=1 units=128 dropout=0.2  ->  val=0.001714 | train=0.002224 | test=0.002332

2026/05/10 19:03:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.0  ->  val=0.001712 | train=0.002223 | test=0.002333

2026/05/10 19:03:29 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 32 dropout=0.2  ->  val=0.001714 | train=0.002226 | test=0.002336

2026/05/10 19:03:42 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.0  ->  val=0.001712 | train=0.002221 | test=0.002333

2026/05/10 19:04:02 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units= 64 dropout=0.2  ->  val=0.001713 | train=0.002225 | test=0.002333

2026/05/10 19:04:23 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.0  ->  val=0.001715 | train=0.002230 | test=0.002340

2026/05/10 19:04:59 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_gru_mlp layers=2 units=128 dropout=0.2  ->  val=0.001714 | train=0.002225 | test=0.002333

2026/05/10 19:05:06 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.0  ->  val=0.001711 | train=0.002221 | test=0.002338

2026/05/10 19:05:13 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 32 dropout=0.2  ->  val=0.001706 | train=0.002217 | test=0.002339

2026/05/10 19:05:19 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.0  ->  val=0.001709 | train=0.002217 | test=0.002342

2026/05/10 19:05:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units= 64 dropout=0.2  ->  val=0.001710 | train=0.002217 | test=0.002333

2026/05/10 19:05:33 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.0  ->  val=0.001709 | train=0.002207 | test=0.002331

2026/05/10 19:05:40 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=1 units=128 dropout=0.2  ->  val=0.001710 | train=0.002218 | test=0.002331

2026/05/10 19:05:48 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.0  ->  val=0.001713 | train=0.002221 | test=0.002332

2026/05/10 19:05:56 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 32 dropout=0.2  ->  val=0.001714 | train=0.002225 | test=0.002334

2026/05/10 19:06:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.0  ->  val=0.001713 | train=0.002226 | test=0.002338

2026/05/10 19:06:10 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units= 64 dropout=0.2  ->  val=0.001713 | train=0.002224 | test=0.002334

2026/05/10 19:06:17 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.0  ->  val=0.001709 | train=0.002214 | test=0.002334

2026/05/10 19:06:25 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

arch=cnn_mlp    layers=2 units=128 dropout=0.2  ->  val=0.001713 | train=0.002224 | test=0.002332

### Resultados — Etapa 1 (top 10)

In [5]:
results_arch_df.head(10)

,arch,n_layers,units,dropout,MAE_train,MAE_val,MAE_test,epochs,n_params
0,cnn_lstm,1,32,0.0,0.002204,0.001702,0.002353,15,11319
1,cnn_gru,1,32,0.2,0.002185,0.001704,0.002346,21,9335
2,cnn_lstm,1,32,0.2,0.002210,0.001705,0.002350,16,11319
3,cnn_mlp,1,32,0.2,0.002217,0.001706,0.002339,11,4055
4,cnn_mlp,1,128,0.0,0.002207,0.001709,0.002331,15,28439
5,cnn_mlp,2,128,0.0,0.002214,0.001709,0.002334,11,35223
6,cnn_mlp,1,64,0.0,0.002217,0.001709,0.002342,11,10135
7,cnn_gru,2,32,0.2,0.002184,0.001709,0.002362,21,15671
8,cnn_gru_mlp,1,64,0.0,0.002165,0.001709,0.002355,18,36439
9,cnn_lstm_mlp,1,128,0.0,0.002224,0.001709,0.002335,11,166807

## Etapa 2 — Hiperparámetros de entrenamiento

Se fija la arquitectura ganadora de la Etapa 1 y se busca sobre `learning_rate` × `batch_size`.

Criterio de selección: **MAE de validación mínimo**.

In [6]:
best_arch = results_arch_df.iloc[0]
print(f"Mejor arquitectura: arch={best_arch.arch}  n_layers={int(best_arch.n_layers)}  units={int(best_arch.units)}  dropout={best_arch.dropout}")
print(f"  MAE val = {best_arch.MAE_val:.6f}")

train_grid = list(itertools.product([1e-2, 1e-3, 1e-4], [64, 128, 256]))

results_train = []
for lr, bs in train_grid:
    run_name = f"{EXPERIMENT_NAME}_train_{best_arch.arch}_lr{lr:.0e}_batch{bs}"
    existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing.empty:
        mlflow.delete_run(existing.iloc[0].run_id)

    with mlflow.start_run(run_name=run_name):
        model = build_model(
            best_arch.arch, int(best_arch.n_layers), int(best_arch.units),
            float(best_arch.dropout), lr=lr,
        )
        mae_tr, mae_val, mae_te, h = fit_eval(model, batch_size=bs)

        for epoch, (tl, vl) in enumerate(zip(h.history["loss"], h.history["val_loss"])):
            mlflow.log_metric("train_loss", tl, step=epoch)
            mlflow.log_metric("val_loss",   vl, step=epoch)

        fig = plot_training_curve(h)
        mlflow.log_figure(fig, "plots/loss_curve.png")
        plt.close(fig)

        mlflow.log_param("arch",               best_arch.arch)
        mlflow.log_param("n_layers",           int(best_arch.n_layers))
        mlflow.log_param("units",              int(best_arch.units))
        mlflow.log_param("dropout",            float(best_arch.dropout))
        mlflow.log_param("kernel_size",        KERNEL_SIZE)
        mlflow.log_param("learning_rate",      lr)
        mlflow.log_param("batch_size",         bs)
        mlflow.log_param("input_window_size",  INPUT_W)
        mlflow.log_param("output_window_size", OUTPUT_W)
        mlflow.log_param("n_params",           model.count_params())
        mlflow.log_param("epochs",             len(h.history["loss"]))

        mlflow.log_metric("train_mae", mae_tr)
        mlflow.log_metric("val_mae",   mae_val)
        mlflow.log_metric("test_mae",  mae_te)

        mlflow.keras.log_model(model, name="model")

        results_train.append({
            "learning_rate": lr, "batch_size": bs,
            "MAE_train": mae_tr, "MAE_val": mae_val, "MAE_test": mae_te,
            "epochs": len(h.history["loss"]),
        })
        print(f"lr={lr:.0e} batch={bs:>3}  ->  val={mae_val:.6f} | train={mae_tr:.6f} | test={mae_te:.6f}")

results_train_df = pd.DataFrame(results_train).sort_values("MAE_val").reset_index(drop=True)

Mejor arquitectura: arch=cnn_lstm  n_layers=1  units=32  dropout=0.0
  MAE val = 0.001702

2026/05/10 19:06:35 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch= 64  ->  val=0.001809 | train=0.002298 | test=0.002472

2026/05/10 19:06:43 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch=128  ->  val=0.001829 | train=0.002366 | test=0.002485

2026/05/10 19:06:50 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-02 batch=256  ->  val=0.001779 | train=0.002301 | test=0.002433

2026/05/10 19:06:59 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch= 64  ->  val=0.001730 | train=0.002207 | test=0.002360

2026/05/10 19:07:08 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch=128  ->  val=0.001702 | train=0.002204 | test=0.002353

2026/05/10 19:07:16 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-03 batch=256  ->  val=0.001714 | train=0.002214 | test=0.002343

2026/05/10 19:07:26 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch= 64  ->  val=0.001707 | train=0.002211 | test=0.002338

2026/05/10 19:07:38 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch=128  ->  val=0.001701 | train=0.002192 | test=0.002338

2026/05/10 19:07:50 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

lr=1e-04 batch=256  ->  val=0.001698 | train=0.002196 | test=0.002339

In [7]:
results_train_df

   learning_rate  batch_size  MAE_train   MAE_val  MAE_test  epochs
0         0.0001         256   0.002196  0.001698  0.002339      45
1         0.0001         128   0.002192  0.001701  0.002338      34
2         0.0010         128   0.002204  0.001702  0.002353      15
3         0.0001          64   0.002211  0.001707  0.002338      17
4         0.0010         256   0.002214  0.001714  0.002343      13
5         0.0010          64   0.002207  0.001730  0.002360      13
6         0.0100         256   0.002301  0.001779  0.002433      11
7         0.0100          64   0.002298  0.001809  0.002472      13
8         0.0100         128   0.002366  0.001829  0.002485      11

## Modelo final y comparación con benchmarks

Se reentrena el modelo ganador con la configuración completa y se compara con la regresión lineal.

In [8]:
from util import load_benchmark

best_train = results_train_df.iloc[0]
print("Configuración ganadora:")
print(f"  arch          = {best_arch.arch}")
print(f"  n_layers      = {int(best_arch.n_layers)}")
print(f"  units         = {int(best_arch.units)}")
print(f"  dropout       = {float(best_arch.dropout)}")
print(f"  learning_rate = {best_train.learning_rate:.0e}")
print(f"  batch_size    = {int(best_train.batch_size)}")

final_model = build_model(
    best_arch.arch, int(best_arch.n_layers), int(best_arch.units),
    float(best_arch.dropout), lr=float(best_train.learning_rate),
)
mae_tr_f, mae_val_f, mae_te_f, hist_f = fit_eval(
    final_model, batch_size=int(best_train.batch_size), patience=20,
)

linreg_bench = load_benchmark("lr_benchmark")
linreg_row   = linreg_bench[
    (linreg_bench.input_window == INPUT_W) & (linreg_bench.output_window == OUTPUT_W)
].iloc[0]

run_name_final = f"{EXPERIMENT_NAME}_final"
existing = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name_final}"')
if not existing.empty:
    mlflow.delete_run(existing.iloc[0].run_id)

with mlflow.start_run(run_name=run_name_final):
    for epoch, (tl, vl) in enumerate(zip(hist_f.history["loss"], hist_f.history["val_loss"])):
        mlflow.log_metric("train_loss", tl, step=epoch)
        mlflow.log_metric("val_loss",   vl, step=epoch)

    fig_f = plot_training_curve(hist_f, show=True)
    mlflow.log_figure(fig_f, "plots/loss_curve.png")
    plt.close(fig_f)

    mlflow.log_param("arch",               best_arch.arch)
    mlflow.log_param("n_layers",           int(best_arch.n_layers))
    mlflow.log_param("units",              int(best_arch.units))
    mlflow.log_param("dropout",            float(best_arch.dropout))
    mlflow.log_param("kernel_size",        KERNEL_SIZE)
    mlflow.log_param("learning_rate",      float(best_train.learning_rate))
    mlflow.log_param("batch_size",         int(best_train.batch_size))
    mlflow.log_param("input_window_size",  INPUT_W)
    mlflow.log_param("output_window_size", OUTPUT_W)
    mlflow.log_param("n_params",           final_model.count_params())
    mlflow.log_param("epochs",             len(hist_f.history["loss"]))
    mlflow.log_metric("train_mae",         mae_tr_f)
    mlflow.log_metric("val_mae",           mae_val_f)
    mlflow.log_metric("test_mae",          mae_te_f)
    mlflow.keras.log_model(final_model, name="model")

summary = pd.DataFrame([
    {"modelo": "Regresión lineal",                 "MAE_train": linreg_row.MAE_train, "MAE_test": linreg_row.MAE_test},
    {"modelo": f"Mejor mixto ({best_arch.arch})",  "MAE_train": mae_tr_f,             "MAE_test": mae_te_f},
])
summary["Δ vs lin.reg. (test)"] = summary["MAE_test"] - linreg_row.MAE_test
display(summary)

Configuración ganadora:
  arch          = cnn_lstm
  n_layers      = 1
  units         = 32
  dropout       = 0.0
  learning_rate = 1e-04
  batch_size    = 256

/Users/jchulvi/projects/Neural-Networks-Forecasting/util.py:221: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
2026/05/10 19:08:03 WARNING mlflow.keras.save: You are saving a Keras model without specifying model signature.

                   modelo  MAE_train  MAE_test  Δ vs lin.reg. (test)
0        Regresión lineal   0.002192  0.002340          0.000000e+00
1  Mejor mixto (cnn_lstm)   0.002196  0.002339         -8.449911e-07

## Top-10 configuraciones por etapa

In [9]:
fig, axes = plt.subplots(1, 2, figsize=(16, 5))

def plot_top(ax, df, label_cols, title, top=10):
    top_df = df.head(top).iloc[::-1]
    labels = top_df[label_cols].astype(str).agg(" · ".join, axis=1)
    ypos = np.arange(len(top_df))
    ax.barh(ypos - 0.2, top_df["MAE_val"],   height=0.4, label="MAE val",   color="steelblue")
    ax.barh(ypos + 0.2, top_df["MAE_train"], height=0.4, label="MAE train", color="lightgray")
    ax.set_yticks(ypos)
    ax.set_yticklabels(labels, fontsize=9)
    ax.set_xlabel("MAE")
    ax.set_title(title)
    ax.legend(loc="lower right")
    ax.grid(True, axis="x", alpha=0.3)

plot_top(axes[0], results_arch_df,  ["arch", "n_layers", "units", "dropout"],
         "Etapa 1 — arquitectura (top 10)")
plot_top(axes[1], results_train_df, ["learning_rate", "batch_size"],
         "Etapa 2 — entrenamiento (top 9)")

plt.tight_layout()
plt.show()

/var/folders/py/c5_xfbqn469g5_844mv32gt40000gn/T/ipykernel_28054/3018486118.py:22: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()