# Hybrid CNN-RNN models for assigned windows

This notebook trains hybrid neural networks that combine **Conv1D** layers with **LSTM/GRU** layers.

Assigned windows:

| Input window | Output window |
|---:|---:|
| 10 | 30 |
| 10 | 90 |
| 30 | 1 |
| 30 | 5 |

The goal is to evaluate mixed architectures on the forecasting task and export results that can be used directly in the final report.

The test set is not used for model selection. For each run, the notebook uses:

1. train split for fitting the model,
2. validation split for early stopping and model comparison,
3. test split for final evaluation.

In [1]:
import os
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")

import sys
import json
from pathlib import Path
from datetime import datetime

# Locate project root from notebook execution directory.
_here = Path.cwd().resolve()
_candidates = [_here, *_here.parents]
PROJECT_ROOT = next(p for p in _candidates if (p / "util.py").exists())
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler

import keras
from keras import backend as K
from keras.models import Model
from keras.layers import (
    Input,
    Conv1D,
    BatchNormalization,
    SpatialDropout1D,
    LSTM,
    GRU,
    Bidirectional,
    Dense,
    Dropout,
)
from keras.callbacks import EarlyStopping, ReduceLROnPlateau

from util import get_train_test, RANDOM_SEED, plot_training_curve

try:
    from util import configure_mlflow
except ImportError:
    import mlflow

    def configure_mlflow(experiment_name: str):
        tracking_uri = f"sqlite:///{PROJECT_ROOT / 'model' / 'mlflow.db'}"
        mlflow.set_tracking_uri(tracking_uri)
        mlflow.set_experiment(experiment_name)
        return mlflow


np.random.seed(RANDOM_SEED)
keras.utils.set_random_seed(RANDOM_SEED)

DATA_OUT = PROJECT_ROOT / "data" / "hybrid"
HISTORY_DIR = DATA_OUT / "history"
PLOTS_DIR = DATA_OUT / "plots"

DATA_OUT.mkdir(parents=True, exist_ok=True)
HISTORY_DIR.mkdir(parents=True, exist_ok=True)
PLOTS_DIR.mkdir(parents=True, exist_ok=True)

mlflow = configure_mlflow("hybrid_cnn_rnn_models")

FAST_DEV_RUN = os.getenv("FAST_DEV_RUN", "0") == "1"
LOG_MODEL_ARTIFACT = os.getenv("LOG_MODEL_ARTIFACT", "0") == "1"

print("PROJECT_ROOT:", PROJECT_ROOT)
print("FAST_DEV_RUN:", FAST_DEV_RUN)
print("LOG_MODEL_ARTIFACT:", LOG_MODEL_ARTIFACT)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1777989694.280381 2124792 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1777989694.280732 2124792 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1777989694.993920 2124792 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1777989694.994315 2124792 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

PROJECT_ROOT: /home/hugo/Desktop/Neural-Networks-Forecasting
FAST_DEV_RUN: False
LOG_MODEL_ARTIFACT: False

## Configuration

The full run trains three hybrid architectures for each assigned window:

- `CNN_LSTM`
- `CNN_GRU`
- `CNN_BiGRU`

The hyperparameters are intentionally controlled and comparable across windows. This avoids an excessively large search while still producing a clean comparison between hybrid architectures.

A fast smoke test can be launched from terminal with:

```bash
FAST_DEV_RUN=1 jupyter nbconvert --to notebook --execute model/hybrid/01_hybrid_cnn_rnn_grid.ipynb \
  --output 01_hybrid_cnn_rnn_grid_executed.ipynb \
  --output-dir model/hybrid/outputs
```

In [2]:
WINDOWS = [
    (10, 30),
    (10, 90),
    (30, 1),
    (30, 5),
]

ARCHITECTURES = [
    {
        "architecture": "CNN_LSTM",
        "filters": 64,
        "kernel_size": 3,
        "rnn_units": 64,
        "dense_units": 64,
        "spatial_dropout": 0.10,
        "dropout": 0.15,
        "learning_rate": 3e-4,
        "batch_size": 128,
    },
    {
        "architecture": "CNN_GRU",
        "filters": 64,
        "kernel_size": 3,
        "rnn_units": 64,
        "dense_units": 64,
        "spatial_dropout": 0.10,
        "dropout": 0.15,
        "learning_rate": 3e-4,
        "batch_size": 128,
    },
    {
        "architecture": "CNN_BiGRU",
        "filters": 64,
        "kernel_size": 5,
        "rnn_units": 64,
        "dense_units": 64,
        "spatial_dropout": 0.10,
        "dropout": 0.20,
        "learning_rate": 3e-4,
        "batch_size": 128,
    },
]

MAX_EPOCHS = 80
EARLY_STOPPING_PATIENCE = 10
LR_PATIENCE = 5
VALIDATION_RATIO = 0.10

if FAST_DEV_RUN:
    WINDOWS = WINDOWS[:1]
    ARCHITECTURES = ARCHITECTURES[:1]
    MAX_EPOCHS = 2
    EARLY_STOPPING_PATIENCE = 1
    LR_PATIENCE = 1

print("Windows:", WINDOWS)
print("Architectures:", [cfg["architecture"] for cfg in ARCHITECTURES])
print("Max epochs:", MAX_EPOCHS)

Windows: [(10, 30), (10, 90), (30, 1), (30, 5)]
Architectures: ['CNN_LSTM', 'CNN_GRU', 'CNN_BiGRU']
Max epochs: 80

## Data preparation

The function `get_train_test` returns data with the sequence format required by recurrent and convolutional models:

```text
X: samples × input_window × assets
y: samples × assets
```

The validation set is taken from the end of the training set. Inputs are standardized using only the training split to avoid data leakage.

In [3]:
def split_train_val(X_train, y_train, val_ratio=VALIDATION_RATIO):
    val_size = int(len(X_train) * val_ratio)
    if val_size <= 0:
        raise ValueError("Validation split is empty. Increase the training size or validation ratio.")

    X_val = X_train[-val_size:]
    y_val = y_train[-val_size:]
    X_train_final = X_train[:-val_size]
    y_train_final = y_train[:-val_size]
    return X_train_final, y_train_final, X_val, y_val


def scale_X_only(X_train, X_val, X_test):
    """Scale only the inputs. The target remains in the original return scale."""
    n_train, window, n_assets = X_train.shape
    n_val = X_val.shape[0]
    n_test = X_test.shape[0]

    scaler = StandardScaler()

    X_train_2d = X_train.reshape(n_train, -1)
    X_val_2d = X_val.reshape(n_val, -1)
    X_test_2d = X_test.reshape(n_test, -1)

    X_train_scaled = scaler.fit_transform(X_train_2d).reshape(n_train, window, n_assets)
    X_val_scaled = scaler.transform(X_val_2d).reshape(n_val, window, n_assets)
    X_test_scaled = scaler.transform(X_test_2d).reshape(n_test, window, n_assets)

    return X_train_scaled, X_val_scaled, X_test_scaled


def load_window_data(input_window, output_window):
    d = get_train_test(
        input_window_size=input_window,
        output_window_size=output_window,
    )

    X_train_raw, y_train_raw = d.X_train, d.y_train
    X_test_raw, y_test = d.X_test, d.y_test

    X_train_raw, y_train, X_val_raw, y_val = split_train_val(X_train_raw, y_train_raw)
    X_train, X_val, X_test = scale_X_only(X_train_raw, X_val_raw, X_test_raw)

    return X_train, y_train, X_val, y_val, X_test, y_test

## Hybrid model builder

The hybrid models first use a convolutional layer to detect local temporal patterns. The recurrent block then models the sequential component of the window. The final dense layers map the learned representation to the 23 output assets.

In [4]:
def build_hybrid_model(input_window, n_assets, cfg):
    architecture = cfg["architecture"]

    inputs = Input(shape=(input_window, n_assets))

    x = Conv1D(
        filters=cfg["filters"],
        kernel_size=cfg["kernel_size"],
        padding="causal",
        activation="relu",
    )(inputs)
    x = BatchNormalization()(x)
    x = SpatialDropout1D(cfg["spatial_dropout"])(x)

    if architecture == "CNN_LSTM":
        x = LSTM(cfg["rnn_units"], return_sequences=False)(x)
    elif architecture == "CNN_GRU":
        x = GRU(cfg["rnn_units"], return_sequences=False)(x)
    elif architecture == "CNN_BiGRU":
        x = Bidirectional(GRU(cfg["rnn_units"], return_sequences=False))(x)
    else:
        raise ValueError(f"Unknown architecture: {architecture}")

    x = Dense(cfg["dense_units"], activation="relu")(x)
    x = Dropout(cfg["dropout"])(x)

    outputs = Dense(n_assets, activation="linear")(x)

    model = Model(inputs=inputs, outputs=outputs)
    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=cfg["learning_rate"]),
        loss="mae",
        metrics=["mae"],
    )
    return model

## Training and MLflow logging

Each run is logged to MLflow with the window, architecture, hyperparameters, metrics and training curve. CSV files are also generated under `data/hybrid/` for easier inclusion in the report.

In [5]:
def safe_run_name(architecture, input_window, output_window):
    return f"hybrid_{architecture}_input{input_window}_output{output_window}"


def delete_existing_mlflow_run(run_name):
    existing_runs = mlflow.search_runs(filter_string=f'tags.mlflow.runName = "{run_name}"')
    if not existing_runs.empty:
        for run_id in existing_runs["run_id"]:
            mlflow.delete_run(run_id)


def save_history_and_plot(history, run_name):
    history_df = pd.DataFrame(history.history)
    history_path = HISTORY_DIR / f"{run_name}_history.csv"
    plot_path = PLOTS_DIR / f"{run_name}_loss_curve.png"

    history_df.to_csv(history_path, index=False)

    fig = plot_training_curve(history)
    fig.savefig(plot_path, dpi=150, bbox_inches="tight")
    plt.close(fig)

    return history_path, plot_path


def train_one_model(input_window, output_window, cfg):
    K.clear_session()
    keras.utils.set_random_seed(RANDOM_SEED)

    run_name = safe_run_name(cfg["architecture"], input_window, output_window)
    delete_existing_mlflow_run(run_name)

    X_train, y_train, X_val, y_val, X_test, y_test = load_window_data(input_window, output_window)
    n_assets = X_train.shape[2]

    model = build_hybrid_model(input_window, n_assets, cfg)

    callbacks = [
        EarlyStopping(
            monitor="val_loss",
            patience=EARLY_STOPPING_PATIENCE,
            min_delta=1e-6,
            restore_best_weights=True,
        ),
        ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.5,
            patience=LR_PATIENCE,
            min_lr=1e-6,
        ),
    ]

    print()
    print("=" * 90)
    print(f"Training {run_name}")
    print("X_train:", X_train.shape, "y_train:", y_train.shape)
    print("X_val:  ", X_val.shape, "y_val:  ", y_val.shape)
    print("X_test: ", X_test.shape, "y_test: ", y_test.shape)
    print("Params:", model.count_params())

    history = model.fit(
        X_train,
        y_train,
        validation_data=(X_val, y_val),
        epochs=MAX_EPOCHS,
        batch_size=cfg["batch_size"],
        callbacks=callbacks,
        verbose=1,
        shuffle=True,
    )

    y_pred_train = model.predict(X_train, verbose=0)
    y_pred_val = model.predict(X_val, verbose=0)
    y_pred_test = model.predict(X_test, verbose=0)

    row = {
        "model": cfg["architecture"],
        "input_window": input_window,
        "output_window": output_window,
        "MAE_train": mean_absolute_error(y_train, y_pred_train),
        "MAE_val": mean_absolute_error(y_val, y_pred_val),
        "MAE_test": mean_absolute_error(y_test, y_pred_test),
        "params": model.count_params(),
        "epochs_trained": len(history.history["loss"]),
        "filters": cfg["filters"],
        "kernel_size": cfg["kernel_size"],
        "rnn_units": cfg["rnn_units"],
        "dense_units": cfg["dense_units"],
        "spatial_dropout": cfg["spatial_dropout"],
        "dropout": cfg["dropout"],
        "learning_rate": cfg["learning_rate"],
        "batch_size": cfg["batch_size"],
    }

    history_path, plot_path = save_history_and_plot(history, run_name)
    row["history_path"] = str(history_path.relative_to(PROJECT_ROOT))
    row["plot_path"] = str(plot_path.relative_to(PROJECT_ROOT))

    with mlflow.start_run(run_name=run_name):
        mlflow.set_tag("model_family", "Hybrid_CNN_RNN")
        mlflow.set_tag("model_name", cfg["architecture"])
        mlflow.log_params({
            "input_window_size": input_window,
            "output_window_size": output_window,
            "architecture": cfg["architecture"],
            "filters": cfg["filters"],
            "kernel_size": cfg["kernel_size"],
            "rnn_units": cfg["rnn_units"],
            "dense_units": cfg["dense_units"],
            "spatial_dropout": cfg["spatial_dropout"],
            "dropout": cfg["dropout"],
            "learning_rate": cfg["learning_rate"],
            "batch_size": cfg["batch_size"],
            "epochs_trained": row["epochs_trained"],
            "n_params": row["params"],
            "validation_ratio": VALIDATION_RATIO,
        })

        for epoch, (loss, val_loss) in enumerate(zip(history.history["loss"], history.history["val_loss"]), start=1):
            mlflow.log_metric("train_loss", float(loss), step=epoch)
            mlflow.log_metric("val_loss", float(val_loss), step=epoch)

        mlflow.log_metric("train_mae", float(row["MAE_train"]))
        mlflow.log_metric("val_mae", float(row["MAE_val"]))
        mlflow.log_metric("test_mae", float(row["MAE_test"]))
        mlflow.log_artifact(str(history_path), artifact_path="history")
        mlflow.log_artifact(str(plot_path), artifact_path="plots")

        if LOG_MODEL_ARTIFACT:
            mlflow.keras.log_model(model, name=f"{run_name}_model")

    print("Result:", json.dumps({k: v for k, v in row.items() if not k.endswith('_path')}, indent=2))
    return row

## Execute grid

The full run trains 12 models:

```text
4 windows × 3 architectures = 12 hybrid models
```

The best model for each window is selected by validation MAE.

In [6]:
rows = []

for input_window, output_window in WINDOWS:
    for cfg in ARCHITECTURES:
        row = train_one_model(input_window, output_window, cfg)
        rows.append(row)

        partial = pd.DataFrame(rows)
        partial.to_csv(DATA_OUT / "hybrid_all_results_partial.csv", index=False)

results = pd.DataFrame(rows)
results = results.sort_values(["input_window", "output_window", "MAE_val"]).reset_index(drop=True)
results_path = DATA_OUT / "hybrid_all_results.csv"
results.to_csv(results_path, index=False)

best_by_window = (
    results.sort_values("MAE_val")
    .groupby(["input_window", "output_window"], as_index=False)
    .first()
    .sort_values(["input_window", "output_window"])
)
best_path = DATA_OUT / "hybrid_best_by_window.csv"
best_by_window.to_csv(best_path, index=False)

print("All results saved to:", results_path)
print("Best by window saved to:", best_path)

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
pd.set_option("display.float_format", "{:.8f}".format)

display(results[[
    "model", "input_window", "output_window", "MAE_train", "MAE_val", "MAE_test", "params", "epochs_trained"
]])

display(best_by_window[[
    "model", "input_window", "output_window", "MAE_train", "MAE_val", "MAE_test", "params", "epochs_trained"
]])

==========================================================================================
Training hybrid_CNN_LSTM_input10_output30
X_train: (13078, 10, 23) y_train: (13078, 23)
X_val:   (1453, 10, 23) y_val:   (1453, 23)
X_test:  (1615, 10, 23) y_test:  (1615, 23)
Params: 43415
Epoch 1/80

E0000 00:00:1777989697.988503 2124792 cuda_executor.cc:1737] INTERNAL: CUDA Runtime error: Failed call to cudaGetRuntimeVersion: Error loading CUDA libraries. GPU will not be used.: Error loading CUDA libraries. GPU will not be used.

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1:47 1s/step - loss: 0.1277 - mae: 0.1277

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1247 - mae: 0.1247

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1207 - mae: 0.1207

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1172 - mae: 0.1172

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1140 - mae: 0.1140

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1110 - mae: 0.1110

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1083 - mae: 0.1083

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1058 - mae: 0.1058

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1035 - mae: 0.1035

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1010 - mae: 0.1010

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0990 - mae: 0.0990

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0970 - mae: 0.0970

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0952 - mae: 0.0952

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0934 - mae: 0.0934

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0917 - mae: 0.0917

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0901 - mae: 0.0901

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0885 - mae: 0.0885

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0612 - mae: 0.0612 - val_loss: 0.0100 - val_mae: 0.0100 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0199 - mae: 0.0199

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0187 - mae: 0.0187

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0177 - mae: 0.0177

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0167 - mae: 0.0167

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0157 - mae: 0.0157

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0148 - mae: 0.0148

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0141 - mae: 0.0141

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0135 - mae: 0.0135

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0130 - mae: 0.0130

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0124 - mae: 0.0124

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0115 - mae: 0.0115

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0111 - mae: 0.0111

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0107 - mae: 0.0107

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0104 - mae: 0.0104

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0101 - mae: 0.0101

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0023 - mae: 0.0023

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0023 - mae: 0.0023 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0022 - mae: 0.0022

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0023 - mae: 0.0023

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0023 - mae: 0.0023 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0022 - mae: 0.0022

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0021 - mae: 0.0021

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 16/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 17/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 18/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0021 - mae: 0.0021

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 19/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 20/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 21/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 22/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 23/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 24/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 25/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 26/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0021 - mae: 0.0021

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 27/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 28/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 29/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0022 - mae: 0.0022

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 30/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0021 - mae: 0.0021

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 31/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 32/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 33/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 15/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Result: {
  "model": "CNN_LSTM",
  "input_window": 10,
  "output_window": 30,
  "MAE_train": 0.0022019303807590557,
  "MAE_val": 0.001698554908080839,
  "MAE_test": 0.0023271370211301835,
  "params": 43415,
  "epochs_trained": 33,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_GRU_input10_output30
X_train: (13078, 10, 23) y_train: (13078, 23)
X_val:   (1453, 10, 23) y_val:   (1453, 23)
X_test:  (1615, 10, 23) y_test:  (1615, 23)
Params: 35351
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1:55 1s/step - loss: 0.2363 - mae: 0.2363

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2310 - mae: 0.2310

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2250 - mae: 0.2250

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2195 - mae: 0.2195

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2143 - mae: 0.2143

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2096 - mae: 0.2096

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2053 - mae: 0.2053

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2013 - mae: 0.2013

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1975 - mae: 0.1975

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1939 - mae: 0.1939

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1906 - mae: 0.1906

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1873 - mae: 0.1873

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1843 - mae: 0.1843

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1813 - mae: 0.1813

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1784 - mae: 0.1784

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1757 - mae: 0.1757

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1730 - mae: 0.1730

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.1267 - mae: 0.1267 - val_loss: 0.0224 - val_mae: 0.0224 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0554 - mae: 0.0554

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0528 - mae: 0.0528

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0509 - mae: 0.0509

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0492 - mae: 0.0492

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0474 - mae: 0.0474

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0456 - mae: 0.0456

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0438 - mae: 0.0438

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0419 - mae: 0.0419

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0403 - mae: 0.0403

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0388 - mae: 0.0388

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0373 - mae: 0.0373

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0360 - mae: 0.0360

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0346 - mae: 0.0346

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0332 - mae: 0.0332

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0320 - mae: 0.0320

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0309 - mae: 0.0309

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0153 - mae: 0.0153 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0022 - mae: 0.0022

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0025 - mae: 0.0025

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0025 - mae: 0.0025

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0025 - mae: 0.0025

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0025 - mae: 0.0025

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0025 - mae: 0.0025

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0025 - mae: 0.0025

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0025 - mae: 0.0025

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0025 - mae: 0.0025

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0025 - mae: 0.0025

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0025 - mae: 0.0025

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0025 - mae: 0.0025

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0025 - mae: 0.0025

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0025 - mae: 0.0025

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0025 - mae: 0.0025

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0025 - mae: 0.0025

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0024 - mae: 0.0024

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0024 - mae: 0.0024 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0023 - mae: 0.0023 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0023 - mae: 0.0023

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0023 - mae: 0.0023 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0022 - mae: 0.0022

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 24/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 16/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 17/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 18/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 19/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 20/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 21/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 22/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 23/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 24/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 25/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 26/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 27/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  8/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 14/103 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 28/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 29/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 30/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 31/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0022 - mae: 0.0022

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 32/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 33/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Epoch 34/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Epoch 35/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 19/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Result: {
  "model": "CNN_GRU",
  "input_window": 10,
  "output_window": 30,
  "MAE_train": 0.0022019189244073707,
  "MAE_val": 0.001698527509930831,
  "MAE_test": 0.0023197140191211865,
  "params": 35351,
  "epochs_trained": 35,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_BiGRU_input10_output30
X_train: (13078, 10, 23) y_train: (13078, 23)
X_val:   (1453, 10, 23) y_val:   (1453, 23)
X_test:  (1615, 10, 23) y_test:  (1615, 23)
Params: 67351
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:54 2s/step - loss: 0.2837 - mae: 0.2837

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.2767 - mae: 0.2767

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2676 - mae: 0.2676

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2593 - mae: 0.2593

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2518 - mae: 0.2518

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2450 - mae: 0.2450

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2386 - mae: 0.2386

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2327 - mae: 0.2327

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2272 - mae: 0.2272

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2219 - mae: 0.2219

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2169 - mae: 0.2169

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2121 - mae: 0.2121

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2075 - mae: 0.2075

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2030 - mae: 0.2030

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1987 - mae: 0.1987

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1946 - mae: 0.1946

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1905 - mae: 0.1905

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1866 - mae: 0.1866

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1829 - mae: 0.1829

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1792 - mae: 0.1792

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1757 - mae: 0.1757

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - loss: 0.1054 - mae: 0.1054 - val_loss: 0.0086 - val_mae: 0.0086 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0165 - mae: 0.0165

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0151 - mae: 0.0151

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0143 - mae: 0.0143

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0137 - mae: 0.0137

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0132 - mae: 0.0132

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0127 - mae: 0.0127

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0124 - mae: 0.0124

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0121 - mae: 0.0121

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0118 - mae: 0.0118

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0115 - mae: 0.0115

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0113 - mae: 0.0113

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0111 - mae: 0.0111

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0109 - mae: 0.0109

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0106 - mae: 0.0106

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0104 - mae: 0.0104

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0103 - mae: 0.0103

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0101 - mae: 0.0101

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0099 - mae: 0.0099

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0097 - mae: 0.0097

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0096 - mae: 0.0096

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0066 - mae: 0.0066 - val_loss: 0.0019 - val_mae: 0.0019 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0050 - mae: 0.0050

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0042 - mae: 0.0042

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0040 - mae: 0.0040

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0038 - mae: 0.0038

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0037 - mae: 0.0037

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0036 - mae: 0.0036

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0035 - mae: 0.0035

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0035 - mae: 0.0035

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0035 - mae: 0.0035

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0034 - mae: 0.0034

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0034 - mae: 0.0034

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0034 - mae: 0.0034

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0033 - mae: 0.0033

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0033 - mae: 0.0033

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0033 - mae: 0.0033

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0033 - mae: 0.0033

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0032 - mae: 0.0032

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0032 - mae: 0.0032

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0032 - mae: 0.0032

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0032 - mae: 0.0032

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0029 - mae: 0.0029 - val_loss: 0.0018 - val_mae: 0.0018 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0030 - mae: 0.0030

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0029 - mae: 0.0029

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0028 - mae: 0.0028

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0027 - mae: 0.0027

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0027 - mae: 0.0027

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0025 - mae: 0.0025

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0025 - mae: 0.0025 - val_loss: 0.0018 - val_mae: 0.0018 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0026 - mae: 0.0026

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0025 - mae: 0.0025

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0025 - mae: 0.0025

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0025 - mae: 0.0025

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0025 - mae: 0.0025

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0025 - mae: 0.0025

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0024 - mae: 0.0024 - val_loss: 0.0018 - val_mae: 0.0018 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0026 - mae: 0.0026

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0024 - mae: 0.0024

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0024 - mae: 0.0024

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0023 - mae: 0.0023 - val_loss: 0.0018 - val_mae: 0.0018 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0023 - mae: 0.0023

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0023 - mae: 0.0023 - val_loss: 0.0018 - val_mae: 0.0018 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.0000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0023 - mae: 0.0023

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0022 - mae: 0.0022

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0024 - mae: 0.0024

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0023 - mae: 0.0023

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0025 - mae: 0.0025

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0023 - mae: 0.0023

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.5000e-04

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 16/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 17/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 18/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 7.5000e-05

Epoch 19/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 20/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 21/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 22/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 28ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 23/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 20/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0022

 25/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0022

 30/103 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0022 - mae: 0.0022

 35/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 40/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 45/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 3.7500e-05

Epoch 24/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 25/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 26/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 13/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 18/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 23/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 29/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 34/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 39/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 44/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 27/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 28/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 1.8750e-05

Epoch 29/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 30/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 31/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 32/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  7/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 27/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 32/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 37/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 42/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 33/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 11/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 16/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 21/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 26/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 31/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 36/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 41/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 46/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 9.3750e-06

Epoch 34/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0021 - mae: 0.0021

  6/103 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0022 - mae: 0.0022

 12/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 17/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 22/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 28/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 33/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 38/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 43/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0022 - mae: 0.0022

103/103 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0022 - mae: 0.0022 - val_loss: 0.0017 - val_mae: 0.0017 - learning_rate: 4.6875e-06

Result: {
  "model": "CNN_BiGRU",
  "input_window": 10,
  "output_window": 30,
  "MAE_train": 0.0022019157152735717,
  "MAE_val": 0.0017126260708758875,
  "MAE_test": 0.002367523427293608,
  "params": 67351,
  "epochs_trained": 34,
  "filters": 64,
  "kernel_size": 5,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.2,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_LSTM_input10_output90
X_train: (13030, 10, 23) y_train: (13030, 23)
X_val:   (1447, 10, 23) y_val:   (1447, 23)
X_test:  (1609, 10, 23) y_test:  (1609, 23)
Params: 43415
Epoch 1/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1:48 1s/step - loss: 0.1270 - mae: 0.1270

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1237 - mae: 0.1237

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1202 - mae: 0.1202

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1168 - mae: 0.1168

 25/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1137 - mae: 0.1137

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1108 - mae: 0.1108

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1081 - mae: 0.1081

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1057 - mae: 0.1057

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1034 - mae: 0.1034

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1010 - mae: 0.1010

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0990 - mae: 0.0990

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0971 - mae: 0.0971

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0952 - mae: 0.0952

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0935 - mae: 0.0935

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0918 - mae: 0.0918

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0902 - mae: 0.0902

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0886 - mae: 0.0886

102/102 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.0617 - mae: 0.0617 - val_loss: 0.0101 - val_mae: 0.0101 - learning_rate: 3.0000e-04

Epoch 2/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0189 - mae: 0.0189

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0184 - mae: 0.0184

 14/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0176 - mae: 0.0176

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0167 - mae: 0.0167

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0159 - mae: 0.0159

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0150 - mae: 0.0150

 39/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0143 - mae: 0.0143

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0135 - mae: 0.0135

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0130 - mae: 0.0130

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0124 - mae: 0.0124

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0118 - mae: 0.0118

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0113 - mae: 0.0113

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0109 - mae: 0.0109

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0105 - mae: 0.0105

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0101 - mae: 0.0101

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0098 - mae: 0.0098

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0051 - mae: 0.0051 - val_loss: 9.3573e-04 - val_mae: 9.3573e-04 - learning_rate: 3.0000e-04

Epoch 3/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0013 - mae: 0.0013

  8/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0015 - mae: 0.0015

 15/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0015 - mae: 0.0015

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0015 - mae: 0.0015

 29/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0015 - mae: 0.0015

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0015 - mae: 0.0015

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0015 - mae: 0.0015

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0015 - mae: 0.0015

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0015 - mae: 0.0015

 63/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0015 - mae: 0.0015

 69/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0015 - mae: 0.0015

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0015 - mae: 0.0015

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0015 - mae: 0.0015

 89/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0015 - mae: 0.0015

 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0015 - mae: 0.0015

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0014 - mae: 0.0014

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0014 - mae: 0.0014 - val_loss: 9.2869e-04 - val_mae: 9.2869e-04 - learning_rate: 3.0000e-04

Epoch 4/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0013 - mae: 0.0013

  8/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 15/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0014 - mae: 0.0014

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0014 - mae: 0.0014

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0014 - mae: 0.0014

 34/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0014 - mae: 0.0014

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0014 - mae: 0.0014

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 55/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3072e-04 - val_mae: 9.3072e-04 - learning_rate: 3.0000e-04

Epoch 5/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  8/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 14/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 54/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 75/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2889e-04 - val_mae: 9.2889e-04 - learning_rate: 3.0000e-04

Epoch 6/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 14/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 34/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 54/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 60/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2921e-04 - val_mae: 9.2921e-04 - learning_rate: 3.0000e-04

Epoch 7/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 39/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 60/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2942e-04 - val_mae: 9.2942e-04 - learning_rate: 3.0000e-04

Epoch 8/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0013 - mae: 0.0013

  8/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 15/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 34/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 55/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2601e-04 - val_mae: 9.2601e-04 - learning_rate: 1.5000e-04

Epoch 9/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  8/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 14/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 28/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 35/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 55/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 69/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2514e-04 - val_mae: 9.2514e-04 - learning_rate: 1.5000e-04

Epoch 10/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0013 - mae: 0.0013

  8/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 15/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 28/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 34/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2538e-04 - val_mae: 9.2538e-04 - learning_rate: 1.5000e-04

Epoch 11/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 14/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2583e-04 - val_mae: 9.2583e-04 - learning_rate: 1.5000e-04

Epoch 12/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0013 - mae: 0.0013

  8/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 14/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 45/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 65/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2560e-04 - val_mae: 9.2560e-04 - learning_rate: 1.5000e-04

Epoch 13/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  8/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 15/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 28/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 35/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 54/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 60/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2776e-04 - val_mae: 9.2776e-04 - learning_rate: 7.5000e-05

Epoch 14/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0013 - mae: 0.0013

  8/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 14/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 34/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 65/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 89/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2766e-04 - val_mae: 9.2766e-04 - learning_rate: 7.5000e-05

Epoch 15/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0013 - mae: 0.0013

  8/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 15/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 28/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 34/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 65/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2741e-04 - val_mae: 9.2741e-04 - learning_rate: 7.5000e-05

Epoch 16/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 14/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 39/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 60/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2751e-04 - val_mae: 9.2751e-04 - learning_rate: 7.5000e-05

Epoch 17/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0013 - mae: 0.0013

  8/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 14/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 28/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 35/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 54/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 60/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2708e-04 - val_mae: 9.2708e-04 - learning_rate: 7.5000e-05

Epoch 18/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0014 - mae: 0.0014

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 39/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 45/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 65/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2873e-04 - val_mae: 9.2873e-04 - learning_rate: 3.7500e-05

Result: {
  "model": "CNN_LSTM",
  "input_window": 10,
  "output_window": 90,
  "MAE_train": 0.0012672964374926753,
  "MAE_val": 0.0009260068052901379,
  "MAE_test": 0.0012698138543522559,
  "params": 43415,
  "epochs_trained": 18,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_GRU_input10_output90
X_train: (13030, 10, 23) y_train: (13030, 23)
X_val:   (1447, 10, 23) y_val:   (1447, 23)
X_test:  (1609, 10, 23) y_test:  (1609, 23)
Params: 35351
Epoch 1/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 1:53 1s/step - loss: 0.2327 - mae: 0.2327

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2263 - mae: 0.2263

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2212 - mae: 0.2212

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2159 - mae: 0.2159

 25/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2111 - mae: 0.2111

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2068 - mae: 0.2068

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2027 - mae: 0.2027

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1989 - mae: 0.1989

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1953 - mae: 0.1953

 55/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1919 - mae: 0.1919

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1886 - mae: 0.1886

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1855 - mae: 0.1855

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1825 - mae: 0.1825

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1797 - mae: 0.1797

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1769 - mae: 0.1769

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1742 - mae: 0.1742

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1716 - mae: 0.1716

102/102 ━━━━━━━━━━━━━━━━━━━━ 2s 11ms/step - loss: 0.1272 - mae: 0.1272 - val_loss: 0.0224 - val_mae: 0.0224 - learning_rate: 3.0000e-04

Epoch 2/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0568 - mae: 0.0568

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0543 - mae: 0.0543

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0527 - mae: 0.0527

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0509 - mae: 0.0509

 25/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0491 - mae: 0.0491

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0473 - mae: 0.0473

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0455 - mae: 0.0455

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0438 - mae: 0.0438

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0421 - mae: 0.0421

 55/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0405 - mae: 0.0405

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0390 - mae: 0.0390

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0376 - mae: 0.0376

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0362 - mae: 0.0362

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0350 - mae: 0.0350

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0338 - mae: 0.0338

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0327 - mae: 0.0327

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0316 - mae: 0.0316

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0154 - mae: 0.0154 - val_loss: 9.3655e-04 - val_mae: 9.3655e-04 - learning_rate: 3.0000e-04

Epoch 3/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0015 - mae: 0.0015

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0017 - mae: 0.0017

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0018 - mae: 0.0018

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0018 - mae: 0.0018

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0017 - mae: 0.0017

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0017 - mae: 0.0017

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0017 - mae: 0.0017

 44/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0017 - mae: 0.0017

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0017 - mae: 0.0017

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0016 - mae: 0.0016

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0016 - mae: 0.0016

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0016 - mae: 0.0016

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0016 - mae: 0.0016

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0016 - mae: 0.0016

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0016 - mae: 0.0016

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0016 - mae: 0.0016

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0016 - mae: 0.0016

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0015 - mae: 0.0015 - val_loss: 9.2823e-04 - val_mae: 9.2823e-04 - learning_rate: 3.0000e-04

Epoch 4/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0014 - mae: 0.0014

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0015 - mae: 0.0015

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0015 - mae: 0.0015

 25/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0015 - mae: 0.0015

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0015 - mae: 0.0015

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 54/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 64/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 70/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0014 - mae: 0.0014 - val_loss: 9.2913e-04 - val_mae: 9.2913e-04 - learning_rate: 3.0000e-04

Epoch 5/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 25/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0014 - mae: 0.0014

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.3057e-04 - val_mae: 9.3057e-04 - learning_rate: 3.0000e-04

Epoch 6/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 25/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 55/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2963e-04 - val_mae: 9.2963e-04 - learning_rate: 3.0000e-04

Epoch 7/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 25/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 55/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2900e-04 - val_mae: 9.2900e-04 - learning_rate: 3.0000e-04

Epoch 8/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 25/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 55/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2554e-04 - val_mae: 9.2554e-04 - learning_rate: 1.5000e-04

Epoch 9/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 44/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2540e-04 - val_mae: 9.2540e-04 - learning_rate: 1.5000e-04

Epoch 10/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 44/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2547e-04 - val_mae: 9.2547e-04 - learning_rate: 1.5000e-04

Epoch 11/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 25/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 55/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2528e-04 - val_mae: 9.2528e-04 - learning_rate: 1.5000e-04

Epoch 12/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 25/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 55/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2543e-04 - val_mae: 9.2543e-04 - learning_rate: 1.5000e-04

Epoch 13/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 44/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2817e-04 - val_mae: 9.2817e-04 - learning_rate: 7.5000e-05

Epoch 14/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 25/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2804e-04 - val_mae: 9.2804e-04 - learning_rate: 7.5000e-05

Epoch 15/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 19/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 25/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 55/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2797e-04 - val_mae: 9.2797e-04 - learning_rate: 7.5000e-05

Epoch 16/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  8/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 14/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 44/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2770e-04 - val_mae: 9.2770e-04 - learning_rate: 7.5000e-05

Epoch 17/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 13/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 20/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 44/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2773e-04 - val_mae: 9.2773e-04 - learning_rate: 7.5000e-05

Epoch 18/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  8/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 14/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 40/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 64/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 70/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.2868e-04 - val_mae: 9.2868e-04 - learning_rate: 3.7500e-05

Result: {
  "model": "CNN_GRU",
  "input_window": 10,
  "output_window": 90,
  "MAE_train": 0.0012678380975484102,
  "MAE_val": 0.0009255387974828743,
  "MAE_test": 0.0012772014000845705,
  "params": 35351,
  "epochs_trained": 18,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_BiGRU_input10_output90
X_train: (13030, 10, 23) y_train: (13030, 23)
X_val:   (1447, 10, 23) y_val:   (1447, 23)
X_test:  (1609, 10, 23) y_test:  (1609, 23)
Params: 67351
Epoch 1/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2:42 2s/step - loss: 0.2828 - mae: 0.2828

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.2754 - mae: 0.2754

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2669 - mae: 0.2669

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2588 - mae: 0.2588

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2509 - mae: 0.2509

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2438 - mae: 0.2438

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2374 - mae: 0.2374

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2314 - mae: 0.2314

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2258 - mae: 0.2258

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2206 - mae: 0.2206

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2156 - mae: 0.2156

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2108 - mae: 0.2108

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2061 - mae: 0.2061

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2017 - mae: 0.2017

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1974 - mae: 0.1974

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1933 - mae: 0.1933

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1893 - mae: 0.1893

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1854 - mae: 0.1854

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1816 - mae: 0.1816

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1780 - mae: 0.1780

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1745 - mae: 0.1745

102/102 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 0.1050 - mae: 0.1050 - val_loss: 0.0084 - val_mae: 0.0084 - learning_rate: 3.0000e-04

Epoch 2/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0104 - mae: 0.0104

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0129 - mae: 0.0129

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0131 - mae: 0.0131

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0129 - mae: 0.0129

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0126 - mae: 0.0126

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0123 - mae: 0.0123

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0119 - mae: 0.0119

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0116 - mae: 0.0116

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0113 - mae: 0.0113

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0110 - mae: 0.0110

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0108 - mae: 0.0108

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0105 - mae: 0.0105

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0103 - mae: 0.0103

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0100 - mae: 0.0100

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0098 - mae: 0.0098

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0096 - mae: 0.0096

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0094 - mae: 0.0094

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0093 - mae: 0.0093

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0091 - mae: 0.0091

 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0090 - mae: 0.0090

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0088 - mae: 0.0088

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0057 - mae: 0.0057 - val_loss: 0.0011 - val_mae: 0.0011 - learning_rate: 3.0000e-04

Epoch 3/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0025 - mae: 0.0025

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0028 - mae: 0.0028

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0028 - mae: 0.0028

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0028 - mae: 0.0028

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0027 - mae: 0.0027

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0027 - mae: 0.0027

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0026 - mae: 0.0026

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0025 - mae: 0.0025

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0025 - mae: 0.0025

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0025 - mae: 0.0025

 63/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0025 - mae: 0.0025

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0024 - mae: 0.0024

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0021 - mae: 0.0021 - val_loss: 0.0010 - val_mae: 0.0010 - learning_rate: 3.0000e-04

Epoch 4/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0016 - mae: 0.0016

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0017 - mae: 0.0017

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0016 - mae: 0.0016

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0016 - mae: 0.0016

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0016 - mae: 0.0016

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0016 - mae: 0.0016

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 54/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 64/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 70/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 75/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0016 - mae: 0.0016

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0016 - mae: 0.0016 - val_loss: 9.9925e-04 - val_mae: 9.9925e-04 - learning_rate: 3.0000e-04

Epoch 5/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0015 - mae: 0.0015

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0015 - mae: 0.0015

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0014 - mae: 0.0014 - val_loss: 9.8330e-04 - val_mae: 9.8330e-04 - learning_rate: 3.0000e-04

Epoch 6/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 89/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0014 - mae: 0.0014

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0014 - mae: 0.0014 - val_loss: 9.7396e-04 - val_mae: 9.7396e-04 - learning_rate: 3.0000e-04

Epoch 7/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 18/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 23/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 28/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 63/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.6828e-04 - val_mae: 9.6828e-04 - learning_rate: 3.0000e-04

Epoch 8/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 65/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 70/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 75/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

101/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.6166e-04 - val_mae: 9.6166e-04 - learning_rate: 3.0000e-04

Epoch 9/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 64/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 69/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.5429e-04 - val_mae: 9.5429e-04 - learning_rate: 1.5000e-04

Epoch 10/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 63/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.5330e-04 - val_mae: 9.5330e-04 - learning_rate: 1.5000e-04

Epoch 11/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 54/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 64/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 69/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 75/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.5046e-04 - val_mae: 9.5046e-04 - learning_rate: 1.5000e-04

Epoch 12/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4948e-04 - val_mae: 9.4948e-04 - learning_rate: 1.5000e-04

Epoch 13/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4770e-04 - val_mae: 9.4770e-04 - learning_rate: 1.5000e-04

Epoch 14/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4693e-04 - val_mae: 9.4693e-04 - learning_rate: 7.5000e-05

Epoch 15/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 54/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 64/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 69/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4637e-04 - val_mae: 9.4637e-04 - learning_rate: 7.5000e-05

Epoch 16/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 63/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 89/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4622e-04 - val_mae: 9.4622e-04 - learning_rate: 7.5000e-05

Epoch 17/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 63/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 69/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4552e-04 - val_mae: 9.4552e-04 - learning_rate: 7.5000e-05

Epoch 18/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4536e-04 - val_mae: 9.4536e-04 - learning_rate: 7.5000e-05

Epoch 19/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4681e-04 - val_mae: 9.4681e-04 - learning_rate: 3.7500e-05

Epoch 20/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4559e-04 - val_mae: 9.4559e-04 - learning_rate: 3.7500e-05

Epoch 21/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 63/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4539e-04 - val_mae: 9.4539e-04 - learning_rate: 3.7500e-05

Epoch 22/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 18/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 23/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 28/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 34/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 39/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 45/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4514e-04 - val_mae: 9.4514e-04 - learning_rate: 3.7500e-05

Epoch 23/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4504e-04 - val_mae: 9.4504e-04 - learning_rate: 3.7500e-05

Epoch 24/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4432e-04 - val_mae: 9.4432e-04 - learning_rate: 1.8750e-05

Epoch 25/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 23/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 28/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 54/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 65/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 70/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4430e-04 - val_mae: 9.4430e-04 - learning_rate: 1.8750e-05

Epoch 26/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 63/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 89/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4373e-04 - val_mae: 9.4373e-04 - learning_rate: 1.8750e-05

Epoch 27/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4313e-04 - val_mae: 9.4313e-04 - learning_rate: 1.8750e-05

Epoch 28/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 63/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 89/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4278e-04 - val_mae: 9.4278e-04 - learning_rate: 1.8750e-05

Epoch 29/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4218e-04 - val_mae: 9.4218e-04 - learning_rate: 9.3750e-06

Epoch 30/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4205e-04 - val_mae: 9.4205e-04 - learning_rate: 9.3750e-06

Epoch 31/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 87/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 92/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 97/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4202e-04 - val_mae: 9.4202e-04 - learning_rate: 9.3750e-06

Epoch 32/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 26ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 77/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 82/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4193e-04 - val_mae: 9.4193e-04 - learning_rate: 9.3750e-06

Epoch 33/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 57/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 83/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 88/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 93/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 98/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4194e-04 - val_mae: 9.4194e-04 - learning_rate: 9.3750e-06

Epoch 34/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 36/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 41/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 46/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 51/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 56/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 62/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 67/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 72/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 89/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4161e-04 - val_mae: 9.4161e-04 - learning_rate: 4.6875e-06

Epoch 35/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 52/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 63/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 78/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 84/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 89/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 94/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 99/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4164e-04 - val_mae: 9.4164e-04 - learning_rate: 4.6875e-06

Epoch 36/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 23/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 28/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 54/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 64/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 69/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 75/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4153e-04 - val_mae: 9.4153e-04 - learning_rate: 4.6875e-06

Epoch 37/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 38/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 44/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 50/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 55/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 61/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 66/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 71/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 76/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 81/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 86/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 91/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4150e-04 - val_mae: 9.4150e-04 - learning_rate: 4.6875e-06

Epoch 38/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  7/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 12/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 17/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 22/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 33/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 39/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 44/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 49/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 54/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 64/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 69/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 74/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4143e-04 - val_mae: 9.4143e-04 - learning_rate: 4.6875e-06

Epoch 39/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 26/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 31/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 43/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 48/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 59/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 65/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 70/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 75/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 80/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 95/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

100/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4122e-04 - val_mae: 9.4122e-04 - learning_rate: 2.3438e-06

Epoch 40/80

  1/102 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0013 - mae: 0.0013

  6/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 11/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 16/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 21/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 27/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 32/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 37/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 42/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 47/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 53/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 58/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 63/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 68/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 73/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 79/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 85/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 90/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

 96/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0013 - mae: 0.0013

102/102 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 0.0013 - mae: 0.0013 - val_loss: 9.4113e-04 - val_mae: 9.4113e-04 - learning_rate: 2.3438e-06

Result: {
  "model": "CNN_BiGRU",
  "input_window": 10,
  "output_window": 90,
  "MAE_train": 0.001264951270778499,
  "MAE_val": 0.0009420497462331457,
  "MAE_test": 0.0012713904127120807,
  "params": 67351,
  "epochs_trained": 40,
  "filters": 64,
  "kernel_size": 5,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.2,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_LSTM_input30_output1
X_train: (13086, 30, 23) y_train: (13086, 23)
X_val:   (1453, 30, 23) y_val:   (1453, 23)
X_test:  (1616, 30, 23) y_test:  (1616, 23)
Params: 43415
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1:47 1s/step - loss: 0.1257 - mae: 0.1257

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.1258 - mae: 0.1258

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1245 - mae: 0.1245

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1227 - mae: 0.1227

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1209 - mae: 0.1209

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1191 - mae: 0.1191

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1173 - mae: 0.1173

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1156 - mae: 0.1156

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1140 - mae: 0.1140

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1125 - mae: 0.1125

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1110 - mae: 0.1110

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1096 - mae: 0.1096

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1083 - mae: 0.1083

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1070 - mae: 0.1070

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1058 - mae: 0.1058

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1046 - mae: 0.1046

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1035 - mae: 0.1035

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1020 - mae: 0.1020

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1009 - mae: 0.1009

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0999 - mae: 0.0999

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0989 - mae: 0.0989

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0979 - mae: 0.0979

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0970 - mae: 0.0970

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0960 - mae: 0.0960

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0951 - mae: 0.0951

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0942 - mae: 0.0942

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0933 - mae: 0.0933

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0925 - mae: 0.0925

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0916 - mae: 0.0916

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0908 - mae: 0.0908

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0899 - mae: 0.0899

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0891 - mae: 0.0891

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0883 - mae: 0.0883

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0875 - mae: 0.0875

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - loss: 0.0609 - mae: 0.0609 - val_loss: 0.0129 - val_mae: 0.0129 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0189 - mae: 0.0189

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0189 - mae: 0.0189

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0189 - mae: 0.0189

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0188 - mae: 0.0188

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0186 - mae: 0.0186

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0184 - mae: 0.0184

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0181 - mae: 0.0181

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0179 - mae: 0.0179

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0178 - mae: 0.0178

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0176 - mae: 0.0176

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0174 - mae: 0.0174

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0172 - mae: 0.0172

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0171 - mae: 0.0171

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0169 - mae: 0.0169

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0168 - mae: 0.0168

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0166 - mae: 0.0166

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0165 - mae: 0.0165

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0164 - mae: 0.0164

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0163 - mae: 0.0163

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0162 - mae: 0.0162

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0161 - mae: 0.0161

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0160 - mae: 0.0160

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0159 - mae: 0.0159

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0159 - mae: 0.0159

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0158 - mae: 0.0158

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0157 - mae: 0.0157

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0156 - mae: 0.0156

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0156 - mae: 0.0156

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0155 - mae: 0.0155

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0154 - mae: 0.0154

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0154 - mae: 0.0154

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0153 - mae: 0.0153

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0153 - mae: 0.0153

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0152 - mae: 0.0152

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0134 - mae: 0.0134 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0122 - mae: 0.0122

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0120 - mae: 0.0120

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0120 - mae: 0.0120

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0120 - mae: 0.0120

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0120 - mae: 0.0120

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0120 - mae: 0.0120

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0120 - mae: 0.0120

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0120 - mae: 0.0120

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0120 - mae: 0.0120

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0120 - mae: 0.0120

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0120 - mae: 0.0120

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0120 - mae: 0.0120

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0119 - mae: 0.0119

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0119 - mae: 0.0119

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0119 - mae: 0.0119

 50/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0119 - mae: 0.0119

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0122 - mae: 0.0122

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0119 - mae: 0.0119

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0119 - mae: 0.0119

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0119 - mae: 0.0119

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0119 - mae: 0.0119

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0119 - mae: 0.0119

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0119 - mae: 0.0119

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0120 - mae: 0.0120

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0120 - mae: 0.0120

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0118 - mae: 0.0118

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0118 - mae: 0.0118

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0118 - mae: 0.0118

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0120 - mae: 0.0120

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0118 - mae: 0.0118

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0118 - mae: 0.0118

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0118 - mae: 0.0118

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 57/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 60/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 50/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Result: {
  "model": "CNN_LSTM",
  "input_window": 30,
  "output_window": 1,
  "MAE_train": 0.011841174736365789,
  "MAE_val": 0.009037406434693002,
  "MAE_test": 0.012244008447683663,
  "params": 43415,
  "epochs_trained": 15,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_GRU_input30_output1
X_train: (13086, 30, 23) y_train: (13086, 23)
X_val:   (1453, 30, 23) y_val:   (1453, 23)
X_test:  (1616, 30, 23) y_test:  (1616, 23)
Params: 35351
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:04 1s/step - loss: 0.2268 - mae: 0.2268

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.2231 - mae: 0.2231

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2214 - mae: 0.2214

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2194 - mae: 0.2194

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2173 - mae: 0.2173

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2150 - mae: 0.2150

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2126 - mae: 0.2126

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2104 - mae: 0.2104

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2081 - mae: 0.2081

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2059 - mae: 0.2059

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2037 - mae: 0.2037

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2016 - mae: 0.2016

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1996 - mae: 0.1996

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1976 - mae: 0.1976

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1956 - mae: 0.1956

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1938 - mae: 0.1938

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.1920 - mae: 0.1920

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1903 - mae: 0.1903

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1886 - mae: 0.1886

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1869 - mae: 0.1869

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1853 - mae: 0.1853

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1837 - mae: 0.1837

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1822 - mae: 0.1822

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1807 - mae: 0.1807

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1792 - mae: 0.1792

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1778 - mae: 0.1778

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1763 - mae: 0.1763

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1749 - mae: 0.1749

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1735 - mae: 0.1735

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1722 - mae: 0.1722

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1709 - mae: 0.1709

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1695 - mae: 0.1695

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1682 - mae: 0.1682

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1670 - mae: 0.1670

103/103 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - loss: 0.1236 - mae: 0.1236 - val_loss: 0.0258 - val_mae: 0.0258 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - loss: 0.0507 - mae: 0.0507

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0512 - mae: 0.0512

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0510 - mae: 0.0510

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0503 - mae: 0.0503

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0495 - mae: 0.0495

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0487 - mae: 0.0487

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0479 - mae: 0.0479

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0471 - mae: 0.0471

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0463 - mae: 0.0463

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0455 - mae: 0.0455

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0447 - mae: 0.0447

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0439 - mae: 0.0439

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0432 - mae: 0.0432

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0424 - mae: 0.0424

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0417 - mae: 0.0417

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0410 - mae: 0.0410

 50/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0403 - mae: 0.0403

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0397 - mae: 0.0397

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0391 - mae: 0.0391

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0385 - mae: 0.0385

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0379 - mae: 0.0379

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0374 - mae: 0.0374

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0369 - mae: 0.0369

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0363 - mae: 0.0363

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0359 - mae: 0.0359

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0354 - mae: 0.0354

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0350 - mae: 0.0350

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0345 - mae: 0.0345

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0341 - mae: 0.0341

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0337 - mae: 0.0337

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0333 - mae: 0.0333

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0330 - mae: 0.0330

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0326 - mae: 0.0326

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0323 - mae: 0.0323

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0209 - mae: 0.0209 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0121 - mae: 0.0121

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0120 - mae: 0.0120

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0121 - mae: 0.0121

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0121 - mae: 0.0121

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0120 - mae: 0.0120

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0121 - mae: 0.0121

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0121 - mae: 0.0121

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0120 - mae: 0.0120

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0120 - mae: 0.0120

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0120 - mae: 0.0120

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0120 - mae: 0.0120

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0120 - mae: 0.0120

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0120 - mae: 0.0120

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0120 - mae: 0.0120

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0120 - mae: 0.0120

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0120 - mae: 0.0120

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0120 - mae: 0.0120

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0120 - mae: 0.0120

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0120 - mae: 0.0120

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0120 - mae: 0.0120

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0120 - mae: 0.0120 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0119 - mae: 0.0119

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 16/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 50/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0118 - mae: 0.0118

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0118 - mae: 0.0118

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 17/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Result: {
  "model": "CNN_GRU",
  "input_window": 30,
  "output_window": 1,
  "MAE_train": 0.011839064340824984,
  "MAE_val": 0.009037314276052972,
  "MAE_test": 0.012245782536809864,
  "params": 35351,
  "epochs_trained": 17,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_BiGRU_input30_output1
X_train: (13086, 30, 23) y_train: (13086, 23)
X_val:   (1453, 30, 23) y_val:   (1453, 23)
X_test:  (1616, 30, 23) y_test:  (1616, 23)
Params: 67351
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:48 2s/step - loss: 0.2713 - mae: 0.2713

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.2675 - mae: 0.2675

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.2616 - mae: 0.2616

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.2563 - mae: 0.2563

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.2513 - mae: 0.2513

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.2467 - mae: 0.2467

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2424 - mae: 0.2424

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2383 - mae: 0.2383

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2343 - mae: 0.2343

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2305 - mae: 0.2305

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2268 - mae: 0.2268

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2233 - mae: 0.2233

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2199 - mae: 0.2199

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2166 - mae: 0.2166

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2134 - mae: 0.2134

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2103 - mae: 0.2103

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2072 - mae: 0.2072

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2043 - mae: 0.2043

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2015 - mae: 0.2015

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.1987 - mae: 0.1987

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1959 - mae: 0.1959

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1933 - mae: 0.1933

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1906 - mae: 0.1906

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1881 - mae: 0.1881

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1856 - mae: 0.1856

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1831 - mae: 0.1831

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1807 - mae: 0.1807

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1784 - mae: 0.1784

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1761 - mae: 0.1761

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1739 - mae: 0.1739

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1717 - mae: 0.1717

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1696 - mae: 0.1696

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1675 - mae: 0.1675

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1655 - mae: 0.1655

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1636 - mae: 0.1636

103/103 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - loss: 0.0981 - mae: 0.0981 - val_loss: 0.0153 - val_mae: 0.0153 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - loss: 0.0200 - mae: 0.0200

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0223 - mae: 0.0223

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0224 - mae: 0.0224

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0221 - mae: 0.0221

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0219 - mae: 0.0219

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0218 - mae: 0.0218

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0217 - mae: 0.0217

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0215 - mae: 0.0215

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0213 - mae: 0.0213

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0211 - mae: 0.0211

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0210 - mae: 0.0210

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0208 - mae: 0.0208

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0207 - mae: 0.0207

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0205 - mae: 0.0205

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0204 - mae: 0.0204

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0203 - mae: 0.0203

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0201 - mae: 0.0201

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0200 - mae: 0.0200

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0199 - mae: 0.0199

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0198 - mae: 0.0198

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0197 - mae: 0.0197

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0196 - mae: 0.0196

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0195 - mae: 0.0195

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0194 - mae: 0.0194

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0193 - mae: 0.0193

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0192 - mae: 0.0192

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0191 - mae: 0.0191

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0190 - mae: 0.0190

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0189 - mae: 0.0189

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0188 - mae: 0.0188

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0187 - mae: 0.0187

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0187 - mae: 0.0187

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0186 - mae: 0.0186

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0185 - mae: 0.0185

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0184 - mae: 0.0184

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0159 - mae: 0.0159 - val_loss: 0.0092 - val_mae: 0.0092 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0126 - mae: 0.0126

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0135 - mae: 0.0135

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0137 - mae: 0.0137

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0136 - mae: 0.0136

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0136 - mae: 0.0136

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0135 - mae: 0.0135

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0135 - mae: 0.0135

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0134 - mae: 0.0134

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0134 - mae: 0.0134

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0134 - mae: 0.0134

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0133 - mae: 0.0133

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0133 - mae: 0.0133

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0133 - mae: 0.0133

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0133 - mae: 0.0133

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0132 - mae: 0.0132

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0132 - mae: 0.0132

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0132 - mae: 0.0132

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0132 - mae: 0.0132

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0132 - mae: 0.0132

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0132 - mae: 0.0132

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0132 - mae: 0.0132

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0131 - mae: 0.0131

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0131 - mae: 0.0131

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0131 - mae: 0.0131

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0131 - mae: 0.0131

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0131 - mae: 0.0131

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0131 - mae: 0.0131

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0131 - mae: 0.0131

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0131 - mae: 0.0131

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0131 - mae: 0.0131

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0130 - mae: 0.0130

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0130 - mae: 0.0130

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0130 - mae: 0.0130

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0130 - mae: 0.0130

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0130 - mae: 0.0130

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0127 - mae: 0.0127 - val_loss: 0.0091 - val_mae: 0.0091 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0126 - mae: 0.0126

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0127 - mae: 0.0127

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0126 - mae: 0.0126

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0125 - mae: 0.0125

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0125 - mae: 0.0125

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0124 - mae: 0.0124

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0124 - mae: 0.0124

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0124 - mae: 0.0124

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0124 - mae: 0.0124

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0124 - mae: 0.0124

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0124 - mae: 0.0124

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0124 - mae: 0.0124

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0123 - mae: 0.0123

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0123 - mae: 0.0123

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0123 - mae: 0.0123

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0123 - mae: 0.0123

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0123 - mae: 0.0123

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0123 - mae: 0.0123

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0123 - mae: 0.0123

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0121 - mae: 0.0121 - val_loss: 0.0091 - val_mae: 0.0091 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0121 - mae: 0.0121

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0121 - mae: 0.0121

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0121 - mae: 0.0121

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0121 - mae: 0.0121

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0121 - mae: 0.0121

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0120 - mae: 0.0120 - val_loss: 0.0091 - val_mae: 0.0091 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0120 - mae: 0.0120

  6/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0120 - mae: 0.0120

  9/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0120 - mae: 0.0120

 12/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0120 - mae: 0.0120

 15/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0120 - mae: 0.0120

 18/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0120 - mae: 0.0120

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0120 - mae: 0.0120

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0120 - mae: 0.0120

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0120 - mae: 0.0120

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0120 - mae: 0.0120

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0120 - mae: 0.0120

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 48/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 54/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 60/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0120 - mae: 0.0120

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0091 - val_mae: 0.0091 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0119 - mae: 0.0119

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0120 - mae: 0.0120

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0120 - mae: 0.0120

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0120 - mae: 0.0120

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0120 - mae: 0.0120

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0119 - mae: 0.0119

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0119 - mae: 0.0119

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0119 - mae: 0.0119

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.0000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0119 - mae: 0.0119

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0120 - mae: 0.0120

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0119 - mae: 0.0119

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0119 - mae: 0.0119

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0119 - mae: 0.0119

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0119 - mae: 0.0119

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0119 - mae: 0.0119

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0119 - mae: 0.0119

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0119 - mae: 0.0119

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0119 - mae: 0.0119

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0119 - mae: 0.0119

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0119 - mae: 0.0119

 48/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0119 - mae: 0.0119

 51/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0119 - mae: 0.0119

 54/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0119 - mae: 0.0119

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0118 - mae: 0.0118

 60/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0119 - mae: 0.0119

 63/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0119 - mae: 0.0119

 66/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0119 - mae: 0.0119

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0119 - mae: 0.0119

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0119 - mae: 0.0119

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0119 - mae: 0.0119

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0119 - mae: 0.0119

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0119 - mae: 0.0119

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0119 - mae: 0.0119

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0119 - mae: 0.0119

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0119 - mae: 0.0119

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0119 - mae: 0.0119

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0119 - mae: 0.0119

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0119 - mae: 0.0119 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.5000e-04

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 16/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 17/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 18/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 7.5000e-05

Epoch 19/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.7500e-05

Epoch 20/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0119 - mae: 0.0119

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0119 - mae: 0.0119

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0119 - mae: 0.0119

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0119 - mae: 0.0119

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0119 - mae: 0.0119

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0119 - mae: 0.0119

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.7500e-05

Epoch 21/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.7500e-05

Epoch 22/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 48/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 50/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 53/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 56/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.7500e-05

Epoch 23/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0118 - mae: 0.0118

  6/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0118 - mae: 0.0118

  8/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0118 - mae: 0.0118

 11/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0118 - mae: 0.0118

 14/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0118 - mae: 0.0118

 18/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0118 - mae: 0.0118

 20/103 ━━━━━━━━━━━━━━━━━━━━ 2s 25ms/step - loss: 0.0118 - mae: 0.0118

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 3.7500e-05

Epoch 24/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0120 - mae: 0.0120

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0118 - mae: 0.0118

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0118 - mae: 0.0118

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0118 - mae: 0.0118

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0118 - mae: 0.0118

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - loss: 0.0118 - mae: 0.0118 - val_loss: 0.0090 - val_mae: 0.0090 - learning_rate: 1.8750e-05

Result: {
  "model": "CNN_BiGRU",
  "input_window": 30,
  "output_window": 1,
  "MAE_train": 0.011832614151847753,
  "MAE_val": 0.009040093023828329,
  "MAE_test": 0.01226149057640972,
  "params": 67351,
  "epochs_trained": 24,
  "filters": 64,
  "kernel_size": 5,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.2,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_LSTM_input30_output5
X_train: (13082, 30, 23) y_train: (13082, 23)
X_val:   (1453, 30, 23) y_val:   (1453, 23)
X_test:  (1616, 30, 23) y_test:  (1616, 23)
Params: 43415
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1:45 1s/step - loss: 0.1322 - mae: 0.1322

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.1272 - mae: 0.1272

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.1247 - mae: 0.1247

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1226 - mae: 0.1226

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1207 - mae: 0.1207

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.1188 - mae: 0.1188

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.1171 - mae: 0.1171

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1154 - mae: 0.1154

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1138 - mae: 0.1138

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.1124 - mae: 0.1124

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1109 - mae: 0.1109

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1096 - mae: 0.1096

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1083 - mae: 0.1083

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.1070 - mae: 0.1070

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.1058 - mae: 0.1058

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.1046 - mae: 0.1046

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1034 - mae: 0.1034

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1023 - mae: 0.1023

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1012 - mae: 0.1012

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.1001 - mae: 0.1001

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0991 - mae: 0.0991

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0981 - mae: 0.0981

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0971 - mae: 0.0971

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0961 - mae: 0.0961

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0952 - mae: 0.0952

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0942 - mae: 0.0942

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0933 - mae: 0.0933

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0924 - mae: 0.0924

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0915 - mae: 0.0915

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0907 - mae: 0.0907

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0898 - mae: 0.0898

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0890 - mae: 0.0890

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0881 - mae: 0.0881

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0870 - mae: 0.0870

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - loss: 0.0595 - mae: 0.0595 - val_loss: 0.0092 - val_mae: 0.0092 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0179 - mae: 0.0179

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0163 - mae: 0.0163

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0159 - mae: 0.0159

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0155 - mae: 0.0155

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0151 - mae: 0.0151

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0147 - mae: 0.0147

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0143 - mae: 0.0143

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0140 - mae: 0.0140

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0137 - mae: 0.0137

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0134 - mae: 0.0134

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0131 - mae: 0.0131

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0129 - mae: 0.0129

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0126 - mae: 0.0126

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0124 - mae: 0.0124

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0122 - mae: 0.0122

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0120 - mae: 0.0120

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0118 - mae: 0.0118

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0116 - mae: 0.0116

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0115 - mae: 0.0115

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0113 - mae: 0.0113

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0112 - mae: 0.0112

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0110 - mae: 0.0110

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0109 - mae: 0.0109

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0107 - mae: 0.0107

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0106 - mae: 0.0106

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0105 - mae: 0.0105

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0104 - mae: 0.0104

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0103 - mae: 0.0103

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0102 - mae: 0.0102

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0101 - mae: 0.0101

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0100 - mae: 0.0100

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0100 - mae: 0.0100

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0099 - mae: 0.0099

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0073 - mae: 0.0073 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0055 - mae: 0.0055

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 30/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 33/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0056 - mae: 0.0056

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

  8/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 11/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 75/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 78/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 81/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 84/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 87/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 69/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 72/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 38/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 41/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 44/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 47/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 50/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 53/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 30ms/step - loss: 0.0053 - mae: 0.0053

  5/103 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0054 - mae: 0.0054

  9/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0054 - mae: 0.0054

 12/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 15/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 18/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 21/103 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0055 - mae: 0.0055

 24/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 27/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 62/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 65/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 68/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 71/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 74/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 90/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 96/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 14/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 17/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 20/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 23/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 26/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 29/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 32/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 36/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 48/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 51/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 4s 40ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 35/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 39/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 42/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 45/103 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 77/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 80/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 83/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 86/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 89/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 92/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

 98/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

101/103 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Result: {
  "model": "CNN_LSTM",
  "input_window": 30,
  "output_window": 5,
  "MAE_train": 0.005483642863130011,
  "MAE_val": 0.004153366739480499,
  "MAE_test": 0.005595812866250607,
  "params": 43415,
  "epochs_trained": 13,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_GRU_input30_output5
X_train: (13082, 30, 23) y_train: (13082, 23)
X_val:   (1453, 30, 23) y_val:   (1453, 23)
X_test:  (1616, 30, 23) y_test:  (1616, 23)
Params: 35351
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 1:53 1s/step - loss: 0.2274 - mae: 0.2274

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.2246 - mae: 0.2246

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.2247 - mae: 0.2247

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2225 - mae: 0.2225

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.2202 - mae: 0.2202

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2179 - mae: 0.2179

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2154 - mae: 0.2154

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2131 - mae: 0.2131

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2109 - mae: 0.2109

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2087 - mae: 0.2087

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2066 - mae: 0.2066

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2045 - mae: 0.2045

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2025 - mae: 0.2025

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.2005 - mae: 0.2005

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1986 - mae: 0.1986

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1967 - mae: 0.1967

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1949 - mae: 0.1949

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.1931 - mae: 0.1931

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1914 - mae: 0.1914

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1896 - mae: 0.1896

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1879 - mae: 0.1879

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1863 - mae: 0.1863

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1847 - mae: 0.1847

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1831 - mae: 0.1831

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1816 - mae: 0.1816

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1800 - mae: 0.1800

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1786 - mae: 0.1786

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1771 - mae: 0.1771

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1756 - mae: 0.1756

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1742 - mae: 0.1742

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1729 - mae: 0.1729

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1715 - mae: 0.1715

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1701 - mae: 0.1701

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1688 - mae: 0.1688

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.1675 - mae: 0.1675

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - loss: 0.1237 - mae: 0.1237 - val_loss: 0.0239 - val_mae: 0.0239 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0550 - mae: 0.0550

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0520 - mae: 0.0520

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0512 - mae: 0.0512

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0502 - mae: 0.0502

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0493 - mae: 0.0493

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0484 - mae: 0.0484

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0475 - mae: 0.0475

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0466 - mae: 0.0466

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0457 - mae: 0.0457

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0448 - mae: 0.0448

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0439 - mae: 0.0439

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0430 - mae: 0.0430

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0421 - mae: 0.0421

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0413 - mae: 0.0413

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0404 - mae: 0.0404

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0396 - mae: 0.0396

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0388 - mae: 0.0388

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0380 - mae: 0.0380

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0373 - mae: 0.0373

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0366 - mae: 0.0366

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0359 - mae: 0.0359

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0352 - mae: 0.0352

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0346 - mae: 0.0346

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0340 - mae: 0.0340

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0334 - mae: 0.0334

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0329 - mae: 0.0329

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0323 - mae: 0.0323

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0318 - mae: 0.0318

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0313 - mae: 0.0313

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0309 - mae: 0.0309

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0304 - mae: 0.0304

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0300 - mae: 0.0300

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0296 - mae: 0.0296

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0291 - mae: 0.0291

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0288 - mae: 0.0288

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0158 - mae: 0.0158 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0057 - mae: 0.0057

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0058 - mae: 0.0058

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0058 - mae: 0.0058

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0058 - mae: 0.0058

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0058 - mae: 0.0058

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0058 - mae: 0.0058

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0058 - mae: 0.0058

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0058 - mae: 0.0058

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0057 - mae: 0.0057

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0057 - mae: 0.0057

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0057 - mae: 0.0057

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0057 - mae: 0.0057

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0057 - mae: 0.0057

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0057 - mae: 0.0057

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0057 - mae: 0.0057

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0057 - mae: 0.0057

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0057 - mae: 0.0057

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0057 - mae: 0.0057

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0057 - mae: 0.0057

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0057 - mae: 0.0057

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 32ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - loss: 0.0054 - mae: 0.0054

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 33ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 54/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 56/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 16/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 34ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 17/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 31ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Result: {
  "model": "CNN_GRU",
  "input_window": 30,
  "output_window": 5,
  "MAE_train": 0.00547891108633939,
  "MAE_val": 0.004154082290087165,
  "MAE_test": 0.005581278321996095,
  "params": 35351,
  "epochs_trained": 17,
  "filters": 64,
  "kernel_size": 3,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.15,
  "learning_rate": 0.0003,
  "batch_size": 128
}

==========================================================================================
Training hybrid_CNN_BiGRU_input30_output5
X_train: (13082, 30, 23) y_train: (13082, 23)
X_val:   (1453, 30, 23) y_val:   (1453, 23)
X_test:  (1616, 30, 23) y_test:  (1616, 23)
Params: 67351
Epoch 1/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 2:45 2s/step - loss: 0.2804 - mae: 0.2804

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.2712 - mae: 0.2712

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.2663 - mae: 0.2663

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.2609 - mae: 0.2609

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.2558 - mae: 0.2558

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.2511 - mae: 0.2511

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2465 - mae: 0.2465

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2422 - mae: 0.2422

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2381 - mae: 0.2381

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2341 - mae: 0.2341

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2304 - mae: 0.2304

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2268 - mae: 0.2268

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2233 - mae: 0.2233

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2199 - mae: 0.2199

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2167 - mae: 0.2167

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2135 - mae: 0.2135

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2104 - mae: 0.2104

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2074 - mae: 0.2074

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2044 - mae: 0.2044

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.2015 - mae: 0.2015

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1987 - mae: 0.1987

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1959 - mae: 0.1959

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1932 - mae: 0.1932

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1906 - mae: 0.1906

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1880 - mae: 0.1880

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1855 - mae: 0.1855

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1830 - mae: 0.1830

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1806 - mae: 0.1806

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1783 - mae: 0.1783

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1760 - mae: 0.1760

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1737 - mae: 0.1737

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1715 - mae: 0.1715

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1694 - mae: 0.1694

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1673 - mae: 0.1673

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1653 - mae: 0.1653

103/103 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - loss: 0.0974 - mae: 0.0974 - val_loss: 0.0111 - val_mae: 0.0111 - learning_rate: 3.0000e-04

Epoch 2/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - loss: 0.0144 - mae: 0.0144

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0138 - mae: 0.0138

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0140 - mae: 0.0140

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0142 - mae: 0.0142

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0144 - mae: 0.0144

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0144 - mae: 0.0144

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0144 - mae: 0.0144

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0143 - mae: 0.0143

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0142 - mae: 0.0142

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0141 - mae: 0.0141

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0141 - mae: 0.0141

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0140 - mae: 0.0140

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0138 - mae: 0.0138

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0137 - mae: 0.0137

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0136 - mae: 0.0136

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0135 - mae: 0.0135

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0134 - mae: 0.0134

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0133 - mae: 0.0133

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0132 - mae: 0.0132

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0131 - mae: 0.0131

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0130 - mae: 0.0130

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0129 - mae: 0.0129

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0129 - mae: 0.0129

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0128 - mae: 0.0128

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0127 - mae: 0.0127

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0126 - mae: 0.0126

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0125 - mae: 0.0125

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0124 - mae: 0.0124

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0124 - mae: 0.0124

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0123 - mae: 0.0123

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0122 - mae: 0.0122

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0121 - mae: 0.0121

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0121 - mae: 0.0121

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0120 - mae: 0.0120

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0119 - mae: 0.0119

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0096 - mae: 0.0096 - val_loss: 0.0043 - val_mae: 0.0043 - learning_rate: 3.0000e-04

Epoch 3/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0062 - mae: 0.0062

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0062 - mae: 0.0062

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0063 - mae: 0.0063

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0064 - mae: 0.0064

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0065 - mae: 0.0065

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0066 - mae: 0.0066

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0066 - mae: 0.0066

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0066 - mae: 0.0066

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0066 - mae: 0.0066

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0066 - mae: 0.0066

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0067 - mae: 0.0067

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0067 - mae: 0.0067

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0067 - mae: 0.0067

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0067 - mae: 0.0067

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0067 - mae: 0.0067

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0066 - mae: 0.0066

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0066 - mae: 0.0066

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0066 - mae: 0.0066

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0066 - mae: 0.0066

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0066 - mae: 0.0066

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0066 - mae: 0.0066

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0066 - mae: 0.0066

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0066 - mae: 0.0066

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0066 - mae: 0.0066

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0066 - mae: 0.0066

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0066 - mae: 0.0066

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0066 - mae: 0.0066

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0066 - mae: 0.0066

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0066 - mae: 0.0066

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0066 - mae: 0.0066

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0066 - mae: 0.0066

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0066 - mae: 0.0066

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0065 - mae: 0.0065

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0065 - mae: 0.0065

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0065 - mae: 0.0065

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0063 - mae: 0.0063 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 4/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0057 - mae: 0.0057

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0057 - mae: 0.0057

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0058 - mae: 0.0058

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0058 - mae: 0.0058

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0058 - mae: 0.0058

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0058 - mae: 0.0058

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0058 - mae: 0.0058

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0058 - mae: 0.0058

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0058 - mae: 0.0058

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0058 - mae: 0.0058

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0059 - mae: 0.0059

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0058 - mae: 0.0058

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0058 - mae: 0.0058

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0058 - mae: 0.0058

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0058 - mae: 0.0058

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0058 - mae: 0.0058

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0058 - mae: 0.0058

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0058 - mae: 0.0058

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0058 - mae: 0.0058

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0058 - mae: 0.0058

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0058 - mae: 0.0058

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0058 - mae: 0.0058 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 5/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0055 - mae: 0.0055

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0056 - mae: 0.0056

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0057 - mae: 0.0057

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0057 - mae: 0.0057

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0057 - mae: 0.0057

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0057 - mae: 0.0057

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0057 - mae: 0.0057

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0057 - mae: 0.0057

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0057 - mae: 0.0057

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0057 - mae: 0.0057

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0057 - mae: 0.0057

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0057 - mae: 0.0057

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0057 - mae: 0.0057

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 6/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0056 - mae: 0.0056

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0056 - mae: 0.0056 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 7/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0056 - mae: 0.0056

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 8/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.0000e-04

Epoch 9/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 35ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 10/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 57/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 59/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 1s 24ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 11/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 12/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 13/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 1.5000e-04

Epoch 14/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 15/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 16/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 17/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 18/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 7.5000e-05

Epoch 19/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 38ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 20/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 21/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 22/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 36ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 94/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

100/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Epoch 23/80

  1/103 ━━━━━━━━━━━━━━━━━━━━ 3s 37ms/step - loss: 0.0053 - mae: 0.0053

  4/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

  7/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0054 - mae: 0.0054

 10/103 ━━━━━━━━━━━━━━━━━━━━ 2s 24ms/step - loss: 0.0054 - mae: 0.0054

 13/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 16/103 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - loss: 0.0055 - mae: 0.0055

 19/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 22/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 25/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 28/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 31/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 34/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 37/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 40/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 43/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 46/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 49/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 52/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 55/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 58/103 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - loss: 0.0055 - mae: 0.0055

 61/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 64/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 67/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 70/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 73/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 76/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 79/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 82/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 85/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 88/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 91/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 93/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 95/103 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.0055 - mae: 0.0055

 97/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

 99/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

102/103 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.0055 - mae: 0.0055

103/103 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - loss: 0.0055 - mae: 0.0055 - val_loss: 0.0042 - val_mae: 0.0042 - learning_rate: 3.7500e-05

Result: {
  "model": "CNN_BiGRU",
  "input_window": 30,
  "output_window": 5,
  "MAE_train": 0.005475444310269932,
  "MAE_val": 0.004154587375939196,
  "MAE_test": 0.00560020186720127,
  "params": 67351,
  "epochs_trained": 23,
  "filters": 64,
  "kernel_size": 5,
  "rnn_units": 64,
  "dense_units": 64,
  "spatial_dropout": 0.1,
  "dropout": 0.2,
  "learning_rate": 0.0003,
  "batch_size": 128
}
All results saved to: /home/hugo/Desktop/Neural-Networks-Forecasting/data/hybrid/hybrid_all_results.csv
Best by window saved to: /home/hugo/Desktop/Neural-Networks-Forecasting/data/hybrid/hybrid_best_by_window.csv

        model  input_window  output_window  MAE_train    MAE_val   MAE_test  params  epochs_trained
0     CNN_GRU            10             30 0.00220192 0.00169853 0.00231971   35351              35
1    CNN_LSTM            10             30 0.00220193 0.00169855 0.00232714   43415              33
2   CNN_BiGRU            10             30 0.00220192 0.00171263 0.00236752   67351              34
3     CNN_GRU            10             90 0.00126784 0.00092554 0.00127720   35351              18
4    CNN_LSTM            10             90 0.00126730 0.00092601 0.00126981   43415              18
5   CNN_BiGRU            10             90 0.00126495 0.00094205 0.00127139   67351              40
6     CNN_GRU            30              1 0.01183906 0.00903731 0.01224578   35351              17
7    CNN_LSTM            30              1 0.01184117 0.00903741 0.01224401   43415              15
8   CNN_BiGRU            30              1 0.01183261 0.00904009 0.01226149   67351              24
9    CNN_LSTM            30              5 0.00548364 0.00415337 0.00559581   43415              13
10    CNN_GRU            30              5 0.00547891 0.00415408 0.00558128   35351              17
11  CNN_BiGRU            30              5 0.00547544 0.00415459 0.00560020   67351              23

      model  input_window  output_window  MAE_train    MAE_val   MAE_test  params  epochs_trained
0   CNN_GRU            10             30 0.00220192 0.00169853 0.00231971   35351              35
1   CNN_GRU            10             90 0.00126784 0.00092554 0.00127720   35351              18
2   CNN_GRU            30              1 0.01183906 0.00903731 0.01224578   35351              17
3  CNN_LSTM            30              5 0.00548364 0.00415337 0.00559581   43415              13

## Comparison against linear regression benchmark

The repository already contains `data/lr_benchmark.csv`. The table below compares the selected best hybrid model for each assigned window against that benchmark.

A negative `delta_vs_lr` means that the hybrid model improves the linear regression benchmark.

In [7]:
lr_path = PROJECT_ROOT / "data" / "lr_benchmark.csv"

if lr_path.exists():
    lr = pd.read_csv(lr_path).rename(columns={
        "MAE_train": "LR_MAE_train",
        "MAE_test": "LR_MAE_test",
    })

    comparison = best_by_window.merge(
        lr[["input_window", "output_window", "LR_MAE_train", "LR_MAE_test"]],
        on=["input_window", "output_window"],
        how="left",
    )

    comparison["delta_vs_lr"] = comparison["MAE_test"] - comparison["LR_MAE_test"]
    comparison["pct_delta_vs_lr"] = 100 * comparison["delta_vs_lr"] / comparison["LR_MAE_test"]

    comparison_path = DATA_OUT / "hybrid_comparison_vs_lr.csv"
    comparison.to_csv(comparison_path, index=False)

    display(comparison[[
        "input_window", "output_window", "model", "MAE_test", "LR_MAE_test", "delta_vs_lr", "pct_delta_vs_lr", "params"
    ]])

    print("Comparison saved to:", comparison_path)
else:
    print("No lr_benchmark.csv found. Benchmark comparison skipped.")

   input_window  output_window     model   MAE_test  LR_MAE_test  delta_vs_lr  pct_delta_vs_lr  params
0            10             30   CNN_GRU 0.00231971   0.00235841  -0.00003870      -1.64088107   35351
1            10             90   CNN_GRU 0.00127720   0.00128239  -0.00000519      -0.40451180   35351
2            30              1   CNN_GRU 0.01224578   0.01292421  -0.00067843      -5.24926902   35351
3            30              5  CNN_LSTM 0.00559581   0.00587674  -0.00028093      -4.78039767   43415

Comparison saved to: /home/hugo/Desktop/Neural-Networks-Forecasting/data/hybrid/hybrid_comparison_vs_lr.csv

## Test MAE matrix

This matrix is directly usable in the report to summarize the best hybrid model by window.

In [8]:
matrix = best_by_window.pivot(index="input_window", columns="output_window", values="MAE_test")
matrix_path = DATA_OUT / "hybrid_test_mae_matrix.csv"
matrix.to_csv(matrix_path)

display(matrix)
print("Matrix saved to:", matrix_path)

output_window         1          5          30         90
input_window
10                   NaN        NaN 0.00231971 0.00127720
30            0.01224578 0.00559581        NaN        NaN

Matrix saved to: /home/hugo/Desktop/Neural-Networks-Forecasting/data/hybrid/hybrid_test_mae_matrix.csv